### ISSUE TITLE
OpenGL 3.2 feature request: Having OpenGL 1.4 style correct lighting for liquids and lava

### ISSUE THREAD

**Issue by AtifArshad1995** [yquake2/yquake2#1014]
Generally speaking, I prefer the overall lighting in OpenGL 3.2 over the 1.4 renderer. However I can't get it to have bright looking liquids/lava that I can easily set with GL 1.4

See screenshots below. First screenshot show OpenGL 3.2 with intensity set to 2.0 and overbright bits set to 1.3. This is what it looks like:
![1](https://github.com/yquake2/yquake2/assets/43236181/03136bff-ea5b-4c7f-a6c2-88899bbcbb4b)

The 2nd screenshot is OpenGL 1.4. I set intensity for this renderer as 2.0 and overbright bits set to 1.0. The lava looks much brighter (like a real lava should):
![2](https://github.com/yquake2/yquake2/assets/43236181/158d95c3-cbb2-4aae-817e-3339d20be519)

I noticed that in OpenGL 1.4, it's the overbright bits cvar that controls how this looks. 0 and 1 are identical in most areas, except that lava/liquids are bright at 1. Can a feature/cvar be added for GL 3.2 for similar looking lava/liquids.

**Comment by DanielGibson** [comment]
What does the same scene look like in the soft renderer?

**Comment by AtifArshad1995** [comment]
> What does the same scene look like in the soft renderer?

This is software with sw_overbrightbits value set to 1.3:
![img](https://github.com/yquake2/yquake2/assets/43236181/1949fca7-e3a4-4938-92ed-e31cb8d2ed8f)

Lava is not as bright as that in OGL 1.4, but brighter than that of OGL 3.2

**Comment by DanielGibson** [comment]
I just pushed a fix to master, please test
