### ISSUE TITLE
Ubuntu 22.04.2 LTS: Where are the configuration files stored?

### ISSUE THREAD

**Issue by PzKpfw6** [yquake2/yquake2#1015]
I have recently moved from Windows, to Linux, and I have the old configuration from Windows with all of my keybinds. Where is the configuration stored in Ubuntu/Linux?

**Comment by PzKpfw6** [comment]
Never mind, I am retarded. For those who were wondering like I was, the configuration in stored in /home/tomas/.yq2/baseq2

**Comment by BjossiAlfreds** [comment]
If you prefer user data being saved to the Quake 2 folder, you can start the game with the -portable option.
