### ISSUE TITLE
Question about compiling

### ISSUE THREAD

**Issue by deuxsonic** [yquake2/yquake2#102]
I compiled YQ2 from source for the first time and I'm wondering if I need to also get the source for CTF and the mission packs and compile them for them to work properly with updates to the main game or is it okay to keep updating just the baseq2's game.dll and not the ones for CTF/Xatrix/Rogue? Previously I would wait for official releases because they came with everything I assumed compiled at the same time so I didn't worry about it all working.

**Comment by Yamagi** [comment]
Hello,
the API between the client / server and the game modules is unchanged from Quake II 3.21. So there's no need to recompile the game modules when you update your client.
