### ISSUE TITLE
Reckoning - game freeze in Core Reactor

### ISSUE THREAD

**Issue by quietust** [yquake2/yquake2#1024]
Partway through the map "Core Reactor", after taking the first power cube and entering the area behind the yellow forcefields (with a lava pool at the bottom), as soon as I try to ride the lift up to the second level the game completely freezes, leaving nothing but ambient sounds playing in the background.

Fortunately, I was able to avoid the freeze by noclipping through the ceiling to get to the second floor - once I was past that area, I was able to complete the rest of the map without problems.

Platform: Ubuntu 20.04 LTS
Version: 8.20 + xatrix-2.11 (built manually)
Renderer: OpenGL 3.2
Attachments: [config.cfg](https://github.com/yquake2/yquake2/files/11647865/config.txt), [savegame](https://github.com/yquake2/yquake2/files/11647857/save.zip)

**Comment by j4reporting** [comment]
> Version: 7.42+ctf1.06~dfsg-1 (installed via apt)

Are you  using the game saves created with the outdated version?  If yes, please try again with a new game launched   with the current version 8.20.

**Comment by quietust** [comment]
The savegame was indeed created with the older version, and upon replaying the level from scratch in 8.20 (with god mode and a stack of railguns) it didn't hang.

It would seem that whatever version of xatrix I had previously (2.07) contained a bug which corrupted something in the save itself, and 2.11 no longer produces that same corruption but still hangs if it was present.

Feel free to close.

**Comment by Yamagi** [comment]
The problem with the savegames is, that the level logic is encoded into the files. When  it was a logic bug in the older version just updating the source wasn't enough, you needed the new savegame.
