### ISSUE TITLE
Unable to install dependency packages in Void Linux

### ISSUE THREAD

**Issue by PzKpfw6** [yquake2/yquake2#1026]
I need to install dependencies for compilation and proper game play, but the Debian names do not work (build-essential libgl1-mesa-dev libsdl2-dev libopenal-dev libcurl4-openssl-dev). What are the names of the libraries for Void linux or what repository do I have to add?

**Comment by protocultor** [comment]
Never heard of Void Linux, and the little I've read about it, I'm not being sold. But here are some of the equivalent packages I've found just by looking for them:
```
build-essential		-> base-devel
libgl1-mesa-dev		-> glu-devel (I think)
libsdl2-dev		-> SDL2-devel
libopenal-dev		-> libopenal-devel
libcurl4-openssl-dev	-> libcurl-devel
```
You should give them a try.

**Comment by PzKpfw6** [comment]
Thank you for that, it is appreciated. I have forgotten to close this when i figured it out by simply searching them in the official Void Package site. All of those look familiar except for glu-devel.
