### ISSUE TITLE
No death messages (obituaries)

### ISSUE THREAD

**Issue by mooreye** [yquake2/yquake2#1035]
According to Quake 2 wiki, there should be custom death messages if killed by a specific monster, for example: https://quake.fandom.com/wiki/Light_Guard_(Q2)#Death_Message

In reality, only generic `Player died.` is ever displayed.

**Comment by BjossiAlfreds** [comment]
I think Zaero might have some monster related obituaries, but the official games never had this, only obituaries for player deaths in DM and co-op.
