### ISSUE TITLE
[Feature Request] Option to disable mouse acceleration / Enable raw mouse input

### ISSUE THREAD

**Issue by boafen** [yquake2/yquake2#1038]
I have looked through the doumentation and found option to disable mouse acceleration / Enable raw mouse input.
vkQuake2 for example has this feature and it would be great if yamagi did too!
Thank you for all the work you do for this amazing game!

**Comment by protocultor** [comment]
See the comments here: https://github.com/yquake2/yquake2/issues/1084
YQ2 uses raw mouse input, unless there's a bug in SDL 2.
Which OS are you using?

**Comment by boafen** [comment]
Windows 10 Pro - Version 22H2 - Build 19045.3930

I think i must have been experiencing a placebo back when i posted this as ive just tried feeling the same sensitivity in both Yamagi and the Quake 2 rerelease and they feel the same.

**Comment by protocultor** [comment]
AFAIK the rerelease also uses SDL2 for input, so any problem with SDL2 will be felt in both the rerelease and YQ2.
The important thing is that none of the mouse options in Windows should have any effect on the game.

**Comment by boafen** [comment]
Yeah just tried VKQuake 2 as well as Yamagi and the Rerelease and they all feel the same. Thanks for the help!
