### ISSUE TITLE
[Feature Request] Weapon and Inventory Binds

### ISSUE THREAD

**Issue by OpenRift412** [yquake2/yquake2#1042]
I think one of the core features that Yamagi is lacking is the ability to set binds for weapons and inventory items in the menus. Would be a much appreciated QoL feature.

**Comment by protocultor** [comment]
What's the difference with https://github.com/yquake2/yquake2/issues/958 ?

**Comment by Yamagi** [comment]
Yes, this a duplicate.

**Comment by OpenRift412** [comment]
Sorry, my bad.
