### ISSUE TITLE
OpenGL 4.6 Rendering Backend

### ISSUE THREAD

**Issue by atsb** [yquake2/yquake2#1045]
I have created an OpenGL 4.6 backend for Yamagi Q2, still have some cleaning up to do and other things (it is fully portable) and I have abided by every standard set in the other renderers, but just asking really if this would be wanted as a PR?

I know OpenGL 3.2 is supported more or less on modern cards, but it is nice to be able to have that flexibility to use in the future, more modern features or standards that aren't available in 3.2.

**Comment by Calinou** [comment]
The issue with OpenGL > 4.1 is that it doesn't run on macOS, with no way to work around this (unlike Vulkan).

**Comment by turol** [comment]
AMD GCN1.0 does support Vulkan (on Linux needs some kernel parameters). It's the previous generation (VLIW5?) that doesn't have Vulkan but does have OpenGL 4.5

**Comment by 0lvin** [comment]
@atsb if your render could reuse vulkan shaders and does not have external dependencies or cpp code, you can create PR to ref_vk repository, and gl4.6 render could temporary live with vulkan render until decision about stability of render from @Yamagi and @DanielGibson. 

What do you think about such idea?

**Comment by atsb** [comment]
@0lvin sounds good.  I’ll take a look at the vulkan renderer for reference.  The 4.6 renderer is in the same style as the 3.2 renderer (it was formed from it) with needed updates to colour (to make it look more like vanilla - slightly darker).  No dependencies and slots in exactly like the existing renderers.

I was planning on adding compute shaders similar to IronWail but as a first step, you’re right.  It’s better to get it living next to something and battle hardened first.

Thanks :) I’ll do a PR once I’ve looked at vulkan

**Comment by Yamagi** [comment]
The big problem with the Vulkan renderer is, that Vulkan implementation may abort the current frame at every API call. Quake II doesn't support that, at least not without a fair amount of refactoring. The only way to drop out of a frame is this scary and fragile longjmp() construct... And that is a real problem. Under Windows with afair Intel GPUs it was enough to alt-tab out of YQ2 and at the next API call the game would crash.

But back to the topic. Nice work with an OpenGL 4.6 renderer. I am little bit hesitant to add another renderer to the main repo. In fact I have this pipe dream to move the GL1 renderer into a separate repository and ship it as an optional part. Mostly to lessen the maintenance burden. What about an own repository for the GL4(?) renderer? Not a second renderer in the ref_vk repo, but a separate one. We could even give you write access to that repo...

**Comment by atsb** [comment]
Honestly, if that is what you would prefer then you'll get no complaints from me.

**Comment by Yamagi** [comment]
Hi @atsb, I just created a new repository yquake2/ref_gl4 and send you an invitation for write access to it. If you are still interested you can push and develop your code there. It would be nice if you could push it to `master` and not `main` to stay in line with the other older repositories.

**Comment by atsb** [comment]
Absolutely.  Thanks a lot!  I'll push it there in the next few days and continue work there.  I'll make sure to push it to master not main.

**Comment by 0lvin** [comment]
JFYI: I have added gl4 to remaster sources: https://github.com/yquake2/yquake2remaster/commit/637933a23c5aee50ba6d77d09218d7b685219fb4

**Comment by atsb** [comment]
Thanks @0lvin I will likely do a dll release once the optional ref_gl4 discovery code is added to YQ2 so folks could use it.

**Comment by atsb** [comment]
There seems to be an issue on current builds that yquake2 refuses to detect and populate the rendering list for ref_gl4.dll / ref_gl4.so.  I removed gl3 and renamed it just to be sure and sure enough, it loads fine.  But for some reason, isn't being detected in its normal state.

**Comment by 0lvin** [comment]
> There seems to be an issue on current builds that yquake2 refuses to detect and populate the rendering list for ref_gl4.dll / ref_gl4.so. I removed gl3 and renamed it just to be sure and sure enough, it loads fine. But for some reason, isn't being detected in its normal state.

Menu does not automatically detects render list, for show new render need to add gl4 to list of known renders, look to https://github.com/yquake2/yquake2remaster/blob/8.31RR3/src/client/menu/videomenu.c#L114. 

Also could be apply automatic creation of windows binaries for gl4, look to example for ref_vk: https://github.com/yquake2/ref_vk/blob/master/.github/workflows/windows.yml

**Comment by Yamagi** [comment]
Done in e72ef48ae7ead7b7de4aa45f3dbde51345315703.

**Comment by 0lvin** [comment]
@atsb it looks like https://github.com/glhrmfrts/empros-quake2 has some additional cool features, maybe some of it is worth of backporting as gl4 has no limitation in OpenGL supported level as based on latest API version, what do you think?

**Comment by atsb** [comment]
I'll take a look, seems quite exciting!
