### ISSUE TITLE
We kindly request your assistance in implementing .t3d loading and processing for our project. This 3D format is essential for our open-source engine, reminiscent of the Unreal/Unreal Tournament era. Your expertise and support in this matter would be greatly appreciated.  Thank you for considering our plea, and we look forward to your valuable contribution.  (relevant files: model_brush.c, relevant function: void T3d_Attempt_Which_will_Mod_OBJ_Load(dp_model_t *mod, void *buffer, void *bufferend)

### ISSUE THREAD

**Issue by chaosesqueteam** [yquake2/yquake2#1056]
We kindly request your assistance in implementing .t3d loading and processing for our project. This 3D format is essential for our open-source engine, reminiscent of the Unreal/Unreal Tournament era. Your expertise and support in this matter would be greatly appreciated.

Thank you for considering our plea, and we look forward to your valuable contribution.

(relevant files: model_brush.c, relevant function: void T3d_Attempt_Which_will_Mod_OBJ_Load(dp_model_t *mod, void *buffer, void *bufferend)

**Comment by Yamagi** [comment]
This is not in our scope. We aim to preserve Q2, not being an engine to be used for total conversions. If you want this - you should really consider using a more modern engine or at least something which isn't as buggy and fragile as Q2 - you should fork our code and implement your changes there.
