### ISSUE TITLE
Potential New Icon

### ISSUE THREAD

**Issue by deuxsonic** [yquake2/yquake2#106]
![q2_256](https://cloud.githubusercontent.com/assets/7662909/10709976/53efb824-7a10-11e5-9158-573e0bef3fce.png)

I created a black Quake II icon file that includes all sizes in all bit depths. If you like it you can use it.

http://www.mediafire.com/download/t1eyoqdjd5rho2j/q2.ico (Can't attach icons apparently.)
http://www.mediafire.com/download/a2ritmuqrpt129b/q2.svg (I think some platforms use vectors for icons so here's the vector version.)

**Comment by Yamagi** [comment]
That looks really nice. I just need to make sure that MinGWs resource compiler can handle the file.

**Comment by Yamagi** [comment]
Committed. Thank you. :)
