### ISSUE TITLE
Necessary commands to add monsters/items to .ent files

### ISSUE THREAD

**Issue by maximus105** [yquake2/yquake2#1063]
A complete list of commands with a description of their actions is needed to add all possible monsters/items to the .ent files. The .ent files from the mapfixes folder will be used. Should these commands be placed at the beginning or at the end of the .ent file? So that when loading maps, added monsters/items appear correctly on the map. And what affects the number of monsters/items depending on the difficulty level of the game when starting a new game?

**Comment by BjossiAlfreds** [comment]
The order of entities doesn't matter except in 3 cases:
1. The first entity must be worldspawn
2. Teamchained entities (the "team" field) will choose the first entity as the team master
3. First player start entity has priority for loading map from console

Always add entities at the end. This avoids pre-cache desync issues if you make changes to the ent file and use it with an existing savegame.

The spawnflags field controls when entities spawn. 256 = not easy, 512 = not medium, 1024 = not hard/nightmare, 2048 = not deathmatch, 4096 = not co-op (only used by GroundZero I think)

Add these different values together to get your spawnflags. Example: If you want an entity to be hard/nightmare-only, then it's 256 + 512 = 768.

Here's an example entity:
{
"classname" "monster_gladiator"
"origin" "0 50 100" (replace numbers with actual co-ordinates)
"angle" "270"
"spawnflags" "768" (hard/nightmare-only, spawns in all game modes)
}

As a side note, are you on Windows? My custom game dll has a lot of features for level manipulation and lots of other gameplay customization. If it's something you might be interested in send me an email.
