### ISSUE TITLE
Yquake2 does not start after compiling with buildenv

### ISSUE THREAD

**Issue by maximus105** [yquake2/yquake2#1064]
Everything compiles without errors, files

game.dll 
ref_soft.dll
ref_gles3.dll
ref_gl3.dll
ref_gl1.dll
q2ded.exe
quake2.exe
yquake2.exe

are appear in the \release folder when executing the make command via mingw64.exe. But when I run quake2.exe or yquake2.exe, the game does not start with an error message "An error occurred while starting the application (0xc000007b). To exit the application, click OK". While the official yquake2 v8.20 starts properly.

make
Build configuration

YQ2_ARCH = x86_64 COMPILER = gcc
WITH_CURL = yes
WITH_OPENAL = yes
WITH_RPATH = yes
WITH_SYSTEMWIDE = no
WITH_SYSTEMDIR =

===> Building yquake2.exe
make release/yquake2.exe
make[1]: Entering directory '/home/User/yquake2'
===> CC src/backends/generic/misc.c
===> CC src/client/cl_cin.c
===> CC src/client/cl_console.c
===> CC src/client/cl_download.c
===> CC src/client/cl_effects.c
===> CC src/client/cl_entities.c
===> CC src/client/cl_input.c
===> CC src/client/cl_inventory.c
===> CC src/client/cl_keyboard.c

When running mingw32.exe and compiling, yquake2 starts normally.

make
Build configuration

YQ2_ARCH = i386 COMPILER = gcc
WITH_CURL = yes
WITH_OPENAL = yes
WITH_RPATH = yes
WITH_SYSTEMWIDE = no
WITH_SYSTEMDIR =

===> Building yquake2.exe
make release/yquake2.exe
make[1]: Entering directory '/home/User/yquake2'
===> CC src/backends/generic/misc.c
===> CC src/client/cl_cin.c
===> CC src/client/cl_console.c
===> CC src/client/cl_download.c
===> CC src/client/cl_effects.c
===> CC src/client/cl_entities.c
===> CC src/client/cl_input.c
===> CC src/client/cl_inventory.c
===> CC src/client/cl_keyboard.c

**Comment by Yamagi** [comment]
A 64 bit build requires 64 bit libraries. You need at least the 64 bit version of SDL2.dll. You can find the latest build under https://github.com/libsdl-org/SDL/releases/tag/release-2.28.3

**Comment by maximus105** [comment]
Thanks. Where can I download 64 bit libraries curl.dll and openal32.dll ?

**Comment by apsoyka** [comment]
I ran into this issue too, and it didn't even occur to me that I was building a 64-bit binary.

You can find a copy of `libcurl-x64.dll` from [curl.se/windows](https://curl.se/windows/), and a copy of `soft_oal.dll` from [openal-soft.org/openal-binaries/](https://openal-soft.org/openal-binaries/).

**Comment by Yamagi** [comment]
The official openal-soft DLL should work. I'm not so sure about the curl DLL, because in the past they were problematic. I'm building the curl DLL shipped with releases and testbuilds myself. However most players won't need curl anyways, it's only necessary for HTTP downloads.
