### ISSUE TITLE
"Vanilla Mode"

### ISSUE THREAD

**Issue by OpenRift412** [yquake2/yquake2#1066]
I think it would be nice to have a toggle that allows for vanilla game behavior without any of the fixes, allowing for faithful gameplay in a modern port. I can only assume that this is already a thing when recording demos, since Yamagi able to play back vanilla demos without any desync.

**Comment by SilentMRG** [comment]
As far as I know, yquake2 offers a vanilla experience with small adjustments here and there, and in my humble opinion these adjustments help more than hinder the overall experience. In other words, for you to have a more vanilla experience than the one presented in yquake2, just install Quake 2 directly from the retail disc on an old machine. Or you can choose to play yquake2 in Software mode or through OpenGL 1.4.

**Comment by OpenRift412** [comment]
> As far as I know, yquake2 offers a vanilla experience with small adjustments here and there, and in my humble opinion these adjustments help more than hinder the overall experience. In other words, for you to have a more vanilla experience than the one presented in yquake2, just install Quake 2 directly from the retail disc on an old machine. Or you can choose to play yquake2 in Software mode or through OpenGL 1.4.

Noted. I mostly bring this up for the sake of compatibility with speedrunning, unless that's out of scope for Yamagi.

**Comment by SilentMRG** [comment]
According to the yquake2 home page: 

"Yamagi Quake II is an enhanced client for id Software's Quake II with focus on offline and coop gameplay. Both the gameplay and the graphics are unchanged, but many bugs in the last official release were fixed and some nice to have features like widescreen support and a modern OpenGL 3.2 renderer were added. Unlike most other Quake II source ports Yamagi Quake II is fully 64-bit clean. It works perfectly on modern processors and operating systems. Yamagi Quake II runs on nearly all common platforms; including FreeBSD, Linux, NetBSD, OpenBSD, Windows and macOS (experimental)."

There is support for a single player, so it is possible to speedrun, I don't see that bug fixes will interfere with this type of gameplay.

**Comment by SilentMRG** [comment]
![0 tmfbLDU_hIeg0B3B](https://github.com/yquake2/yquake2/assets/62117728/fb340dda-1034-40ad-9efd-2219533df785)

**Comment by BjossiAlfreds** [comment]
Speedrun leaderboards tend to be pretty strict about what mods (if any) you use on PC. Though I'm not aware of an active Quake 2 speedrunning community like the ones for Mario 64 or Golden Eye.

Question is what counts as a mod. Just re-compiling an old codebase could have subtle effects on the in-game experience that add slight dis/advantage for speedruns.
