### ISSUE TITLE
Since commit 7456daf *all* savegame slots invisible on Linux. 

### ISSUE THREAD

**Issue by xorw** [yquake2/yquake2#107]
The savegames are actually written into "~/.yq2/baseq2/save" but since commit 7456daf65f1855549c4fe3cd959efa27b3da1593  *all* savegame slots are shown as *empty* in the loading screen on Linux. Deleting "~/.yq2/baseq2/save" and creating new savegames does not correct this behavior.

Commit 2e82fe85fdc60967ffd2640d031f4f558473dd35 (and older) does not have this problem, savegames from from same and following commits are working properly.

My system is: Debian/testing (Linux 4.2.2 #1 SMP Thu Oct 1 01:16:34 CEST 2015 i686 GNU/Linux), quake 2 game data is soft linked from "~/.yq2/baseq2".

**Comment by Yamagi** [comment]
Hi,
I need some more data to analyze the problem. Can you start the game with filesystem debugging ('./quake2 +set fs_debug 1'), open the "Load" menu and send me the output? Additionally the output of 'find ~/.yq2/baseq2/save' would be nice.

**Comment by DanielGibson** [comment]
I can't reproduce it either.
can you give us the output of `ls -l ~/.yq2/` and `ls -l ~/.yq2/baseq2/`?
furthermore, what's your actual homedir? any special characters in your username or something?

**Comment by xorw** [comment]
here is my '~/.yq2' dirctory zipped after running './quake2 +set fs_debug 1' and entering load menu, using commit 1d709e5e27089e4e899419899214a8b3183a86d9

![yq2_zip](https://cloud.githubusercontent.com/assets/15349589/10776935/7a80ad14-7d16-11e5-831f-407ffca46a5a.png)

**Comment by DanielGibson** [comment]
this probably shouldn't break savegame handling, but: no pak1.pak and pak2.pak?

furthermore: I'd still like the output of ls -l, see above :)

**Comment by xorw** [comment]
the quake 2 disc I've used to get the game data from does only have pak0.pak.
and I've played the game completely with an older version of yquake2.

(ls -l ~/.yq2/) 
baseq2  console_history.txt

(ls -l ~/.yq2/baseq2/)
config.cfg  music  pak0.pak  players  qconsole.log  save  video

**Comment by DanielGibson** [comment]
pak1 and pak2 are from the patch, see section 1.2 in the README.

the output is not from "ls -l" (lowercase-L).

**Comment by xorw** [comment]
ok, added pak1 and pak2; used './quake2 +set fs_debug 1' again, 
no change - tried load savegame, started new game, created new savegeme, tried to load new savegame - all savegame slots still shown as empty...

(yq2.tar.xz.png) 
![yq2 tar xz](https://cloud.githubusercontent.com/assets/15349589/10777686/39256e60-7d1e-11e5-958f-6bff66b47be5.png)

**Comment by DanielGibson** [comment]
could you also start the game in a terminal and paste the output from starting until "Console initialized."? (That part is missing in qconsole.log)
It should look somehow like:
```
Yamagi Quake II v5.31
=====================

Client build options:
 + SDL2
 - CD audio
 + OGG/Vorbis
 + OpenAL audio
 + Zip file support
Platform: Linux
Architecture: amd64
Byte ordering: little endian

WARNING: refusing to create relative path '../../q2_data/baseq2'.
Added packfile '../../q2_data/baseq2/pak0.pak' (3307 files).
Added packfile '../../q2_data/baseq2/pak1.pak' (279 files).
Added packfile '../../q2_data/baseq2/pak2.pak' (2 files).
Using binary dir /home/caedes/gamedev/yquake2-git/release/baseq2/ to fetch paks
Using '/home/caedes/.yq2/baseq2' for writing.
execing default.cfg
couldn't exec yq2.cfg
execing config.cfg
basedir is write protected.
Console initialized.
```

**Comment by DanielGibson** [comment]
Btw, while what you're doing should probably work in theory, it'd be easier if you didn't symlink all the files to ~/.yq2/baseq2/, but just started the game with

`./quake2 +set basedir  /mnt/sdb1/assets/quake2`

**Comment by xorw** [comment]
Thanks :) 
Using './quake2 +set basedir /mnt/sdb1/assets/quake2' AND removing all (linked) game data files from '~/.yq2/baseq2' fixes the problem. 

But isn't it kind of strange that even '+set basedir' does not work as long as there are any game data files in '~/.yq2/baseq2'? Was this behavior intended?

**Comment by Yamagi** [comment]
That was a braino on my side. The issue should be fixes now. Thank you for your help.
