### ISSUE TITLE
cvars not recognized

### ISSUE THREAD

**Issue by Q3BFG10K** [yquake2/yquake2#1073]
Yamagi 8.30 Win10-64, GOG version.

**aimfix**
**g_monsterfootsteps**
**g_machinegun_norecoil**

Aren't recognized by the program (i.e. console says unknown command when you type them).

![quake2](https://github.com/yquake2/yquake2/assets/40132921/bb415bc6-972f-41d5-bfee-f88d86c18103)

Every 5 program launches or so they randomly work and are accepted, but then stop working next program launch.

**Comment by 0lvin** [comment]
Footstep cvar is supported only with baseq2 game, have you used custom mod? Maybe issues is related used game library.

**Comment by BjossiAlfreds** [comment]
Did you put the game.dll file into the baseq2 folder?

**Comment by Q3BFG10K** [comment]
> Footstep cvar is supported only with baseq2 game, have you used custom mod? Maybe issues is related to used game library. Have you used original game or some mod?

No mods, not even official expansion packs, just baseq2.

> Are you by chance trying to run these before starting a game session? These cvars are part of the game.dll so they are not initialized until you start a game session (start a new game, load a save, etc.).

Yes, that's it. So is **autoexec.cfg** required to make them stick?

**Comment by BjossiAlfreds** [comment]
You can create your own cfg files and then put +exec <your_cfg_name>.cfg in the launch params of the shortcut. You can also set cvars there directly: +set aimfix 1 +set g_monsterfootsteps 1 ....

**Comment by apartfromtime** [comment]
Avoid using autoexec.cfg, may not have the intended behaviour.

**Comment by Yamagi** [comment]
I can't reproduce this, neither under Windows 10 nor under Linux. Are you sure that always the same game.so get's loaded? The game prints the build date into the console:

```
-------- game initialization -------
Loading library: game.so
Game is starting up.
Game is baseq2 built on Nov 18 2023.
------------------------------------
```

If the game loads another DLL each other start, we still or again have a problem with the fragile search path logic.

**Comment by Q3BFG10K** [comment]
I figured it out, I was using **+disconnect** to stop startup demos playing. It works after I remove it.

Is there a better way to stop startup demos playing, aside from loading an invalid name?
