### ISSUE TITLE
Noisy video using OpenGL using AMDGPU

### ISSUE THREAD

**Issue by CosmicHeron** [yquake2/yquake2#1074]
With the recent 8.30 update I've been having an odd issue with yquake2. If I select either OpenGL 3.2 or OpenGL ES3 (for unknown reason unable to select Vulkan using the vk_ref renderer anymore, it always reverts back to OpenGL 3.2), the game runs but there are random, pure blue pixels/texels appearing and disappearing constantly. This does not happen if I switch to software rendering.

As mentioned in the title, I'm running an RX7900XTX using the `amdgpu` Mesa drivers, with yquake2 installed from the [yamagi-quake2](https://aur.archlinux.org/packages/yamagi-quake2) AUR package (for completeness sake, the AUR package of the Vulkan renderer that stopped working: [yamagi-quake2-ref_vk](yamagi-quake2-ref_vk)). These visual artifacts do not happen in any other game running either OpenGL or Vulkan, nor do they seem to appear when testing the game on a laptop using Intel UHD Graphics 620 using the `i915` Mesa drivers, so I can only assume some recent change to the OpenGL renderers broke something with how they interact with AMD GPUs?

**Comment by DanielGibson** [comment]
YQ2 8.30 broke the rendering API, so the yamagi-quake2-ref_vk AUR must be updated to latest master of https://github.com/yquake2/ref_vk

@0lvin might make sense to create a new release of ref_vk?

Otherwise I guess that your problem with the OpenGL renderers are some kind of driver bug (either buggy mesa release or maybe incomplete upgrade or whatever)

**Comment by CosmicHeron** [comment]
Switching to [yamagi-quake2-ref_vk-git](https://aur.archlinux.org/packages/yamagi-quake2-ref_vk-git) and I can now select the Vulkan again and it's not exhibiting any glitches.

**Comment by Yamagi** [comment]
I can test the GL3 renderer tomorrow on my Arch Linux system and my 5700XT. However I don't expect any problems, I would have noticed them two weeks ago when I tested the 8.30 release and we hadn't any bigger changes to the GL3 renderer in ages.

Can you send us you config, in case that some non standard options causes it?

**Comment by CosmicHeron** [comment]
I've reset it just now to make sure it was not some odd configuration from an older version causing the issue but I still got the same random blue texels flickering when using the OpenGL renderers.

```
// generated by quake, do not modify
unbindall
bind TAB "inven"
bind ENTER "invuse"
bind SPACE "+moveup"
bind + "sizeup"
bind - "sizedown"
bind 0 "use BFG10K"
bind 1 "use Blaster"
bind 2 "use Shotgun"
bind 3 "use Super Shotgun"
bind 4 "use Machinegun"
bind 5 "use Chaingun"
bind 6 "use Grenade Launcher"
bind 7 "use Rocket Launcher"
bind 8 "use HyperBlaster"
bind 9 "use Railgun"
bind = "sizeup"
bind [ "invprev"
bind ] "invnext"
bind a "+moveleft"
bind b "use rebreather"
bind d "+moveright"
bind e "use environment suit"
bind g "use grenades"
bind h "wave 0"
bind i "use invulnerability"
bind j "wave 1"
bind k "wave 2"
bind l "wave 3"
bind p "use power shield"
bind q "use quad damage"
bind s "+back"
bind t "messagemode"
bind u "wave 4"
bind w "+forward"
bind x "score"
bind BACKSPACE "invdrop"
bind PAUSE "pause"
bind UPARROW "+forward"
bind DOWNARROW "+back"
bind LEFTARROW "+left"
bind RIGHTARROW "+right"
bind CTRL "+movedown"
bind SHIFT "+speed"
bind F1 "cmd help"
bind F2 "menu_savegame"
bind F3 "menu_loadgame"
bind F4 "menu_keys"
bind F5 "menu_startserver"
bind F6 "echo Quick Saving...; wait; save quick"
bind F9 "echo Quick Loading...; wait; load quick"
bind F10 "menu_quit"
bind F12 "screenshot"
bind MOUSE1 "+attack"
bind MWHEELDOWN "weapprev"
bind MWHEELUP "weapnext"
set adr0 ""
set adr1 ""
set adr2 ""
set adr3 ""
set adr4 ""
set adr5 ""
set adr6 ""
set adr7 ""
set adr8 ""
set aimfix "0"
set al_device ""
set al_driver "libopenal.so.1"
set allow_download "1"
set allow_download_maps "1"
set allow_download_models "1"
set allow_download_players "0"
set allow_download_sounds "1"
set busywait "1"
set cfg_unbindall "1"
set cl_async "1"
set cl_audiopaused "1"
set cl_gun "2"
set cl_http_downloads "1"
set cl_libcurl "libcurl.so.3"
set cl_limitsparksounds "0"
set cl_loadpaused "1"
set cl_maxfps "-1"
set cl_r1q2_lightstyle "1"
set cl_run "1"
set cl_showfps "0"
set cl_unpaused_scvis "1"
set cl_vwep "1"
set colorterminal "1"
set coop_elevator_delay "1.0"
set coop_pickup_weapons "1"
set crosshair "1"
set crosshair_3d "0"
set crosshair_3d_glow "0"
set crosshair_scale "-1"
set exponential_speedup "0"
set fov "90"
set freelook "1"
set g_commanderbody_nogod "0"
set g_footsteps "1"
set g_machinegun_norecoil "0"
set g_monsterfootsteps "0"
set g_select_empty "0"
set gender "male"
set gender_auto "1"
set gl1_stereo "0"
set gl1_stereo_convergence "1"
set gl1_stereo_separation "-0.4"
set gl3_colorlight "1"
set gl3_intensity "1.5"
set gl3_intensity_2D "1.5"
set gl3_libgl ""
set gl3_overbrightbits "1.3"
set gl3_particle_fade_factor "1.2"
set gl3_particle_size "40"
set gl3_particle_square "0"
set gl3_usebigvbo "-1"
set gl3_usefbo "1"
set gl_finish "0"
set gl_polyblend "1"
set gl_texturemode "GL_LINEAR_MIPMAP_LINEAR"
set gyro_calibration_x "0.0"
set gyro_calibration_y "0.0"
set gyro_calibration_z "0.0"
set gyro_mode "2"
set gyro_pitchsensitivity "1.0"
set gyro_turning_axis "0"
set gyro_yawsensitivity "1.0"
set hand "0"
set horplus "1"
set hostname "noname"
set in_grab "2"
set in_sdlbackbutton "0"
set joy_flick_smoothed "8.0"
set joy_flick_threshold "0.65"
set joy_forwardsensitivity "1.0"
set joy_haptic_distance "100.0"
set joy_haptic_filter "!weapons/*grenlb !weapons/*hgrenb !weapons/*open !weapons/*warn weapons/ player/*land player/*burn player/*pain player/*fall player/*death players/*burn players/*pain players/*fall players/*death doors/ plats/ world/*dish  world/*drill2a world/*dr_ world/*explod1 world/*rocks world/*rumble  world/*quake  world/*train2 "
set joy_haptic_magnitude "0.0"
set joy_layout "0"
set joy_left_deadzone "0.16"
set joy_left_expo "2.0"
set joy_left_snapaxis "0.15"
set joy_pitchsensitivity "1.0"
set joy_right_deadzone "0.16"
set joy_right_expo "2.0"
set joy_right_snapaxis "0.15"
set joy_sidesensitivity "1.0"
set joy_yawsensitivity "1.0"
set logfile "1"
set lookstrafe "0"
set m_filter "0"
set m_forward "1"
set m_pitch "0.022"
set m_side "0.8"
set m_up "1"
set m_yaw "0.022"
set name "Player"
set ogg_enable "1"
set ogg_ignoretrack0 "0"
set ogg_pausewithgame "0"
set ogg_shuffle "0"
set ogg_volume "0.7"
set r_2D_unfiltered "0"
set r_anisotropic "16"
set r_clear "0"
set r_consolescale "-1"
set r_customheight "768"
set r_customwidth "1024"
set r_farsee "0"
set r_fixsurfsky "0"
set r_gunfov "80"
set r_hudscale "-1"
set r_lerp_list ""
set r_menuscale "-1"
set r_mode "25"
set r_modulate "1"
set r_msaa_samples "4"
set r_nolerp_list "pics/conchars.pcx pics/ch1.pcx pics/ch2.pcx pics/ch3.pcx"
set r_retexturing "1"
set r_scale8bittextures "0"
set r_shadows "0"
set r_validation "0"
set r_videos_unfiltered "0"
set r_vsync "1"
set rate "8000"
set s_doppler "0"
set s_feedback_kind "0"
set s_khz "44"
set s_loadas8bit "0"
set s_mixahead "0.14"
set s_occlusion_strength "0"
set s_openal "1"
set s_ps_sorting "1"
set s_reverb_preset "-1"
set s_underwater "1"
set s_underwater_gain_hf "0.25"
set s_volume "0.7"
set sensitivity "3"
set skin "male/grunt"
set sv_entfile "1"
set vid_displayindex "0"
set vid_displayrefreshrate "-1"
set vid_fullscreen "1"
set vid_gamma "1.0"
set vid_highdpiaware "0"
set vid_maxfps "300"
set vid_pauseonfocuslost "0"
set vid_rate "-1"
set vid_renderer "vk"
set viewsize "100"
set vk_custom_particles "1"
set vk_device "-1"
set vk_dynamic "1"
set vk_finish "0"
set vk_lmaptexturemode "VK_MIPMAP_LINEAR"
set vk_mip_nearfilter "0"
set vk_overbrightbits "1.0"
set vk_particle_att_a "0.01"
set vk_particle_att_b "0.0"
set vk_particle_att_c "0.01"
set vk_particle_max_size "40"
set vk_particle_min_size "2"
set vk_particle_size "40"
set vk_pixel_size "1"
set vk_postprocess "1"
set vk_sampleshading "1"
set vk_texturemode "VK_MIPMAP_LINEAR"
set vk_underwater "1"
set windowed_mouse "0"
```

**Comment by 0lvin** [comment]
@CosmicHeron I have tagged new ref_vk [1.0.6 release](https://github.com/yquake2/ref_vk/releases/tag/v1.0.6)
without windows build for now. 

You could try also gl4 version from [ReRelease](https://github.com/yquake2/yquake2remaster) repository. Repository has all current renders and merged baseq2/CTF/rogue/xatrix to single library.

Gl4 could also built from [ref_vk](https://github.com/yquake2/ref_gl4) repository.

**Comment by CosmicHeron** [comment]
Thanks, ref_vk 1.0.6 works perfect. I have built and ran the ReRelease version just now with the remaster assets. Other than the lighting not being right with the OpenGL renderers, I don't seem to get any blue texel artifacts with them. And Vulkan worked as expected from what I saw.

**Comment by Yamagi** [comment]
I gave it a try. I don't see the problem on my rather up to date Arch Linux with `mesa 1:23.2.1-2` on an Radeon 5700XT. However, there are differences between Navi1 and Navi3 GPUs. So this isn't 100% compareable:

![image](https://github.com/yquake2/yquake2/assets/1224576/fb16a029-034b-4b05-903b-709ff0482bc1)

You could try it with `gl3_usefbo 0`. I don't think that it will make any difference, but it may be worth a try. You could also try downgrading to 8.20 and see if the problem persists.

**Comment by CosmicHeron** [comment]
I've tried all the versions back to 8.00, still the same glitching on OpenGL renderers, so I guess the issue has been around but haven't noticed it because I always switched to Vulkan. What's interesting though, the blue texels only show up on the map geometry. The player hand and weapon, enemies, items, explosive barrels and such are unaffected and will even be drawn over those texels partially obscuring them. The same goes if I look into the skybox. So I guess something isn't going right at that specific rendering stage.

**Comment by Yamagi** [comment]
I have again tried to reproduce this, with my 5700XT and an Ryzen 5700G IGP. I still don't see the problem. Given that this is the only report and you are seeing the artifacts back to 8.00 - released more than 2 years ago - I guess this is either something in your setup or (another) bug in the radeonsi GPU driver when running on RDNA3 GPUs.
