### ISSUE TITLE
Unable to do Full Build of Source on Windows

### ISSUE THREAD

**Issue by deuxsonic** [yquake2/yquake2#108]
After replacing my copy of filesystem.c with this copy, I can no longer build the source on Windows even after deleting the build directory and rebuilding everything:

===> CC src/common/filesystem.c
src/common/filesystem.c:421:1: error: conflicting types for 'FS_FOpenFile'
 FS_FOpenFile(const char *name, fileHandle_t *f, qboolean gamedir_only)
 ^
In file included from src/common/filesystem.c:28:0:
src/common/header/common.h:689:5 note: previous declaration of 'FS_FOpenFile' was here
int FS_FOpenFile(const char *name, fileHandle_t *f, fsMode_t mode);
     ^
make[1]: *** [build/client/src/common.filesystem.o] Error 1
make[1]: Leaving directory '/c/mingw/yquake2-master'
make: *** [client] Error 2

Since it does it no matter what now, I'm lost since nothing else has changed since.

**Comment by Yamagi** [comment]
There's something wrong with your code checkout. common.h:689 is 'int FS_FOpenFile(const char *name, fileHandle_t *f, qboolean gamedir_only);' (https://github.com/yquake2/yquake2/blob/master/src/common/header/common.h#L689) and not 'int FS_FOpenFile(const char *name, fileHandle_t *f, fsMode_t mode);' as in your code...

**Comment by deuxsonic** [comment]
What should I do to fix it?
 


     On Wednesday, October 28, 2015 5:14 AM, Yamagi <notifications@github.com> wrote:
   

 Closed #108.—

**Comment by Yamagi** [comment]
7456daf65f1855549c4fe3cd959efa27b3da1593 wasn't limited to filesystem.c, it was a commit with changes all over the code. So just copying filesystem.c wasn't enough. The best way is to clone the repo with git and update it with 'git pull'.

**Comment by deuxsonic** [comment]
I didn't realize more files were changed. Silly me. Usually it's faster for me to just make the changes in the code myself rather than set everything up each time there's a change.

**Comment by DanielGibson** [comment]
not really..
once you've cloned the code with git, doing a `git pull` is really the easiest and fastest way to get the latest changes.
