### ISSUE TITLE
*nix: config files should be located at XDG-compliant locations instead of ~/.yq2

### ISSUE THREAD

**Issue by axltxl** [yquake2/yquake2#109]
Nowadays, many programs deployed on *nix variants are adopting `XDG_CONFIG_HOME` as their way to locate/save their configuration files. As a step to (sort of) modernize quake2, I think `yq2` should consider this, since the adoption of `XDG_CONFIG_HOME` has helped a lot tackling overpopulation of dotfiles inside a `$HOME` directory, besides, it has given a consistent directory that an user can always look at should he/she needs to get access to a config file. The approach on that would be something like this:

* Refactoring @ `src/common/header/common.h `: get rid of `CFGDIR` and implement a function/macro for that (let's call it for now `get_cfg_dir`):

```c
char *get_cfg_dir(void) {
#ifdef _WIN32
    return "YamagiQ2";
#else
    char config_home[32]; // this will hold the config directory

   // let's see about that XDG_CONFIG_HOME
    if (getenv("XDG_CONFIG_HOME")) {
        sprintf(config_home, "%s/yq2", getenv("XDG_CONFIG_HOME"));
    }
    else {
        // there is no XDG_CONFIG_HOME on this system
        // so the fallback will be to look at $HOME/.config
        sprintf(config_home, "%s/.config/yq2", getenv("HOME"));

      // at this point, yq2 can look in $HOME/.yq2 followed by a deprecation warning
      // or something alike
    }

    // you've been served, Sir
    return config_home;
#endif
}
```

* Replace `CFGDIR` with `get_cfg_dir` all across the project
* Once done, pray for the best :)

Cheers to everyone :wine_glass: !!

Source: http://standards.freedesktop.org/basedir-spec/latest/ar01s03.html

**Comment by DanielGibson** [comment]
just some notes about the code, in case you're using that kind of code elsewhere:
* OSX would need to be handled differently, I doubt that people are used to XDG there
* 32chars are not enough for the path (in case usernames are a bit longer or `$XDG_DATA_HOME` is not just `~/.config/`. `/home/HansPeterWurst/.config/yq2/` wouldn't fit)
* related: `sprintf()` will overflow in  that case. don't use it, use `snprintf()` instead.

**Comment by axltxl** [comment]
* You are totally right about OSX, I assumed too quickly that OSX was compliant with XDG. However, there things pointed out in [this post](http://stackoverflow.com/questions/3373948/equivalents-of-xdg-config-home-and-xdg-data-home-on-mac-os-x) that are considerable for that approach, nevertheless, OSX is most likely out of the picture since my proposal applies to *nix variants aware of XDG standards (almost any Desktop-based Linux distro *I think* FreeBSD as well).
* The code I posted was merely hypothetical, I just wrote it on-the-fly, so to say :sweat_smile:. There are likely several things I didn't think about as I just wanted to let myself be understood. By the way, many thanks for your thorough and precise remarks on my code :+1: :relaxed:. The actual implementation would be obviously way different.
* If you guys are OK with such proposal, I could start a feature branch on this matter.

Cheers :wine_glass:

**Comment by DanielGibson** [comment]
I'd wait for Yamagi's thoughts on this before starting a feature branch ;-)

**Comment by Yamagi** [comment]
I don't like this idea. There're several reasons:
* XDG is unportable. It may work on most Linux distributions. On FreeBSD things start to get dirty. But YQ2 runs on several more platforms. NetBSD, OpenBSD, once there was a HP-UX guy and there're still some of the Solaris 9 on sun4u folks left.
* User would need to move their again. In my nightmares I'm still dreaming of the flameware after I changed .quake2 to .yq2. At that time I had at least technical reasons.
* I'm an old, grumpy, conservative guy and in my opinion configuration data belongs into  ~/.$app and not into a random path somewhere in my file system.

**Comment by axltxl** [comment]
What about this?:

* The feature is entirely optional and up to the user whether he wants to use it. 
* A CMake flag (let's say `YQ2_USE_XDG`) would trigger this feature on compile time, otherwise, `yq2` would assume `~/.yq2` as always.

Still, if you consider this too much of a hassle, then no feature branch will be considered on my account. By the way, thanks for your quick feedback.

Peace :wine_glass:

**Comment by DanielGibson** [comment]
If implementing it optionally, I see two probable outcomes:
1. Some Linux Distro starts enabling XDG in their Yamagi Quakle2 packages and people will be confused where their configs and savegames are
2. No Linux Distro enables this and nobody uses the optional code

**Comment by Yamagi** [comment]
Don't missunderstand me. While I personally don't like ~/.config/, I would agree if YQ2 was a young project. Most newer desktop applications use XDG, maybe some users search their savegames in ~/.config/. But YQ2 is an old project with a huge user base. All users would need to migrate their config, server admins would need to alter their scripts and so on. It's not worth the hassle. Let's stick to ~/.yq2 and invest our energy in newer projects with less history and less broken code.

**Comment by axltxl** [comment]
It's OK, I see the point :sweat_smile:. It looks like such a feature would be trouble at best. Indeed, it's not worth the hassle. I agree. Thanks for your time!.

Cheers :wine_glass:

**Comment by Manuel-K** [comment]
To make the matter more complicated, the savegames should ideally go to ~/.local/share and the config to ~/.config. This makes the XDG stuff a huge nuisance.

**Comment by DanielGibson** [comment]
> To make the matter more complicated, the savegames should ideally go to ~/.local/share and the config to ~/.config.

not really sure about that.. if I recall correctly, this was discussed on the SDL mailing list and someone actually asked the freedesktop guys and they said that it should probably all go to `~/.config/`
I think ~/.local/share/ is mostly for data you  wouldn't wanna backup when reinstalling your system (like browser cache and things like that)

(unfortunately, SDL2's `SDL_GetPrefPath()` returns `~/.local/share/<gamename>` - this was implemented and released like that before people asked the freedesktop guys..)

**Comment by mckaygerhard** [comment]
thansk god and extraterrestial for that facts:

>I'm an old, grumpy, conservative guy

i-m also and old conservative guy, and this project yquake2 still compiles in my russian eepc with gcc 4.1 and sdl 1.2.11... well without x11 gamma (set WITH_X11_GAMMA=no in makefile)
please can any tell me what its the difference and how influence that setting in gamma?

**Comment by Yamagi** [comment]
Some SDL 1.2 version and some graphics driver had problems setting hardware gamma. Therefor I've implemented a way to set the gamma in software through an old X11 interface. With WITH_X11_GAMMA hardware gamma is used. If it's working for you (or if you don't need to adjust gamma) everything's okay.

**Comment by mckaygerhard** [comment]
ok thanks for the info, i have more curiosity around, witch specific? or well what are u receiving or got reported with problems?¿

and currently i have to stop in that! going hurry to my home and rund the engine with zaero to check!!!!

**Comment by DanielGibson** [comment]
This bug was (is?) also present in SDL2 with X11 because of an X.org bug introduced in 2010, which broke setting gamma per window.

See https://bugzilla.libsdl.org/show_bug.cgi?id=1680 and https://bugs.freedesktop.org/show_bug.cgi?id=27222 for more information.

Our workaround is to set gamma for the whole screen when using X11, by using xrandr, if I recall correctly.
