### ISSUE TITLE
[Warning] Area 51 (2005)

### ISSUE THREAD

**Issue by SilentMRG** [yquake2/yquake2#1090]
Hello everybody!

I just want to let you know that the source code is available here: https://github.com/ProjectDreamland/area51

And it's important to remember that the game in question is Freeware, and free of copyright since 2008, so if any programmer is interested in starting a source port project now is a good time, and there will be no barriers to it.

Cheers!

**Comment by NeonKnightOA** [comment]
Excellent!

Question: are there any problems preventing it from being relicensed into GPLv2+?

**Comment by SilentMRG** [comment]
Honestly, I don't know how to answer that precisely. The only thing I think is that there is no problem, considering that everything related to the game has been copyright free for 16 years! And during all these years no one claimed anything from IP. This game literally belongs to no one, and it could be someone's if they are quick enough to significantly improve this title, and that's where the source port comes in. And this game needs one.

**Comment by Yamagi** [comment]
The problem with such code is always that no one can never be sure that there isn't a lawyer somewhere smelling a good deal. You can work for 20 years with the code, put a lot of effort in it and then some day someone claims the copyright and sends a DMCA claim or sues you directly for a billion dollars in damages.

**Comment by 0lvin** [comment]
What about a case when we have SDK, e.g SiN and Heretic 2 or publicly available documentation like Anachronox. I suspect if we implement custom mod based on such information until it in a separate repository with a mention original noncommercial usage, such usage will be safe.
What do you think?

**Comment by Yamagi** [comment]
Fortunately I'm not a lawyer. ;) My understanding is, that reverse engineering something is legal as long it's clear that no confidential informations were used. Dynamic linking at runtime from code under GPL and other licenses should be okay, that's more or less what for example Nvidia is doing for their Linux kernel driver.

**Comment by SilentMRG** [comment]
> What about a case when we have SDK, e.g SiN and Heretic 2 or publicly available documentation like Anachronox. I suspect if we implement custom mod based on such information until it in a separate repository with a mention original noncommercial usage, such usage will be safe.
> What do you think?

As far as I know SiN, Heretic 2 and Anachronox are not and have never been freeware. These games are even for sale in digital stores, like GOG. And SiN specifically must be a property of Nightdive Studios.

The thing about Area 51 is that it has been freeware since 2008 and was even distributed by the US Air Force. In the link above the guy explains that he bought the source code from a former employee of Midway Studios Austin, therefore, the source code does not belong to anyone, and I think that a lawyer would be in a very bad place if he tried to claim ownership of this game, whatever is the allegation. Well, this is obviously my opinion based on facts published on the internet, hehe.
