### ISSUE TITLE
[Suggestion] cl_laseralpha cvar

### ISSUE THREAD

**Issue by BjossiAlfreds** [yquake2/yquake2#1098]
I've always found it really hard to see red and blue lasers (I'm visually impaired), at least outside the software renderer. There could be other players with the same problem so I figured I'd suggest making the laser alpha value customizable, instead of hard-coding it to 0.3.

I can do a PR if you are interested.

**Comment by Yamagi** [comment]
That sounds like a good idea. Go ahead :)
