### ISSUE TITLE
Possible Console Option For Where Version Number Is?

### ISSUE THREAD

**Issue by deuxsonic** [yquake2/yquake2#110]
Right now, the console displays quite a bit of information in the lower right corner, the full name of the port, version, time, and date. Would it be possible to have a CVAR to condense it down to read something like "YQuake2 v5.31" or "YQ2 v5.31"? I'm sure the date and time are useful to some (being able to keep track of what time it is and how long you've been playing) but it seems kind of long to me. I tried to figure out a way to have 2 different options it could display but when the strings for it are shortened, it will instead display other console artwork to fill up the rest of the box of text, so there's more to it than I thought (I'm a noob at messing with source code.) Just an idea since the console often just shows the version number and the shortened behavior could be disabled by default.

**Comment by Yamagi** [comment]
I don't see the point in this. The clock can only be seen when the console is opened, there's enough screen space and the 20 gettimeofday() syscalls don't hurt anyone. But if you really want a cvar to switch the clock off, a pull request would be welcome.
