### ISSUE TITLE
[Feature] Steam Audio

### ISSUE THREAD

**Issue by apartfromtime** [yquake2/yquake2#1101]
[Steam Audio](https://github.com/ValveSoftware/steam-audio) recently went open source.

**Comment by Yamagi** [comment]
If someone want's to write a backend for it... However I don't think that it will gain us anything. The problem isn't OpenAL or SDL, it's Quake II providing not enough data for really good sound. Sound coordinates are two dimensional, sounds don't take the level geometry into account and are calculated per area. We can't change it, because sounds are part of the network protocol.

**Comment by 0lvin** [comment]
It looks like debian does not have steam audio package, and steam audio should be embedded to code or to be external dependence requires additional steps before build. 

Do you like to have specific feature implemented in steam audio?

**Comment by apartfromtime** [comment]
> If someone want's to write a backend for it... However I don't think that it will gain us anything. The problem isn't OpenAL or SDL, it's Quake II providing not enough data for really good sound. Sound coordinates are two dimensional, sounds don't take the level geometry into account and are calculated per area. We can't change it, because sounds are part of the network protocol.

> It looks like debian does not have steam audio package, and steam audio should be embedded to code or to be external dependence requires additional steps before build.
> 
> Do you like to have some specific feature implemented in steam audio?

To my understanding steam audio could do the spatialisation taking the level geometry into account.

**Comment by Yamagi** [comment]
OpenAL could do that too if the geometry were available to the sound system. But it isn't. It might be possible to hack something: 

If I remember right - all that was years ago - the game basically creates a temporary sound entity which is send to the client. The sound samples are stored as mono files. The classic sound systems spartializes each sound based upon the offset between the players and the temporary entities origin coordinates and mixes all concurrent sound into a stereo stream. With OpenAL we just pass the sample and the coordinates to OpenAL and the library does the rest, including full support for surround.

The level geometry is available to the client, it's used mainly for collision detection and player movement prediction. One "just" needs to reads that geometry information, convert it into something OpenAL or any other sound library can understand and upload it.

However, that would be a lot of work with questionable gain. The sound effects still would be 22 kHz, distorted, etc. Everything involving geometry is expensive, it doesn't matter on modern hardware, but the retro gaming guys will complain. And I'm not a big fan of such deep architectural changes anymore, the game is finally working nice and most bugs were introduced by ourselfs through well mend changes...

**Comment by 0lvin** [comment]
Code already has logic for change reverberation setting by distance to wall, that disabled by default as I remember. Also Rerelease and RTX versions has some additional information about surface materials, I suppose it could also used for change reverberation. But none of RTX or Rerelease has some files for describe sound environment as I know.

**Comment by apartfromtime** [comment]
While I don't share the same complaints as the retro gaming guys, if there isn't much to be gained I'd consider this issue resolved.
