### ISSUE TITLE
Question about using Rogue game.dll for BaseQ2

### ISSUE THREAD

**Issue by Q3BFG10K** [yquake2/yquake2#1104]
If you drop Rogue game.dll into baseq2 folder, you get enhanced AI in the original game. 

This works fine until the first Iron Maiden enemy, which is rendered as a small brown triangle. I assume it's because the Rogue version has no code for this monster.

Is this a bug that can be corrected, or is it something that's not supported?

**Comment by Q3BFG10K** [comment]
> I believe you are confused because the _rerelease/remaster_ has all expansions unified into one.

No, Quake2 wiki mentioned this trick years ago with the original release. But they do it by starting Ground Zero and then typing "map base1" to start the main campaign.

I assume doing it their way would have the same problem with the Iron Maiden, because it still doesn't load game.dll from the base game?

**Comment by 0lvin** [comment]
For this case issues related to different name of iron maiden model, bitch2 vs bitch. Solution could be add required model or add hacks for replace model on fly like in https://github.com/yquake2/yquake2remaster/blob/master/src/client/refresh/files/models.c#L3065

**Comment by 0lvin** [comment]
Note: if a game library does not have some monster, game will mention it in logs as error with entity and such monster will not appear in any form in the game.

**Comment by Q3BFG10K** [comment]
@0lvin, you're right.

![Console](https://github.com/yquake2/yquake2/assets/40132921/907cb81a-9477-4adc-b45d-8a8179c9a1aa)

 Without touching the source code, can this be worked around, such as using map entities instead?

**Comment by BjossiAlfreds** [comment]
You could simply load rogue normally and then execute `map base1` from the console.

**Comment by Q3BFG10K** [comment]
Closing this one as I don't think anything more can be done here.
