### ISSUE TITLE
Issues with tag allocator PR

### ISSUE THREAD

**Issue by turol** [yquake2/yquake2#1107]
For some reason I can't comment on this PR (and only that PR)
https://github.com/yquake2/yquake2/pull/1106

Changing `int` parameter to `size_t` is not safe on 64-bit windows:
https://godbolt.org/z/eeadY1qGE
https://godbolt.org/z/WPPeGTexb

Also the code as posted does not work correctly on 32-bit. In the overflow check in Z_TagMalloc the addition will overflow and the comparison with `UINT_MAX` will always be false.

**Comment by protocultor** [comment]
Can you try commenting anything on mine, just to test? Being able to post issues but not comment doesn't make any sense. Can you screenshot what appears at the bottom of the page in the PR? Did you try with any other browser?

**Comment by turol** [comment]
It seems to be fixed now.
