### ISSUE TITLE
sdl3 compile fails

### ISSUE THREAD

**Issue by Franck6666** [yquake2/yquake2#1113]
Hi,

using arch linux with all updates and the aur sdl3 git and latest yquake2 git, fails to compile right.
Kindly Regards and hoping u can fix this.

Build configuration
===> Building q2ded
===> Building quake2
===> Building baseq2/game.so
===> Building ref_gl3.so
===> Building ref_gles3.so
make release/ref_gl3.so
===> Building ref_gl1.so
make release/ref_gles3.so
===> Building ref_soft.so
make release/q2ded
make release/ref_gl1.so
make release/ref_soft.so
make release/quake2
============================
make release/baseq2/game.so
make[1] : on entre dans le répertoire « /home/franck/yquake2 »
make[1] : on entre dans le répertoire « /home/franck/yquake2 »
make[1] : on entre dans le répertoire « /home/franck/yquake2 »
YQ2_ARCH = x86_64 COMPILER = gcc
make[1] : on entre dans le répertoire « /home/franck/yquake2 »
make[1] : on entre dans le répertoire « /home/franck/yquake2 »
make[1] : on entre dans le répertoire « /home/franck/yquake2 »
make[1] : on entre dans le répertoire « /home/franck/yquake2 »
WITH_CURL = yes
WITH_OPENAL = yes
WITH_RPATH = yes
WITH_SDL3 = yes
WITH_SYSTEMWIDE = no
WITH_SYSTEMDIR = 
============================

make[1]: « release/q2ded » est à jour.
make[1] : on quitte le répertoire « /home/franck/yquake2 »
===> CC src/client/refresh/soft/sw_main.c
===> CC src/client/refresh/gl3/gl3_sdl.c
===> CC src/client/refresh/gl1/gl1_sdl.c
===> CC src/common/shared/shared.c
===> CC src/client/refresh/gl3/glad-gles3/src/glad.c
===> CC src/client/vid/glimp_sdl3.c
===> CC src/common/md4.c
===> CC src/backends/unix/shared/hunk.c
make[1]: « release/baseq2/game.so » est à jour.
make[1] : on quitte le répertoire « /home/franck/yquake2 »
===> CC src/client/refresh/gl3/gl3_sdl.c
src/client/refresh/gl1/gl1_sdl.c: Dans la fonction « RI_GetSDLVersion »:
src/client/refresh/gl1/gl1_sdl.c:316:9: erreur: nom de type « SDL_Version » inconnu; vouliez-vous utiliser « SDL_VERSION » ?
  316 |         SDL_Version ver;
      |         ^~~~~~~~~~~
      |         SDL_VERSION
Dans le fichier inclus depuis /usr/include/SDL3/SDL.h:79,
                 depuis src/client/refresh/gl1/gl1_sdl.c:31:
src/client/refresh/gl1/gl1_sdl.c:321:9: erreur: l'objet appelé n'est pas une fonction ou un pointeur de fonction
  321 |         SDL_VERSION(&ver);
      |         ^~~~~~~~~~~
src/client/refresh/gl1/gl1_sdl.c:323:19: erreur: accès au membre « major » de quelque chose qui n'est ni une structure ni une union
  323 |         return ver.major;
      |                   ^
src/client/refresh/gl1/gl1_sdl.c:324:1: attention: le contrôle a atteint la fin d'une fonction non « void » [-Wreturn-type]
  324 | }
      | ^
make[1]: *** [Makefile:616: build/ref_gl1/src/client/refresh/gl1/gl1_sdl.o] Error 1
make[1] : on quitte le répertoire « /home/franck/yquake2 »
make: *** [Makefile:604: ref_gl1] Error 2
make: *** Attente des tâches non terminées....
src/client/refresh/soft/sw_main.c: Dans la fonction « RE_PrepareForWindow »:
src/client/refresh/soft/sw_main.c:1789:21: erreur: « SDL_SWSURFACE » non déclaré (première utilisation dans cette fonction); vouliez-vous utiliser « SDL_Surface » ?
 1789 |         int flags = SDL_SWSURFACE;
      |                     ^~~~~~~~~~~~~
      |                     SDL_Surface
src/client/refresh/soft/sw_main.c:1789:21: note: chaque identificateur non déclaré est rapporté une seule fois pour chaque fonction dans laquelle il apparaît
src/client/refresh/soft/sw_main.c: Dans la fonction « GetRefAPI »:
src/client/refresh/soft/sw_main.c:1818:9: erreur: nom de type « SDL_Version » inconnu; vouliez-vous utiliser « SDL_VERSION » ?
 1818 |         SDL_Version ver;
      |         ^~~~~~~~~~~
      |         SDL_VERSION
Dans le fichier inclus depuis /usr/include/SDL3/SDL.h:79,
                 depuis src/client/refresh/soft/sw_main.c:25:
src/client/refresh/soft/sw_main.c:1822:9: erreur: l'objet appelé n'est pas une fonction ou un pointeur de fonction
 1822 |         SDL_VERSION(&ver);
      |         ^~~~~~~~~~~
src/client/refresh/soft/sw_main.c:1828:42: erreur: accès au membre « major » de quelque chose qui n'est ni une structure ni une union
 1828 |         refexport.framework_version = ver.major;
      |                                          ^
src/client/refresh/gl3/gl3_sdl.c: Dans la fonction « GL3_GetSDLVersion »:
src/client/refresh/gl3/gl3_sdl.c:471:9: erreur: nom de type « SDL_Version » inconnu; vouliez-vous utiliser « SDL_VERSION » ?
  471 |         SDL_Version ver;
      |         ^~~~~~~~~~~
      |         SDL_VERSION
Dans le fichier inclus depuis /usr/include/SDL3/SDL.h:79,
                 depuis src/client/refresh/gl3/gl3_sdl.c:33:
src/client/refresh/gl3/gl3_sdl.c:476:9: erreur: l'objet appelé n'est pas une fonction ou un pointeur de fonction
  476 |         SDL_VERSION(&ver);
      |         ^~~~~~~~~~~
src/client/refresh/gl3/gl3_sdl.c:478:19: erreur: accès au membre « major » de quelque chose qui n'est ni une structure ni une union
  478 |         return ver.major;
      |                   ^
src/client/refresh/gl3/gl3_sdl.c:479:1: attention: le contrôle a atteint la fin d'une fonction non « void » [-Wreturn-type]
  479 | }
      | ^
make[1]: *** [Makefile:655: build/ref_gl3/src/client/refresh/gl3/gl3_sdl.o] Error 1
make[1] : on quitte le répertoire « /home/franck/yquake2 »
make: *** [Makefile:644: ref_gl3] Error 2
src/client/refresh/soft/sw_main.c: Dans la fonction « RE_InitContext »:
src/client/refresh/soft/sw_main.c:1913:61: erreur: « SDL_RENDERER_PRESENTVSYNC » non déclaré (première utilisation dans cette fonction)
 1913 |                 renderer = SDL_CreateRenderer(window, NULL, SDL_RENDERER_PRESENTVSYNC);
      |                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~
src/client/refresh/soft/sw_main.c:1913:28: erreur: trop d'arguments pour la fonction « SDL_CreateRenderer »
 1913 |                 renderer = SDL_CreateRenderer(window, NULL, SDL_RENDERER_PRESENTVSYNC);
      |                            ^~~~~~~~~~~~~~~~~~
Dans le fichier inclus depuis /usr/include/SDL3/SDL.h:69:
/usr/include/SDL3/SDL_render.h:218:44: note: déclaré ici
  218 | extern SDL_DECLSPEC SDL_Renderer * SDLCALL SDL_CreateRenderer(SDL_Window *window, const char *name);
      |                                            ^~~~~~~~~~~~~~~~~~
src/client/refresh/gl3/gl3_sdl.c: Dans la fonction « GL3_GetSDLVersion »:
src/client/refresh/soft/sw_main.c:1921:28: erreur: trop d'arguments pour la fonction « SDL_CreateRenderer »
 1921 |                 renderer = SDL_CreateRenderer(window, NULL, 0);
      |                            ^~~~~~~~~~~~~~~~~~
/usr/include/SDL3/SDL_render.h:218:44: note: déclaré ici
  218 | extern SDL_DECLSPEC SDL_Renderer * SDLCALL SDL_CreateRenderer(SDL_Window *window, const char *name);
      |                                            ^~~~~~~~~~~~~~~~~~
src/client/vid/glimp_sdl3.c: Dans la fonction « GLimp_Init »:
src/client/refresh/gl3/gl3_sdl.c:471:9: erreur: nom de type « SDL_Version » inconnu; vouliez-vous utiliser « SDL_VERSION » ?
  471 |         SDL_Version ver;
      |         ^~~~~~~~~~~
      |         SDL_VERSION
Dans le fichier inclus depuis /usr/include/SDL3/SDL.h:79,
                 depuis src/client/refresh/gl3/gl3_sdl.c:33:
src/client/refresh/gl3/gl3_sdl.c:476:9: erreur: l'objet appelé n'est pas une fonction ou un pointeur de fonction
  476 |         SDL_VERSION(&ver);
      |         ^~~~~~~~~~~
src/client/vid/glimp_sdl3.c:417:17: erreur: nom de type « SDL_Version » inconnu; vouliez-vous utiliser « SDL_VERSION » ?
  417 |                 SDL_Version version;
      |                 ^~~~~~~~~~~
      |                 SDL_VERSION
src/client/vid/glimp_sdl3.c:419:17: erreur: trop d'arguments pour la fonction « SDL_GetVersion »
  419 |                 SDL_GetVersion(&version);
      |                 ^~~~~~~~~~~~~~
Dans le fichier inclus depuis /usr/include/SDL3/SDL.h:79,
                 depuis src/client/vid/glimp_sdl3.c:42:
/usr/include/SDL3/SDL_version.h:147:33: note: déclaré ici
  147 | extern SDL_DECLSPEC int SDLCALL SDL_GetVersion(void);
      |                                 ^~~~~~~~~~~~~~
src/client/refresh/gl3/gl3_sdl.c:478:19: erreur: accès au membre « major » de quelque chose qui n'est ni une structure ni une union
  478 |         return ver.major;
      |                   ^
src/client/vid/glimp_sdl3.c:421:70: erreur: accès au membre « major » de quelque chose qui n'est ni une structure ni une union
  421 |                 Com_Printf("SDL version is: %i.%i.%i\n", (int)version.major, (int)version.minor, (int)version.patch);
      |                                                                      ^
src/client/vid/glimp_sdl3.c:421:90: erreur: accès au membre « minor » de quelque chose qui n'est ni une structure ni une union
  421 |                 Com_Printf("SDL version is: %i.%i.%i\n", (int)version.major, (int)version.minor, (int)version.patch);
      |                                                                                          ^
src/client/vid/glimp_sdl3.c:421:110: erreur: accès au membre « patch » de quelque chose qui n'est ni une structure ni une union
  421 |                 Com_Printf("SDL version is: %i.%i.%i\n", (int)version.major, (int)version.minor, (int)version.patch);
      |                                                                                                              ^
src/client/refresh/gl3/gl3_sdl.c:479:1: attention: le contrôle a atteint la fin d'une fonction non « void » [-Wreturn-type]
  479 | }
      | ^
src/client/vid/glimp_sdl3.c: Dans la fonction « GLimp_GetFrameworkVersion »:
src/client/vid/glimp_sdl3.c:909:9: erreur: nom de type « SDL_Version » inconnu; vouliez-vous utiliser « SDL_VERSION » ?
  909 |         SDL_Version ver;
      |         ^~~~~~~~~~~
      |         SDL_VERSION
src/client/vid/glimp_sdl3.c:910:9: erreur: l'objet appelé n'est pas une fonction ou un pointeur de fonction
  910 |         SDL_VERSION(&ver);
      |         ^~~~~~~~~~~
src/client/vid/glimp_sdl3.c:912:19: erreur: accès au membre « major » de quelque chose qui n'est ni une structure ni une union
  912 |         return ver.major;
      |                   ^
src/client/vid/glimp_sdl3.c:913:1: erreur: expected declaration or statement at end of input
  913 | ;
      | ^
make[1]: *** [Makefile:710: build/ref_gles3/src/client/refresh/gl3/gl3_sdl.o] Error 1
make[1]: *** Attente des tâches non terminées....
src/client/vid/glimp_sdl3.c:914: attention: le contrôle a atteint la fin d'une fonction non « void » [-Wreturn-type]
make[1]: *** [Makefile:482: build/client/src/client/vid/glimp_sdl3.o] Error 1
make[1] : on quitte le répertoire « /home/franck/yquake2 »
make: *** [Makefile:471: client] Error 2
make[1]: *** [Makefile:744: build/ref_soft/src/client/refresh/soft/sw_main.o] Error 1
make[1]: *** Attente des tâches non terminées....
make[1] : on quitte le répertoire « /home/franck/yquake2 »
make: *** [Makefile:693: ref_gles3] Error 2
make[1] : on quitte le répertoire « /home/franck/yquake2 »
make: *** [Makefile:736: ref_soft] Error 2

**Comment by protocultor** [comment]
Note that YQ2 currently can only be built on the **_prerelease 3.1.2_** version of SDL3. And I know nothing about AUR packages, but if you're using [this](https://aur.archlinux.org/packages/sdl3-git) then you're not actually using the prerelease 3.1.2 version, but a much later one, no matter what the AUR package version says.

It's not difficult to guess this. _Prerelease 3.1.2_ was published on git on May 1st, and the AUR package was published on May 22nd. But more importantly, you are getting this error:
`error: unknown type name «SDL_Version»; did you mean to use «SDL_VERSION»?`
...which is produced by [this commit](https://github.com/libsdl-org/SDL/commit/661f2fc1fca76f79f536919fefe5887a875b6afb), made on May 14th.

Needless to say, going after the very latest commit of SDL3 is a waste of effort (dudes like to go back and forth on supported features), so you can either:
- See if you can rollback to the actual prerelease 3.1.2 version of your AUR package.
- Or use the git repository of SDL and build it yourself on the `prerelease-3.1.2` tag.

**Comment by Franck6666** [comment]
Hi there

i did solved the problem like u proposed with the prerelease-3.1.2 using for both yquake2 and rev_vk for compiling successfully, but this wasn't possibly with aur., there seems  to be no Option to getting an older package. So maually did go back to the preview version of sd3.

What is notable to mention as Change Experience with SDL3, the game feels smoother when moving around, very nice.

Graphic Enhancements ? hmm no, cant see any, looks like before, but smoother using a GeForce GTX 1060 6GB with Vulkan

Loading library: ref_vk.so
Byte ordering: little endian

Refresh: Yamagi Quake II Vulkan Refresher 1.0.7 (based on vkQuake2 v1.4.3)
Platform: Linux
Architecture: x86_64
Build date: Jun 11 2024

Setting mode 18: 1440x900 (vid_fullscreen 1)
User requested 1440x900@-1.000000, setting closest mode 1440x900@59.887444
Real display mode: 1440x900@59.89
Enabled extensions: VK_KHR_surface VK_KHR_xlib_surface 
...created Vulkan instance
...created Vulkan surface
...found 1 Vulkan-capable device(s)
Supported present modes: VK_PRESENT_MODE_FIFO_KHR VK_PRESENT_MODE_FIFO_RELAXED_KHR VK_PRESENT_MODE_IMMEDIATE_KHR 
...present mode VK_PRESENT_MODE_MAILBOX_KHR not supported, using present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
...trying swapchain extent: 1440x900
...trying swapchain image format: 44
...created Vulkan swapchain
...created synchronization objects
...MSAAx1 is used
...created 3 Vulkan render passes
...created Vulkan command pools
...created world depth buffer
...created UI depth buffer
...created world color buffer
...created world postpocess color buffer
...created 3 Vulkan image view(s)
...created 3 Vulkan framebuffers
...created 2 Vulkan commandbuffers
Reallocate space for 512 models.
Drawable size: 1440x900
------------------------------------
Vulkan API: 1.3
Header version: 285
Devices found:
   #0: NVIDIA GeForce GTX 1060 6GB
Using device #0:
   deviceName: NVIDIA GeForce GTX 1060 6GB
   resolution: 1440x900
   driverVersion: 535.179.0 (0x85ECC000)
   apiVersion: 1.3.242
   deviceID: 7171
   vendorID: 0x10DE (NVIDIA)
   deviceType: VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
   gfx/present/transfer: 0/0/1
Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
Swapchain image format: 44
Supported present modes: VK_PRESENT_MODE_FIFO_KHR VK_PRESENT_MODE_FIFO_RELAXED_KHR VK_PRESENT_MODE_IMMEDIATE_KHR 
Enabled extensions: VK_KHR_surface VK_KHR_xlib_surface 
Enabled layers: 
Successfully initialized Vulkan!
Successfully loaded ref_vk.so as rendering backend
