### ISSUE TITLE
Long-standing pair of warnings during build on Windows

### ISSUE THREAD

**Issue by deuxsonic** [yquake2/yquake2#112]
Line 6327 in client\refresh\files\stb_image.h leads to a pair of warnings about stbi__12h_gamma and stbi__12h_scale being unused. This has been around for ages, and I've just been ignoring them. Commenting out the line gets rid of the warnings. Since I know you want code as clean as possible I'm wondering if this is anything of interest?

**Comment by svdijk** [comment]
Yeah I noticed them too... Fixed as of 57c494c.

**Comment by DanielGibson** [comment]
Generally: stb_image.h is thirdparty code (a library) which we might update from time to time, so I personally didn't bother changing it.
In this case it doesn't really matter (it's only a small change), but generally I prefer not to patch thirdparty code.

**Comment by svdijk** [comment]
Yeah I thought about that, but found the warnings too annoying in our otherwise clean build. I've created an upstream pull request, so hopefully we won't have to do this again in the future :-)

**Comment by DanielGibson** [comment]
Ahh - very good :-)
