### ISSUE TITLE
[Original bug] Spawntemp data usable after level load

### ISSUE THREAD

**Issue by BjossiAlfreds** [yquake2/yquake2#1139]
If the very last entity in the entity string contains spawntemp fields, like "item", it will stay for the rest of the level and all entities spawned mid-game can read the field value.

Example steps to reproduce:
1. Add "item" "ammo_cells" to the last entity in map fact2's entity string.
2. Start the map and go to where the misc_insane guys are falling into the slime.
3. Notice that they all drop cells when they die.

I will do a PR that addresses this issue.

**Comment by Yamagi** [comment]
Fixed with the merge of #1140
