### ISSUE TITLE
compiling with x11 gamma hardware error on some sdl/x11 configs

### ISSUE THREAD

**Issue by mckaygerhard** [yquake2/yquake2#114]
i'll try to compile yamangi quake again and older but hard optimized version of xorg and sdl,xorg ( xorg 1.1 at X11R7.1 as 7.1; and sdl 1.2 version 1.2.14 with sound patchies for rt)

under xorg 1.7.7 at X11R7.5 with sdl 1.2.15 compiles and build and excelent executable..

i got and error when try again older configs:

```
===> CC src/backends/sdl/refresh.c
src/backends/sdl/refresh.c:71: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
src/backends/sdl/refresh.c: En la función ‘UpdateHardwareGamma’:
src/backends/sdl/refresh.c:276: error: ‘XRRScreenResources’ no se declaró aquí (primer uso en esta función)
src/backends/sdl/refresh.c:276: error: (Cada identificador no declarado solamente se reporta una vez
src/backends/sdl/refresh.c:276: error: ara cada funcion en la que aparece.)
src/backends/sdl/refresh.c:276: error: ‘res’ no se declaró aquí (primer uso en esta función)
src/backends/sdl/refresh.c:276: aviso: declaración implícita de la función ‘XRRGetScreenResources’
src/backends/sdl/refresh.c:285: aviso: declaración implícita de la función ‘XRRGetCrtcGammaSize’
src/backends/sdl/refresh.c:296: error: ‘XRRCrtcGamma’ no se declaró aquí (primer uso en esta función)
src/backends/sdl/refresh.c:296: aviso: declaración implícita de la función ‘XRRAllocGamma’
src/backends/sdl/refresh.c:298: error: argumento de tipo inválido de ‘->’
src/backends/sdl/refresh.c:299: error: argumento de tipo inválido de ‘->’
src/backends/sdl/refresh.c:300: error: argumento de tipo inválido de ‘->’
src/backends/sdl/refresh.c:304: aviso: declaración implícita de la función ‘XRRSetCrtcGamma’
src/backends/sdl/refresh.c:306: aviso: declaración implícita de la función ‘XRRFreeGamma’
src/backends/sdl/refresh.c:309: aviso: declaración implícita de la función ‘XRRFreeScreenResources’
src/backends/sdl/refresh.c: En la función ‘InitGamma’:
src/backends/sdl/refresh.c:396: error: ‘gammaRamps’ no se declaró aquí (primer uso en esta función)
src/backends/sdl/refresh.c:412: error: ‘XRRScreenResources’ no se declaró aquí (primer uso en esta función)
src/backends/sdl/refresh.c:412: error: ‘res’ no se declaró aquí (primer uso en esta función)
src/backends/sdl/refresh.c:420: error: ‘XRRCrtcGamma’ no se declaró aquí (primer uso en esta función)
src/backends/sdl/refresh.c:420: error: expected expression before ‘)’ token
src/backends/sdl/refresh.c:431: error: ‘origGamma’ no se declaró aquí (primer uso en esta función)
src/backends/sdl/refresh.c:431: aviso: declaración implícita de la función ‘XRRGetCrtcGamma’
src/backends/sdl/refresh.c:433: error: ‘gammaCopy’ no se declaró aquí (primer uso en esta función)
src/backends/sdl/refresh.c: En la función ‘RestoreGamma’:
src/backends/sdl/refresh.c:460: error: ‘gammaRamps’ no se declaró aquí (primer uso en esta función)
src/backends/sdl/refresh.c:476: error: ‘XRRScreenResources’ no se declaró aquí (primer uso en esta función)
src/backends/sdl/refresh.c:476: error: ‘res’ no se declaró aquí (primer uso en esta función)
make[1]: *** [build/client/src/backends/sdl/refresh.o] Error 1
```

theres's any possibility to make it possible to build with that envronment?

**Comment by mckaygerhard** [comment]
i transcribing the previous conversation to here,and thans for clarify...also theres a good idea make some wiki ino, i can make it at leas a start point

Yamagi commented 
>Some SDL 1.2 version and some graphics driver had problems setting hardware gamma. Therefor I've implemented a way to set the gamma in software through an old X11 interface. With WITH_X11_GAMMA hardware gamma is used. If it's working for you (or if you don't need to adjust gamma) everything's okay.

  
mckaygerhard commented 
>ok thanks for the info, i have more curiosity around, witch specific? or well what are u receiving or got reported with problems?¿
and currently i have to stop in that! going hurry to my home and rund the engine with zaero to check!!!!
 
DanielGibson commented 
>This bug was (is?) also present in SDL2 with X11 because of an X.org bug introduced in 2010, which broke setting gamma per window.
See https://bugzilla.libsdl.org/show_bug.cgi?id=1680 and https://bugs.freedesktop.org/show_bug.cgi?id=27222 for more information.

Our workaround is to set gamma for the whole screen when using X11, by using xrandr, if I recall correctly.

**Comment by Yamagi** [comment]
I'm unable to reproduce this with SDL2 set to no and X11GAMMA set to yes. The error seems to indicate that your X11 header do something wrong with XRRCrtcGamma. Can you tell us the exact version of you libXrandr package? For example in my system:
  libXrandr-1.5.0                X Resize and Rotate extension library

**Comment by mckaygerhard** [comment]
apart of the minimal version of xrandr, that the gcc 4.1 have a problem in the line 71 where are the condition for gamma:
```
src/backends/sdl/refresh.c:71: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
```
in that line theres that declaration that refers to u said aroud `XRRCrtcGamma` 
```
#ifdef X11GAMMA
XRRCrtcGamma** gammaRamps = NULL;/*<---- here line 71 throwns error declaration*/
int noGammaRamps = 0;
#endif
```

yes seem that mnimal version to have gamma correction must be Xrandr 1.2.0 from debian as i can see in the commit c712df73eeb0cb84aad6a0bec2be0f480418c217 of the git debian packaging, 
so the problem its the required version?

theres any possibility to include only portions of code inside the sources for able to build? please!

and if there's no way to provide fallback feel free to close this issue ... the bug patch for sdl are in some place , so i can fix my on sdl libs?

**Comment by Yamagi** [comment]
I just had a look at Xrandr.h, XRRCrtcGamma is the same in version 1.2 and 1.3. So that shouldn't be the problem. The next step would be to have a look at the preprocessed code. You can get it with the gcc option -E, for example:

` gcc48 -E -O2 -fno-strict-aliasing -fomit-frame-pointer -Wall -pipe -g -ggdb -MMD -fwrapv -DCDA -DOGG -DUSE_OPENAL -DDEFAULT_OPENAL_DRIVER='"libopenal.so.1"' -DZIP -DNOUNCRYPT -DX11GAMMA -I/usr/local/include/SDL -I/usr/local/include -D_REENTRANT -D_THREAD_SAFE -I/usr/local/include -D_THREAD_SAFE   -I/usr/local/include -D_THREAD_SAFE   -I/usr/local/include -o refresh.E src/backends/sdl/refresh.c`

This will generate a long file refresh.E with the preprocessed source, including all headers. I need to see that file.

**Comment by mckaygerhard** [comment]
the XRRCrtcGamma are since 1.2 and i try to compile agains 1.1.1... 

in any case here: https://drive.google.com/file/d/0B9CZefVq84E_cXVVbXhBVzRlX2M/view?usp=sharing

if i on the right, ahd minimal must be 1.2 theres any possibility to include only portions of code inside the sources for able to build? i mean using inline declarations in that case if possible!!!

**Comment by DanielGibson** [comment]
Your X.org version is from 2006 O_o

If you insist on using severely outdated software: You don't need Yamagi 
Quake 2's X11 Gamma, because on your stoneage X.org the per-window gamma 
that SDL uses should still work.

**Comment by mckaygerhard** [comment]
yeah works for debian ethc (several years old) hav no problems, but for xorg in lenny and squeeze i have it! so for lenny i have that problem! i used a special debian lenny in my low end machines, eepc for childrens, for my alumns

the bug are from sdl 1.2.15 and i used sdl 1.2.14 in the olders and 1.2.15 in squeeze so i think if xorg server are 1.7.4 the bug was repórted agains xorg 1.7.5, but seems if i patched sdl 1.2.14 and 1.2.15 qith that https://bugzilla.libsdl.org/attachment.cgi?id=1008&action=diff should be resolved?

or may still i donyt need the x11 gamma set to yes in builds?

**Comment by Yamagi** [comment]
The problem is with compiling is indeed, that you libXrandr hasn't support for gamma. But as Daniel said, X11GAMMA is more or less unnecessary. You'll need it only when gamma adjustment through SDL ("hardware gamma") isn't working for you. And even than you can always set the gamma by hand with the good old "xgamma" tool.

**Comment by mckaygerhard** [comment]
thanks for the help and thanks for the tip, so for avoid porting recent xlrand lib i'll patch the sdllib of my implementation.. and in second i'll use the xgamma tool.
