### ISSUE TITLE
[Cinematic] Pressing "Enter\Return" during cinematic produces the main menu

### ISSUE THREAD

**Issue by apartfromtime** [yquake2/yquake2#1145]
Pressing "Return\Enter" during a cinematic produces a call to `M_MainMenu_f` but the call doesn't come from `Key_Event`, the only place `M_Menu_Main_f` can be found outside of menu. The `main_menu` command doesn't appear to be placed on the command buffer. Is this a bug?

**Comment by Yamagi** [comment]
I can't reproduce this under Linux. Pressing "Return" aborts the cinematic and proceeds to the loading plaque. I would suggest adding a break point to the beginning of `M_Menu_Main_f()` and print a back trace when it triggers. That should show how the code ended up there. Hopefully it's not a bug in the `cls.key_dest` logic, but in that case it would have to go through `Key_Event()`.

**Comment by BjossiAlfreds** [comment]
I see the same behavior in both YQ2 and the original game. Pressing return during the logo or demos brings up the menu, and pressing it during the intro or intermission skips to the loading screen. As far as I can tell everything is working as intended.

**Comment by apartfromtime** [comment]
I get the expected behaviour in the original on Windows.

Someone will have to give me a "How to guide" on generating the debug symbols on Windows.

**Comment by apartfromtime** [comment]
Please ignore, I had forgotten I bound `menu_main` to enter while testing change to the menu.
