### ISSUE TITLE
Working with unpacked data

### ISSUE THREAD

**Issue by HuubVanAmelsvoort** [yquake2/yquake2#1155]
It seems that its not possible to run the game with no pak files in the datadir?
I've unpacked my pak files en point to the datadir with -datadir <thelocation>, but than I get the error:
GetPCXPalette: Couldn't load pics/colormap.pcx

Working with Windows10.

thanks in advance for an answer.

**Comment by Yamagi** [comment]
Do you have the extracted files in a subdir baseq2/ under your datadir? The datadir is the top level directory, the mod directory (baseq2/ for the main game) is still needed under it.

**Comment by HuubVanAmelsvoort** [comment]
Sorry, I thought I already told you the problem.
The problem was that I gave the datadir including baseq2.
So I had to remove the baseq2 from the path and then it was solved.

Thanks.

**Comment by HuubVanAmelsvoort** [comment]
As said.
