### ISSUE TITLE
ref_vk

### ISSUE THREAD

**Issue by Franck6666** [yquake2/yquake2#1156]
Hi,

since yquake2 is able to compile with cuurent sdl3  the 
ref_vk does it not 

===> CC src/vk/vk_mesh.c
===> CC src/vk/vk_model.c
===> CC src/vk/vk_pipeline.c
===> CC src/vk/vk_main.c
===> CC src/vk/vk_misc.c
src/vk/vk_main.c: Dans la fonction « GetRefAPI »:
src/vk/vk_main.c:1720:9: erreur: nom de type « SDL_Version » inconnu; vouliez-vous utiliser « SDL_VERSION » ?
 1720 |         SDL_Version ver;
      |         ^~~~~~~~~~~
      |         SDL_VERSION
Dans le fichier inclus depuis /usr/local/include/SDL3/SDL.h:81,
                 depuis src/vk/header/local.h:35,
                 depuis src/vk/vk_main.c:28:
src/vk/vk_main.c:1724:9: erreur: l'objet appelé n'est pas une fonction ou un pointeur de fonction
 1724 |         SDL_VERSION(&ver);
      |         ^~~~~~~~~~~
src/vk/vk_main.c:1729:42: erreur: accès au membre « major » de quelque chose qui n'est ni une structure ni une union
 1729 |         refexport.framework_version = ver.major;
      |                                          ^
make[1]: *** [Makefile:358: build/src/vk/vk_main.o] Error 1
make[1]: *** Attente des tâches non terminées....
make[1] : on quitte le répertoire « /home/franck/ref_vk »
make: *** [Makefile:348: ref_vk] Error 2

~/ref_vk master*

**Comment by protocultor** [comment]
This issue belongs to the **[ref_vk](https://github.com/yquake2/ref_vk)** project.
Anyway, I did a PR that updates it to SDL 3.1.3.

**Comment by Franck6666** [comment]
Hi,

Million thx - it compiles now fine

but it doesnt work wiht actuel yquake2, here is the output after changing to vulkan

----- refresher initialization -----
Loading library: ref_vk.so
Byte ordering: little endian

Refresh: Yamagi Quake II Vulkan Refresher 1.0.8 (based on vkQuake2 v1.4.3)
Platform: Linux
Architecture: x86_64
Build date: Oct 15 2024

Setting mode 21: 1920x1080 (vid_fullscreen 1)
RE_PrepareForWindow() Loader import failed: Haptic: Mouse isn't a haptic device.User requested 1920x1080@-1.000000, setting closest mode 1920x1080@50.000000
Real display mode: 1920x1080@50.00
Enabled extensions: VK_KHR_surface VK_KHR_xlib_surface 
...created Vulkan instance
Vkimp_CreateSurface() SDL_Vulkan_CreateSurface failed: The specified window isn't a Vulkan windowRE_InitContext() - could not initialize Vulkan!
R_SetMode() - invalid mode
Setting mode 4: 640x480 (vid_fullscreen 0)
RE_PrepareForWindow() Loader import failed: The specified window isn't a Vulkan windowReal display mode: 1920x1080@50.00
Enabled extensions: VK_KHR_surface VK_KHR_xlib_surface 
...created Vulkan instance
Vkimp_CreateSurface() SDL_Vulkan_CreateSurface failed: The specified window isn't a Vulkan windowRE_InitContext() - could not initialize Vulkan!
R_SetMode() - could not revert to safe mode
RE_Init() - could not R_SetMode()
ERROR: Loading ref_vk.so as rendering backend failed.
------------------------------------

Retrying with gl3...

**Comment by Franck6666** [comment]
the compile warning is gone but sttill not working

Log Output:

----- refresher initialization -----
Loading library: ref_vk.so
Byte ordering: little endian

Refresh: Yamagi Quake II Vulkan Refresher 1.0.8 (based on vkQuake2 v1.4.3)
Platform: Linux
Architecture: x86_64
Build date: Oct 15 2024

Setting mode 21: 1920x1080 (vid_fullscreen 1)
RE_PrepareForWindow() Loader import failed: Haptic: Mouse isn't a haptic device.User requested 1920x1080@-1.000000, setting closest mode 1920x1080@50.000000
Real display mode: 1920x1080@50.00
Enabled extensions: VK_KHR_surface VK_KHR_xlib_surface 
...created Vulkan instance
Vkimp_CreateSurface() SDL_Vulkan_CreateSurface failed: The specified window isn't a Vulkan windowRE_InitContext() - could not initialize Vulkan!
R_SetMode() - invalid mode
Setting mode 4: 640x480 (vid_fullscreen 0)
RE_PrepareForWindow() Loader import failed: The specified window isn't a Vulkan windowReal display mode: 1920x1080@50.00
Enabled extensions: VK_KHR_surface VK_KHR_xlib_surface 
...created Vulkan instance
Vkimp_CreateSurface() SDL_Vulkan_CreateSurface failed: The specified window isn't a Vulkan windowRE_InitContext() - could not initialize Vulkan!
R_SetMode() - could not revert to safe mode
RE_Init() - could not R_SetMode()
ERROR: Loading ref_vk.so as rendering backend failed.
------------------------------------

Retrying with gl3...
----- refresher initialization -----
Loading library: ref_gl3.so
Byte ordering: little endian

Refresh: Yamagi Quake II OpenGL3 Refresher
Client: 8.42pre

Setting mode 4: 640x480 (vid_fullscreen 1)
User requested 640x480@-1.000000, setting closest mode 640x480@59.939999
Real display mode: 640x480@59.94
Successfully loaded OpenGL function pointers using glad, got version 3.2!
Drawable size: 640x480

**Comment by protocultor** [comment]
Currently I don't have a Vulkan video card, so what I did was a blind "hail mary" fixing the compilation only, since  I cannot check the end result of it. I didn't expect other kind of errors; my apologies for this.
Looking at your log, I believe `ref_vk` has the same error @0lvin is fixing in his PR #1154 with the change of "meaning" for the return value of `SDL_LockTexture()`, or maybe another SDL function.
Unfortunately, cannot help you going blindly with this.

**Comment by Franck6666** [comment]
yeah understand u and no excuse needed as its ur free time u using for helping. If i can  do any providing in more informations just ask.

A little Summary maybe for analyzing, as yquake2 did get able to compile withs the sdl preview, instantly ref_vk stopped working. So a separate  re-compile ws needed, but didn't worked,. Since the last 2 investigations from ur side today, the compiling works again but u know, the hole Abillity to work, did get lost.  As u have no proper Hardware things are more difficult but maybe ur not the only who can fix this, are u ?

**Comment by Yamagi** [comment]
I only had a very short look, but this looks somehow strange. ´GLimp_InitGraphics()´ in the client calls ´RE_PrepareForWindow()` in ref_vk which returns `SDL_WINDOW_VULKAN` as window flags. These flag get fed into `CreateSDLWindow()`. I made sure hat the correct functions are called (there are function pointers and you never know) and even tried to hardcode the `SDL_WINDOW_VULKAN` flag. Nevertheless `SDL_Vulkan_CreateSurface()` insists on the window not being a Vulkan window.

According to https://wiki.libsdl.org/SDL3/SDL_Vulkan_CreateSurface that `SDL_WINDOW_VULKAN` flag should be enough... 

The same happens with SDL3 master / main as of today instead of the 3.1.3 preview release.

**Comment by Franck6666** [comment]
Hi there, u see any light at the Horizont ?

**Comment by Yamagi** [comment]
Someone will need to look deeper into this. I can do it, but not in the next two or three weeks. No time, sorry... This is either a bug in SDL or - that is more likely - we are using the API the wrong way. It wouldn't be the first time that SDL functions are called in the wrong order or something like that. While it has become better SDLs docs are still rather rudimentary and such thinks are often not that obviously.

**Comment by Yamagi** [comment]
And SDL 2 is still working, of course. At least I hope so, I haven't tested it. SDL 2 will stay the default for the time being, at least about one year after Debian Trixie is released and the various distros based upon it had time to catch up.

**Comment by Yamagi** [comment]
This was a bug in the SDL 3 backend of YQ2 and not in the Vulkan renderer. SDL 3 changed the way how Window flags are handled and my implementation was wrong. It still worked with the OpenGL renderers but Vulkan couln't pass its `SDL_WINDOW_VULKAN` flag anymore. Its fixed in YQ2 master.

**Comment by Franck6666** [comment]
much thx works good, were all human
