### ISSUE TITLE
gl1_stencilshadow no longer works

### ISSUE THREAD

**Issue by protocultor** [yquake2/yquake2#1159]
This cvar, which enables stencil test in shadows to avoid them to flicker when using GL1, no longer works on `master` branch as of 07ee830712126dd0f50540eb6095bdb122c20c68, in either _SDL 2_ or _3_.

Last time I tested it was with 667ddafd839d5a35ecf1939cf03ba5c44683e00c, where it worked with no issues in _SDL 2_. I have vague memories of having tested it with the previous prerelease version of _SDL 3_ (_3.1.2_), but I'm not sure, and cannot recreate that environment right now.

I'm assuming one of the changes to be able to support the new _SDL 3.1.3_ is the culprit. Specifically, the return value of `SDL_GL_SetAttribute()`, which it seems not to be reliable anymore to check success when setting an OpenGL window attribute, [according to its own documentation](https://wiki.libsdl.org/SDL3/SDL_GL_SetAttribute).

https://github.com/yquake2/yquake2/blob/master/src/client/refresh/gl1/gl1_sdl.c#L107

**Comment by DanielGibson** [comment]
the problem here is that I'm an idiot and switched the SDL2 and SDL3 code

**Comment by protocultor** [comment]
_Errare humanum est._ Thanks for the quick fix!
