### ISSUE TITLE
Option to place user files in game root?

### ISSUE THREAD

**Issue by deuxsonic** [yquake2/yquake2#116]
I'm wondering about the difficulty of an option to use the vanilla Quake 2 behavior of storing saves and configs in the game's root folder rather than in the user profile (Documents/YamagiQ2 on Windows.)

**Comment by Jarvik7** [comment]
On some platforms the user might not have write permissions for that folder.
Makes it not work in the expected way on a multi-user platform as well.
Is there a need for that functionality other than it being vanilla behavior?

(on OSX having the data in ~ also bothers me though)

**Comment by deuxsonic** [comment]
It is useful for having a portable copy of the game, such as a copy of the game on a USB thumb drive.

**Comment by Yamagi** [comment]
It may be enough to comment lines 1240 and 1654 in filesystem.c, but I didn't gave it a try.
