### ISSUE TITLE
Request add a third-person view

### ISSUE THREAD

**Issue by FrensisMcBlob** [yquake2/yquake2#1160]
Hi. Add a third-person view to Yamagi. Here is the link to the mod. There is source code in the archive. https://www.moddb.com/games/quake-2/downloads/third-person-perspective

**Comment by 0lvin** [comment]
Could you please try yquake2remaster repository? it contains third person cvar.

**Comment by FrensisMcBlob** [comment]
Unfortunately, no. I play on my android phone on the Quad Touch app, there's only a Yamagi port.

**Comment by FrensisMcBlob** [comment]
Hi. Can you tell me if Yamagi can read texture materials such as Normals, Specular and Displacement. If it can, what is the correct name for them? I call for example 1_norm, 1_gloss, 1_bump. But Yamagi doesn't read them.

**Comment by 0lvin** [comment]
As I know, official remaster does not have support texture materials. Something like it could be provided only as name of material in .mat file and additionally as _glow.png. And both of cases are not implemented in yquake2remaster for now. 

I suppose support of such effects like you mentioned will require deep rewrite at least one render and have assets for testing that it's not goal for now. 

If you have such assets, could you please share link to it?

**Comment by protocultor** [comment]
"Texture materials" did not exist back when Q2 just released, and with Yamagi being a "chocolate" kind of port (meaning: being as accurate to the original release as possible, with QoL features on top), it just doesn't support those. I'm sure other source ports do them; try KMQuake2, Q2Pro and its derivatives, or any other that doesn't include a software renderer as an option.
Have to mention that providing support for materials might mean incompatibility with classic mods, and other side effects, that Yamagi has managed to avoid.

**Comment by FrensisMcBlob** [comment]
> If you have such assets, could you please share link to it?

I can link you to the materials I made for baseq2, juggernaut, rogue, xatrix, zaero. All textures in x_norm (normals), x_gloss (specular), x_bump (disolacement).
Give me your mailing address.

**Comment by Yamagi** [comment]
That mod implements the 3rd person through the game modul. You could compile the game module for YQ2, in fact the screenshot on ModDB even shows that mod running inside YQ2. Someone with too much sparetime could even merge that mod with out game code to get all our bugfixes.
