### ISSUE TITLE
Switching between clients creates an incompatible config.cfg

### ISSUE THREAD

**Issue by kke** [yquake2/yquake2#1165]
I'd like the configuration auto-save to update something like `yq2.cfg` instead of `config.cfg`. Now when switching between different clients, each write their config over `config.cfg` on quit or when changing settings and it breaks it for the other clients as they contain incompatible settings. When starting up, the `yq2.cfg` would then be preferred over loading `config.cfg`.

I'll make the same issue on https://github.com/skullernet/q2pro)](https://github.com/skullernet/q2pro/issues/373 but in reverse :)

**Comment by DanielGibson** [comment]
Don't the different clients write their configs in different directories?
yq2 saves in $HOME/.yq2/ (on Unix-likes) or My Documents\YamagiQ2\ (on windows) - no idea where Q2Pro writes their configs, but most probably somewhere else

**Comment by Yamagi** [comment]
This can only be a problem when the game is running in portal mode (started with `-portable`) and there it's kind of expected. Disabling the 'do not clash with other clients'-logic will lead to clashes with other clients. ;)
