### ISSUE TITLE
Incorrect usage info in SV_DumpUser_f

### ISSUE THREAD

**Issue by m-x-d** [yquake2/yquake2#1166]
https://github.com/yquake2/yquake2/blob/6ff7413b65f0698813e42092895446078e574501/src/server/sv_cmd.c#L522

Should be "Usage: dumpuser \<userid\>\n", I suppose.

**Comment by protocultor** [comment]
Just FYI, this "misunderstanding" comes from the original Q2 3.21 source code:
https://github.com/id-Software/Quake-2/blob/master/server/sv_ccmds.c#L860
