### ISSUE TITLE
Incorrect strncmp checks in SV_BeginDownload_f

### ISSUE THREAD

**Issue by m-x-d** [yquake2/yquake2#1167]
https://github.com/yquake2/yquake2/blob/9f6c455b458ce7a4ff11ca073f4696bcab2a010d/src/server/sv_user.c#L317 Should be 8 to match "players/" length?

https://github.com/yquake2/yquake2/blob/9f6c455b458ce7a4ff11ca073f4696bcab2a010d/src/server/sv_user.c#L319 Should be 7 to match "models/" length?

https://github.com/yquake2/yquake2/blob/9f6c455b458ce7a4ff11ca073f4696bcab2a010d/src/server/sv_user.c#L323 Should be 5 to match "maps/" length?

**Comment by DanielGibson** [comment]
I think you're right about this. That code was already like this in orig Q2 - looks like a copy&paste fail =)
