### ISSUE TITLE
Download progress hidden when "ui scale auto"

### ISSUE THREAD

**Issue by SiemensSchuckert** [yquake2/yquake2#1172]
### UDP download progress hidden on 1920x1080 with "ui scale auto"

1. 640x480 screen
2. 1920x1080 screen

![_dp_ex](https://github.com/user-attachments/assets/2f070af4-1a46-4969-93b5-d3f08bb37003)

**Comment by Yamagi** [comment]
As an educated guess the calculation of the Y position is missing the scaling factor: [cl_console.c#L793](https://github.com/yquake2/yquake2/blob/master/src/client/cl_console.c#L793) I'll need to take a deeper look before I can come up with a fix.

**Comment by Yamagi** [comment]
Yepp, the calculations of the Y position where missing the scaling factor. I have pushed a fix. Thank you for the report. :)
