### ISSUE TITLE
Long Strings Going Off Screen

### ISSUE THREAD

**Issue by deuxsonic** [yquake2/yquake2#120]
I know this is probably really pushing what can reasonably be done, but occasionally there are strings that go off screen with scale as I like, and I don't know if word wrap is possible in these circumstances or if it would make the problem worse by pushing other things or displaying on top of them.
![q1](https://cloud.githubusercontent.com/assets/7662909/11454747/097cdb4c-9607-11e5-8a79-b9615c55256b.JPG)
![q2](https://cloud.githubusercontent.com/assets/7662909/11454748/0981d2e6-9607-11e5-8046-9c8e02495f82.JPG)

**Comment by svdijk** [comment]
How are these examples handled at 320x200 resolution? If they are handled differently than in your screenshots, I think that qualifies as a bug.

**Comment by deuxsonic** [comment]
That's a good question. I'm curious if mode 13h or qVGA are even possible with this hardware. I'll have to see what happens on an older computer.
 


    On Sunday, December 13, 2015 8:35 AM, svdijk <notifications@github.com> wrote:
 

 How are these examples handled at 320x200 resolution? If they are handled differently than in your screenshots, I think that qualifies as a bug.—

**Comment by svdijk** [comment]
Or you could try 320x240 in windowed mode. (Note that I updated my earlier response from 320x200 to the intended 320x240.)

**Comment by deuxsonic** [comment]
Even in the console, if I hold a key down it goes off screen but it's not like a text editor where you get a horozontal scroll bar when this happens so anything that's longer than 38 characters exactly (less should probably be allowed before it wraps a line) will go off screen starting at where the cursor is at with 5x scaling but a definite number isn't going to work for variable scaling unless it's counted out for the whole numbers 1x - 6x and then if it's some decimal just rounding up to the nearest whole number to know how many characters wide the screen is.

**Comment by svdijk** [comment]
Just pushed a fix for the console line length in commit 31ffb96, which also fixes the issue in your second screenshot.

What happens in your first screenshot also happens at resolution 320x240 with no scaling, e.g. it is "original" behaviour. I'm not personally interested in changing that, sorry.

**Comment by deuxsonic** [comment]
Original console behavior for a line that is longer than the screen when typing is for it to scroll to the right as you type keeping the last segment of what you've written visible rather than having it locked at the beginning of the line.

**Comment by deuxsonic** [comment]
That fixes it. I'm pretty sure your changes are how it was done originally.
