### ISSUE TITLE
I can't see the guns.

### ISSUE THREAD

**Issue by kolunio82** [yquake2/yquake2#124]
Clean quake 2 3.20 with 5.33:

pic - https://dl.dropboxusercontent.com/u/4271477/q2.jpg

**Comment by maraakate** [comment]
Type "hand 0" in console

**Comment by kolunio82** [comment]
Didn't help/

**Comment by Yamagi** [comment]
Maybe cl_gun set to something else than 2?

**Comment by Yamagi** [comment]
No reply in 4 weeks -> close.
