### ISSUE TITLE
OSStatus Error

### ISSUE THREAD

**Issue by craigerskine** [yquake2/yquake2#126]
I followed the directions exactly using my original Quake 2 disc. I get the following error when I launch the app in OS X 10.11.3.
![Error Message](https://cloud.githubusercontent.com/assets/56437/13197861/9b4d58ea-d7bf-11e5-82de-74dd289b71fb.png)

**Comment by Jarvik7** [comment]
Works fine for me. Are you building from source?
Run the 'quake2' binary directly from the terminal and see what the console output is.

**Comment by Jarvik7** [comment]
Works-for-me and no response from OP. I suspect it is a user error in any case.

Suggest closing the issue.

**Comment by Yamagi** [comment]
Okay.
