### ISSUE TITLE
MacOS 10.9, 10.10 and 10.11 make error

### ISSUE THREAD

**Issue by stabuck** [yquake2/yquake2#127]
Hiya,

I've installed Xcode and home-brew under MacOS 10.9.5, 10.10.5 and 10.11.3 and I get the same error when trying to make yquake 2.

mp-MacBook-Air:quake2-5.33 mp$ make
Build configuration
============================
WITH_CDA = no
WITH_OPENAL = yes
WITH_SDL2 = yes
WITH_X11GAMMA = no
WITH_ZIP = yes
WITH_SYSTEMWIDE = no
WITH_SYSTEMDIR = 
============================

WARNING: CDA disabled because SDL2 doesn't support it!

===> Building quake2
/Library/Developer/CommandLineTools/usr/bin/make release/quake2
===> CC src/backends/generic/qal.c
src/backends/generic/qal.c:35:10: fatal error: 'AL/al.h' file not found
#include <AL/al.h>
         ^
1 error generated.
make[1]: *** [build/client/src/backends/generic/qal.o] Error 1
make: *** [client] Error 2
mp-MacBook-Air:quake2-5.33 mp$ 

Any ideas what could be causing this ?

Thanks

**Comment by Jarvik7** [comment]
Silly question, but is the openal-soft library installed?

**Comment by stabuck** [comment]
Hiya.. Just checked this and its installed please see below

mp-MacBook-Air:~ mp$ brew install openal-soft --universal
Warning: openal-soft-1.17.2 already installed

**Comment by Jarvik7** [comment]
I'll try compiling when I get the chance. There have been a few other OSX build complaints so maybe something broke.

**Comment by stabuck** [comment]
thanks for the update.. if you need me to test anything please let me know as I can test against different builds of MacOS X if you need.

ta

Lee

**Comment by Jarvik7** [comment]
Got it compiling now. Looks like whoever remade the makefile simply forgot to define the OpenAL directory for Darwin.

**Comment by stabuck** [comment]
I’ve now compiled the data and its working thank you for you help.

Time for some fragging :)

Thanks

Lee
