### ISSUE TITLE
Feature reqest: Add support for external entity lists

### ISSUE THREAD

**Issue by MilkeyWilkey** [yquake2/yquake2#131]
This will allow to change map's layouts without changing maps itselves or changing dll. This will allow for quick and easy map fixes, mods and gametypes to be made.
For now they are easily editable within maps, but are glued together

**Comment by Thraka** [comment]
It would be nice to see this on every game.

**Comment by Yamagi** [comment]
I've looked into thus and decided to not implement this. External entity lists aren't that easy to implement and would require changes to some delicate code paths. This is a lot of work and has a high probability to introduce new hard to find bugs. Sorry. :(
