### ISSUE TITLE
Yamagi Quake 2 Install Mac Problems/Confusion

### ISSUE THREAD

**Issue by Quindorrian** [yquake2/yquake2#132]
I have tried following the readme file, re-read it many times and once I get to the compile section, I am completely lost.  I have no idea what to do to get this to work on OSX.  The readme seems to leave a massive ton of important details out for a newbie like me.  For example, it never says what to do with the downloaded 5.33 file.  I guess I was supposed to extract it, but it doesn't say where.  It talks about some sort of zip file, but doesn't say where it is.  So, I found the file (I think) and extracted it (Still doesn't say where to extract it to) and found the Quake II executable.  I show contents on it and copy the base2 files over (which doesn't make sense to me, but that is what the readme says). I try to then run the app and it comes up with the window to run the game.  When I try to run the game at that point, the window disappears and nothing happens.

Would someone please help me with this?  The directions really don't make sense to me and they aren't very clear.  Thanks for any and all help.

**Comment by Jarvik7** [comment]
There is no current binary release for OSX. You probably downloaded the source code.
You need to compile it yourself following the instructions in the txt file (chapter 3.6).

**Comment by Quindorrian** [comment]
Ok, well this is a big problem considering how misleading the ReadMe is.  To quote the ReadMe, "Installation can be done by using the binary release or by compiling the source."  This seems to indicate that a binary release is available.  Additionally, it states, "Compiling Yamagi Quake II from source is unnecessary as long as you will not use the github version or want to develop on OS X."  Given these statements, I am EXTREMELY disappointed in this Yamagi release.  So, what you are telling me is I need to be a computer programmer to get this to work, which means this is useless to me and most people out there....  Wow....  Did not quite expect this considering how (over)hyped this Yamagi Quake 2 is...

**Comment by DanielGibson** [comment]
I fixed the Readme.

The problem is that neither Yamagi nor me have a Mac to create OSX binaries.

You don't need to be a programmer to compile things, you just need to be able to open a terminal and follow a few lines of instructions. I do understand though that this is a barrier, especially for OS X users.

Yamagi Quake2 being hyped (or even overhyped) is news to me.

**Comment by Quindorrian** [comment]
Well, I know how to open a terminal, but I would need very detailed, step by step, instructions to be able to do anything further.  I've never used the terminal before, honestly.  If you could provide that, I would gladly do it and send you the compiled binary file by drop-box.  I just need much clearer and more detailed instructions than was in the read-me.  I do appreciate the quick responses and such though.  Anything you could do to help is much appreciated.

**Comment by Jarvik7** [comment]
https://drive.google.com/file/d/0B_AGwHqca9hQQjRmbWFHRjl4V3c/view?usp=sharing

Here is a binary. Tested with shareware .pak files on OSX 10.11. You may need to adjust your resolution. It defaulted to something huge on my computer that went off-screen.

**Comment by Quindorrian** [comment]
Thanks for the help, Jarvik.  So far, it is still not working.  I copying my baseq2 stuff over into the expanded (show contents) app you sent over and it doesn't seem to do anything when I double-click the app.  Well, it opens up the window to launch Quake 2, at least.  But, when I click "start", it disappears and nothing happens.  Is there something else I need to do?

**Comment by Quindorrian** [comment]
At this point, it really doesn't seem like this Yamagi Quake 2 is viable for OS X at all...  Honestly, it's very disappointing considering all the posts on various sites about how this is the best way to run Quake 2 on a Mac...  I just don't see that being the case.  May it's just outdated info from an old version of OS X?  I ended up following the directions for getting Deus Ex to run my Mac through Winery and tried them for Quake 2 and they worked without issue.  So, it seems Winery works much better than any of these other programs and with much less hassle.

**Comment by maraakate** [comment]
The problem is none of the developers own a Mac and I don't think they're going to run out and buy one for the few people who want to play this on a Mac.  This is an on-going problem with Daikatana as well because it is hard to find a Mac developer who is willing to clean up and maintain the code for these old games.  You should relax and stop insulting the developers.

**Comment by Quindorrian** [comment]
I haven't insulted anyone personally.  It's nothing personal against any person.  The ReadMe was just very misleading.

**Comment by Quindorrian** [comment]
I found someone that is helping me with this and will post the directions once I get it to work if someone would be able to revise the readme to be more clear and with further instructions once I post the instructions?  Seems that it is pretty darn complicated to install this on the mac and create the binary.  Willing to help/contribute with any lessons learned, though.  I mean, it still works in Winery, but it is pretty vanilla.

**Comment by Jarvik7** [comment]
Obviously the makefile works since I just compiled and tested it after downloading the source.

**Comment by Quindorrian** [comment]
Yes, but didn't you just say you don't have a Mac?  So, unless you are running the latest version of OS X, how can you say for sure the MakeFile works?

I am not getting an error message.  I have nothing to work with, either, honestly.  It literally closes and does nothing else.

**Comment by Jarvik7** [comment]
Nope, didn't say that at all. Someone else said the developers don't have Macs, which is true. I'm not one of the developers.

**Comment by Quindorrian** [comment]
Well, I got it to work and will post the solution.  Experiencing some glitches though.  The big one is that it keeps resetting my gamma when the Id Software logo comes up, but the slider stays the same.  So, it's darker than I like.  Even if I set a gamma value in an auto exec, it resets it as the game is loading.  Everything else seems to be working.  Any ideas on that?

**Comment by Quindorrian** [comment]
I have amended the ReadMe as follows:


3. Installation on OS X
=======================
Yamagi Quake II has full support for Apple OS X. All features are
supported, including the IPv6 network code and the OpenAL sound backend.
As there currently is no binary release for OS X, you need to compile the source.

3.1 Supported Systems
---------------------
Yamagi Quake II should run on every Mac with Intel CPU and OS X 10.6
or higher.

3.2 Retail Version
------------------
If you own Quake II, first get the official point release to Quake II 3.20:
ftp://ftp.idsoftware.com/idstuff/quake2/q2-3.20-x86-full-ctf.exe
Use this and only this file! Unofficial pointreleases or something like
that will not work and may crash your game!

Although this file is listed as a .exe file, it can actually be extracted like a zip file.  Extract the file into a new directory (we recommend quake2\) and remove
the following files and directories:
- 3.20_Changes.txt
- quake2.exe
- ref_gl.dll
- ref_soft.dll
- baseq2\gamex86.dll
- baseq2\maps.lst
- ctf\ctf2.ico
- ctf\gamex86.dll
- ctf\readme.txt
- ctf\server.cfg
- xatrix\gamex86.dll
- rogue\gamex86.dll

Now put the Quake II CD-ROM into your cd drive and copy "pak0.pak" and
the directory "video\" to the "baseq2\" directory of your installation.

3.3 Demo Version
----------------
If you haven't got Quake II, try the demo version. Get it here:
ftp://ftp.idsoftware.com/idstuff/quake2/q2-314-demo-x86.exe

Extract this file into a new directory and delete everything but
"baseq2\pak0.pak" and the "baseq2\players\" directory. No patching
is needed for the demo, in fact it would break it.

3.4 Addons
----------
Due to license issues - Yamagi Quake II is covered by the GPL and the
addons are under the id Software SDK license - the addons are
distributed separately. You can get them at http://www.yamagi.org/quake2,
both contain installation instructions. But nevertheless you'll need an
installation of the full Quake II game with our client for playing them.
The same applies to the "ctf" capture the flag addon. 

3.5 Compiling
-------------
You must compile Yamagi Quake II on your specific OS X in order to install Quake II on OS X.  Follow these steps:

1. Install XCode with the "Unix Develoment Tools”.  Depending on your OS X version, the name of these can be different.  Xcode is currently a Free App on the Apple App Store.

2. Install dependencies using Homebrew (http://brew.sh).  Once you have Homebrew installed, run the following commands by typing them into the terminal (terminal can be opened from the OS X launchpad) and hitting return after each one from the terminal to install dependencies:

   **brew install sdl2 --universal
   brew install openal-soft --universal
   brew install libogg --universal
   brew install libvorbis --universal**
   
3. Unzip the corresponding current version of Yamagi Quake 2 from the website.

4. Navigate through the unzipped Yamagi Quake 2 folders and locate a file called “Make”.  Correct the “Make” file by opening with a simple text editor and adding/modifying the matching section of code as follows ("**" is modified code):

        # Base include path. 
        ifeq ($(OSTYPE),Linux) 
        INCLUDE := -I/usr/include 
        else ifeq ($(OSTYPE),FreeBSD) 
        INCLUDE := -I/usr/local/include 
        else ifeq ($(OSTYPE),OpenBSD) 
        INCLUDE := -I/usr/local/include 
        else ifeq ($(OSTYPE),Windows) 
        INCLUDE := -I/custom/include 
        **else ifeq ($(OSTYPE),Darwin)**
        **INCLUDE := -I/usr/local/opt/openal-soft/include -I/usr/local/include**
        endif 

        # ---------- 

        # Base LDFLAGS. 
        ifeq ($(OSTYPE),Linux) 
        LDFLAGS := -L/usr/lib -lm -ldl -rdynamic 
        ifeq ($(OSTYPE),FreeBSD) 
        LDFLAGS := -L/usr/local/lib -lm 
        else ifeq ($(OSTYPE),OpenBSD) 
        LDFLAGS := -L/usr/local/lib -lm 
        else ifeq ($(OSTYPE),Windows) 
        LDFLAGS := -L/custom/lib -lws2_32 -lwinmm 
        else ifeq ($(OSTYPE), Darwin) 
        **LDFLAGS := $(OSX_ARCH) -lm -L/usr/local/opt/openal-soft/lib -L/usr/local/lib**
        endif 

5. Open a terminal.  Type “cd” (without the quotes), hit spacebar, and then locate unzipped Yamagi Quake II in the finder (leave terminal open).  Drag the folder and drop it into the open terminal.  This will automatically enter the folder path into the terminal.  Press enter/return.  Alternatively, you can just type the complete path where the unzipped folder is stored.  Next, type “Make” (without the quotes) and press enter/return.  For example, this is what it could look like in the terminal:

             cd /Users/yamagi/Desktop/QUAKE2_5_33
             make

   The “make” process should end with the following line in the terminal: 

             ===> LD release/baseq2/game.dylib

   Two important files are generated by the “make” command.  The two resultant files can be found by drilling down further in the "build" folder in the unzipped Yamagi quote folder.  Open the "release" folder (under "build") and you'll see the generated "quake2" .exe program.  Then, open the "baseq2" folder under that, and you'll see the "game.dylib" library file.  

6. Drill into the stuff/osx folders to locate a zip file called "quake2-appbundle.zip". Open/Extract this zip file to reveal a "Quake 2.app" directory and a bunch of stuff inside that. This directory structure is still missing some things before it can be a working app, so some files need to be moved into here to finalize a working app. 

7. Move or copy everything out of that quake 2 directory created in step 3.2 or 3.3 and into the "Quake 2.app/Contents/Resources/baseq2" directory.  To do this, the Quake 2.app file must first be selected, then right click and “Show contents” to drill into the file structure.  The files you're moving should be: "pak0.pak", "pak1.pak", "pak2.pak", the "players" directory, and the "video" directory.

8. Move the "yq2.cfg" file into the "Quake 2.app/Contents/Resources/baseq2" directory to have a nicer default configuration. 

9. Move the "game.dylib" library file that we built in step 5 into the "Quake 2.app/Contents/Resources/baseq2" directory. 

10. And finally move the “quake2.exe" program file that was created in step 5 into the "Quake 2.app/Contents/Resources" directory. The app is now ready to run and can be moved to the applications or anywhere desired.

**Comment by Jarvik7** [comment]
I think you aren't using the current sourcecode. I fixed openAL in the makefile over 2 months ago.
https://github.com/yquake2/yquake2/commit/ca753d4f87ef1b645dd694f441a3a8bb0fddc219
Download the current code from github.

Also, if you want to submit changes, make a pull request instead of posting changes into an issue thread.

**Comment by neogeographica** [comment]
(FYI he was working with the most recent release, from January.)

I'm not sure the above change completely addresses the directories issues. FWIW, in my experience with a clean El Capitan system, the build of master-branch code still fails with:
```bash
===> CC src/backends/sdl/input.c
src/backends/sdl/input.c:35:10: fatal error: 'SDL2/SDL.h' file not found
```
unless /usr/local/include is added as an include path.

And it fails with:
```bash
===> LD release/quake2
ld: library not found for -lvorbis
```
unless /usr/local/lib is added as a library path.

**Comment by Quindorrian** [comment]
Thank you neogeographica; yes, I downloaded mine right from here a day or two ago: http://www.yamagi.org/quake2/

So, it seems the site has not been updated with the latest build?  

Jarvik, honestly, the format of this "forum" is also very confusing for me.  I have no idea what "pull" even means and when I go there to post, it doesn't seem so simple to just post the readme update there.  You are more than welcome to post it on my behalf.  

I'm just glad I got this to work, but the brightness bug is a game-breaker for me right now.  The reason I sought out Yamagi Quake 2 in the first place is that it support the high res texture packs (at least it says it does) on Mac.  Winery doesn't seem to support these fan based engine rebuilds that I can figure out, but it does run vanilla Quake 2 perfectly.  Just some insight.

**Comment by Jarvik7** [comment]
@neogeographica Are you sure you've installed the dependencies with homebrew?
I built the latest source on a clean, fully updated El Capitan with the dependencies via homebrew and it worked without issue.
Also, if one has problems the first step is always to try the latest code to see if something is already fixed. The January point release was 4 months ago.

@Quindorrian 
Regarding the "forum", it's github. Just take the opportunity to learn it, since it's what most open source projects use. In any case, your change isn't needed because it was already done 2 months ago. The website holds the latest point release of the code, not the "current" code. I have no control over when the devs decide to make a point release.

Regarding brightness, no idea. I am not one of the devs. Maybe one of them will reply to your other open issue.

**Comment by neogeographica** [comment]
> Are you sure you've installed the dependencies with homebrew?

Figured this one out.

Installing Xcode from the app store will (as of some recent release -- Mavericks I think) get you the "command line tools" installed automatically without a separate step/option.

However that will not configure some Unix-y/Linux-y search paths to be used by default.  Doing "xcode-select --install" is necessary to if you want those paths (like /usr/local/include and /usr/local/lib) to be assumed, even if the command-line tools are already installed.

You can use "echo | clang -v -E -x c++ -" to test the preprocessor to see what paths it is searching by default, and similarly "clang -Xlinker -v" to check the linker's default paths.

**Comment by Yamagi** [comment]
The last release from january is missing ca753d4. I guess that changeset is needed on OS X to be able to build YQ2 with OpenAL support. The later changes aren't important:

* Stereo support is somewhat special.
* Gibs moving on conveyor belts is just cosmetics.
* gl_ext_multitexturing defaulting to 1 leads to a minor render glitch in city3.

Nevertheless we can do a new release this or next weekend. 

Regarding brightness: That's working on FreeBSD, Linux and Windows. In fact there's no reason why Quake II should reset the gamma ramp when playing cinematics. It looks like another SDL2 issue on OS X, maybe it thinks that the application has lost focus. The mouse cursor is ungrabbed during cinematics, menus, in console and when the game is paused...

**Comment by Quindorrian** [comment]
Ok, but how do I fix the brightness issue?  You closed my other thread with no solution.  Or, am I just SOL?

**Comment by DanielGibson** [comment]
@Jarvik7: can you reproduce that brightness setting problem? i.e. try setting it very bright in the video menu, restart the game and observe if it starts bright and remains bright during logo video and ingame.

@Quindorrian: could you try using the latest code instead of the last Yamagi Quake2 release? You can download it at https://github.com/yquake2/yquake2/archive/master.zip

**Comment by Quindorrian** [comment]
Gave it a try and it still does the brightness thing :(  Thanks for the help though.

**Comment by Jarvik7** [comment]
@DanielGibson 
Just tested it, I will post in the issue thread for this bug.
