### ISSUE TITLE
Feature Request: Software Renderer (or a likeness of)

### ISSUE THREAD

**Issue by Thraka** [yquake2/yquake2#133]
One of my favorite engines for quake 1 is [engoo](http://leileilol.mancubus.net/engoo/) and I would love something like this for Quake 2. Honestly I think the texture rendering for normal Q2 HW rendering always looked bad compared to software mode. But software mode didn't have colored lighting and other neat stuff.

Is there a way to get HW rendering to look like software?

**Comment by DanielGibson** [comment]
Try entering the following in the console: `/gl_texturemode GL_NEAREST_MIPMAP_NEAREST`.
It should disable texture filtering.

**Comment by Thraka** [comment]
Perfect! Thank you :)

**Comment by DanielGibson** [comment]
great! :-)
