### ISSUE TITLE
HD Textures and Models

### ISSUE THREAD

**Issue by Quindorrian** [yquake2/yquake2#135]
Well, now that the brightness and the other bugs have been fixed, I am setting off to get the textures and such upgraded in Yamagi Quake 2 on OS X.  I downloaded the one from the readme for the textures and it works perfect, but what about the models and weapons?  Is anything out there for Quake 2?  I've tried the models pack in the link in the readme, but it doesn't seem to work at all...  There is a site that has high definition stuff but it doesn't list Yamagi there (http://quake2lithium.com/lithdownloads/viewcategory/15-high-resolution-paks).  Would they work?  Thank for the help.

**Comment by Quindorrian** [comment]
This is what I've found so far.  These upgrade everything but the enemy models and seem to work perfectly so far!  http://realistic.tastyspleen.net/PAKS/HI%20RES%20PAKS/

**Comment by Yamagi** [comment]
The problem with the high res skin pak is that it doesn't match all models, leading to distorted texturing.

**Comment by Quindorrian** [comment]
Thanks Yamagi.  But, shouldn't it still work - albeit with some messed up textures here and there?  What I am seeing is that it doesn't work at all.  Perhaps it's for the best...  Just can't believe how many people went through the trouble of doing all these retextures but didn't do the models....

**Comment by mckaygerhard** [comment]
**i can sure the problem its the case-sensity names of files..** when i tested in my venenux box.. 

i uses that and see 88 files load but after renamed lowercase and ajust some config files..

```
Added packfile '/home/remoto/Descargas/quake2/baseq2/pak7.pak' (88 files).
Added packfile '/home/remoto/Descargas/quake2/baseq2/pak8.pak' (122 files).
Added packfile '/home/remoto/Descargas/quake2/baseq2/z6_32bitclr_png_allmaps.pak' (1655 files).
```

i have problem loading the Juggernaut: The New Story  expansion game, this due some maps have hardcoded paths that use UPPERcase names and other lowercase, so some files (in especial textures) dont load...

**Comment by Yamagi** [comment]
Windows is case insensitive, nearly all other system are the opposite... Since Quake II is rather chaotic it's hard to work around this problem in code. There best solution is to repack the mods gamedata and the retexturing pack to match the source.

**Comment by mckaygerhard** [comment]
i spected that response.. i tried but seems the only tool that help to do that its the q3map2 de the files are bsp maps... but this tool comes now with gtkradiant and packagin of that are a painfull!

there's another tool or othe location to download the sources only for q3map2 tool or similar?

**Comment by Yamagi** [comment]
If you want to decompile and edit the maps have a look at Quark: http://quark.sourceforge.net/ In my experience Quake is rather slow but it's the only full featured game data editor for Quake II still working without too much hassle.

**Comment by mckaygerhard** [comment]
seems the quark tools looks pretty good, but also seems its not native linux.. u make me sufer!

i can note u have a repo with https://github.com/yquake2/maptools some tools, did those works for edit juggernau bsp q3 files?

**Comment by Yamagi** [comment]
The maptools repo is just a port of id Softwares original game data compilers to 64 bit Linux. I don't think that they can be used to decompile .bsp maps. But do you even need to decompile the maps, can't you just rename / copy the textures, models and so on?

**Comment by mckaygerhard** [comment]
yeah, imilar, decomnpile can be hard to do due the only tool for linux depends on network, 

seems the only solution its made names in lowercase and in uppercase, if i made a script and i have same file but in both uppercase and lowercase, by example:
MAPS/JDM1.BSP
and
maps/jdm1.bsp
and 
MAPS/jdm1.bsp

the yquake2 engine will load only the pointed for the mod or all the founds!?

i''ll think that i can made a script that make symlinks in lowercase and uppercase when necesary and this solves (not so elegant .. well)!

**Comment by Yamagi** [comment]
I just had a deeper look. Making Quake IIs file loading logic case insensitive is next to impossible. The first and biggest problem is, that not all files loaded through the central infrastructure in filesystem.c. But even if that could be fixed (it can't for mods) a rather invasive refactoring of the code would be necessary. So the best solution to this problem is to rename the files and / or poke mod authors to get their stuff right.

**Comment by mckaygerhard** [comment]
yeah, i confirm that! i mde a very crude script and test some maps now load, some not! its a pain and well the only solution for

thans in any @Yamagi
