### ISSUE TITLE
ReadMe Update Request

### ISSUE THREAD

**Issue by Quindorrian** [yquake2/yquake2#136]
I posted my recommended update in the previous issue thread, which now appears to be closed.  I've tried messing with "pull requests" and I just can't figure it out to post my recommended ReadMe update.  Would someone please help me?  Trust me when I say you are helping all OS X users by updating the ReadMe.  Otherwise, people are going to continue to be lost and probably not be vocal about it (unlike me).  Thank you very much.

P.S. On a side note, would someone make sure the main Yamagi download gets updated from the master file with all these corrections?  Haven't tried the main download yet, since all these issues have been being worked out, but I just want to make sure.

**Comment by Jarvik7** [comment]
Your change isn't needed because:
1) It's asking users to modify the makefile. If the makefile needs to be changed it should be changed in the code, not by end users
2) It's fixing something that was already fixed 2 months ago. You were using an older copy of the source.

**Comment by DanielGibson** [comment]
Weren't there also changes improving the explanation?
I'll probably compare those changes to our version of the README and copy over the parts still relevant.

We'll probably do a new release soonish (maybe this week/weekend?), so the official download should work better with OSX then.

**Comment by Quindorrian** [comment]
Thanks Daniel.  Yes, there were some pretty big changes to the explanation.  I agree that the make file section won't be needed as long as the main download site is corrected to the current master file download.  But, the biggest thing in the readme was further explanation, which I would say is crucial for someone is who is not intimately familiar with terminal and such.  Just figured I'd try to help out.  Thanks again.

**Comment by neogeographica** [comment]
Aside from things that will be fixed in the upcoming release, the main remaining issue seems to just be mentioning the need to do "xcode-select --install" to set up the include and library paths.

The other suggested changes have to do with level of detail, for people who aren't familiar with compiling on OS X or with building stuff in general. There could be some wordsmithing applied here and there to help with that, but perhaps any effort would be better applied toward just providing prebuilt binaries? It's hard to anticipate everyone's level of experience and it would be a heavy burden for any one project to take on the responsibility for filling in that background.

I'm not sure what the issues are with providing OS X binaries at the moment, but if it's mainly a matter of finding OS X users to help build them, then I can pitch in.

**Comment by DanielGibson** [comment]
Well, they need to be built and we need a way to bundle the needed libs (SDL2, ogg/vorbis, maybe openal-soft, did I miss anything?).
Furthermore the binaries should be built in a way so they don't require the latest OSX version, ideally support for 10.5 or 10.6 and newer should be achieved.

**Comment by Quindorrian** [comment]
Daniel and Neo, this would help a lot, but as I understand, the devs don't have access to OS X?  This is why I wanted to help out with a more detailed readme.  I ended up having to go to another forum to get help installing because I couldn't understand the current readme - much of which is due to my ignorance with compiling and such.  From what I know, the average Mac user is going to run into the same problem(s).

**Comment by Jarvik7** [comment]
I am against the readme being updated to hold people's hand and teaching
them to compile. Honestly it explains too much already.

Two things should happen to make it more user friendly.
#1 is OS X binaries
#2 is submitting a recipe to homebrew so one need only type 'brew install
yquake2'

**Comment by Quindorrian** [comment]
What?!  Seriously dude? 

The Readme doesn't even explain what the Make file even does, what files it creates, and where it puts them.  It leaves out TONS of other un-obvious, important details.  I would take the time to list them, but not if you are automatically going to write me off.

**Comment by Yamagi** [comment]
The intent of the README was to provide an more or less easy to follow guide to compile the source. It was never meant to be a complete guide into build systems, compilers and dependency tracking. Jarvik's right, the 'how to compile' stuff could be cut down to the essential minimum. Windows has binaries, the unixoid systems have package managers. So OS X should follow the one or the other. Either provide binaries or add YQ2 to a popular package manager. 

What a Makefile is and who make(1) works is rather well documented: http://lmgtfy.com/?q=Makefile

**Comment by Quindorrian** [comment]
You guys really come off as pretty damn elitist.  Good luck getting lasting support from many people on this.  Not sure why you feel that someone who wants to play this should be a developer.  Think about it...  People that are looking to play Quake 2 on their mac are old school gamers (not developers) wanting to enjoy the game casually on their Mac.  I know a ton of PC and Mac users and not a single damn one of them would know wtf you are even talking about with Binaries and all this jargon.  I probably put in too much time into this honestly, but I was just trying to help out.

If you want to do this the right way you would, either: 1. Make the instructions more clear (despite what you say, the directions aren't clear even if you are a developer) 2. Make a simple installer.  Otherwise, why even bother with this version of Quake 2?  You are limiting it to about 5 % of the Quake 2 fans out there, since the other 95% would not be willing to figure it out and just move on with life.  Not that you are really caring about opinions so much, but my 2 cents.

**Comment by Jarvik7** [comment]
1) You are welcome for my effort in tracking down your gamma bug and compiling a binary for you.

2) The readme for a piece of game software is not the place to teach people how to use OSX tools. It is not a tutorial.
If you do not feel like spending any time or effort on learning how to use a compiler (not programming), you can wait for the binaries that someone has already pledged to provide.

3) The developers owe you nothing. They spend their own time doing this for free. Maybe you can turn your sense of entitlement and negativity into something productive and learn how to make the change you want.

**Comment by Quindorrian** [comment]
Of all the arrogant, cop-out responses I have received...  Since when should your "project" REQUIRE people to learn OS X tools?  It's quite easy for you to get this ass-backwards in your mind standing up high on your developers podium.  But, SIR, you indeed have this all wrong.  See, the noble developer does not EXPECT the common man to BEEEEEE a developer.  Of course, you being the elitist fuck that you are, think that somehow your half-assed "project" is cooler than everyone else and that if we can't compile shit, well we just suck.  

I've been trying to tell you OVER and OVER and OVER and OVER, and you just don't fucking listen.  99.999999999% OF ALL PEOPLE USING COMPUTERS DO NOT KNOW WTF HOW TO COMPILE SHIT!  You got that?  In addition.....drum roll....news flash.....   99.99999999999% OF THOSE SAME PEOPLE WILL NOT WANT TO TAKE THE TIME TO LEARN.  Unless they are damn desperate.

In addition to all this, there is a community out there revolving around this game and people outside this "Github" nonsense (WTF is a Github, anyway) also feel that your instructions are bullshit non-sense and they question some missing features in your "mod" (such as networking protocol).

As far as you taking the effort to fix the gamma bug - IT WAS LIKE PULLING TEETH DUDE.  First, others had to jump in for you to be convinced it was a bug.  Then, it was excuses.  Look, do you actually want to do this right, or is half-assing it more your speed?  What exactly are your motives/intentions for even doing this project?  You want it to work or you just lazily slop-jobbing it?  Your choice.

Oh, and your welcome for taking the time to actually write a readme and pointing out that the download was outdated and that a gamma bug even exists.  Next time, I'll just do what most people have already done: Tried it, failed, said nothing, moved on with life.  Yeah.

**Comment by maraakate** [comment]
bro it just works.

**Comment by Jarvik7** [comment]
You keep thinking I'm one of the developers. I'm not.
I'm just a user who wanted to use yquake2 on my Mac and fixed the OSX support so the devs wouldn't just totally remove it.

re: gamma: What? You seem to have a problem keeping people straight. Again.

Also, I doubt anyone cares what the "marketshare" of yquake2 is. If someone doesn't want to take the time to figure anything out, why should anyone else take the time to help them?

**Comment by maraakate** [comment]
Also, there isn't that many OS X users out there demanding ports of 
these games and when something like the gamma code has been working fine 
across multiple platforms (even my DOS port has working on the fly gamma 
changes!) then it's assumed the most likely scenario is something 
configured improperly on your target machine..  whoops that was too big 
of words, i mean your computer dude... or ibook, whatever.

**Comment by DanielGibson** [comment]
We're doing this in our freetime, for fun. We don't get paid for this. At all.

Neither Yamagi nor me care about OSX very much, as we're don't own Macs.
In fact, we don't really use Windows much either, for years we only supported Linux and FreeBSD. Windows support was (re-)added some years ago, because it wasn't too hard, we have Windows partitions on our PCs and in VMs to test anyway (which is not a legal option for OSX), creating portable Windows executables isn't as painful as it is for OSX.
As Jarvik7 wrote, we were gonna remove OSX support, but kept it after he fixed it. We don't care very much if that only reaches OSX users who know how to compile.

So stop pretending we owe you or any Mac user anything. The gamma bug still is an OSX bug btw (thus we couldn't reproduce it on our systems), so maybe try insulting Apple - at least you paid for their crappy products so **they** actually owe you support.

Your bitching does not improve our motivation to further support OSX, by the way. Standing incompetent users can be annoying, but if they add entitlement and insults that's more than we're willing to take. Remember, we're doing this project for fun.

**Comment by Yamagi** [comment]
We'll rework the README before the next release. It won't happen this weekend, but maybe in the coming week. It depends on my day job and on several other projects with higher priority.
