### ISSUE TITLE
Game freezing after loading map

### ISSUE THREAD

**Issue by chaoticdream** [yquake2/yquake2#139]
Hi,

I just finished installing Yamagi quake and when I launch a new game on hard it loads  properly but after a few seconds of moving around it gets really laggy then stops responding altogether. I also tried q2dm1 with the same result. I am running in 1920x1080 res on a 52" HDTV for monitor. I have tried anniso filtering off, enabling disabling vsync , setting cl_maxfps to 95 and gl_swapinterval to 1.   System information is as follows:

OS Windows 10
AMD FX 9590 CPU
Nvidia GTX 970 GPU
16GB Ram

Any insight into what i can do to get this working would be greatly appreciated!

**Comment by chaoticdream** [comment]
I just found another thing, when it freezes if i click the fire button the weapon shoots and the game unfreezes and runs choppy before freezing again and i can repeat the process by firing my weapon again. I also just tried in windowed mode with 1280x1024 resolution with no changes in performance

**Comment by chaoticdream** [comment]
Here is a video of what I am seeing as well https://youtu.be/Oe3zF_xx9mw

**Comment by maraakate** [comment]
I didn't see this until now but set gl_dynamic to 0 and gl_ext_multitexture to 0.
