### ISSUE TITLE
Multiplayer  Players Weapon Models wont show up

### ISSUE THREAD

**Issue by KOYK** [yquake2/yquake2#140]
Multiplayer  Players Weapon Models wont show up in during game.(weapons on hands used by other players) only the default shotgun model is used,and not the weapon model currently the user is holding.

ps. i am using "eraser bot mod" but i tested it on the original quake 2 and the weapons worked as they should.BUT in Yamagi Version they don't. So any fix will be much appreciated.

**Comment by DanielGibson** [comment]
I just tested this in real multiplayer (standard quake2 deathmatch) and the weapons show up.

What Yamagi Quake2 release (version) are you using, what operating system, do you have a link to that mod?

**Comment by KOYK** [comment]
My Yamagi version is 5,30.the mod is called eraser bot,but the install file wont work in windows 7(if you are using win7) you have to install it on winxp. but anyway here is the link http://www.fileplanet.com/35414/30000/fileinfo/Eraser-Bot-1.01-(FINAL!)

to be clear: i don't mean the weapon you hold in your own hands,but the weapon you see that other players are holding in ther hands*

**Comment by DanielGibson** [comment]
We released 5.34 yesterday, could you test that as well?
(you can download it at http://deponie.yamagi.org/quake2/windows/quake2-5.34.zip )

**Comment by Yamagi** [comment]
This may be a special case of issue #119. Can you copy the baseq2/players directory into into your mod directory and try again?

**Comment by KOYK** [comment]
i tested  5.34v and it can't even load the mod, console say "initgame map mod v1.01 missing maps.txt" and "unable to read bots.cfg" i have those files in place btw.
on 5.30v this is not happening,and the mod works on that version(except from the weapons thingy)

AND i have all the player models on the mod dir and also on the game dir
baseq2/players & eraser/players

**Comment by maraakate** [comment]
check if maps.txt and bots.cfg is not completely lowercase as linux is 
case sensitive and windows isn't.  Some older mods had upper case names 
and whatnot, remnants of Windows 9x crud.

Frank

**Comment by KOYK** [comment]
nope nothing.

**Comment by Yamagi** [comment]
I thought that commit 7456daf could have broken some mods, but Erazer is working for me on all version from 5.30 to 5.34. Tested on Windows 7 64-Bit. You could try to create the `Documents\YamagiQ2\Erazer` directory by hand if it isn't already there. There're some mods that try to read their config directory before the Quake II filesystem even knows that it exists. Also make sure that Quake II can write into the Erazor install directory. Some old mods insists on writing into their install directories... If everything fails please send the `Documents\YamagiQ2\stdout.txt`. Maybe Erazer is kind enough to tell us what's missing.

**Comment by Yamagi** [comment]
Regarding the weapon models: The weapon models are registred successfully, all files are found by the game. So this problem isn't caused by broken paths or missing files. Maybe Erazor doesn't send weapon change events the clients, but at this time that's just an educated guess.

**Comment by KOYK** [comment]
1) Documents\YamagiQ2\Erazer.well i check that and there is already there,so we are ok on that.
2) "Also make sure that Quake II can write into the Erazor install directory" how i do that? (sorry)
<details> 
  <summary>3) stdout.txt </summary>
   Yamagi Quake II v5.34
=====================

Client build options:
 + SDL2
 - CD audio
 + OGG/Vorbis
 + OpenAL audio
 + Zip file support
Platform: Windows
Architecture: AMD64
Byte ordering: little endian

Added packfile './baseq2/pak0.pak' (3307 files).
Added packfile './baseq2/pak1.pak' (279 files).
Using binary dir C:\Games\quake2\baseq2/ to fetch paks
Added packfile 'C:\Games\quake2\baseq2/pak0.pak' (3307 files).
Added packfile 'C:\Games\quake2\baseq2/pak1.pak' (279 files).
Added packfile 'C:\Games\quake2\baseq2/pak0.pak' (3307 files).
Added packfile 'C:\Games\quake2\baseq2/pak1.pak' (279 files).
Added packfile './Eraser/pak5.pak' (1 files).
Using binary dir C:\Games\quake2\Eraser/ to fetch paks
Added packfile 'C:\Games\quake2\Eraser/pak5.pak' (1 files).
Added packfile 'C:\Games\quake2\Eraser/pak5.pak' (1 files).
Using 'C:/Users/ELoyros/DOCUME~1/YamagiQ2/Eraser' for writing.
execing default.cfg
couldn't exec yq2.cfg
execing config.cfg
Winsock Initialized
Console initialized.

------- sound initialization -------
LoadLibrary(openal32.dll)
...opening OpenAL device:ok
...creating OpenAL context: ok
...making context current: ok

OpenAL settings:
AL_VENDOR: OpenAL Community
AL_RENDERER: OpenAL Soft
AL_VERSION: 1.1 ALSOFT 1.17.2
AL_EXTENSIONS: AL_EXT_ALAW AL_EXT_BFORMAT AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_BFORMAT AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_LOKI_quadriphonic AL_SOFT_block_alignment AL_SOFT_buffer_samples AL_SOFT_buffer_sub_data AL_SOFT_deferred_updates AL_SOFT_direct_channels AL_SOFT_loop_points AL_SOFT_MSADPCM AL_SOFT_source_latency AL_SOFT_source_length

Available OpenAL devices:
- OpenAL Soft on Speakers (Realtek High Definition Audio)
- OpenAL Soft on Realtek Digital Output (Realtek High Definition Audio)

Current OpenAL device:
- OpenAL Soft

Number of OpenAL sources: 31

Starting Ogg Vorbis.
OGG_LoadPlaylist: could not open playlist: No such file or directory.
20 Ogg Vorbis files found.
Sound sampling rate: 0
------------------------------------

----- refresher initialization -----
Byte ordering: little endian

Refresher build options:
 + Retexturing support
 - Gamma via X11
Refresh: Yamagi Quake II OpenGL Refresher
SDL video driver is "windows".
setting mode 21: 1920 1080
Got 8 bits of stencil.
Using hardware gamma via SDL.

OpenGL setting:
GL_VENDOR: NVIDIA Corporation
GL_RENDERER: GeForce GTX 960/PCIe/SSE2
GL_VERSION: 4.5.0 NVIDIA 347.88
GL_EXTENSIONS: GL_ARB_depth_texture GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_imaging GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_shader_objects GL_ARB_shading_language_100 GL_ARB_shadow GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_mirrored_repeat GL_ARB_texture_non_power_of_two GL_ARB_texture_rectangle GL_ARB_transpose_matrix GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_window_pos GL_ATI_draw_buffers GL_ATI_texture_float GL_ATI_texture_mirror_once GL_S3_s3tc GL_EXT_texture_env_add GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_compiled_vertex_array GL_EXT_Cg_shader GL_EXT_depth_bounds_test GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_packed_pixels GL_EXT_pixel_buffer_object GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_specular_color GL_EXT_shadow_funcs GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_texture3D GL_EXT_texture_compression_s3tc GL_EXT_texture_cube_map GL_EXT_texture_edge_clamp GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_EXT_texture_filter_anisotropic GL_EXT_texture_lod GL_EXT_texture_lod_bias GL_EXT_texture_mirror_clamp GL_EXT_texture_object GL_EXT_vertex_array GL_IBM_rasterpos_clip GL_IBM_texture_mirrored_repeat GL_KTX_buffer_region GL_NV_blend_square GL_NV_copy_depth_to_color GL_NV_depth_clamp GL_NV_fence GL_NV_float_buffer GL_NV_fog_distance GL_NV_fragment_program GL_NV_fragment_program_option GL_NV_fragment_program2 GL_NV_half_float GL_NV_light_max_exponent GL_NV_multisample_filter_hint GL_NV_occlusion_query GL_NV_packed_depth_stencil GL_NV_pixel_data_range GL_NV_point_sprite GL_NV_primitive_restart GL_NV_register_combiners GL_NV_register_combiners2 GL_NV_texgen_reflection GL_NV_texture_compression_vtc GL_NV_texture_env_combine4 GL_NV_texture_rectangle GL_NV_texture_shader GL_NV_texture_shader2 GL_NV_texture_shader3 GL_NV_vertex_array_range GL_NV_vertex_array_range2 GL_NV_vertex_program GL_NV_vertex_program1_1 GL_NV_vertex_program2 GL_NV_vertex_program2_option GL_NV_vertex_program3 GL_NVX_conditional_render GL_SGIS_generate_mipmap GL_SGIS_texture_lod GL_SGIX_depth_texture GL_SGIX_shadow GL_SUN_slice_accum GL_WIN_swap_hint WGL_EXT_swap_control 


Probing for OpenGL extensions:
...using GL_EXT_compiled_vertex_array
...using GL_EXT_point_parameters
...GL_EXT_shared_texture_palette not found
...using GL_ARB_multitexture
...using GL_EXT_texture_filter_anisotropic
...using GL_ARB_texture_non_power_of_two
...using GL_ARB_texture_env_combine
------------------------------------

------- input initialization -------
------------------------------------

-------- game initialization -------
==== InitGame ====

==== Map Mod v1.01 set up ====
Adding maps to cycle: BASE1, IKDM1, MINTRO, MPQ1, SEVERED1, TOD

------------------------------------

------- server initialization ------
0 entities inhibited
0 teams with 0 entities
------------------------------------

==== Yamagi Quake II Initialized ====

*************************************

KOYK connected
[0.0.0.0]:0: client_connect
------- server initialization ------
0 entities inhibited
0 teams with 0 entities
------------------------------------


Changing map...
reconnecting...
game will be changed for next game.




Installation
execing launcher.cfg
Map: base2
                                     
pics
                                     
maps/base2.bsp
                                     
models/weapons/v_blast/tris.md2
                                     
models/objects/gibs/sm_meat/tris.md2
                                     
models/objects/gibs/arm/tris.md2
                                     
models/objects/gibs/bone/tris.md2
                                     
models/objects/gibs/bone2/tris.md2
                                     
models/objects/gibs/chest/tris.md2
                                     
models/objects/gibs/skull/tris.md2
                                     
models/objects/gibs/head2/tris.md2
                                     
models/monsters/gunner/tris.md2
                                     
models/monsters/infantry/tris.md2
                                     
models/monsters/soldier/tris.md2
                                     
models/objects/laser/tris.md2
                                     
models/deadbods/dude/tris.md2
                                     
models/items/ammo/shells/medium/tris.
                                     
models/items/healing/medium/tris.md2
                                     
models/weapons/g_shotg/tris.md2
                                     
models/weapons/v_shotg/tris.md2
                                     
weapons/v_shotg/flash2/tris.md2
                                     
models/items/armor/shard/tris.md2
                                     
models/items/ammo/bullets/medium/tris
                                     
models/items/ammo/grenades/medium/tri
                                     
models/weapons/v_handgr/tris.md2
                                     
models/items/healing/large/tris.md2
                                     
models/monsters/flyer/tris.md2
                                     
models/items/healing/stimpack/tris.md
                                     
models/items/armor/jacket/tris.md2
                                     
models/objects/debris1/tris.md2
                                     
models/objects/debris2/tris.md2
                                     
models/objects/debris3/tris.md2
                                     
models/objects/barrels/tris.md2
                                     
models/weapons/g_shotg2/tris.md2
                                     
models/weapons/v_shotg2/tris.md2
                                     
models/weapons/g_machn/tris.md2
                                     
models/weapons/v_machn/tris.md2
                                     
models/objects/gibs/head/tris.md2
                                     
models/items/quaddama/tris.md2
                                     
images
                                     
client 0
                                     
sky
                                     

Dynamic node-table generation ENABLED

==== ShutdownGame ====
Gamedir should be a single filename, not a path.
-------- game initialization -------
==== InitGame ====
==== Map Mod v1.01 - missing maps.txt file ====
------------------------------------

------- server initialization ------
********************
ERROR: Game Error: Unable to read bots.cfg. Cannot continue.

********************
==== ShutdownGame ====

----------- shutting down ----------
Shutting down Ogg Vorbis.
Shutting down OpenAL.
Shutting down input.
</details>
4) OK Weapon problem solved on 5,30v: user\Documents\YamagiQ2\Eraser\config.cfg
        set view_weapons "0" i change it to 1
i did change that on my quake2 mod folder but it didn't work for some reason.
But now that i change it on my Documents\YamagiQ2\Eraser\config.cfg it worked (by the way i didn't know that there was an extra Yamagi dir on Documents.sorry for that)

**Comment by Yamagi** [comment]
The 'view_weapons' cvar seems to instruct Eraser to send weapon change events to the client. It may be some kind of performance optimization back from the bad old days were 28kbit/s connects were standard and every single bit war precious. I'm glad that the problem was solved without debugging through the entity parsing code. ;)

Regarding the loading problem: It  looks like some kind of file search path problem. I'm still unable to reproduce it, but I have a vague idea were to look. Give me a few days.

**Comment by KOYK** [comment]
haha yea that would be a waste of time,sorry for the inconvenience.

by they way i notice something,after the change i made in the cfg(YQ5,30v),the view_weapons "1" line got replaced by cl_vwep "1", i don't know if this is natural or a bug,but i felt that i had to report it to you.

Take your time,you already done more that you needed to,by reviving this game for us.

**Comment by DanielGibson** [comment]
view_weapons seems to be a CVar from eraser, while cl_vwep is a CVar of the client itself (defaulting to "1").  
So whatever happened there is most probably eraser's fault and as things seem to work for you now doesn't really matter anyway ;)
