### ISSUE TITLE
Continuous integration with travis-ci or something

### ISSUE THREAD

**Issue by smcv** [yquake2/yquake2#145]
ioquake3 uses [travis-ci](https://travis-ci.org/) for continuous integration, and I've also contributed travis-ci glue to OpenJK (although it isn't used in the official OpenJK repository). Would there be interest in connecting up something like that for yquake2? This would avoid pull requests that caused regressions on a platform that is built by the CI; it's possible to configure the travis-ci hook to run for every pull request, so you can see when you review a pull request whether it broke any of the builds.

The easiest possible build would be an ordinary 64-bit build on Ubuntu 12.04 or 14.04. The travis-ci glue that was merged into OpenJK also does a 32-bit build on Ubuntu, and 32- and 64-bit builds targeting Windows using the mingw-w64 toolchain, resulting in reasonably complete coverage (the most notable omissions being OS X and anything non-x86).

For another project (ostree) I'm also experimenting with using travis-ci's support for Docker to do builds in a Debian environment.

In other projects I've been doing this by writing a generic `ci-install` shell script that would work on any Debian derivative, and a `ci-build` shell script that would work on any reasonably complete Unix platform, so that the `.travis.yml` (the only part specific to travis-ci) is as small as possible.

**Comment by Yamagi** [comment]
We've got a Travis setup at work and I'm a big supporter for FreeBSDs Jenkins CI system. But din't know if it's really worth the effort to setup a continuous integration server for Quake II. It's a small project with about 0 to 10 commits a month, most of them being bugfixes. Over the years build failures were never a problem, with you pull request a rare exception. ;) A much bigger problem are game play regressions that are often hard to find.

**Comment by Jarvik7** [comment]
Aside from OSX build failures, haha.
