### ISSUE TITLE
Enemies not spawning on The Reckoning

### ISSUE THREAD

**Issue by gohanzo** [yquake2/yquake2#148]
I apologize if this is related or not, while playing the Reckoning on the first level the enemies don't spawn, the error in the console is the following:

monster_gekk doesn't have a spawn function
130 entities inhibited
3 teams with 8 entities

Thanks!

**Comment by Yamagi** [comment]
Hi,
are you seeing this on Windows or on Linux?

Regards,
Yamagi

**Comment by gohanzo** [comment]
Thanks for the response,

I’m sorry i should have specified, i am seeing this in Mac OS X El Capitan.
by the way, where is the config file on Yamagi Quake 2, i cannot seen to find it.

Thanks again!

**Comment by maraakate** [comment]
Are you using the right gamex86.so (or whatever it's called on this port) in your /xatrix/ directory?  If it's not there it would default to the regular gamex86.so which would not have the spawn functions for the new enemies.

**Comment by maraakate** [comment]
And did you start the game with yquake2 +set game xatrix ?

**Comment by Yamagi** [comment]
Yes, that would have been my question too. This sound like a wrong game.dynlib. 

The config is in /Users/$username/.yq2.

**Comment by gohanzo** [comment]
Yes, i created the game.so from the command line, and i am playing the game by entering the command yquake2 +set game xatrix after doubleclicking the quake 2.app (see screenshot) or i need to enter that while on the game console?

So explain me please since i am very new with the command line but i am learning on my own,

I follow the instructions, i created the game.dylib (placed on baseq2 dir), q2ded and quake2 (placed on root install dir) by using the command “make” on terminal. 

is that the only game.dylib i need for the game? or am i missing something else?

also under rogue dir and xatrix dir, i created the game.so files for each using the source files.

Thanks!!!

**Comment by Yamagi** [comment]
You'll need to build the game.dynlib from the 'xatrix' source (https://github.com/yquake2/xatrix) and put it into the xatrix/ subdirectory. The game.dynlib found in the baseq2/ subdirectory is needed for the main game only and not for the addons.

**Comment by gohanzo** [comment]
I thought that is what i am doing, 

- Downloaded the quake2-xatrix-2.04 zip and unzipped to my desktop,
- Opened Terminal and CD to quake2-xatrix-2.04 and enter “make”
- It creates “game.so but i don’t see the game.dylib anywhere (when i tried that for the main quake 2 game it     created the game.dylib along with the other files.
- what am i missing?

Thank you!!!

**Comment by Yamagi** [comment]
Ahhh... That's a bug or better an oversight in the build system. The filename is wrong, you can just rename game.so to game.dynlib. I'll fix that.

**Comment by gohanzo** [comment]
Thank you for noticing, i was not sure what i was doing wrong, i will rename the file and see how it goes :-)
by the way could you take a look at this screenshots… the one without the errors or warnings is from the Rogue source and perhaps you could tell what’s wrong with it, the other one for Xatrix source is fine i think.

**Comment by gohanzo** [comment]
When you fix it make sure is called “game.dylib”
since that’s how OS X shows

**Comment by Yamagi** [comment]
Yes, you're right. Thank's for the hint.

Did you forget the screenshot? :)

**Comment by gohanzo** [comment]
I sent it, prior to the game.dylib discussion :-) but here it is again!!

Thank you so much for your help!!!

**Comment by maraakate** [comment]
Still not showing up, can you upload it and post a link?

**Comment by gohanzo** [comment]
Here are the screenshots: 

![rogue_screenshot](https://cloud.githubusercontent.com/assets/21012784/17649892/6476b61c-620d-11e6-859b-d9775d9bcf55.jpg)

![xatrix_screenshot](https://cloud.githubusercontent.com/assets/21012784/17649895/6a805d60-620d-11e6-92aa-48df334cbfd6.jpg)

**Comment by maraakate** [comment]
Just some compiler warnings, should work OK for you.

**Comment by gohanzo** [comment]
Cool, so far so good. 

one last question, is it better to launch the quake 2 add ons from the quake 2 launcher or by using the add command line option from the launcher?

Thanks!!!

![quake2_launcher_command](https://cloud.githubusercontent.com/assets/21012784/17649942/47e3b436-620e-11e6-98fc-b166f1e9d663.jpg)

![quake2_launcher](https://cloud.githubusercontent.com/assets/21012784/17649943/4ae53894-620e-11e6-9417-fe89297e68a2.jpg)

**Comment by Yamagi** [comment]
In theory that shouldn't make any difference. In practice I don't know. Just test it :)

**Comment by gohanzo** [comment]
Both worked fine and i don't see a difference.

Thanks everyone that took the time to help me!!! 

Hans
