### ISSUE TITLE
Guard Runs In Place On Base1

### ISSUE THREAD

**Issue by shoober420** [yquake2/yquake2#151]
I remember when playing Quake 2 as a kid, that this specific Guard would run at me when I was half way down the hall way in Base1.

http://i1124.photobucket.com/albums/l562/shoober420/quake03_zps8dkmiadf.jpg

Since using Yamagi for a couple of years, this Guard will now just run in place near the door, and not run down the hallway to meet you half way. I never thought of mentioning it because its very minor, but thought I might as well mention it. There's another instance of an Enforcer in Base2 that also runs in place that I clearly remember will run at you and meet you half way. It seems that the script for these specific enemies is not working anymore.

I'm on Arch Linux, and my full system specs are in my Steam profile which is linked in my github profile.

**Comment by maraakate** [comment]
Are you using a 64-bit version of yq2?  May be another one of those 
32-bit to 64-bit porting issues.

Frank

**Comment by shoober420** [comment]
Yes, I'm on 64 bit.

**Comment by Yamagi** [comment]
This is a long standing issue. I was never able to locate the problem. Maybe Daniel and I will have another look.

**Comment by shoober420** [comment]
Thank you sir.

**Comment by MilkeyWilkey** [comment]
I can confirm this. Just finished the whole game and this happens alot. My theory is that it's somehow linked to ai's starting thinking or path nodes. also commonly happens when enemy is running in circles before even spotting you (sight sound plays when you shoot at him). and another thing is that enemies frequently just dont pay attention to you even when you are in the straight line of sight and relatively close to them.

**Comment by iButane** [comment]
>  Are you using a 64-bit version of yq2? May be another one of those 32-bit to 64-bit porting issues.

Is the windows prebuild intentionally 32 bit? I noticed a *32 next to it on my windows 7 (64 bit) taskbar earlier today.

I also have this issue throughout the game where the guard runs in one spot etc. Seems like everyone does?

**Comment by MilkeyWilkey** [comment]
this happens in, at least, all of the windows builds on the site. I'm using win7 x64

**Comment by Yamagi** [comment]
Can anyone screenshot that enforcer in base2? I'm unable to find it.

**Comment by shoober420** [comment]
I'm sorry I haven't responded sooner. I ran into some kernel trouble with 4.8.2. All is good now. Fricking ACPI! Here's the enforcer in base2.

http://i1124.photobucket.com/albums/l562/shoober420/quake04_zpskyzdhb5r.jpg

**Comment by DanielGibson** [comment]
I just committed a fix for this. This bug has been in yq2 since 2009 :)

**Comment by Yamagi** [comment]
New binaries (build from the 'master' branches HEAD) can be found here: http://deponie.yamagi.org/quake2/misc/quake2-6.00-stuck_enemies.zip Please note that currently the fix is just in baseq2 and not in the addons.

**Comment by shoober420** [comment]
I just did a git pull and tested the recent commits, and they for sure fixed the issue. Awesome! Great job! Thank you so much! The AI seems a little smarter too.
