### ISSUE TITLE
Black Texture In Base2

### ISSUE THREAD

**Issue by shoober420** [yquake2/yquake2#152]
I didn't really notice this until the end of the first unit.

http://i1124.photobucket.com/albums/l562/shoober420/quake00_zpsqvrzz14u.jpg

This could be my cvar settings in my autoexec. I'll play around with it and see if a cvar is responsible. Heres my config just for reference.

allow_download "0"
allow_download_maps "0"
allow_download_models "0"
allow_download_players "0"
allow_download_sounds "0"

cl_async "0"
cl_maxfps "120"
cl_run "1"

fov "105"
crosshair_scale "1"
ogg_enable "0"

gl_anisotropic "16"
gl_cull "1"
gl_palettedtexture "0"
gl_pointparameters "2"
gl_swapinterval "0"
gl_farsee "1"
gl_hudscale "3"
gl_consolescale "3"
gl_maxfps "120"
gl_multitexture "0"
gl_mtexcombine "0"
gl_menuscale "3"
gl_novis "1"
gl_overbrightbits "0"
gl_round_down "0"
gl_shadows "0"
gl_stencilshadow "0"
gl_texturealphamode "GL_RGBA"
gl_texturesolidmode "GL_RGB"
gl_texturemode "GL_LINEAR"

name "TyranT"
rate "25000"

s_mixahead "0.035"

**Comment by shoober420** [comment]
I found it. Its the gl_novis cvar. Once you disable it by setting it to 0, that black texture disappears. Is it drawing a structure it shouldn't be when its enabled?

**Comment by Yamagi** [comment]
gl_novis is a debug cvar. Disabling the visibility calculations make the renderer slower (no visibility considerations -> more polygons and textures to render) and may cause render problems. Likely there are invisible objects in the scene. With gl_novis set to 0 they're omitted, with a value of 1 they're considered for the lighting pass leading to misslighting and / or wrong shadows.

**Comment by shoober420** [comment]
Ok, I've played through the game before with it enabled and this was the only time I've seen such a thing, so I'll just close this. Thank you for clearing that up Yamagi.
