### ISSUE TITLE
'ERROR: CL_AddMuzzleFlash2: bad offset' crash

### ISSUE THREAD

**Issue by iButane** [yquake2/yquake2#153]
When playing this MOD: http://musashi.backshooters.com/smd.html the game crashes every time with the above error message whenever an Enforcer starts to fire his machine gun. This doesn't happen in the classic campaign but only when running this MOD. The Enforcer enemy appears to be exact same one from the vanilla campaign.

 I tried the mod with q2pro, unofficial 3.24 patch and it doesn't crash there.

**Comment by Yamagi** [comment]
Thank you. It's fixed in HEAD. :)
