### ISSUE TITLE
Monster AI in coop mode

### ISSUE THREAD

**Issue by box-tortoise** [yquake2/yquake2#155]
Recent fixes included this line so that single player game monster AI works as in vanilla Quake2:
```
if (coop->value && (self->monsterinfo.search_time < level.time))
```
However, recent fixes to Rogue and Xatrix retain some of the original Yamagi code which originally broke monster AI:
```
if (coop && coop->value && (self->monsterinfo.search_time < level.time))
```
The value of 'coop' is a large integer in non-coop single player mode, as logging showed in a test build, so it should not be necessary. Also, if coop is active, then this statement has the potential to break AI given that 'coop' produces unintended values.

**Comment by DanielGibson** [comment]
it's a pointer, if it's valid it's a (probably large) integer.
maybe the NULL check is not necessary, but this is not a bug
