### ISSUE TITLE
Mutant Stuck In Upper Mines (mine1)

### ISSUE THREAD

**Issue by shoober420** [yquake2/yquake2#157]
This mutant is stuck and just leaps repeatedly in mine1. He appears to be floating as well.

http://i1124.photobucket.com/albums/l562/shoober420/uppermines_zpsqpnradke.jpg

**Comment by Yamagi** [comment]
This should be fixed in HEAD. Thank you :)

**Comment by shoober420** [comment]
You're very welcome sir :)
