### ISSUE TITLE
Not fully portable (on Windows?)

### ISSUE THREAD

**Issue by DX37** [yquake2/yquake2#158]
Latest client still creates and uses files from Documents directory only (C:\Users\%USER%\Documents\YamagiQ2).
How I can set it fully portable? If I start Quake 2 with "+set game baseq2" parameters, it uses saves and config form game dir, but still creates YamagiQ2 dir in Documents and saves logs there.

**Comment by iButane** [comment]
I find this a bit annoying myself but have gotten used to it.

**Comment by Yamagi** [comment]
I'll have a look at it. We'll likely fix the baseq2-case and provide a mechanism to disable the usage of the users home directory altogether.

**Comment by Yamagi** [comment]
Okay, I've just pushed the fix. When fs_portable is set to 1 the game writes it's configuration data, the savegames, etc. into the binary dir. An example: The game is installed to D:\quake2 and started with `D:\quake2\quake2.exe +set fs_portable 1`. The data will written to  D:\quake2 .

**Comment by DX37** [comment]
I'll compile and test it.

**Comment by DX37** [comment]
It's work, but not all.
![2017-03-13 21-00-58](https://cloud.githubusercontent.com/assets/12829428/23857569/58f1ed42-0830-11e7-94ae-de8ae7ae6b0a.png)

**Comment by Yamagi** [comment]
I totally forgot about that files. I've just pushed a fix.

**Comment by Yamagi** [comment]
It's called 'portalable', now. And no longer 'fs_portable'.

**Comment by DX37** [comment]
@Yamagi It's still creates dir YamagiQ2 and std*.txt files in it.

**Comment by DX37** [comment]
With e229008 commit it seems like it's fixed now. Thanks, @Yamagi!

**Comment by Yamagi** [comment]
That's very nice to know. Thank you!
