### ISSUE TITLE
Various code inconsistencies across game DLL and mission pack DLLs

### ISSUE THREAD

**Issue by maraakate** [yquake2/yquake2#160]
During my merge of all 3 game DLLs into one self-contained unit I've noticed these inconsistencies :
(Note: /* FS comments are my personal comments about it, if there is some)

in sv_physicsstep for rogue:
if (!ent->inuse) /* FS: Coop: Rogue specific -- "g_touchtrigger free problem".  Looks like a workaround/fix.  Probably OK as-is. */
{
return;
}

* ThrowHead sets self->targetname = NULL; Not in rogue.
* in Move_Calc you check for !ent and !func, but you dont check for !func in rogue
* same for AngleMove_Calc
* train_blocked doesn't check for !self or !other in rogue.
* train_use checks !self and !other but it should check !self and !activator in rogue
* door_secret_move6 doesn't check for !self in rogue.
* door_secret_die doesnt check for !attacker in rogue.
* MoveClientToIntermission does gi.linkentity(ent) in xatrix, but not in rogue or game.  I added this to my mod and it seems to work fine with it in.

In g_spawn.c:

* ED_ParseEdict in rogue checks !ent and !data but it doesnt in xsrc or game
* ED_ParseField checks for !ent in rogue but it appears unused
* ED_NewString checks for !string and returns NULL in rogue but not in the other two
* This one looks like a memory leak fix thats missing in rogue:
     ED_CallSpawn if !ent->classname it also calls G_FreeEdict(ent) in xsrc and game but not in rogue
* spawnentites changes things to const for certain chars in rogue, but not in the other two
* same with ParseEdict, com_token becomes a const char in rogue
* ED_ParseField:
 in rogue:
      if (!(f->flags & FFL_NOSPAWN) && !Q_strcasecmp(f->name, (char *)key))

in xatrix and game:
       if (!(f->flags & FFL_NOSPAWN) && !Q_stricmp(f->name, key))
* ED_NewString has const char for g_spawn in game but not the others
* Check ED_ParseField, compare it to game and xsrc/rsrc:
     F_INT, F_FLOAT and F_ANGLEHACK use atoi or atof where needed
     game uses strtol and strtod instead

* /* sexed models. you can add more, max 19
  	   THIS ORDER MUST MATCH THE DEFINES IN g_local.h
  	   these models are only loaded in coop or deathmatch.
  	   not singleplayer. */
  in rsrc and and xsrc it has a check for a multiplayer game, but not in game.

**Comment by maraakate** [comment]
Also, check this across your code:  You already pointed this one out to me, but I did grab the source from github a year ago: https://github.com/yquake2/xatrix/commit/d5d771d37308ebae01cb0f18b5db179236437878

This was breaking xware.bsp func_trains for me when it had both paranoia checks.  I'll leave it here in case someone is using older code and runs into this problem again.

**Comment by maraakate** [comment]
in monster_start you check !self->max_health before equaling to self->health in game.dll but not the others

**Comment by maraakate** [comment]
M_CheckGround 		ent->velocity[2] = trace.ent->velocity[2]; in game.dll
but in xsrc and rsrc its just set to 0

**Comment by maraakate** [comment]
M_CategorizePosition for get waterlevel in xsrc/rsrc it = ent->s.origin
but in game.dll you use ent->absmax and ent->absmin for this stufff

**Comment by maraakate** [comment]
Okay, really last one:

https://bitbucket.org/neozeed/q2dos/commits/02ae071cf3e3c689cd4b40138bc19a81ed8e8656

This was a verified oversight you mentioned to me in IRC.  Just want to leave that here so you don't forget either.

**Comment by Yamagi** [comment]
Thank you! During the next weeks I'll go through the addons again and have a look at these points. There're at least to other known bugs in rogue not mentioned here:

  * Sometimes but all always the help computer messages are reset to their initial value after a savegame was loaded. Maybe some necessary strings are not included in the samegames.
  * When a savegame is loaded while a medic commander spawns a monster there's a small chance for an empty and disfunctional enemy model being left over.

**Comment by maraakate** [comment]
This was only during coop.  But I did notice that you omitted the gi.unicast (present in original q2 code) in the help computer messages.  I noticed that was causing the messages to not update properly.  That could be part of the problem.

The medic save foolery sounds very similar to DK Wyndrax issue with his wisp spawns ;).

**Comment by Yamagi** [comment]
Hi,
I've merged most of these changes to the three games. Most of these changes should be no-ops or corner cases that are unlikely to be seen in practice. Some comments:

> MoveClientToIntermission does gi.linkentity(ent) in xatrix, but not in rogue or game. I added this to my mod and it seems to work fine with it in.

This looks like a work around in case that in multiplayer one player moves to intermission but for some reasons the others doesn't. 


> This one looks like a memory leak fix thats missing in rogue:
> ED_CallSpawn if !ent->classname it also calls G_FreeEdict(ent) in xsrc and game but not in rogue

Yes, that's a leak. It shouldn't matter since unknown entities are very unlikely.


> ED_ParseField:
> in rogue:
> if (!(f->flags & FFL_NOSPAWN) && !Q_strcasecmp(f->name, (char *)key))
>
> in xatrix and game:
> if (!(f->flags & FFL_NOSPAWN) && !Q_stricmp(f->name, key))

This is another corner case fix and only necessary if casing in the mapping is different to the code. I've merged rogues version to the other games since it looks safer.

> in monster_start you check !self->max_health before equaling to self->health in game.dll but not the others

I don't know why this was inserted. To my understanding self->max_health is always the same as self->health when the monster starts. I've merged it to the addons.


> M_CategorizePosition for get waterlevel in xsrc/rsrc it = ent->s.origin but in game.dll you use ent->absmax and ent->absmin for this stufff

This fixes the "can't enter the pipes in xsewer2"-problem. Nice find!


> One more:
> SP_trigger_gravity

baseq2 and xatrix are the same since in most implementations atoi() is just a wrapper around (int)strtol(nptr, (char **)NULL, 10). Nevertheless I've merged baseq2s versions. rogue has some change to the gravity code, I've replaces atof() with strtof() to solve a type missmatch.

Thank's again,
Yamagi
