### ISSUE TITLE
Enemies Ignore Player When In Plain Sight

### ISSUE THREAD

**Issue by shoober420** [yquake2/yquake2#162]
I've noticed this several times while on my most recent playthrough. Enemies will sometimes blindly stare and not acknowledge you. A great example of this happening is in the Borehole (mine2). At the start of the map when you enter through the door to see the Gladiator kill an marine and run into the other room, there are Gunners in there above on the ledge. When you first enter the room, they don't notice you, sometimes for as long as 10 seconds, then out of nowhere they start shooting at you. Here is a screenshot of them blindly staring while im clearly in there sight.

http://i1124.photobucket.com/albums/l562/shoober420/quake00%201_zpscxe26mby.jpg

**Comment by maraakate** [comment]
Is this the latest build?  There was a recent issue with this that was 
fixed.

**Comment by shoober420** [comment]
If your talking about the enemies running in place issue, this one is different.

**Comment by Yamagi** [comment]
I'm sorry but I can't reproduce this. As soon as I drop out of notarget mode the Gunners recognize me. As long as I'm in a sightline.

**Comment by shoober420** [comment]
I just tried again, and it for sure takes them a couple seconds to react. Try without using cheats. Pick up the grenade launcher and kill the gladiator, then run into the room. It takes the Gunners a good couple seconds to even notice you.

**Comment by Yamagi** [comment]
I gave it anither try. Even if I dont cheat I'm recognized as soon as I get in sight. I've even checked the original client, it's behavior is exactly the same.

**Comment by shoober420** [comment]
Were you by chance on nightmare difficulty? I played through on nightmare. I'll try it on the other difficulty settings and see if it happens.

**Comment by shoober420** [comment]
Please reopen this. I just tried it again on skill "1",  and found out that jumping left and right in front of them will make them not attack you at all, regardless of what skill level your on. They just will look left and right at you. I never made a video in Linux before, but I will for this because you can't reproduce it. I'll let you know when I've uploaded it.

**Comment by DanielGibson** [comment]
A video (ideally from start of the level to the bug) and the output of `cvarlist` might be helpful, yeah.

**Comment by shoober420** [comment]
I'll look up good video recording software when I get home from work and upload the video to YouTube and link it here. My system specs are in my Steam profile, which is linked in my GitHub profile. I'm using Arch Linux 64bit.

**Comment by eGax** [comment]
Simple Screen Recorder or OBS Studio are great for desktop & game recording.

**Comment by shoober420** [comment]
I went with simple screen recorder. It's a nice program. I'm compiling VLC from git just to make sure it's a good video. It's rather hilarious. I'll post when I upload it.

**Comment by eGax** [comment]
Yeah SSR is my go to most the time.

**Comment by shoober420** [comment]
Here is the video. Its quite amusing.

https://youtu.be/y9oQItjx6no

**Comment by Yamagi** [comment]
There's something very, very wrong. Neither Daniel nor I can reproduce that. Can you send me the binaries (quake2, q2ded and baseq2/game.so) that show the problem? My mail address is yamagi -at- yamagi -dot- org.

**Comment by DanielGibson** [comment]
Can you double-check that the notarget cvar is set to 0?

**Comment by Yamagi** [comment]
And a third request: Cam you recompile the game with "make VERBOSE=1" and send us the build log? Just to be sure that nothing is messed up by strange compiler flags.

**Comment by shoober420** [comment]
The notary cvar is for sure disabled. At the start of the video, you can see that the gladiator is shooting at me. Also, the Gunners on the ledge turn left and right as I jump around back and forth. It's really strange. They see me, but don't do anything unless I stand completely still for a couple of seconds.

Another odd thing is when I was making videos of this, I would sometimes start the game just as I did and the Gunners would notice me as I was shooting at the gladiator. It only happens sometimes. Well, most of the time I noticed the behavior in the video when I was making videos of this. I did it numerous times.

I do work today, so when I get home I will send a copy of the game.so and compile with the "VERBOSE=1" flag. In the meantime, I'll go through my cvars and see if it's something along those lines.

Remember, sometimes they do behave normally, so try it a couple times and it just might happen.

**Comment by DanielGibson** [comment]
please don't just send game.so, but also the quake2 executable itself :)

**Comment by maraakate** [comment]
In Q2DOS this problem is happening too (uses YQ2 game.so code).  I just verified it myself.

If you're fast, kill the railgun guard then venture past the two gunners the gunner who is walking up the stairs usually doesnt notice you either.  But, if you sit for a moment before you start running and gunning they respond OK.  This may be related to monsterinfo.pausetime.  Are these few enemies part of a hint node path?  The game has to settle for a few seconds with all the spawning and respawning going on.

However, I haven't sat there for a good 10 seconds then start the gibfest, so I'll have to try that and try Quake 2 v3.20 code by itself as well.

Other possibilites are the !self && !activator checks in UseTarget and friends (if they have something to use from a trigger script?) that are removed in xatrix because they broke the trains in xware1.bsp.  If its an over-paranoia check it's possible to try using game xatrix and starting the same map and see if it happens in xatrix game code.

**Comment by shoober420** [comment]
Here is my autoexec.cfg:

`allow_download "0"
allow_download_maps "0"
allow_download_models "0"
allow_download_players "0"
allow_download_sounds "0"

cl_async "0"
cl_maxfps "120"
cl_run "1"

fov "105"
crosshair_scale "1"
ogg_enable "0"

gl_anisotropic "16"
gl_cull "1"
gl_palettedtexture "0"
gl_pointparameters "2"
gl_swapinterval "0"
gl_farsee "1"
gl_hudscale "3"
gl_consolescale "3"
gl_maxfps "120"
gl_menuscale "3"
gl_novis "0"
gl_overbrightbits "1"
gl_round_down "0"
gl_shadows "0"
gl_stencilshadow "0"
gl_texturealphamode "GL_RGBA"
gl_texturesolidmode "GL_RGB"
gl_texturemode "GL_LINEAR"

name "TyranT"
rate "25000"

s_mixahead "0.035"`

Here is my config.cfg:

`// generated by quake, do not modify
unbindall
bind TAB "inven"
bind ENTER "invuse"
bind SPACE "+moveup"
bind ' "invdrop"
bind + "sizeup"
bind , "+moveleft"
bind - "sizedown"
bind . "+moveright"
bind / "weapnext"
bind 0 "use BFG10K"
bind 1 "use Blaster"
bind 2 "use Shotgun"
bind 3 "use Super Shotgun"
bind 4 "use Machinegun"
bind 5 "use Chaingun"
bind 6 "use Grenade Launcher"
bind 7 "use Rocket Launcher"
bind 8 "use HyperBlaster"
bind 9 "use Railgun"
bind = "sizeup"
bind [ "invprev"
bind \ "+mlook"
bind ] "invnext"
bind a "+moveleft"
bind b "use rebreather"
bind d "+moveright"
bind e "use environment suit"
bind g "use grenades"
bind h "wave 0"
bind i "use invulnerability"
bind j "wave 1"
bind k "wave 2"
bind l "screenshot"
bind p "use power shield"
bind q "use quad damage"
bind s "+back"
bind t "messagemode"
bind u "wave 4"
bind w "+forward"
bind x "score"
bind z "+lookdown"
bind BACKSPACE "invdrop"
bind PAUSE "pause"
bind DOWNARROW "+back"
bind LEFTARROW "+left"
bind RIGHTARROW "+right"
bind ALT "+strafe"
bind CTRL "+movedown"
bind SHIFT "+speed"
bind INS "+klook"
bind DEL "+lookdown"
bind PGDN "+lookup"
bind END "centerview"
bind F1 "cmd help"
bind F2 "menu_savegame"
bind F3 "menu_loadgame"
bind F4 "menu_keys"
bind F5 "menu_startserver"
bind F6 "echo Quick Saving...; wait; save quick"
bind F9 "echo Quick Loading...; wait; load quick"
bind F10 "menu_quit"
bind F12 "screenshot"
bind MOUSE1 "+attack"
bind MOUSE2 "+strafe"
bind MWHEELDOWN "+movedown"
bind MWHEELUP "+moveup"
set al_device ""
set al_driver "libopenal.so.1"
set allow_download "0"
set allow_download_maps "0"
set allow_download_models "0"
set allow_download_players "0"
set allow_download_sounds "0"
set cfg_unbindall "1"
set cl_async "0"
set cl_drawfps "0"
set cl_gun "2"
set cl_maxfps "120"
set cl_run "1"
set cl_vwep "1"
set crosshair "1"
set crosshair_scale "1"
set exponential_speedup "0"
set fov "105"
set freelook "1"
set gender "male"
set gender_auto "1"
set gl_anisotropic "16"
set gl_consolescale "3"
set gl_customheight "768"
set gl_customwidth "1024"
set gl_farsee "1"
set gl_finish "0"
set gl_hudscale "3"
set gl_maxfps "120"
set gl_menuscale "3"
set gl_mode "23"
set gl_modulate "1"
set gl_msaa_samples "0"
set gl_overbrightbits "1"
set gl_palettedtexture "0"
set gl_particle_att_a "0.01"
set gl_particle_att_b "0.0"
set gl_particle_att_c "0.01"
set gl_particle_max_size "40"
set gl_particle_min_size "2"
set gl_particle_size "40"
set gl_pointparameters "2"
set gl_retexturing "1"
set gl_shadows "0"
set gl_stencilshadow "0"
set gl_stereo "0"
set gl_stereo_anaglyph_colors "rc"
set gl_stereo_convergence "1"
set gl_stereo_separation "-0.4"
set gl_swapinterval "0"
set gl_texturealphamode "GL_RGBA"
set gl_texturemode "GL_LINEAR"
set gl_texturesolidmode "GL_RGB"
set hand "0"
set horplus "0"
set hostname "noname"
set in_grab "2"
set in_mouse "0"
set intensity "2"
set logfile "1"
set lookspring "1"
set lookstrafe "0"
set m_filter "0"
set m_pitch "0.022"
set msg "1"
set name "TyranT"
set ogg_enable "0"
set rate "25000"
set s_khz "44"
set s_loadas8bit "0"
set s_mixahead "0.035"
set s_openal "1"
set s_openal_maxgain "1.0"
set s_underwater "1"
set s_underwater_gain_hf "0.25"
set s_volume "1"
set sensitivity "4"
set skin "male/grunt"
set vid_fullscreen "1"
set vid_gamma "1"
set viewsize "100"
set windowed_mouse "0"`

**Comment by maraakate** [comment]
Test in xatrix, just do map mine1, then turn around, it will take to you mine2 then see if its happening there.  I tested it a few times with that codebase and its not happening in xatrix.

**Comment by shoober420** [comment]
I've been working. I will post the requested information tomorrow.

**Comment by maraakate** [comment]
Well regarding my similar issue with the enemies standing in place sometimes for a few seconds... this happens in original quake 2 as well.  However, in your situation with them doing it for like a full 10 seconds is somewhat bizarre.  Are you positive you are using a clean compile?

**Comment by shoober420** [comment]
It is usually for a couple seconds, it was only for ten seconds like twice. I've done this numerous times. If you jump around like in the video I made, it could last forever by the looks of it. I build Yamagi straight from GitHub. There's a package for it in the Arch User Repository. I'll link the page and its PKGBUILD below.

AUR page: https://aur.archlinux.org/packages/yamagi-quake2-git/
PKGBUILD: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=yamagi-quake2-git

**Comment by maraakate** [comment]
It sounds to me like it's the same original issue that is present in the 
original Q2 code.

**Comment by shoober420** [comment]
I compiled Yamagi with the VERBOSE=1 flag and can't find the  build log. Does anyone know where it would be located on Linux?

**Comment by maraakate** [comment]
It's nothing you're doing wrong.  I've done some deep digging and here is the problem...

For enemies that have the AI_STAND_GROUND flag and AI_SOUND_TARGET flags set what happens is that parts of AI_CheckAttack fails.  The specific failure is coming from
		if (self->monsterinfo.aiflags & AI_SOUND_TARGET)
		{
			if ((level.time - self->enemy->teleport_time) > 5.0)

So this means that the first 5 full seconds of gameplay the check will fail, then sets show_hostile = level.time + 1;  so a full second has to pass again.

What happens then is later in FindTarget:

		if (r == RANGE_NEAR)
		{
			if ((client->show_hostile < level.time) && !infront(self, client))
			{
				return false;
			}

and I believe later on again in CheckAttack its continously incrementing the show_hostile time so it's stuck in this loop of waiting for you basically to get up in their face for them to give a shit.

**Comment by DanielGibson** [comment]
On 11.12.2016 18:37, shoober420 wrote:
> I compiled Yamagi with the VERBOSE=1 flag and can't find the build log.
> Does anyone know where it would be located on Linux?

There is no real log file, just copy the compiler output from the 
terminal ;)

**Comment by DanielGibson** [comment]
Or do `make VERBOSE=1 > buildlog.txt` to redirect it to a textfile, might be nicer than copying all those lines from the terminal

**Comment by maraakate** [comment]
Okay here is the problem... and I don't understand why they do this...

Every time you jump or shoot a weapon (basically make any noise besides footsteps) the teleport_time timer is reset to level.time.  For enemies that are supposed to stand their ground and only respond to sounds they wait 5 full seconds before deciding to attack you.  During this time, they show_hostile which is supposed to be a hint for other surrounding enemies to attack that don't care about standing their ground or only responding to sounds.  I guess this is to show aggression and wait a few seconds to intimidate you?

In any case, this is apparently intended behaviour.  This only affects enemies in the ai_stand position.  So if you're already shooting at them to wake them up then they continue fighting you until you're out of their view range and then the timer starts all over again if you make a noise, requiring another 5 seconds for them to care about you unless you attacked.

**Comment by maraakate** [comment]
A simple fix for this to only do this check once:

		if (self->monsterinfo.aiflags & AI_SOUND_TARGET)
		{
			if(!self->teleport_time) /* FS: Only set this once! */
			{
				self->teleport_time = self->enemy->teleport_time;
			}
			if ((level.time - self->teleport_time) > 5.0f)

self->teleport_time is only used by the player.  So we can safely use this to copy the players time once.  However, this may break possibilities where enemies stand their ground elsewhere in the map.  I did some quick checking and if you go out of their range before making noise and its outside of the hearable range from them then the think function for this wont set it since they have no self->enemy yet.  So this may or may not be an issue, but enemies should be much more aggressive with this fix.

**Comment by maraakate** [comment]
Here is my current g_ai.c from the q2dos coop mod (has some bits of rogue and xatrix in with it where applicable) should be able to diff or beyondcompare it to see my changes. 

WARNING: This has verbose output, and only cares about the two gunners on the ledge in mine2.bsp to show the output.  All that stuff would have to be stripped for use.

**Comment by maraakate** [comment]
Pastebin with verbose g_ai.c: http://pastebin.ca/3746490

Q2DOS with temporary, unpolished solution: https://bitbucket.org/neozeed/q2dos/commits/40d836b6eacf14f2a497d48c55213cd9b887c7ab

**Comment by shoober420** [comment]
Wow, that is very interesting. Very strange behavior indeed lol

**Comment by maraakate** [comment]
Here is more to the recent q2dos commit:
https://bitbucket.org/neozeed/q2dos/commits/55c7d08ebc221686bac9d356a3b339a28296c462

This allows the enemies to restart this process if we go away from them.  But only care about the first sound fired so theres no penalty for bunny-hopping.

**Comment by shoober420** [comment]
So basically, when I'm in the line of sight for the Gunners with the fix, they will behave normally and shoot immediately?

**Comment by maraakate** [comment]
No, with this fix they will wait 5 seconds the first time they hear a sound from you, then fire.  Previously, every time you made a new sound (i.e. bunnyhopping, shooting) the counter would reset.  With this, it only cares about the first time you make a sound.  If you leave their line of sight for a few seconds, then whole process starts again.

I'm thinking you could check !self->enemy in the newer commit I linked to and if it's been a good 30 or 60 seconds then start the process again of waiting the 5 seconds.

The whole purpose of this oddness is for them to wait for you to attack them, and if 5 seconds pass after they hear you, then they start firing.  It looks odd and seems odd because there's no real animation or grunting noises, etc. to signal that they are warning and kind of "checking you up" to see who makes the first move.

**Comment by maraakate** [comment]
On the other hand, if you think the whole thing is stupid and you just want them to be aggressive, set the timer from 5 to 1 and ignore this commit:
https://bitbucket.org/neozeed/q2dos/commits/55c7d08ebc221686bac9d356a3b339a28296c462

Considering iD purposely did this though you'd be having to readd the patch every time a new build came out.  However, resetting the timer every time you make a new sound is a legitimate bug.  I guess they weren't counting on you bunny hopping around.  However, it's unclear if they should revert back to the stance if you decide to walk away from them then come back to them later.

**Comment by shoober420** [comment]
Ooooh, I fully understand this now. So they are like trying to ambush you in a sense. But I'm resetting their timer by making noise (the bug) and they just stand there. I totally get it now. 

Well, I for sure want iD intention, so I hope Yamagi or DanielGibson pull your latest patch to fix the resetting timer.

**Comment by shoober420** [comment]
Since you explained everything and found the bug and fixed, should I even upload the .so files and build log?

**Comment by maraakate** [comment]
Yes, but part of the problem is should the timer be reset once you leave their view range or should they only stand still one time?  If they should be allowed to do it multiple times should they do it again immediately (like I have it now) or should they wait 30-60 seconds before they do this again?

This will have to be a compromise with Yamagi.  Personally, I think waiting 60 seconds would be a good thing to do.

**Comment by maraakate** [comment]
No, the problem has nothing to do with your build environment.  This is a real bug that is in iD's original code and I guess most people aren't bunny hopping and running around like madmen in Single Player like you and me to notice this oddness. :)

**Comment by shoober420** [comment]
Hmm, well they are trying to be sneaky and ambush you from above. There's also the other Gunner below the steps who just stands there lol. He really doesn't seem to have a reason to be timed like the ones above him on the ledge. It's hard to say. I'll sleep on it lol

**Comment by maraakate** [comment]
OK, shoober420, Yamagi told me he's very likely to change the timeout from 5.0f to 1.0f.  So I went ahead and did that, and also added a check so if 60 seconds have passed since its happened then the timer resets so they will do the stance again.

With this way, they will still be ready to attack if you leave the room briefly and come back, but if you walk around the map for a good minute then come back they will stand still for a second before they attack again.

Relevant commits: 

* https://bitbucket.org/neozeed/q2dos/commits/b4b97567a63454ae8d5a2cb7f6b9594fd9877f1f
* https://bitbucket.org/neozeed/q2dos/commits/fd3ca00c051a367c729f3e26ef936e50cb68fb9c

**Comment by maraakate** [comment]
Yamagi also suggested that in nightmare mode they should be immediately alert.  I agree and here is a commit for that as well:

* https://bitbucket.org/neozeed/q2dos/commits/461c9f30914a691a9edbd7d00e34b263721a08c8

You'll have to change ->intValue to just ->value as Q2DOS has a builtin atoi conversion for that stuff.

**Comment by shoober420** [comment]
I agree, on nightmare they should just be alert at all times. This was quite a strange bug lol. Thanks guys!

**Comment by DanielGibson** [comment]
Ok, our current theory is: 
In `ai_checkattack()` there's the `if (self->monsterinfo.aiflags & AI_SOUND_TARGET)` check.
If that is true it means that the player made a loud noise (see `PlayerNoise()`) and the monster noticed that noise. Now it checks whether that noise was more than 5 seconds ago; in that case it "forgets" that goalentity. Otherwise the monster informs the surrounding monsters that something interesting has happened (via `self->show_hostile = level.time + 1;`) **and then returns false**.

So the problem is that if it has heard you in the last 5 seconds, `ai_checkattack()` aborts at that point with `return false;` - even if the monster might actually **see** you.

Our current fix is to first check visibility and only if the player is *not* visible we do all the sound checking stuff above. So the aforementioned line becomes:
```c++
// only check sound if it's not visible anyway (=> attack if visible)
if (!visible(self, self->goalentity) && (self->monsterinfo.aiflags & AI_SOUND_TARGET)
{ ...
```
Any thoughts on this, @maraakate ?

**Comment by maraakate** [comment]
Does it work properly?  Will they turn around almost immediately and start shooting at you?

with your current fix are you also only caring about the first time they have shot, etc.?

**Comment by DanielGibson** [comment]
It seems to work properly at that point.
They start shooting at you as soon as they see you.
If they don't see you they behave like before, i.e. they turn in the direction of the sound and activate the monsters around them, but don't attack.

No idea if it breaks anything anywhere else, but at least logically it makes sense that seeing the player has higher priority than just hearing him.

**Comment by maraakate** [comment]
Okay.  pastebin your entire g_ai.c and I will merge the changes in an experimental branch on the coop server and test it tonight and let you know if anything funny comes up.

**Comment by DanielGibson** [comment]
https://gist.github.com/DanielGibson/132a1534fec55f3d6dbf7f18f52f613e

**Comment by maraakate** [comment]
I see, so with this change it's basically becoming a clever one-liner.  OK, well test tonight and let you know how it goes.

Also, in ai_run you are missing the self->inuse check:


	if (!self->inuse)
	{
		return;
	}

	G_FreeEdict(tempgoal);

near the end of the function.

**Comment by maraakate** [comment]
The inuse check was probably inherited from rogue branch, not sure where it came from in my travels, but yeah. :+1:

**Comment by maraakate** [comment]
OK.  I played all the whole fact1/reactor-core chapter and to the biggun.bsp level and it worked just fine.

Will play a bit of Xatrix and Rogue as well.

**Comment by DanielGibson** [comment]
sounds good so far, thanks a lot for testing! :)

(And of course for debugging, if you hadn't found out what causes this issue we probably wouldn't have been able to fix it in one afternoon)

**Comment by maraakate** [comment]
Played about 15 minutes each of Xatrix and Rogue and they seem just fine, so I'd say go for it.

**Comment by maraakate** [comment]
Also, can we rename teleport_time to something like last_sound_time or something a bit more descriptive.  teleport_time is misleading; I originally thought it had something to do with the last time you respawned or entered a teleporter.

**Comment by maraakate** [comment]
also, should visible be re-arranged in the if statement i.e.:

if ((self->monsterinfo.aiflags & AI_SOUND_TARGET) && !visible(self, self->goalentity))

Wouldn't that mean it would check the flag first, then run through the visible function, possibly saving a few meager cycles on performance.  May not mean anything on modern PCs, but may matter to me very slightly in my DOS port on Pentium 1 machines (though I haven't tested if it makes a difference there).

**Comment by iButane** [comment]
I've noticed this strange behavior often but never to this extent (like in @shoober420's video) 

Good job on tracking it down and coming up with a good fix!

**Comment by DanielGibson** [comment]
> also, should visible be re-arranged in the if statement i.e.:
> if ((self->monsterinfo.aiflags & AI_SOUND_TARGET) && !visible(self, self->goalentity))

yeah, that should work just as well, good point!

I *think* renaming `teleport_time` should work (i.e. not break anything) - it's not part of a public API (like the interface between game and engine) and savegames don't care about the name either (the type stays the same so the binary data in the savegame just continues working).

Btw, that's different for the propsed `show_hostile` change - changing it to float would break savegames (and possibly behavior in subtle ways); however changing it to int should just work.

**Comment by maraakate** [comment]
Also, check the other issue about the ai sanity checks, I left a comment on one of the commits about possibilites to why the gekk is broken.  It's not broken for me in my coop mod and you missed part of the merge.  However, I can take the same code then and test it in the regular Xatrix game module itself.

**Comment by maraakate** [comment]
But yeah, we should be able to rename teleport_time without breaking thing or causing any real subtle changes anyways.

Show_hostile we should at least make an int to avoid potential confusion as well.

There's a few other things I missed via code inconsistencies, but I will have to diff game DLL versus the coop DLL (which is based from rogue) and will open a new issue tracker about that in a day or so.

**Comment by Yamagi** [comment]
I've just committed the change to baseq2 and both addons teleport_time was renamed to last_sound time. Many thanks to everyone involved!

**Comment by shoober420** [comment]
Such updates, much wow. Thank you guys, and Happy Holidays!!
