### ISSUE TITLE
autoexec.cfg is not automatically executed at startup

### ISSUE THREAD

**Issue by shoober420** [yquake2/yquake2#163]
I'm not sure if this only happens on Linux, but I have to use "+exec autoexec.cfg" when I start the game for my autoexec to load. It will not be seen unless I do this.

**Comment by shoober420** [comment]
I start Yamagi from the CLI just in case that helps.

**Comment by DanielGibson** [comment]
where do you put your autoexec.cfg?

**Comment by shoober420** [comment]
The same directory as the config.cfg is in, which I believe is "~/.yq2/baseq2".

**Comment by Yamagi** [comment]
The problem is in FS_ExecAutoexec(), filesystem.c:1071. For some reason Sys_FindFirst() doesn't find the autoexec.cfg.

**Comment by DanielGibson** [comment]
.. probably because it looks in the installation dir, not in the config dir

**Comment by DanielGibson** [comment]
also, why does it use Sys_FindFirst() when it really only wants to do something like stat()?

**Comment by DanielGibson** [comment]
Better question: Why check if the file exists at all and not just call `Cbuf_AddText("exec autoexec.cfg\n");`? If autoexec.cfg doesn't exist it says "couldn't exec autoexec.cfg", but that shouldn't matter?

**Comment by Yamagi** [comment]
Fixed. Thank you! :)

**Comment by shoober420** [comment]
You're very welcome sir

**Comment by maraakate** [comment]
I didn't test the new commit, but will this fail to execute autoexec.cfg every time you switch a mod now?  If so, that's sort of broken behaviour as I use a different autoexec.cfg in each game directory for setting custom binds or enforcing certain visual settings or whatever.

**Comment by shoober420** [comment]
I can test this for you when I get home from work. Would me installing the mission packs count as a mod?

**Comment by maraakate** [comment]
Yes.  Just make a new autoexec.cfg in xatrix or rogue directories and have it set some specific things different from your baseq2/autoexec.cfg.

**Comment by shoober420** [comment]
I just tested this. Without an autoexec.cfg in the xatrix directory, it will still load the autoexec.cfg from baseq2. When adding an autoexec.cfg to the xatrix directory and changing my fov from 105 to 90, it kept the fov setting at 90. So this seems to be all good.

**Comment by Yamagi** [comment]
Yes, autoexec.cfg is now processed like every other config. The problem mentioned in the commit message is, that an ~/.yq2/$mod/autoexec.cfg overrides a /path/to/q2/$mod/autoexec.cfg. If the mod requires its path/to/q2/$mod/autoexec.cfg to be processed, the user can't have an ~/.yq2/$mod/autoexec.cfg. This is a corner case that likely will never happen in praxis.
