### ISSUE TITLE
show_hostile in g_local.h is a qboolean, but is read like an integer and it's purpose seems possibly misleading or broken.

### ISSUE THREAD

**Issue by maraakate** [yquake2/yquake2#165]
Caedes noticed during my whole adventure of the teleport_time bug that show_hostile is a qboolean.  It's set as show_hostile = level.time + 1; (should be 1.0f for consistency).  And later is read 

			if ((client->show_hostile < level.time) && !infront(self, client))

I'm guessing that part will always read true since level.time is going to be greater than 1 (which a qboolean is when it's set to true? not sure about that part).

If the code was changed to a float this means that show_hostile enemies would delay themselves for a second before returning true in FindTarget.

Does this even matter?  Can show_hostile just be removed with no ill effects?  I haven't tested anything with show_hostile, but it looks like since we fixed the teleport_time issue that show_hostile is probably worthless to keep around.

It being a qboolean is an original id software bug and not a bad compare or merge on Yamagi's half.

**Comment by maraakate** [comment]
It's also weirder that it's reading the client (i.e. you) for show_hostile which is never set.  It's only set for the enemies.  So it seems mostly unused; unless FindTarget is also allowing sight_entity, etc. to be other monsters fighting each other.  If that's the case then the name client is misleading and it should just be named target_enemy or something else more descriptive of what it is.

**Comment by DanielGibson** [comment]
hmm yeah, `level.time` is a float, but show_hostile is an int really and the code looks like using an int - so is the implicit removing of decimals from the float in `self->show_hostile = level.time + 1;` etc important? e.g., if level.time is 1.5, show_hostile will be 2 (as float it'd be 2.5), which might make a difference when later comparing it to level.time again...

**Comment by maraakate** [comment]
I thought qbooleans themselves can only be 1 or 0.  Or do they store as an integer?

**Comment by maraakate** [comment]
The implicit removal of the decimals is already this way in the code.  I was suggesting that it should be 1.0f if it is indeed meant to be accessed as a float since it is comparing itself to level.time which is a float.

**Comment by DanielGibson** [comment]
enums are really stored as 32bit ints normally, the compiler does no implicit conversions to 0/1 here when storing values in a qboolean. See http://ideone.com/Dnh78i

**Comment by maraakate** [comment]
With some very preliminary testing that part is always resolving to true so far.

show_hostile is always being 0.  Even when I change the code to have the 5 second wait period in mine2.bsp for teleport_time instead of 1 (yamagi suggested change).

I'm checking the FindTarget with this debug printf

			if ((client->show_hostile < level.time) && !infront(self, client))
			{
				gi.cprintf(NULL, PRINT_HIGH, "Fail: %i %f\n", client->show_hostile, level.time);
				return false;
			}

Unless %i is not the right way to read its output.

**Comment by maraakate** [comment]
Even as %d (which is the proper thing to do) its still always reading 0, so level.time always wins this check.

**Comment by maraakate** [comment]
Okay, the only time client->show_hostile is every going to resolve to anything is if it's a monster fighting another monster.  If this is the case, then I guess it's purpose would be to leave 1 second for monsters to stare at each other before they start ripping each other apart.

**Comment by maraakate** [comment]
So qboolean should be set to at least an integer (as you said, it may rely on this rounding).  But the other question is should it be checking self->show_hostile instead of client->show_hostile in FindTarget?

And a bigger question to that is, does any of this matter?  Should it just simply be removed.  The misleading comment is that it's supposed to wake up other monsters.  But I don't see how this would be the case.

**Comment by Yamagi** [comment]
I've just changed this to be an integer and added explicit casts were necessary. The change was applies to baseq2 and both addons. Thank you for the suggestion!
