### ISSUE TITLE
Spectator userinfo CVAR is removed.

### ISSUE THREAD

**Issue by maraakate** [yquake2/yquake2#166]
I know YQ2 isn't the ideal client for multiplayer, but I do currently have a person who plays often on my coop server.  I do a svc_stufftext for spectator if using the menu (i.e. ctf menu code).  I know I could ignore it entirely and make everyone start as a spectator; but I do think the spectator CVAR should be added back into YQ2.

Without it then it breaks being able to manually change it on the client side as well.

A workaround for people is to add

set spectator "0" u

to your autoexec.cfg in baseq2.

**Comment by DanielGibson** [comment]
No idea why it was removed, I guess we should add it back?
@Yamagi, do you remember anything?

**Comment by Yamagi** [comment]
I've added them back. Thank you!
