### ISSUE TITLE
ogg music stops and doesn't resume after interrupt

### ISSUE THREAD

**Issue by KillPixelGames** [yquake2/yquake2#167]
Occurs when a switch is activated that also triggers an audio message.  Affects base game and both mission packs.

quick test:  establish comm uplink in the first level of ground zero.  Audio should cut out and not resume.

**Comment by tomgreen66** [comment]
I think I also experienced this problem a while ago.  I fixed a array bounds issue in the code which caused problems with OGG playback - see #168 which hopefully fixes the problem but this was in the menu so might be slightly different.

**Comment by Yamagi** [comment]
What @KillPixelGames is seeing is a feature and not a bug. At important events the background music is stopped by setting the track number to 0. For some reason most source ports dropped that behavior. When the cvar `ogg_ignoretrack0` is set to 1 track 0 is ignored and the music continues to play.

**Comment by iButane** [comment]
The music is supposed to stop when the primary objective is complete. It's not a bug.

**Comment by maraakate** [comment]
I am using some of the OGG code in my Q2DOS port (which shares a lot of
code from v3.24 by Knightmare and YQ2) and the music stops when objectives
are completed.

Maybe it's worth a look at my code and seeing if something got lost in a
merge?

**Comment by Yamagi** [comment]
For me the music stops just as it should. And we haven't changed anything in the audio code for years...

**Comment by KillPixelGames** [comment]
ogg_ignoretrack0 1 works as it should and the music resumes play.  Strange that randomly stopping the music when you complete an objective is a "feature".  I say random because it only happens about 5-7 times throughout the campaign.  Something doesn't feel right about losing music 2 minutes into a 20 minute level.

Anyway, thanks for looking.
