### ISSUE TITLE
possible input issue, unable to move, fire and jump at the same time

### ISSUE THREAD

**Issue by volumetricsteve** [yquake2/yquake2#169]
I'm unable to rocket jump, and it seems like there is an issue with mouse input in general.

In one case,  something will happen when i've fired so I'll continue to fire in-game even when i'm not pressing the mouse button.  I fix this by clicking the button a few more times and the issue temporarily goes away, but will happen 10 or so times throughout the whole game.

In another case, I find I'm just unable to be in motion, jumping and firing at the same time (to perform a backwards rocket jump) in-game, I'll only run backward and jump, but it's like the command to fire gets dropped.

To test, I tried the same thing in another SDL game, ioquake3 and found I had the exact same issue and it shows the same behavior.  When I disable my track-pad, it seems to fix ioquake3, but yquake2 is still effected.

**Comment by DanielGibson** [comment]
What operating system are you using? What version of SDL? What Yamagi Quake2 version (latest git?)?

**Comment by volumetricsteve** [comment]
Crux 3.2 x86_64, I compiled and built the latest version of Yquake2 last night from git.
libsdl 1.2.15-4
libsdl2 2.0.4-2

**Comment by volumetricsteve** [comment]
Interesting, this just got a lot weirder.  I updated my libsdl2 from 2.0.4 to 2.0.5, recompiled yquake2, and reattempted the rocket jump.  I can perform the rocket jump ONLY IF quake2 has *just* been opened.  If you try to rocket jump more than once, it stops working and goes back to acting like it's dropping the mouse-click event.  This can't be a "rocket jump bug" but I'm thinking it's a "mouse position change + 2 dimensions of character movement + click event all at once" bug.   Please let me know if there's any other information I could provide.

**Comment by volumetricsteve** [comment]
Apologies,  I thought i'd updated to 2.0.5 but I actually just recompiled 2.0.4 and was seeing similar behavior.  NOW I've verified I'm on 2.0.5 and the issue seems mostly resolved.  I can perform the jump like 80% of the time now, but I'm still not sure what's going on those other times, it really is as if it just drops click events from the mouse when there's too much else going on.

**Comment by shoober420** [comment]
When I get home from work, I'll do some rocket jumps and see if I have this issue. I'm on Arch Linux. I do use SDL2 git builds using mercurial, but I don't think that would differ in results.

**Comment by shoober420** [comment]
Random question, what mouse and keyboard do you use and what's the polling rate?

**Comment by volumetricsteve** [comment]
I'm on an alienware M11x, but I'm using a usb sharkoon fireglider.  I just beat Quake 2 stem to stern and it seems overall...sorta ok now, but there do seem to be the occasional mouse click hiccups.  I've noticed rocket jumps tend to fail more frequently when I'm aiming really far down at a steep angle.  Jumps where I go from platform to platform more asjcent tend to execute more often.  Movement seems vastly improved in SDL2 2.0.5, but not perfect.  Once in a while it'll still 'jam' where it'll fire continuously until I click a few times to....I assume reset some buffer or register.  The problem can be best described as fidgety.   I'm not sure what my polling rate is, but it's probably at the max for usb which is either 1000 or 2000Hz if memory serves. 

I can't imagine that it would matter, but in Crux, you build a lot of things from source, and it's kinda most like gentoo if you had to compare it to a popular mainline linux.  There aren't a TON of really well tested gaming setups/packages for my distro, but I'm kinda hoping I can help expand on that.

**Comment by shoober420** [comment]
What about your keyboard? You might be having ghosting issues. I think the max key press on USB keyboards is 5 for most.

**Comment by volumetricsteve** [comment]
I'm now more lost on this issue than I was yesterday, it seems like the problem(s) are back in full force.  I tried to do the rocket jump where the big spinny black hole generator thing is and I just could not get it to work.  I closed the game, reopened, loaded my save and I just couldn't do the jump.  It almost feels like there's a time after a key press where clicks are ignored.  It's bizarre.  You kind of have to shake off when it's ignoring click input by doing something else.

I actually got this happening on camera today where you can plainly see me clicking several times and nothing happens, then I switch weapons and I can shoot again.

I can throw the video on youtube if seeing something subtle might help diagnose the issue?

**Comment by DanielGibson** [comment]
Might help.
I'd also like to know which keys are involved - I guess left mouse button for shooting, which keys do you use for forward, backward and jump? Anything else you pressed?
Your window manager and/or desktop environment might also be relevant.
(I just had the idea that maybe you use the `Alt` key for jumping and if you press that and left mouse button, that event might be eaten by the window manager which might use Alt+mouse-drag as a shortcut to move the window.)

**Comment by volumetricsteve** [comment]
Interesting idea on the window manager, but I don't think that's the case here.  WASD for all the normal things, spacebar for jump, shift to run, c for crouch.  First mouse button for fire, second for [next weapon].  I'll see about uploading the video to youtube.

**Comment by volumetricsteve** [comment]
https://youtu.be/RoCAKyxTXF8

Here you can see me pressing no other buttons except the fire button, and it still doesn't fire.  I switch to the BFG and back to the rail gun, this seems to momentarily unbreak the dropped clicks.

**Comment by DanielGibson** [comment]
Hmm.. the video shows the problem, but not how to get into that broken state (which I haven't been able to do myself).
Does it also happen in windowed mode?

**Comment by volumetricsteve** [comment]
It's kinda random how the problem happens, so that's hard to capture..and I think to be of any real use to you, you'd need like a running log of all key ups and downs (I would think)  I'll try to capture that next time it happens, I can say it does mysteriously tend to happen more where it's more inconvenient for the gameplay :|  eg, right about to fight a gladiator.  I think that narrows it down to more active situations where more keys are likely to be pressed at once.

I can also add that it has *never* happened in the final boss fight.  My procedure there is very streamlined.  I activate invulnerability, quad damage and sit in front of the boss with the chaingun and just vomit bullets into him until I need to run to an escape pod.  I suspect the reason it's never happened there is because I'm barely moving, and I'm almost completely stationary while firing.  

I'll try it in windowed mode and get back to you.

**Comment by DanielGibson** [comment]
Thanks!

The problems with bugs like this one (see also #162) is that they often need some specific behavior to trigger, that may depend very much on your personal way of playing.
Like #162 only triggered if the Gunners hear you before they see you, so just running along the corridor more on the left or right side (and then making a noise by shooting or jumping) made it happen (or not). So for some people it happened a lot or even all the time, while Yamagi and me just couldn't reproduce it (probably due to running more on the right side of the corridor so we went into the Gunner's sight early) - and neither we nor the bug reporter were even aware of this (and what really caused the bug).

So in your case the bug might have something to do with your personal timing of pressing keys or maybe with weird behavior of your window manager or even with something completely different that we don't even think of right now, even if it might seem obvious in hindsight (after having figured out the problem).

**Comment by volumetricsteve** [comment]
Exact same behavior in windowed mode.  I'm starting to think that uneven terrain in the game has something to do with it.  I'm currently able to reproduce the issue in the 'upper mines' which is full of weird jagged edges.  This time when it dropped clicks, I moved forward slightly (w) and that was enough to unset whatever causes the dropped clicks.

I'm going to see if I can reproduce this behavior on different hardware, I've been using the same laptop for about 5 years and I'm wondering if there's some goofy firmware level thing going on.

**Comment by volumetricsteve** [comment]
also, i'm using IceWM, sorry I forgot to mention.

**Comment by DanielGibson** [comment]
Different hardware is a good idea!
If it still happens (and you have a way to trigger the problem quickly), another video that shows what happens when it first breaks would be cool.

IceWM.. that brings back memories, I used that in my first years of Linux usage (and then at some point switched to XFCE) :-)

**Comment by volumetricsteve** [comment]
I just read the #162 thread.  That's really interesting, and yeah that does go back to the original quake 2 source.  I saw that same behavior too (rarely) but I've seen it myself at least once.  To add to that, there's the one gunner who is supposed to be coming up the stairs in that area but he has never seen me ever in any game of quake 2 i've ever played with any engine in my entire life.  I always assumed iD built the level wrong and set some weird blindness flag on that particular monster by accident.  

Anyway, not to derail from my own situation (though that is fascinating) ...what I can do most easily and readily is pop a Windows 7 drive in my laptop, and try the latest executable you guys have available for windows and see if I can reproduce the bug there.  I'm guessing that won't be the latest git, but i've been having this issue for years, so...we'll see what happens.

**Comment by DanielGibson** [comment]
#162 was just an example to show how hard it is to reproduce other people's bugs ;)
Luckily, mostly thanks to @maraakate's hard work, we figured it out and fixed it. It was quite hard to just reproduce the problem, then to figure out why it happens. The bugfix itself wasn't easy either, but still the easiest part of the whole process.

Trying to reproduce your problem on Windows sounds like a good idea - with that and testing on different hardware we could probably narrow down the problem a bit.

**Comment by volumetricsteve** [comment]
Wow...so the windows version is incredible, and if it weren't for...well..windows, it'd be the only one I use.  The physics are incredibly fluid, I don't think I felt a single thing out of place.  Aside from soul-shattering amounts of OS Jitter, the game plays flawlessly from an input perspective.  No clicks dropped, no click-hanging.

Now I'm back in linux, and all the same things are still happening, however, I remapped jump to v instead of space...now I can rocket jump a bit more, but not reliably.  I guess space + click means something to IceWM?  or...more frightening, maybe space+click means something to Xorg.  Nothing I do seems to impact how often, or how randomly my clicks get ignored.  

I'll do some digging on icewm to see ...what I may be doing to it.

Alternatively, do you know of a way to launch just an opengl game in X without a window manager?  That might be good to try if I could figure out how to do it.

**Comment by DanielGibson** [comment]
It should work just as well on Linux (and does for most of us ;)).

I doubt that space+click means something to Xorg, else more people (incl. Yamagi and me) should run into your problem.

> Alternatively, do you know of a way to launch just an opengl game in X without a window manager?
Hmm maybe log out, shut down X, login in the terminal and do `startx ./quake2` or maybe `startx xterm`, which should open an xterm without any window manager, and start yq2 from there.

**Comment by volumetricsteve** [comment]
Right, if it were Xorg it'd be haunting everyone.  The beverages of new years eve are still with me :p 

It looks like click space means nothing to icewm either.  I still have to assume removing more parts from the equation should be valuable for testing.  I'll try startx xterm or some variation thereof.

**Comment by volumetricsteve** [comment]
Huh...running without icewm seems to have fixed just about everything....it's still doesn't seem as fluid as it does in windows, but that could be all just in my head.  

icewm has no hot key for space + click or...anything + click, so I have no idea why it'd interrupt anything about input.....but it sure seems to be the culprit.  I'll do more testing and make sure I'm not just incredibly lucky.

**Comment by DanielGibson** [comment]
Could it be that you sometimes accidentally press Alt when pressing space? The keys are next to each other, after all. Or maybe you don't even touch the key but for some (dirt in keyboard? mechanical bug? ...) it (or maybe the Windows or Ctrl Key) gets registered as pressed anyway?

**Comment by volumetricsteve** [comment]
I have my doubts, but just to be sure lemme intentionally hit alt instead of space to see what happens.  My thumb rests comfortably on the middle of the space bar...so I'm not thinking this is too likely, but I'll give it a shot.

**Comment by Yamagi** [comment]
Are there any other applications besides IceWM running in background? For example there was once the problem that running unclutter (removes the mouse cursor after some seconds of inactivity) broke Quake II. And not to forget the rather obscure crashes triggered by some versions of xscreensaver-gnome.

**Comment by shoober420** [comment]
I would try a different window manager first. Give "awesomewm" a try. Its EWMH compliant and uses XCB instead of the inferior Xlib. It's very lightweight as well.

**Comment by volumetricsteve** [comment]
Yamagi - Not that I'm aware of, my .xinitrc contains one line 'exec icewm'  I am 100% certain I am running no instances of anything gnome related.

DanielGibson-  The Mrs. and I are about to start tearing down christmas decorations, so hopefully I can try that later tonight and let you know what I see.

schoober420 - I might just do that for the sake of testing, but I just finished tearing through the first area in quake2 running xinit with only quake2, and it was pretty great - for my own purposes, that's what i'm happy with as a long term solution, but if I can run some tests that could fix things for someone else down the line, i'll take a look and see what crux offers in the way of awesomewm...or maybe i'll end up compiling it from source, we'll see.

Thanks everyone for your time, interest and support on this, also happy new year!

**Comment by volumetricsteve** [comment]
I just replayed all of quake2 from start to finish - no issues at all and I actually managed to shave 30 minutes off my normal time.  All is well, certainly with yquake2.  I realize that when I installed icewm, I installed it with someone else's idea of default options.  Packages in Crux aren't really packages so much as they are source tarballs with options set with automated compilation, so I may just need to look over what the icewm configure script has to offer and maybe I can tinker with something in there?

schoober420 - I'll try an alternate wm sometime..probably awesomewm, but hopefully I can fix whatever weird thing icewm is doing.

I'll post results if I find anything interesting/spooky about icewm.

**Comment by DanielGibson** [comment]
cool!

**Comment by shoober420** [comment]
The window manager is good to use because it well, it manages windows. You can get away with new t using one, but some games need there windows managed, for proper Fullscreen. For example, I used to use "bspwm" because it was extremely light and uses XCB. When I would play this game called "Gone Home" on Steam, it would never size the game correctly when you went Fullscreen. I switched over to awesomewm which has most EWMH supported, and the game fullscreens properly. I haven't tried bspwm for a while, but I learned my lesson about window managers. The super light ones sometimes dont have the greatest window management.

**Comment by volumetricsteve** [comment]
schoober420 - it seems that way, apparently you can compile in gnome2 menu support into icewm, which might make some applications happier, but somehow I don't think that option would fix the issue I was having, it's probably just a little buggy.  IceWM hasn't been updated in a few years, so that doesn't fill me with confidence.  I see an option to compile "--with-x" which...compiles in support for X, which baffles me since it's an x windowing system...so....what is that option enabling?

I'm compiling with it to see what happens.  I've noticed ioquake3 is probably on the list of things that need a wm to work.  It works fine in icewm, but the mouse doesn't work at all if I try to launch it without a window manager *shrug*.

Research continues...

**Comment by DanielGibson** [comment]
If you wanna stick to icewm, maybe try this fork, it promises better EWMH compatibility: https://github.com/bbidulock/icewm

Of course I have no idea if the issue actually has anything to do with EWMH.

**Comment by volumetricsteve** [comment]
I would like to stick with icewm if at all possible, I like to avoid change where I can (see: why i'm still playing quake2)    awesomewm needs a bunch of things I can't readily provide and that would be a sizable project.  icewm+EWMH seems to fail compiling for....a reason I've never seen something fail,...something about fuzzy translations... but I'll harass those people about their software.  In the mean time, I'll ask the Crux folks what window managers they use/have available so I can atleast see if I can get yq2 working in some window manager.

**Comment by shoober420** [comment]
You should give bspwm a try if you want something more lightweight then awesomewm. I just gave bspwm a try again and I'm actually going to stick with it since I prefer very lightweight window managers myself. I found out the issue with Fullscreen IMG with certain games I was having. Tiling window managers will conflict with some games, and it's wise to use a stacking window manager for compatibility. If you set bspwm to floating with a simple script you can find on the Arch Linux wiki, the Fullscreen issue was fixed. It has very little dependencies. Just XCB and the keyboard shortcut program if I remember correctly. It's just about as lightweight as you can get.

**Comment by volumetricsteve** [comment]
Do you have to do anything tricky to get it to work?  Crux provides it, so I just installed it and pointed .xinitrc to it, but nothing ever came up.

**Comment by shoober420** [comment]
Everything you could ever want to know about it is on the Arch wiki.

https://wiki.archlinux.org/index.php/Bspwm

Make sure sxhkd is installed and your keybinds point to launch your terminal. You can edit the keybinds in the config file. Mines located at ~/  .config/sxhkd.

**Comment by volumetricsteve** [comment]
I've done all that and all I get is a black screen.  I got a little further with awesomewm, but that broke during compilation, i forget why but it was a mess.  I have a similar blockage with forked-icewm.  

I did discover this, though, that beyond a doubt, icewm 1.3.8 is doing SOMETHING with my mouse/keyboard inputs.  I managed to throw ioquake3 at bspwm which I can only seem to launch with .xinitrc, and while quake 3 has no sound when launched this way (no idea) the mouse/keyboard issues were completely fixed and I could rocket jump with the best of them.  So...whatever is going on here is squarely in the hands of IceWM doing something unexpected.

My hunt for a window manager that I can compile and run continues....I guess I haven't really given evilwm a fair shake yet because I hate the name....but ...I guess that's next on the list.

**Comment by shoober420** [comment]
When you launch bspwm, you get a black screen. Theres no menu or wallpaper. Its very minimal. I have to spawn a terminal just for the mouse cursor to show up. its completely normal. Just make sure your keybinds in the sxhkd config file are set to launch the terminal of your choice. You have to use "xsetroot" to load wallpapers if I'm not mistaken.

**Comment by volumetricsteve** [comment]
OH.  Well...I wondered if that was the case but I didn't see anyone online being particularly vocal about that aspect of it.  Either way, I'll tinker with it to see if I can get ioquake3 to play nice.

**Comment by shoober420** [comment]
The bspwm Arch wiki has a stub about this.

https://wiki.archlinux.org/index.php/Bspwm#Help.21_I_get_a_blank_screen_and_my_keybindings_don.27t_work.21

**Comment by shoober420** [comment]
Another great window manager I recommend is "2bwm". By default, it's a stacking/floating window manager. With the trouble I've had with bspwm, with it being a timing window manager by default, I've switched to 2bwm. It's built on XCB and does have EWMH support.

**Comment by DanielGibson** [comment]
So it seems like a problem in your window manager or, if it behaves correctly, *maybe* SDL.

I guess we can close this

**Comment by volumetricsteve** [comment]
Oh absolutely, it was 110% a window manager issue.  Thanks for looking into this.
