### ISSUE TITLE
strcmp(attacker->classname, "monster_medic) can be NULL in Killed in g_combat.c

### ISSUE THREAD

**Issue by maraakate** [yquake2/yquake2#170]
During a fast coop play with a few players I hit the map transition and it must have been in the middle of firing off Killed because it crashed at the strcmp(attacker->classname, "monster_medic") in g_combat.c

Added a sanity check, code change is at https://bitbucket.org/neozeed/q2dos/commits/f55926bea61861026ecb1e4920be58a5f1dc2731

**Comment by maraakate** [comment]
Also, there's quite a few strcmp's that check ent->classname in the code.  They probably should have ent && ent->classname sanity checks around them as well.

**Comment by Yamagi** [comment]
I've just pushed a fix the first problem. Adding sanity checks to all `ent->classname` looks like a lot of work, so I'll do it at a later time.
