### ISSUE TITLE
3rd Zigock Bot II

### ISSUE THREAD

**Issue by box-tortoise** [yquake2/yquake2#172]
Been testing 3zb2 bot (maps: q2ctf6 and xmap04) while noting Ponpoko's comment:
"0.97 is still may cause "PF_setmodel: NULL" error.But it don't cause on current version in my local machine."

He didn't note further about it in the binary only 0.97d update. In contrast to the vanilla ctf mod for Quake2, he adds checks in setmodel (g_ctf.c) for a NULL entity name. However, g_func.c has 3zb2 specific calls to setmodel() without these checks (and g_items.c). By adding them, limited testing showed that the PF_setmodel error is avoided. The above setmodel() is seemingly used to place navigational objects such as nearby doors.

The 3zb2 bot was under development, so the bot AI is expected to perform better on certain maps. The bot code is also less stable on a Q2 client at an -O2 optimization setting (tested with -O0 and -Os).

```
g_func.c:
void SP_func_plat (edict_t *ent)
+	if (ent->model)
 	gi.setmodel (ent, ent->model);
 
void SP_func_rotating (edict_t *ent)
+	if (ent->model)
 	gi.setmodel (ent, ent->model);

void SP_func_button (edict_t *ent)
+	if (ent->model)
 	gi.setmodel (ent, ent->model);
 
void SP_func_door (edict_t *ent)
+	if (ent->model)
 	gi.setmodel (ent, ent->model);
 
void SP_func_door_rotating (edict_t *ent
+	if (ent->model)
 	gi.setmodel (ent, ent->model);
 
void SP_func_water (edict_t *self)
+	if (self->model)
 	gi.setmodel (self, self->model);

void SP_func_train (edict_t *self)
+	if (self->model)
 	gi.setmodel (self, self->model);

void SP_func_conveyor (edict_t *self)
+	if (self->model)
 	gi.setmodel (self, self->model);

void SP_func_door_secret (edict_t *ent)
+	if (ent->model)
 	gi.setmodel (ent, ent->model);

SP_func_killbox (edict_t *ent)
+	if (ent->model)
 	gi.setmodel (ent, ent->model);

g_items.c:
-	else
+	else if (ent->item->world_model)
 		gi.setmodel (ent, ent->item->world_model);
 ```
Edit: there are other areas with gi.setmodel that may be guarded against Null value, although the error rarely occurs in the mod. Also, the guard may be extended like this for example (untested snippet):
```
 	if(ent->model)
 		gi.setmodel (ent, ent->model);
 	else
		gi.bprintf(PRINT_HIGH,"%s has no entity name in SP_trigger_teleport\n", ent->targetname);
```

**Comment by box-tortoise** [comment]
Testing further with optimization settings in different Q2 clients. Yamagi Q2 uses -lm for its math library where building Q2. However, Q2Dos has a commit on 3/15/16 to change -lm to -lc -lgcc in the makefile.dj for q2.exe. This change of math library is very reasonable, but it leads to an above corner case where the 3zb2 bot mod is less stable. Test with ctf=1 in xmap04 and activate 7 bots (sv spb 7) and the framerate will soon after decrease to 0 fps. Without this math library change then the framerate stays at the normal rate. There are other maps that lead to this issue, but not at the map start so they are less useful for testing.

Note that q2.exe and 3zb2 dxe were built with -Os instead of -O2, otherwise the sudden decrease in framerate will always occur. It seems to be an interaction between the compiler optimization and math library in the djgpp build. The win32 build works in the above case with a single modification to the 3zb2 makefile: -Os. It is possible that different gcc versions produce different results, however.

**Comment by maraakate** [comment]
Are you saying Q2DOS has a problem with 3zb2?  If so, please report it with details to https://bitbucket.org/neozeed/q2dos.

3zb2 is mostly unmaintained and was ported by a user.  The only thing that was done was updating of some makefiles and cleaning up GCC warnings.

I personally know nothing about the bot.  The user ported it and claimed it worked well in Q2DOS so we took him at his word.  We're only really interested in making sure the baseq2, mission packs, and zaero code work as they should.  Action, Chaos, DDay, and the others are more just fringe benefits for Q2DOS considering you can just connect to a server to play those mods and it's very unlikely anyone would run a true dedicated server from DOS.

**Comment by box-tortoise** [comment]
You may consider reverting the change of the math library from djgpp to gcc. It may lead to other math bugs since it seems to produce different results.

**Comment by maraakate** [comment]
Maybe.  The main reason for the change was I believe the original Q1 makefile (sourced from the 1.01 leak maybe?) used those flags.  But it's been a while so I really don't remember.

**Comment by box-tortoise** [comment]
There have been posts about the accuracy of the bots. To lower the accuracy for the grenade/rocket launcher, this is one possible way:
```
--- bot_fire-orig.c	2017-01-17
+++ bot_fire.c	2017-01-17
@@ -92,9 +92,6 @@ void Get_AimAngle(edict_t *ent,float aim
 			break;
 
 		case WEAP_BLASTER:
-		case WEAP_GRENADES:
-		case WEAP_GRENADELAUNCHER:
-		case WEAP_ROCKETLAUNCHER:
 		case WEAP_PHALANX:
 		case WEAP_BOOMER:
 			if(target != ent->client->zc.last_target)
@@ -151,6 +148,64 @@ void Get_AimAngle(edict_t *ent,float aim
 			if(ent->s.angles[PITCH] > 90) ent->s.angles[PITCH] = 90;
 			else if(ent->s.angles[PITCH] < -90) ent->s.angles[PITCH] = -90;
 			break;
+
+		case WEAP_GRENADES:
+		case WEAP_GRENADELAUNCHER:
+		case WEAP_ROCKETLAUNCHER:
+			if(target != ent->client->zc.last_target)
+			{
+				if(target->svflags & SVF_MONSTER)
+				{
+					VectorSubtract(target->s.origin,target->s.old_origin,targaim);
+				}
+				else
+				{
+					VectorCopy(target->velocity,targaim);
+					targaim[0] *= 32;
+					targaim[1] *= 32;
+					targaim[2] *= 32;
+				}
+				VectorNormalize(targaim);
+				VectorMA(target->s.origin,(11 - aim) * dist/25,targaim,targaim);
+			}
+			else
+			{
+				VectorSubtract(target->s.origin,ent->client->zc.last_pos,targaim);
+				targaim[2] /= 2;
+				VectorMA(target->s.origin,- aim * random() + dist/75,targaim,targaim);
+			}
+			rs_trace = gi.trace(target->s.origin,NULL,NULL,targaim,target,MASK_SHOT);
+			VectorCopy(rs_trace.endpos,targaim);
+
+			if(weapon == WEAP_GRENADELAUNCHER
+				|| weapon == WEAP_ROCKETLAUNCHER
+				|| weapon == WEAP_PHALANX)
+			{
+				if(targaim[2] < (ent->s.origin[2] + JumpMax))
+				{
+					targaim[2] -= 24;
+
+					VectorCopy(ent->s.origin,v);
+					v[2] += ent->viewheight - 8;
+					rs_trace = gi.trace(v,NULL,NULL,targaim,ent,MASK_SHOT);
+					if(rs_trace.fraction != 1.0) targaim[2] += 24;
+				}
+				else if(targaim[2] > (ent->s.origin[2] + JumpMax)) targaim[2] += 5;
+			}
+
+			VectorSubtract(targaim,ent->s.origin,targaim);
+
+			ent->s.angles[YAW] = Get_yaw(targaim);
+			ent->s.angles[PITCH] = Get_pitch(targaim);
+
+			ent->s.angles[YAW] += aim * AIMING_ANGLEGAP_M * (random() - 0.5) *3;
+			if(ent->s.angles[YAW] > 180) ent->s.angles[YAW] -= 360;
+			else if(ent->s.angles[YAW] < -180) ent->s.angles[YAW] += 360;
+
+			ent->s.angles[PITCH] += (aim * AIMING_ANGLEGAP_M * (random() - 0.5) * 3);
+			if(ent->s.angles[PITCH] > 90) ent->s.angles[PITCH] = 90;
+			else if(ent->s.angles[PITCH] < -90) ent->s.angles[PITCH] = -90;
+			break;
 
 		case WEAP_HYPERBLASTER:
 			if(target != ent->client->zc.last_target)
```
Note that there are other occurrences of random() in this function and which are not in this snippet of code. Those may be locations to lower the accuracy of the bots.

Another corner case is the AI having difficulties while carrying flag and using grapple. Been testing with this in bot_fire.c:
```
int CanUsewep(edict_t *ent,int weapon)
{
	gitem_t *item;
	gclient_t	*client;
	int mywep,ammoindex;

	client = ent->client;

+	if(ctf->value)
+		CTFPlayerResetGrapple(ent);

	mywep = Get_KindWeapon(client->pers.weapon);
```

**Comment by sezero** [comment]
@box-tortoise: does -ffast-math help? (both djgpp and win32)

**Comment by box-tortoise** [comment]
Thank you for the reply.

With default 3zb2/makefile.mingw and fast-math, the slowdown issue is there (ctf=1; map=xmap04). However, with default 3zb2/makefile.dj and -ffast-math (gcc453), an error appears that doesn't without fast-math:
cc1.exe: out of memory allocating 1637576 bytes after a total of 18816904 bytes
make.exe: *** [bot_za.o] Error 1

**Comment by sezero** [comment]
The error is something wrong with gcc running under dos. (Try corss-compiling
under linux if you can.) But your win32 result shows that -ffast-math doesn't help.

Possibly something 3zb2 is doing with math functions: -lm links to C-only math
routines, without -lm we link to asm-optimized math routines from libc. Can you
isolate the issue?

**Comment by box-tortoise** [comment]
Thank you. I'll follow your advice.

**Comment by box-tortoise** [comment]
The slowdown issue also is dependent on use of the xmap04 ctf route file. This suggests that the problem line(s) involve the (CTF) bot routing algorithm in Bots_Move_NORM(). In addition, the sensitivity on compiler optimizations points to a difference in precision of values and/or error handling between libm and libc.

I wonder if it is possible to log the difference between the libm and libc generated values and parse for a difference. It would be interesting to determine if libm and libc differ in their handling of error for routine calculations in the code, given that is one possibility. Perhaps it is simpler to log Bots_Move_NORM().

**Comment by maraakate** [comment]
I am confused why this is being reported to yq2 issue tracker and not Q2DOS.  This sounds more like a Q2DOS and DJGPP related issue; especially considering yq2 doesn't maintain a 3zb2 port.

**Comment by box-tortoise** [comment]
Good point, we should return to the non-djgpp issues. In summary, the mingw32 build does not have the above slowdown issue where GCC bug 323 is patched along with use of the excess-precision=standard option. The djgpp/gcc453 also seems to have the excess-precision=standard compiler option, but it doesn't solve the issue as in the mingw32 case. It is unknown why this is the case.

Instead, for the djgpp case, linking the libm math library with the q2 dos executable solves the above issue. No changes needed to 3zb2 files.

Last, the above issue with gcc453 (djgpp) running out of memory was solved by this:
stubedit cc1.exe minstack=1024k

**Comment by box-tortoise** [comment]
Testing two changes to 3zb2 code. No lerping (linear interpolation applied to animations and movement) of bots before respawn. From: https://bitbucket.org/jwaggoner/tmg
```
--- bot_func-orig.c
+++ bot_func.c
@@ -467,6 +467,7 @@ void PutBotInServer (edict_t *ent)
 	ent->s.renderfx = 0;
 	ent->s.effects = 0;
 
+	ent->s.event = EV_OTHER_TELEPORT; // suppress lerping before respawn
 	SelectSpawnPoint (ent, spawn_origin, spawn_angles);
 	VectorCopy (spawn_origin, ent->s.origin);
 	VectorCopy (spawn_angles, ent->s.angles);
@@ -537,6 +538,7 @@ void PutBotInServer (edict_t *ent)
 
 	gi.linkentity (ent);
 	G_TouchTriggers (ent);
+	// BotEndServerFrame(ent); // testing without this line
 }
 
 //----------------------------------------------------------------
```
And NULL check. From: https://github.com/tastyspleen/zigock-q2
```
diff --git a/src/bot_za.c b/src/bot_za.c
--- a/src/bot_za.c
+++ b/src/bot_za.c
@@ -1285,7 +1285,7 @@ int Bot_moveT(edict_t *ent, float ryaw, vec3_t pos, float dist, float *bottom)
         if (rs_trace.contents & contents) {
             *bottom = -9999;    /*return false;*/
         }
-        else if (rs_trace.surface->flags & SURF_SKY) {
+        else if (rs_trace.surface && (rs_trace.surface->flags & SURF_SKY)) {
             *bottom = -9999;
         }

 ```

**Comment by sezero** [comment]
@box-tortoise:  Can you please add necessary information wrt to q2dos at
https://bitbucket.org/neozeed/q2dos/issues/18/
Note: Is 'xmap4' a typo? I can't find such a map.
Note/2: Are the above patches relevant (and/or helpful) for the q2dos issue?

**Comment by box-tortoise** [comment]
It is xmap04 (http://lmctf.wikidot.com/wiki:xmaps2). The route files are posted at a web site under the section "CTF routes": http://ponpoko.tri6.net/3zb2/. The route file is needed to reproduce the above.

I verified that you have the information already posted on an association between the above slowdown issue and gcc math.

On the second note, I don't think any of the above patches (which aren't compiler optimizations) have an impact on the above issue with libc. The use of gcc math is a general Quake 2 issue of interest:
http://blog.jwhitham.org/2015/04/gcc-bug-323-journey-to-heart-of.html
http://blog.jwhitham.org/2015/04/more-fun-with-floating-point-numbers.html
https://www.reddit.com/r/programming/comments/32o069/gcc_bug_323_a_journey_to_the_heart_of/

I don't consider this a specific issue in q2dos since you have not attached a specific development tool to building your project. Also, the libm option is even available in your makefile.

**Comment by sezero** [comment]
Out of curiosity: is the q2dos libm issue happening in software renderer or opengl?
(Asking, because the sw renderer calls Sys_SetFPCW() from R_Init(), but ogl doesn't.)

**Comment by box-tortoise** [comment]
I think so. I'll verify again.

**Comment by box-tortoise** [comment]
It is possible to link with libm for compatibility while using libc math functions for performance:
```
--- q_shared-orig.h
+++ q_shared.h
@@ -38,6 +38,21 @@ Foundation, Inc., 59 Temple Place - Suit
 #include <stdlib.h>
 #include <time.h>
 
+#define abs(n)         __builtin_abs((n))
+#define acos(n)        __builtin_acos((n))
+#define asin(n)        __builtin_asin((n))
+#define cos(n)         __builtin_cos((n)))
+#define log(n)         __builtin_log((n))
+#define exp(n)         __builtin_exp((n))
+#define pow(n)         __builtin_pow((n))
+#define sqrt(n)        __builtin_sqrt((n))
+#define ceil(n)        __builtin_ceil((n))
+#define fabs(n)        __builtin_fabs((n))
+#define floor(n)       __builtin_floor((n))
+#define sin(n)         __builtin_sin((n))
+#define atan(n)        __builtin_atan((n))
+#define atan2(x,y)     __builtin_atan2((x),(y))
+
 
 typedef unsigned char 		byte;
 #if defined(__cplusplus)
```
