### ISSUE TITLE
Crash on custom/user map: ERROR: *Index: overflow

### ISSUE THREAD

**Issue by iButane** [yquake2/yquake2#173]
When playing this 3 map unit: http://colonthreeenterprises.tumblr.com/post/156354414901/my-quake-2-unit-is-finally-here-3c-it-has

The game crashes with that error message when you use the command  'give machinegun' on maps olde2.bsp and olde3.bsp . 'give all' won't crash it and certain weapons you try to summon will crash one map and not the other. Also, the game originally crashed with that message without using the give command at all. 

This doesn't happen on other ports and vanilla Q2.

![quake14](https://cloud.githubusercontent.com/assets/20784457/22895593/09bbd4f0-f1eb-11e6-8c75-de56cab706d7.jpg)

![quake15](https://cloud.githubusercontent.com/assets/20784457/22895521/c9edc982-f1ea-11e6-94f1-bedfebea6038.jpg)

**Comment by DanielGibson** [comment]
I just downloaded the maps, started the game, entered "map olde2" in the console, after the level was loaded "give machinegun", I got the machinegun, no crash. (same for olde3)

Is this enough to reproduce the problem or do I need to be somewhere in the level (not right at start) when entering "give machinegun"?

**Comment by iButane** [comment]
No.. it happens right after I load the map at the start area.

**Comment by iButane** [comment]
k, I just did a fresh new install of Yamagi Q2 (v 6.00; prebuild windows binaries), brand new CFG file etc. to make sure it wasn't an issue with my current install files. Still crashes.  Must be a Windows 7 thing?

**Comment by iButane** [comment]
I did some googling and I think this appears to be a mapping issue? I dunno, but I was able to find this: http://web.archive.org/web/20010202144500/http://mapspy.gamedesign.net/eio.html

Maybe it's related to this other issue with custom maps: https://github.com/yquake2/yquake2/issues/153

**Comment by DanielGibson** [comment]
but that should happen in vanilla q2 and other ports as well then? we certainly didn't lower the entity limit..

**Comment by iButane** [comment]
True...
I wonder if someone else could test these maps on the Windows build.  Just to make sure it's not only on my side.

**Comment by DanielGibson** [comment]
I'll test on Win7 64bit (with the official binaries) later.
In my WinXP virtualmachine it didn't crash, neither on Yamagi's Win10 PC

what skill did you use? (there might be more monsters or other entities on higher skills)

**Comment by DanielGibson** [comment]
Doesn't crash on my Win7 machine either. Looks like the problem really is on your end..

You could try copying the paks freshly from CD again and then unpacking the 3.20 patch over it freshly. Just in case some game data file got corrupted somehow.

You could also try (at least temporarily) deactivating Antivirus software, it tends to suck and break shit (and make your computer actually *less* secure by being buggy and having security vulnerabilities by itself).

**Comment by iButane** [comment]
Oops.. my bad. I forgot to remove the Yamagi folder under users\documents folder. Had some older versions of those maps.

**Comment by iButane** [comment]
No more issues.

**Comment by DanielGibson** [comment]
Not directly related, but were you able to fix the issues you had with yq2 6.00 on WinXP?

Yamagi and me tried it with WinXP VMs, no problems there..

**Comment by iButane** [comment]
No, but I didn't really try anything. I'll give it another go next time.
