### ISSUE TITLE
Huge pixel take all the screen

### ISSUE THREAD

**Issue by PowaBanga** [yquake2/yquake2#175]
Hi,
I reinstall yamagi to play on my mod "dday", and I have a problem : i will try to explain it...
So when I shoot on the floor for exemple, there is some pixels who appears where the shoot is done. It's the same when i shoot on a other player, there is somes pixels who appears to simulate the blood.

The problem is that this pixel are to huge and take all the screen by moment, and i see nothing...
How to resolve that ?

**Comment by DanielGibson** [comment]
can you take a screenshot?
and tell us what operating system, gpu und drivers you're using?

**Comment by PowaBanga** [comment]
Here i toke some screenshot in observer mode, because in game you see nothing

![](https://i58.servimg.com/u/f58/11/14/34/43/-410.jpg)
![](https://i58.servimg.com/u/f58/11/14/34/43/-010.jpg)
![](https://i58.servimg.com/u/f58/11/14/34/43/-110.jpg)
![](https://i58.servimg.com/u/f58/11/14/34/43/-210.jpg)
![](https://i58.servimg.com/u/f58/11/14/34/43/-310.jpg)

**Comment by PowaBanga** [comment]
if this don't help you, maybe can I take a video screen...  ?

**Comment by DanielGibson** [comment]
It *could* be a GPU driver bug..
Could you execute `glxinfo | grep OpenGL` in a terminal and paste the output? Hopefully that'll tell us the GPU and driver used.

**Comment by maraakate** [comment]
are you saying that this only happens in spectator mode?  Or only when the blood decals are generated?

Are you connecting to a dday server or have you compiled dday code for use with yq2?

If you are connecting to a server, give me the IP.

**Comment by DanielGibson** [comment]
Where can I download DDay for Linux?

**Comment by maraakate** [comment]
@DanielGibson We have a port available in q2dos.  You will have to change the gi.dprintfs to remove the DEVELOPER_MSG tags and match up the q_shared.c stuff as appropriate:

https://bitbucket.org/neozeed/q2dos/src/d311f66cf15cac930ceeff97143248d26d5b6dc1/dday/?at=master

**Comment by PowaBanga** [comment]
```glxinfo | grep OpenGL
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ironlake Mobile 
OpenGL version string: 2.1 Mesa 11.2.2
OpenGL shading language version string: 1.20
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 11.2.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
OpenGL ES profile extensions:
```
[Source code of the mod](http://www.ddaydev.com/downloads/code/) If you arrive to compil bots, can you explain to me how did you do that ? ( [post where i speak about bots on DDDev](http://www.ddaydev.com/forum/viewtopic.php?f=9&t=8521&p=97279#p97279)) 
there is not package for linux, so there is not data.
But you can download the datas [on my megaupload](https://mega.nz/#F!nldzSLIL!tsMgorUtWzoyTKijiKTMRA) or by extract of the [install.exe](http://ddaydev.com/site/downloads.php?cat=fullinstall) (is uploading at now)

So the screenshot come from this server : liberty.souers.org:27910
But i compiled the mod myself, and i can see it on dday1 with the axis light gunner on my server (don't to much near you)

**Comment by maraakate** [comment]
it would be gl_ext_pointparameters not gl_pointparameters.

**Comment by DanielGibson** [comment]
nope, in yq2 it's `gl_pointparameters`

**Comment by maraakate** [comment]
then why does his config file say 

set gl_ext_pointparameters "1"

?

**Comment by DanielGibson** [comment]
no idea.. did we rename it recently?

anyway, if you set it in the console you'll have autocompletion (with the tab key), just check which one is available and set that or both or whatever to 0 :)

**Comment by DanielGibson** [comment]
Yep, apparently we renamed it for 6.0 and SUSE is still providing 5.34 - ok, set that to 0 then.

**Comment by maraakate** [comment]
:D

**Comment by Yamagi** [comment]
Some cvars - dependent on OpenGL extensions - were renamed after I rewrote the extension detection logic last summer. It was done sometime between 5.34 and 6.00. I wanted to rename even more cvars but I was told that I shouldn't break existing configs...

Nevertheless, this is the "Older Intel OpenGL drivers have bugg pointparameters"-problem. Setting the cvar should fix it.

**Comment by PowaBanga** [comment]
Ha good, it work thanks you !!!!

Is it normal that the game had bad configurations like this on starting ?

And an other question : can yamagi run Q3 map like egl ?

**Comment by DanielGibson** [comment]
it's not a bad configuration, your GPU driver is just buggy and this cvar works around the bug.

no it can not run Q3 maps.

**Comment by PowaBanga** [comment]
ha ok, thank you very much for your answers !
 (it should be good that yamagi can run Q3 maps for the dday mod the english comunity is porting the game on egl for that, and it don't work on linux i think...)

An other question yet :p is it possible to launch a command to load a specific pak.pak file ? I explain : for exemple we did a pak with french translation of pictures of the game, and now I starting to translate some sounds. It's very funny, and now i think, that it should be good that the pack file is in the default install, but that he is charged only if the user type something like this : `exec french.pak` because the english users don't need it.
