### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by newbie78** [yquake2/yquake2#176]
thanks for great job!

link to crashdump
https://yadi.sk/d/n7KFWeLM3GLq7o
the problem always occurs near the water near railgun on q2dm1

win10lstb / gtx760

**Comment by maraakate** [comment]
Does it occur whenever you get in water for a few seconds?  What screen resolution are you using?

**Comment by Yamagi** [comment]
No answer for 20 days -> Close it. The issue can be reopened if necessary.
