### ISSUE TITLE
I can't see enough far

### ISSUE THREAD

**Issue by PowaBanga** [yquake2/yquake2#178]
Hi all,

I explain my problem, with yamagi, I can't see enough far. So when my enemies are far away of me, they can see me, me not, and they kill me :o 

So the build are cutted, it's not beautifull

![](https://i58.servimg.com/u/f58/11/14/34/43/quake010.jpg)
![]( https://i58.servimg.com/u/f58/11/14/34/43/quake011.jpg)

Maybe there is a way in setting to resolve that ?

**Comment by DanielGibson** [comment]
try setting the `gl_farsee` cvar to `1`

**Comment by PowaBanga** [comment]
it seem that it work, thank you very much !!!!
