### ISSUE TITLE
Crash On Startup, Can't Find ref_gl

### ISSUE THREAD

**Issue by shoober420** [yquake2/yquake2#183]
When trying to start yamagi with the latest commit, I get this error message. I haven't played Quake 2 in a while and was going to try out the new OpenGL renderer, so I'm not sure which commit causes this error. It will still crash even if I try to start with "+vid_renderer ref_gl3".

----- refresher initialization -----
Sys_LoadLibrary failed: /usr/bin/ref_gl1.so: cannot open shared object file: No such file or directory
Shutting down OpenAL.
Cmd_RemoveCommand: force_centerview not added
Cmd_RemoveCommand: +mlook not added
Cmd_RemoveCommand: -mlook not added
Shutting down input.
recursive shutdown
Error: Loading ref_gl1.so as renderer lib failed!

**Comment by DanielGibson** [comment]
why /usr/bin/? is your quake2 executable there? how do you install yquake2 systemwide? where is baseq2/game.so?

(the problem here is most probably that we expect the renderer libs to be in the same directory as the executable, which is not the case for systemwide installations. not sure yet what to do about it.)

**Comment by shoober420** [comment]
My executable is in "/usr/bin". The game.so file is in "/use/share/yamagi-quake2/baseq2". Here is the PKGBUILD for the package in the AUR for Arch Linux. It does compile with "WITH_SYSTEMWIDE=yes".

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=yamagi-quake2-git

**Comment by DanielGibson** [comment]
Correction: It *can* be the case for systemwide installations.
The yamagi-quake2 debian package already puts all the binaries and other yq2-specific data in `/usr/lib/yamagi-quake2/`, like
```
/usr/lib/yamagi-quake2/baseq2/game.so
/usr/lib/yamagi-quake2/q2ded
/usr/lib/yamagi-quake2/quake2
/usr/lib/yamagi-quake2/baseq2/models/crosshair/skin.pcx
/usr/lib/yamagi-quake2/baseq2/models/crosshair/tris.md2
/usr/lib/yamagi-quake2/baseq2/yq2.cfg
```
(and I guess in the future ref_gl1.so and ref_gl2.so will be in there too).

Not sure, if they do that, but they could just symlink `/usr/lib/yamagi-quake2/quake2` to `/usr/bin/quake2` or `/usr/bin/yamagiq2` or whatever and that should just work.

I'd suggest you do something similar, i.e. make sure all binaries (executables, libs) are in the same directory.

**Comment by shoober420** [comment]
I don't seem to have a "/usr/lib/yamagi-quake2" directory. This for sure is an issue with the PKGBUILD for Arch. I'll post about it in the comments and tell him to update it with the latest changes. Thank you for the explanation.

**Comment by DanielGibson** [comment]
looks like that AUR hasn't been updated for the changes to the renderer yet (it used to be in the executable, now it's in ref_gl1.so and we have an additional ref_gl3.so with a brand new OpenGL3-based renderer).

I'd suggest that AUR should use a directory structure similar to debian's package.

BTW, debian's way has the additional advantage that you could install an additional quake2 port that lies in /usr/share/foo-quake2/ and loads the data (but not renderer and game libs) from the same place as yq2, e.g. /usr/share/games/quake2/

**Comment by shoober420** [comment]
Ok, I'll link to this issue and tell him to make the changes you suggested. Thank you.

**Comment by shoober420** [comment]
Would it be possible to have Yamagi-quake2 look for the render files in other directories? For example, it looks for them in the "~/.yq2" directory, or the "baseq2" directory?

**Comment by DanielGibson** [comment]
I don't think that's a good idea, it would only lead to confusion with older versions of a file from one directory is used while the user would expect another version from another dir.

**Comment by shoober420** [comment]
Ok cool, nevermind.
