### ISSUE TITLE
invalid enum AL_MAX_GAIN in openal.c#L610

### ISSUE THREAD

**Issue by xorw** [yquake2/yquake2#184]
Hi,

I noticed stream of errors in linux console running
current version of yquake2 (commit 9359d6d51dbb920ba4a5d91c714fa52bf7e66385):

AL lib: (WW) alSetError: Error generated on context 0x55b0ad800160, code 0xa002

enabling trap-al-error = true in ~/.alsoftrc revealed usage of non existing enum value AL_MAX_GAIN in:

https://github.com/yquake2/yquake2/blob/master/src/client/sound/openal.c#L610

see:

https://github.com/kcat/openal-soft/blob/master/OpenAL32/alListener.c#L101

following change fixed the problem for me:

diff --git a/src/client/sound/openal.c b/src/client/sound/openal.c
index 4261214..4bd18ae 100644
--- a/src/client/sound/openal.c
+++ b/src/client/sound/openal.c
@@ -607,7 +607,7 @@ AL_Update(void)
        /* set listener (player) parameters */
        AL_CopyVector(listener_forward, orientation);
        AL_CopyVector(listener_up, orientation + 3);
-       qalListenerf(AL_MAX_GAIN, s_openal_maxgain->value);
+//     qalListenerf(AL_MAX_GAIN, s_openal_maxgain->value);
        qalDistanceModel(AL_LINEAR_DISTANCE_CLAMPED);
        qalListener3f(AL_POSITION, AL_UnpackVector(listener_origin));
        qalListenerfv(AL_ORIENTATION, orientation);

**Comment by DanielGibson** [comment]
you're right, I think AL_MAX_GAIN is only for sources, not for listeners

**Comment by xorw** [comment]
there seems to be additional problem with raw samples playback - videos and OGG background music are silent (no errors) :(

**Comment by DanielGibson** [comment]
videos and music work for me (Xubuntu 16.04 amd64 with openal-soft 1.16.0)

not sure what could break video sounds, but for music:
* do you have the music tracks in baseq2/music/02.ogg ... 11.ogg ?
  - if you enter `ogg_list` in the console, are they listed there?
* is Options -> OGG music enabled?
* is the Options -> OGG volume slider somewhere in the middle?

**Comment by DanielGibson** [comment]
I just pushed a fix for the AL_MAX_GAIN issue

**Comment by xorw** [comment]
AL_MAX_GAIN issue is fixed. 

(I make silent video/BGM a separate issue; it worked in an earlier commit - but I need to find which one)
