### ISSUE TITLE
Silent streaming audio with newest OpenAL

### ISSUE THREAD

**Issue by xorw** [yquake2/yquake2#185]
Hi,
I noticed missing (silent) streaming audio in videos/OGG background music using current
OpenAL commit 63baa3b1c712317e7826de6f28ecc865d1fb9b58.

I was able to trace the problem back to change:

https://github.com/kcat/openal-soft/commit/5c859af24ea44dabbbb31631309bb08a858a523e

where some buffer semantics was changed/fixed.

I was able to fix the problem with following change:

[xorw_yquake2_openal_change.patch.zip](https://github.com/yquake2/yquake2/files/948199/xorw_yquake2_openal_change.patch.zip)

(small problem remains: when paused during video playback, a small looped chunk of audio from video keeps playing in the game menu...)

**Comment by Yamagi** [comment]
Wow, this is good work. I've committed your patch and added code to clear out all raw samples when the menu or the console is entered during cinematics playback. Thank you! :)
