### ISSUE TITLE
GL3: Some animated textures are rotated by 90°

### ISSUE THREAD

**Issue by Yamagi** [yquake2/yquake2#186]
At least in rware1.bsp in rogue the animated textures of one conveyor belt are rotated by 90°. See the attached screenshot for details: 
![laufband](https://cloud.githubusercontent.com/assets/1224576/25316903/13a404fa-286f-11e7-9467-b091fbfaa84a.jpg)

With GL1 everything looks fine.

**Comment by Yamagi** [comment]
Maybe scroll added to texCoord.y in vertexSrc3DlmFlow in gl3_shaders.c?

**Comment by DanielGibson** [comment]
weird, because in baseq2 it works..

if it breaks might depend on the direction of the conveyor belt (along x or y axis)

**Comment by DanielGibson** [comment]
OTOH, in fact2 there are conveyor belts in different directions and all work

**Comment by DanielGibson** [comment]
\o/

seems like in baseq2 (at least fact2 and ware2) the conveyor belts don't even use SURF_FLOWING, but move brushes around.. that must have been painful to build.
