### ISSUE TITLE
cl_updaterate?

### ISSUE THREAD

**Issue by shoober420** [yquake2/yquake2#187]
I've been playing with the new render and it looks great! The lighting and shading definitely​ looks superior. One thing I've been meaning to ask about is in r1q2 you can set cl_updaterate just like in GoldSrc games like Counter-Strike 1.6. Could this option be implemented, or is it just not necessarily? I do play with cl_async set to 0 because the movement, especially jumping seems changed.

**Comment by Yamagi** [comment]
That's unnecessary. It's an addition of some enhanced network protocols that won't (or even can't) be implemented by yq2. In Quake 2 nearly everything is tied together with everything: The gamecode implements part of the physics, single player mechanics and AI are based upon it. The physic is dependent on the internal timing, bound to the several frame counts. The frame count is used by movement calculations and prediction. Etc. Altering that stuff is nearly impossible without breaking something, for example the single player mode.

cl_async defines how the various internal frame counts are bound together. When set to 0 the renderer framerate is the same as the client framerate. That's mostly the behavior of id Softwares client. In this mode movement physics are depended on the renderer framerate, the more renderer frames are drawn the higher movement inaccuracies are. Staring at about 95 FPS the player can jump much higher than normally. The Quake II version of Q3As 125hz problem.

When set to 1 the renderer framerate (controlled by gl_maxps) is independent from the the client framerate (cl_maxfps), the only constrained is that gl_maxfps >= cl_maxfps is enforced. Regardless how many frames are drawn, movement is always the same. By default cl_maxfps is set to 60. That's a rather high value compared to classic Quake II were often 30 to 40 frames were the maximum. And it's rather low compared to modern Quake II were most players are playing with >100 Frames.

Try to set cl_async to 1 and to fiddle a little bit with different cl_maxfps values until you find some movement behavoir that you like. Just make sure that gl_maxfps is high enough and the vsync isn't capping it.

**Comment by shoober420** [comment]
Ok cool, thank you for the explanation. I'll give cl_async a try again.
