### ISSUE TITLE
HUD and Menu too bright

### ISSUE THREAD

**Issue by shoober420** [yquake2/yquake2#189]
With the new OpenGL 3 renderer, the HUD and Menu are too bright and washed out. The rest of the game looks great. The particles are really nice looking. Is there a way to adjust the brightness of HUD elements and Menu?

**Comment by shoober420** [comment]
The console is very bright too.

**Comment by DanielGibson** [comment]
.. and videos too, I guess. they all use the same shader and they all use gl3_intensity. I wonder what gl3_intensity value you use if they look "very bright".. anyway, will introduce a `gl3_intensity_2D` cvar that lets you set a different intensity for 2D elements (HUD, menu, console, videos)

**Comment by DanielGibson** [comment]
pushed a commit doing that

**Comment by shoober420** [comment]
The gl3_intensity is set to "1.5". I left it at that default value because I saw a comment that you and Yamagi set these values to match the original render as close as possible, so I left this and overbrightbits alone.

**Comment by DanielGibson** [comment]
ok, then try the latest code and set `gl3_intensity_2D` to `1.0`

**Comment by DanielGibson** [comment]
and yeah, we tried tweaking the values to match the orig renderer, but
* in GL1, `intensity` defaults to 2, we use gl3_intensity 1.5 because it looks better (GL1 only supports integer values there)
  - in GL1, `intensity` was not applied to 2D rendering (HUD, menu, console, videos), we did apply gl3_intensity there though and I think it looks better that way and with low intensity values it shouldn't normally look very extreme, but apparently this depends on personal taste and probably the display
  - so now gl3_intensity_2D can be configured independently, a value of `1.0` should look like in the old renderer
* the GL3 renderer looks more like the old multitextured GL1 code (that was disabled by default) than the other GL1 code. that is because the lightmaps are applied via multitexturing in GL3, while default GL1 rendered them in an extra pass (the old software renderer looked even different, for example the shadows weren't as dark).
* the in GL1 the gl_overbrightbits defaulted to 0 (which was mostly identical to 1) and the values were  restricted to 0, 1, 2, 4 - gl3_overbrightbits supports any value and we found 1.3 to look best

so we tried to find a combination of gl3_intensity, gl3_overbrightbits that looked best and mostly matches the old look

**Comment by shoober420** [comment]
Awesome, a value of 1 does make it look how it does in the original. I'm now starting to see why a value of 1.5 was chosen though. The text in the console is white when it's set to 1.5, but when it's at 1, it's more of a greyish color. I still think the videos and sprites do look better with a value of 1 though. I'm on a CRT so that may have something to do it with it. Thank you very much DanielGibson.

**Comment by shoober420** [comment]
So I was switching back between the renders and comparing there brightness levels and found some interesting things. So a value of 2 for gl3_intensity is significantly brighter then a value of 2 for the "intensity" cvar with the old render. I kept switching back and forth while adjusting the gl3_intensity cvar, and found that a value of 1.4 brings identical results to the old render I  regards to intensity levels. So "intensity 2" in the old render is "gl3_intensity 1.4" with the new render. You can really notice ce it in the player models. Should a value of 1.4 for gl3_intensitu be considered the default value with these findings?

**Comment by shoober420** [comment]
I forgot to take into consideration the gl3_overbrightbits cvar. When setting this to 1, then setting gl3_intensity to 2, the renders are the same. Sorry about that one statement, but for sure using gl3_intensity 1.4 when using gl3_overbrightbits 1.3 looks identical to the old render with the new settings. The difference is explosions and other lights look more pronounced and vivid, which is cool.

**Comment by iButane** [comment]
I think the best way to get the most authentic look would be to have Quake 2 v3.21 running on a vintage PC (voodoo 3dfx card, pentium on a CRT monitor etc) next to your current PC for comparison as you tweak all those variables. But without that all we can rely on is our memory and current preference.

The explosions being more vivid is something I haven't seen in ages until now. That's very reminiscent of Q2 running on a 3dfx voodo card as I recall.

Btw, the HUD is also too bright in my screen. It's the very first thing I noticed when I fired up this new GL render. I can live with it, but will be nice when gl3_intensity_2D is added to the win binaries =)

**Comment by shoober420** [comment]
Good point, i wonder if Quake 2 was built around Glide like UT99 was. The explosions and lights have a glow to them now. It looks really neat.

**Comment by iButane** [comment]
Hrmm.. after playing around a bit with gl3_overbrightbits and gl3_intensity, I have to say I really like your combination, shoober420, of 1 and 2 values respectively for those variables. it makes water and lava surfaces look more vibrant.

Btw, will gl_modulate eventually become gl3_modulate? I always keep this at '1'. years of fiddling with these settings has taught me that nothing good, only headaches, has ever come out of changing gl_modulate from 1 to anything else =)

**Comment by shoober420** [comment]
Currently, to stay true to how Quake 2 was originally rendered in terms of brightness, I'm using the following settings. They seem to be exact to GL1 except a tad bit brighter for lights and explosions. They all seem to have a nice glow effect with the GL3. Maybe I'll post a picture of what I mean.

gl3_overbrightbits "1"
gl3_intensity "2"
gl3_intensity_2D "1"

**Comment by DanielGibson** [comment]
the gl3 renderer supports using gl_modulate, should do the same thing as on gl1

no idea if it's any useful, I don't think I ever changed it

**Comment by shoober420** [comment]
Here are two pictures that demonstrate the cool glow effect on lights.

GL3:
![q20](https://cloud.githubusercontent.com/assets/5150898/25415105/27e4f674-2a25-11e7-8700-5445ee0fba27.jpg)

GL1:
![q21](https://cloud.githubusercontent.com/assets/5150898/25415109/2cbf5810-2a25-11e7-86a2-cadb0d0466e0.jpg)

**Comment by Yamagi** [comment]
The look and feel of the original OpenGL renderer was highly dependend on the OpenGL driver. The renderer first drawed the base texture, after that it blended the static lightmap and the dynamic lights into the actual ligtmap, drawed the actual lightmap over the base texture. The blending of the actual lightmap into the base texture was done by the OpenGL driver, another driver meant another blending algorithm with another look.

Other thinks to take into account are, that old CRT displays often were much brighter than modern LCD diplays. For example my trusty old Iiyama HM903DT is at least twice as bright as my current Eizo EV2750. Additionally modern Windows versions seems to have a higher system wide gamma than Win 95 and 98 to compensate the darker displays.

When determining the default settings for GL3 my goal terefore wasn't to exactly mimic the look and feel of GL1. I tried to find settings that are suiteable for most users. The game should look dark, Stroggos is a dark and dirty place. But on the other hand not too dark, especially on modern displays. The colors should be pronounced, not as washed out as on GL1 with Nvidia.

I'm currently working on some documentation regarding cvars. I'll include some hints on how to configure yq2 to mimic the old GL1 look.

**Comment by iButane** [comment]
> The game should look dark, Stroggos is a dark and dirty place. But on the other hand not too dark

I couldn't agree more. I cringe every time I see super bright screenshots especially in singleplayer. Those who play like that don't know what they're missing; it destroys the intended mood and atmosphere of the game.

**Comment by shoober420** [comment]
I took some pics to demonstrate the glowing effect lights have.

GL3:
![q2gl3](https://cloud.githubusercontent.com/assets/5150898/25455933/f45524f4-2ac0-11e7-8d3c-13d212cd2edf.jpg)

GL1:
![q2gl1](https://cloud.githubusercontent.com/assets/5150898/25455943/fa5c253c-2ac0-11e7-8e8c-7f506fb3f442.jpg)

The effect is really cool, and the particles look really sweet. I will personally always use GL3.

**Comment by DanielGibson** [comment]
@iButane Yamagi just created new windows binaries of the latest code: https://deponie.yamagi.org/quake2/misc/quake2-gl3-test3.zip
