### ISSUE TITLE
Stencil Shadows For GL3

### ISSUE THREAD

**Issue by shoober420** [yquake2/yquake2#190]
The shadow code is really poopy with the original render. Would it be possible to implement stencil shadows that don't look as poopy for GL3?

**Comment by DanielGibson** [comment]
generally, yeah, but no idea when someone will get around to do it

**Comment by DanielGibson** [comment]
check out #191 

not perfect, but looks good mostly ;)

**Comment by shoober420** [comment]
Awesome, I can't wait to try this out. Thanks for the awesome render Daniel.

**Comment by shoober420** [comment]
Thank you both for adding this. I'm currently testing as if right now.
