### ISSUE TITLE
Cannot compile on Mac OS X with WITH_OPENAL disabled

### ISSUE THREAD

**Issue by bryab** [yquake2/yquake2#192]
===> LD release/quake2
Undefined symbols for architecture x86_64:
  "_AL_UnqueueRawSamples", referenced from:
      _Con_ToggleConsole_f in cl_console.o
      _M_PushMenu in menu.o
ld: symbol(s) not found for architecture x86_64

**Comment by Yamagi** [comment]
This was broken on all architectures, not only OS X. It's fixed now. Thank you for the report!
