### ISSUE TITLE
Various Shadow Bugs

### ISSUE THREAD

**Issue by shoober420** [yquake2/yquake2#195]
I took some pictures of various shadow bugs I encountered so far. I think some of these are from the lack of shadow volumes.

The first set of 3 is a shadow coming from above the doorway. I can't see what would be causing this. I remember this happening when using shadows with the GL1 render as well.

![q2_0000](https://cloud.githubusercontent.com/assets/5150898/25882376/b24f383e-3532-11e7-8ba9-964a73c4384a.jpg)

![q2_0001](https://cloud.githubusercontent.com/assets/5150898/25882386/b8222398-3532-11e7-838b-3462659757f2.jpg)

![q2_0002](https://cloud.githubusercontent.com/assets/5150898/25882389/ba8a1744-3532-11e7-8e8f-03afc2e364a6.jpg)

This is a shadow that overlaps the edge from the satellite.
![q2_0003](https://cloud.githubusercontent.com/assets/5150898/25882393/bfcd78a4-3532-11e7-9cd3-ab9800e92b97.jpg)

These last two are odd. This shadow is rendered of the dead marine, and will also disable the rendering of the water where the shadow is. This looks similar to the issue with the shadows on destructable walls and floors, except its water.
![q2_0004](https://cloud.githubusercontent.com/assets/5150898/25882400/c419b21a-3532-11e7-939e-83e656cd98ac.jpg)

![q2_0005](https://cloud.githubusercontent.com/assets/5150898/25882403/c97e20d8-3532-11e7-9c97-f9dc2145a646.jpg)

**Comment by DanielGibson** [comment]
Yeah, the shadows are really simple, they're basically a flattened version of the model, put at the lowest point of the model (or models bounding box or sth). Pretty much like the shadows in GL1 (when also setting `gl_stencil_shadows 1` so they don't flicker).

They are no shadow volumes and are expected to look buggy, e.g. by sticking out over edges.

**Comment by Yamagi** [comment]
Like Daniel says this is expected. At least for now, maybe we / he will implement proper shadows at a later point.

**Comment by shoober420** [comment]
Awesome, I'm excited to play with shadow mapping. It will look really cool.
