### ISSUE TITLE
[Feature request] HRTF Audio support

### ISSUE THREAD

**Issue by DarkSwan86** [yquake2/yquake2#197]
Hi!

First of all, thanks for your work on keeping Quake 2 alive! 

I'd like to ask if is it possible to add [HRTF](https://en.wikipedia.org/wiki/Head-related_transfer_function) to Quake 2 audio output, it's useful for who uses headphones when they play. Because i can't judge how difficult it is to implement this feature treat this request as low priority. Maybe @xorw can chime in? :)

Thanks!

**Comment by xorw** [comment]
Hi,

HRTF is already enabled and working with OpenAL Soft.

Please make sure you have following settings in your .alsoftrc config file:
channels = stereo
stereo-mode = headphones

for more info see README of OpenAL Soft: 
https://github.com/kcat/openal-soft,
https://github.com/kcat/openal-soft/blob/master/docs/hrtf.txt

**Comment by Yamagi** [comment]
Like @xorw says we've already got HRTF support through OpenAL Soft.
