### ISSUE TITLE
Crash when launched with Steam

### ISSUE THREAD

**Issue by Khyota** [yquake2/yquake2#201]
I'm trying to launch this with steam so I can play with the steam link and controller. 
It appears to crash at this line:
libgcrypt selftest: binary  (0): No such file or directory
Ohhhh jeeee: ... this is a bug (global.c:137:global_init)

Im running opensuse 42.2, and it works outside of steam. I've attached a log file and a debug backtrace.
[quake2crash.txt](https://github.com/yquake2/yquake2/files/1017157/quake2crash.txt)
[q2debug.txt](https://github.com/yquake2/yquake2/files/1017158/q2debug.txt)

**Comment by RafneQ** [comment]
There is a problem on openSUSE with some Steam games after recent Steam client update. There is a workaround from etamPL on [openSUSE froum](https://forums.opensuse.org/showthread.php/523486-Steam-games-not-working)
In game launch options you have to put:
`env LD_PRELOAD="" %command%`
This will disable Steam overlay but should make game work again.

**Comment by DanielGibson** [comment]
Yeah, this definitely looks like a problem of Steam with SUSE (and the backtrace mentions OpenAL and PulseAudio), I don't think there's anything we can do (but you should try the workaround @RafneQ mentioned, if that doesn't help maybe also set LD_LIBRARY_PATH to "").

I guess that Steam tries to overwrite some system lib with another (probably older) version of that lib and OpenAL or one of its dependencies need the newer/different (system) version.

**Comment by RafneQ** [comment]
You can also try launching steam client with the following command:
STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam
There is opened issue on the [steam-for-linux github page](https://github.com/ValveSoftware/steam-for-linux/issues/5000).
