### ISSUE TITLE
GL3 lib does not build on ARM arch (missing xmmintrin.h)

### ISSUE THREAD

**Issue by akien-mga** [yquake2/yquake2#204]
Hi there,

Version 7.00 fails to build on Mageia's ARM nodes with this error:
```
==> CC src/client/refresh/gl3/gl3_draw.c
In file included from src/client/refresh/gl3/header/local.h:46:0,
                 from src/client/refresh/gl3/gl3_draw.c:28:
src/client/refresh/gl3/header/HandmadeMath.h:202:23: fatal error: xmmintrin.h: No such file or directory
compilation terminated.
Makefile:618: recipe for target 'build/ref_gl3/src/client/refresh/gl3/gl3_draw.o' failed
```

According to [StackOverflow](https://stackoverflow.com/a/22291538), it seems like this include should be made platform specific.

**Comment by akien-mga** [comment]
With this patch it builds fine for me on x86_64, i586, armv7hl and armv5tl, all GNU/Linux with GCC 5.4.0: http://svnweb.mageia.org/packages/cauldron/yamagi-quake2/current/SOURCES/yamagi-quake2-7.00-mga-intrinsics.patch?view=markup&pathrev=1107343

**Comment by DanielGibson** [comment]
can you test if my patch in 36c880e105a48f7d926694e6b335fecaf02c2fb8 fixes the problem?

Thanks!

**Comment by akien-mga** [comment]
I'll try it asap, but I'm not sure it will work. AFAIU, ARM processors (at least Mageia's) do support SSE, hence `__SSE__` is defined, but their relevant header is not named `xmmintrin.h` which is x86-specific. So if I read your patch correctly, ARM builds might still choke on the include.

**Comment by akien-mga** [comment]
Oh wait, I just read the Handmade-Math upstream PR and there was a typo in the SSE conditional, so your fix might be good. Will try it and report back.

**Comment by DanielGibson** [comment]
ARM doesn't support SSE, they have something similar called NEON, but it doesn't only use a different header, but also different functions, so it's no drop-in replacement (and to be honest, HMM only uses SSE in two functions and I doubt it gives any real benefit there anyway)

**Comment by akien-mga** [comment]
I confirm that the patch works fine to build on armv5tl and armv7hl :)

**Comment by DanielGibson** [comment]
Awesome, thanks for testing!

The patch has been accepted upstream (at Handmade Math) as well, so it's definitely here to stay
