### ISSUE TITLE
Custom resolutions won't go higher than 1080p

### ISSUE THREAD

**Issue by pagb666** [yquake2/yquake2#208]
I'm running the latest windows build with a 4k monitor. Anything higher than 1080p will look zoomed in at the center of the screen, showing 1080p worth of viewport. However, it seems to be running at 4k.
(http://i.imgur.com/LuiAui7.png

**Comment by Yamagi** [comment]
Congratulations. It looks like you're the first brave soul trying Quake II on a high DPI setup. :) The problem you're seeing is just that Windows doesn't know that Quake II is high DPI aware (or better: there's no need for it to be scaled). That's quite easy to fix. Can you try the set of binaries found here - http://deponie.yamagi.org/quake2/misc/quake2_highdpi.zip - and tell me if it fixes the issue for you?

**Comment by pagb666** [comment]
Worked like a charm! Only downside, crosshair is SO tiny :P
[](http://i.imgur.com/9kunaWv.jpg)

**Comment by Yamagi** [comment]
There's the `crosshairscale` cvar that scales it :) I'll add it to the stuff/cvarlist.md.
