### ISSUE TITLE
7.01 OSX Package for 10.11+

### ISSUE THREAD

**Issue by JoshuaPettus** [yquake2/yquake2#210]
Hi, I went and made an OSX bundle of 7.01 using your included scripts and layout.  It includes all libraries as frameworks, and OpenALSoft which was recommended.  I know OSX includes its own OpenAL but I wasn't sure which is better.  It also has the current all the dylibs for the missions packs.

https://www.dropbox.com/s/35xuunwrvvkelov/Quake2-OSX-10.11%2B.dmg?dl=0

Regards

**Comment by JoshuaPettus** [comment]
Sorry there was an issue with the OpenALSoft.framework.  Should be working now

**Comment by Yamagi** [comment]
Hi,
I've uploaded it to http://deponie.yamagi.org/quake2/osx/quake2-7.01.dmg. The homepage links to that folder. Thank you! :)

**Comment by clobber** [comment]
@JoshuaPettus Your app bundle isn't redistributable and crashes on launch:

```
dyld: Library not loaded: @rpath/SDL2.framework/Versions/A/SDL2
  Referenced from: /Quake 2.app/Contents/Resources/quake2
  Reason: image not found
/Quake 2.app/Contents/MacOS/q2-launcher.sh: line 101: 62151 Abort trap: 6           "$BIN" $PARAMS
```

Instead, you should try using [macpack](https://github.com/chearon/macpack) which does a good job of automating the process of `otool -L` and `install_name_tool` to properly bundle linked dependencies.

**Comment by JoshuaPettus** [comment]
oh did I forget to define the rpath?  I'll reupload another in a few hours.  Sorry about that!

**Comment by JoshuaPettus** [comment]
Here is a fixed app bundle. Sorry about that! https://www.dropbox.com/s/35xuunwrvvkelov/Quake2-OSX-10.11%2B.dmg?dl=0

**Comment by clobber** [comment]
Thanks! Yeah, macpack was inspired by dylibbundler and solves a lot of issues it had with dependencies. dylibbundler is no longer maintained since 2013, so those looking to package apps should use something like macpack instead.
