### ISSUE TITLE
How to set path to baseq2

### ISSUE THREAD

**Issue by hevanaa** [yquake2/yquake2#211]
I installed YamagiQuake2 from my distro repository. My Quake files are in my Steam Wine folder. There is no easy way to set the path to the pak files. In Quake 1 (darkplaces engine) there is a command line -basedir that you can use to point to the game folder. Now I have to mess with symlinks instead. The README doesn't tell which of the baseq2 folders should point to the game files folder (or kind of, but it says to copy the game files there, but I don't want to do that). Now the engine looks in /usr/bin/baseq2, ~/.yq2/baseq2 and /usr/lib64/games/quake2/baseq2/. Some old guides refers to setting the path in /etc/quake2.conf, which actually seems a good idea, but it doesn't work with this engine.

**Comment by DanielGibson** [comment]
try `yamagi-quake2 +set basedir /path/to/quake2` :)

**Comment by hevanaa** [comment]
Thanks, but it doesn't completely work:

> ...
> Added packfile '/home/shared/SteamWine/common/quake2/baseq2/pak0.pak' (3307 files).
> Added packfile '/home/shared/SteamWine/common/quake2/baseq2/pak1.pak' (279 files).
> Added packfile '/home/shared/SteamWine/common/quake2/baseq2/pak2.pak' (2 files).
> Using binary dir /usr/bin/baseq2/ to fetch paks
> Using '/home/jukk/.yq2/baseq2' for writing.
> execing default.cfg
> couldn't exec yq2.cfg
> execing config.cfg
> basedir is write protected.
> Console initialized.
> ...
> -------- game initialization -------
> LoadLibrary("game.so")
> ********************
> ERROR: failed to load game DLL
> ********************
> Shutting down OpenAL.
> Shutting down input.
> Error: Error during initialization


Wonder why it also thinks that "basedir is write protected.", because it is not.

game.so is in /usr/lib64/games/quake2/baseq2/


If I symlink /usr/bin/baseq2 to the actual game folder, then it just works (without command line arguments).

**Comment by hevanaa** [comment]
Ok, so it overrides the other baseq paths. If then game.so is copied into the baseq folder specified on command line, then it works.

I'm trying to find a simple way to set it up. E.g. install game through Steam (from Windows or Wine), install the quake2 package. Just start it (with path to the game folder).

Maybe my approach is not typical, or I'm missing something. In the end it works, but it feels hard to figure out the steps from documentation and trial and error for a first time user.

**Comment by DanielGibson** [comment]
it /should/ just work - maybe the distros package is somehow broken?
what distro are you using? which yamagi quake2 version?

**Comment by hevanaa** [comment]
quake2-6.00-9.fc26.x86_64 on Fedora 26. 

It works if copying pak files to either ~.yq2/baseq2/ or to /usr/lib64/games/quake2/baseq2/. But I would like to keep my Steam games in one place and not copying them all over the system, and not to users' home dirs.

And the command line also works if I copy game.so to the actual baseq2 folder specified on command line.

I'm trying to find the easiest path of resistance :)

**Comment by Yamagi** [comment]
> I'm trying to find the easiest path of resistance :)

Just build your own binaries. That's pretty straight forward, you'll get an up to date version and you're no longer dependend on the hardcoded pathes of the binaries packages. The problem is, that the WITH_SYSTEMWIDE compile time option used by package mainatainer breaks several corner cases with for example '+set basedir'. There's not much we can do about it since the game needs some strange bugs in the search path magic. Without them the addons and other mods break.

**Comment by hevanaa** [comment]
I'm content with symlinking around the problems. The Steam path also contains a space that has to made a separate symlink for. I just thought, maybe it could be documented better. The easiest for me now is to have a symlink /usr/bin/baseq2 that points to the game folder. Then it also works for other users on the same PC.

I could compile (even create my own rpms, I'm used to that), but it is a small issue not worth the time.

**Comment by DanielGibson** [comment]
you're running an outdated version of yq2, using an apparently broken package (all the binaries should be in the same directory, /usr/bin/quake2 should only symlink to the executable) and you're apparently putting lots of effort into working around all that.

just build yq2 yourself, it's quite easy, you get an up to date version (incl. the new opengl 3 renderer) and it should fix your problems without symlinking baseq2 to /usr/bin/ or similar hacks

**Comment by hevanaa** [comment]
OK, maybe I should complain to the package maintainer. Sounds like it is maybe worth compiling my own version. Thanks anyway.

**Comment by DanielGibson** [comment]
good luck!

you could ask them to package 7.01 while at it ;)
they could look at the debian/ubuntu package, it seems to work well.

(and we should document this for maintainers some day)

**Comment by hevanaa** [comment]
Compiling works fine and opengl 3 works fine: 

> Successfully loaded ref_gl3.so as rendering backend

I'm going to take a look at the rpm...

**Comment by DanielGibson** [comment]
#214 discusses the WITH_SYSTEMWIDE and basedir problems

**Comment by DanielGibson** [comment]
We now have documentation for package maintainers: https://github.com/yquake2/yquake2/blob/master/stuff/packaging.md

**Comment by Effektus** [comment]
start yquake2.exe +set basedir ../Quake2
