### ISSUE TITLE
Joystick support

### ISSUE THREAD

**Issue by 0lvin** [yquake2/yquake2#216]
Original windows demo had support for [DirectInput joystics](https://github.com/id-Software/Quake-2/blob/master/win32/in_win.c). I have add short code for support joystics by SDL, could you please review changes in pull request #215? First axis have used in same way as windows demo for turn and move forward.

Code add support for bind joysticks button to actions and code for turn/move by axis.

**Comment by Yamagi** [comment]
Already merged, thank you :)
