### ISSUE TITLE
GeForce Experience FPS counter not showing up

### ISSUE THREAD

**Issue by GumbyDeath** [yquake2/yquake2#218]
Hello

Installed the latest 7.01 windows client last night and noticed that the GeForce Experience FPS counter does not show up. I tried both the 3.2 and 1.4 versions of OpenGL. The count shows up in the original quake2.exe client.

**Comment by DanielGibson** [comment]
Hi,

not sure what we should do about that..
Can you try renaming quake2.exe to yquake2.exe and see if it still 
happens (in case nvidias driver has some weird quake2 specific hack)?

Otherwise you should probably report the bug to them..

Cheers,
Daniel

**Comment by GumbyDeath** [comment]
Renaming the executable back to quake2.exe fixed the problem. Nice!

**Comment by Yamagi** [comment]
Okay, so Nvidia detects the binary to apply a game specific optimization (or hack).
