### ISSUE TITLE
Some bindings not working from config.cfg file

### ISSUE THREAD

**Issue by GumbyDeath** [yquake2/yquake2#219]
Hello

Installed the latest 7.01 windows client last night. It looks like Yamagi Q2 supports mouse buttons 4 and up for binding. I added a line in my config.cfg file for MOUSE4 and MOUSE5 but they didn't seem to take when I restarted.

**Comment by DanielGibson** [comment]
Does it work if you try to bind those mouse buttons in the Options -> 
customize controls menu?

**Comment by GumbyDeath** [comment]
On a related note what config.cfg  does Yamagi read on start up? I changed the value of name in the confi.cfg files in both baseq2 and ctf and it had the same name as the last time I quit out.

**Comment by Yamagi** [comment]
It reads `$HOME/.yq2/$mod/config.cfg` on unixoid platforms and `%DocumentsDir%\YamagiQ2\$mod\config.cfg` on Windows. $mod defaults to baseq2.

**Comment by Yamagi** [comment]
I can't reproduce this. What exactly so you add to the config.cfg?
