### ISSUE TITLE
Consider *not* changing desktop resolution while fullscreen with sdl2 backend

### ISSUE THREAD

**Issue by galtgendo** [yquake2/yquake2#220]
...that is using SDL_WINDOW_FULLSCREEN_DESKTOP instead of SDL_WINDOW_FULLSCREEN.

The obvious problem with that two additional vars are needed to pass desktop size from sdl2 to opengl renderer. The less obvious is a potential feature: as the resolution picker will be only for windowed mode size, some calls (among them glVieport and glScissor) might need to be used to keep the chosen screen *ratio*, but then proper offset needs to be calculated (some basic letterboxing implemented).

**Comment by Yamagi** [comment]
Hi,
thank's for the suggestion. I've just pushed several commit to master that change the meaning of vid_fullscreen. 0 is still windowed mode, 1 is SDL_WINDOW_FULLSCREEN_DESKTOP and 2 SDL_WINDOW_FULLSCREEN.
