### ISSUE TITLE
another mac 7.01 package

### ISSUE THREAD

**Issue by JoshuaPettus** [yquake2/yquake2#224]
Clobber pointed out I forgot to add an rpath for the framworks included in the bundle.  I went and fixed that.

https://www.dropbox.com/s/35xuunwrvvkelov/Quake2-OSX-10.11%2B.dmg?dl=0

**Comment by Yamagi** [comment]
I've replaced the older version of the package with this one. Thank you!

http://deponie.yamagi.org/quake2/osx/quake2-7.01.dmg
