### ISSUE TITLE
FOV reset after changing video settings

### ISSUE THREAD

**Issue by Keith94** [yquake2/yquake2#225]
I set a custom FOV through autoexec.cfg, but after changing in-game video settings (e.g. MSAA) and applying, the FOV is reset back to default 90. I'm using Yamagi Quake II 7.01 on Windows.

**Comment by Yamagi** [comment]
This is logic error that's somewhat hard to resolve. The problem is: If `horplus` is set to 1 (the default) the video menu resets the `fov` cvar to 90. You'll need to set `horplus` to 0 if you want to use a custom FOV. In the longer term we should remove the `horplus` cvar and replace it by `fov` set to -1.

**Comment by Keith94** [comment]
Thanks for the info. Replacing the horplus cvar sounds like a welcome fix. Can this issue be reopened and added to a milestone?

**Comment by DanielGibson** [comment]
yeah, we'll look into this again when we have some time.

we don't have milestones ;)

**Comment by Yamagi** [comment]
I've reimplemented the FOV selection in the menu. horplus is now always set to 1 (use the console to disable it) and the FOV can be choosen by a slider. Possible values are 60 to 120, the default stays at 90.

**Comment by Keith94** [comment]
Nice to hear you added an FOV slider!
I wonder can the FOV be configured outside the slider range manually (e.g. using console)? If so, is the custom value ever "reset" when applying changes to settings or at any point?

**Comment by Yamagi** [comment]
You can set any value through the console. But if it's smaller than 60 or greater than 120 it'll be reset as soon as you enter the video menu. There's nothing I can do about it, that's just how the menu works. Therefor we've choosen a large range from 60 to 120.

**Comment by Keith94** [comment]
I tried the new build and it works great. I didn't notice the FOV resetting at all when I opened the menu. This was after I set the value to 150. So nothing to really complain about. :)
