### ISSUE TITLE
3440x1440 in autoexec doesn't work

### ISSUE THREAD

**Issue by anishlr** [yquake2/yquake2#229]
I put the following in my autoexec.cfg file under baseq2:
```
set r_customwidth "3440"
set r_customheight "1440"
```

When I go to the game and switch the video mode to custom, this resolution isn't used. Any idea what the problem is?

**Comment by Yamagi** [comment]
Hello,
Yamagi Quake II hasn't got r_* cvars, they're all named gl_*. You need
to set:

set gl_customwidth "3440"
set gl_customheight "1440"
set gl_mode "-1"

Regards,
Yamagi

On Thu, 17 Aug 2017 00:40:47 -0700
Anish Ramaswamy <notifications@github.com> wrote:

> I put the following in my autoexec.cfg file under baseq2:
> ```
> set r_customwidth "3440"
> set r_customheight "1440"
> ```
> 
> When I go to the game and switch the video mode to custom, this resolution isn't used. Any idea what the problem is?
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/yquake2/yquake2/issues/229


-- 
Homepage: https://www.yamagi.org
Github:   https://github.com/yamagi
GPG:      0xeb1472e71d502515

**Comment by anishlr** [comment]
That worked thanks! Is there some documentation for all the cvars available for Yamagi? Or maybe I can look in some source file?

**Comment by Yamagi** [comment]
While we don't have a complete list the most common cvars are
documented in:

https://github.com/yquake2/yquake2/blob/master/stuff/cvarlist.md

And there's also the 'cvarlist' command that outputs an ordered list of
all available cvars.

On Thu, 17 Aug 2017 19:43:07 +0000 (UTC)
Anish Ramaswamy <notifications@github.com> wrote:

> That worked thanks! Is there some documentation for all the cvars available for Yamagi? Or maybe I can look in some source file?
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/yquake2/yquake2/issues/229#issuecomment-323174235


-- 
Homepage: https://www.yamagi.org
Github:   https://github.com/yamagi
GPG:      0xeb1472e71d502515

**Comment by anishlr** [comment]
Thanks a lot!
