### ISSUE TITLE
Feature Request: LOGG music support

### ISSUE THREAD

**Issue by DarkPulse** [yquake2/yquake2#230]
LOGGs are simply regular Ogg Vorbis files, but with info embedded in the Ogg's ID3 tags to create a loop point. The main point of this would be to gain "gapless" looping playback of a music file, as opposed to the traditional end-to-end loop of an Ogg. The format originates with VGMStream, as a way to have looping audio successfully loop without any issues.

Basically, by adding the tag of `lp` to an Ogg's ID3, and giving it a value of `LoopStartSample,LoopEndSample`, a LOGG is created. VGMStream differentiates Looping Oggs from regular Oggs by using the file extension of LOGG (hence, the "name" of the format), but in practice, Looping Oggs could be sorted out from non-looping Oggs simply by parsing the Ogg's ID3 and checking for presence of the `lp` tag - finding it means reading the values to determine the loop; lack of it means it's a regular end-to-end Ogg. That said, it will not "infinitely" loop in one of VGMStream's supported players without the rename - up to you guys if you want to support the difference in file extensions or not, since for Yamagi Quake 2, they technically don't matter.

As an example of what it can do, [I've attached a LOGG I created](https://github.com/yquake2/yquake2/files/1236645/09.zip) out of one of the tracks from the original soundtrack, but massively degraded in quality (32kbps average bitrate, 11 kHz sample rate, reduced to mono sound) to both keep the file size down and to keep it an inferior copy in terms of "usability" while still allowing you to get the full "effect" of what LOGG does. You can find precompiled, ready-to-install builds of the Winamp/XMPlay plugins and standalone player (test.exe) [here](https://github.com/bnnm/vgmstream-builds/blob/master/bin/vgmstream-latest-test-u.zip), and the source code for VGMStream itself [here](https://github.com/kode54/vgmstream). (You'll probably have to build the Audacious/Foobar2000 ones from source, sorry - I looked for precompiled binaries, but couldn't find them!)

If you've got VGMStream set up properly for your player of choice (Winamp/XMplay/Foobar2000 on Windows, Audacious for Linux), then you should be able to play the attached LOGG file "straight" through them. If it functions properly, instead of ending at 2:37 or so like the original song does, it should play the song for the most part like normal, but loop seamlessly at around 2:20, "return" back to around 1:12 (although the elapsed time will not show this reversal), and just keep endlessly playing that section of the song, again and again. The "end" of the file is still there in this file, but never gets played; if I wanted to go for extreme size chopping, I would've simply ended the file at the end of the loop and removed the "end" of the normal song entirely.

If you guys implement support for this, basically, we never have to worry about pauses in our music ever again - once someone creates a LOGG-friendly music pack, that is, and I'd be more than happy to take on that challenge for BaseQ2/Rogue/Xatrix. :)

Technically this isn't quite in the spirit of the original game, but it's a very minor enhancement (and not the kind that is a fundamental alteration from the original Quake 2 experience - it just means your music no longer has pauses from inelegant end-to-end looping).

Thanks in advance for your consideration!

**Comment by Yamagi** [comment]
This would require a lot of refactorings since Quake II supports only one music backend. That's too much work for too little gain. If someone has really need for music files besides OGG/Vorbis he can sen a pull request.

**Comment by SirYodaJedi** [comment]
This might not be useful for music, but it could be useful for sound effects. Per #717, an Ogg Vorbis file can be used instead of a WAV file (`OGG_LoadAsWav` in `./src/client/sound/ogg.c`) for a sound effect (although the comment at the top of the file hasn't been updated to reflect that). This feature is potentially very useful to save space with long ambient sounds playing in a `target_speaker`, but since looping relies on having a cue placed in a WAV file, this isn't currently possible.

**Comment by DanielGibson** [comment]
let's not add more complexity to the sound backend.
