### ISSUE TITLE
Bus Error on Raspberry Pi 3

### ISSUE THREAD

**Issue by tcm8465a** [yquake2/yquake2#231]
A bus error is generated within a minute of the game playing. This can be reproduced every time simply by starting a game and running straight until you touch the window. As soon as you touch the window, the bus error will occur every time.

I am running on a Raspberry Pi 3 using the latest version of Raspbian.

I should be able to provide any additional information if you need it.

**Comment by LethalManBoob** [comment]
I think you should provide the entire log if possible.

**Comment by tcm8465a** [comment]
Not a problem. I will post the entire log this weekend.

**Comment by Yamagi** [comment]
My RPI arrived today. This was a disgusting but easy bug. It's fixed in HEAD. :)
