### ISSUE TITLE
Add refresh rate control

### ISSUE THREAD

**Issue by Keith94** [yquake2/yquake2#234]
I noticed the game is sometimes choosing the wrong refresh rate (60 Hz rather than my native 120 Hz) or it gets changed when toggling vsync on or off. So being able to choose a specific refresh rate (or simply always use the desktop refresh rate) would be nice.

**Comment by Yamagi** [comment]
The game uses the desktop refresh rate if vsync is enabled. To enforce a refresh rate without vsync the gl_maxfps cvar can be set.
