### ISSUE TITLE
Software mode?

### ISSUE THREAD

**Issue by froghawk** [yquake2/yquake2#238]
Is there a way to turn on the software renderer instead of OpenGL? I'm using the OS X version on Sierra.

**Comment by DanielGibson** [comment]
No.

If you want it to kinda look like the software renderer, use the OpenGL3 renderer and set `gl_texturemode GL_NEAREST_MIPMAP_NEAREST` and `gl3_particle_square 1`

**Comment by DanielGibson** [comment]
Will look like this:
![q2_pseudo_sw](https://user-images.githubusercontent.com/1216493/30824802-f63666b0-a230-11e7-9e6c-8d418090226d.jpg)

**Comment by froghawk** [comment]
Thanks for the quick reply. It's a decent compromise.

**Comment by DanielGibson** [comment]
Advantage over real software renderer: It doesn't use that much CPU power (PC stays quite and, esp. relevant for laptops, cooler) and it supports higher resolutions.

Glad I could help, have fun! :)
