### ISSUE TITLE
OSX       use of undeclared identifier 'CLOCK_MONOTONIC'

### ISSUE THREAD

**Issue by JoshuaPettus** [yquake2/yquake2#239]
I tried building the new 7.02 on OSX and got this.  A quick google says that osx doesn't have it.

**Comment by JoshuaPettus** [comment]
Thank-you!  Sorry it took a few days till I could try it out

Unfortunately It still appears to be in a few places

`/Users/me/yquake2-master/src/backends/unix/system.c:88:2: warning: 
      implicit declaration of function 'clock_gettime' is invalid in C99
      [-Wimplicit-function-declaration]
        clock_gettime(CLOCK_MONOTONIC, &now);
        ^
/Users/me/yquake2-master/src/backends/unix/system.c:88:16: error: 
      use of undeclared identifier 'CLOCK_MONOTONIC'
        clock_gettime(CLOCK_MONOTONIC, &now);
                      ^
/Users/me/yquake2-master/src/backends/unix/system.c:92:17: error: 
      use of undeclared identifier 'CLOCK_MONOTONIC'
                clock_gettime(CLOCK_MONOTONIC, &last);`

**Comment by DanielGibson** [comment]
it should work now in the **osx_clock** branch - the fix is not yet in master, so make sure to use that branch

**Comment by JoshuaPettus** [comment]
Excellent, seems to work.  I approve of your methodology.

**Comment by Yamagi** [comment]
We've just merged the fix into master. It should work now.
