### ISSUE TITLE
Version 7.02 for windows is completly broken.

### ISSUE THREAD

**Issue by LethalManBoob** [yquake2/yquake2#243]
Sound keeps bugging out. Wont even load most of the time. The selection icon flickers with the console spamming the message cannot find mouse_curser # or somthing. 

Downgraded to version 7.01. Everythings perfect.

**Comment by Yamagi** [comment]
Like with most Windows issues I wonder why this doen't trigger on all installations. Two of my Windows machines were okay, just one VM showed the problem... Nevertheless, can you give this binaries a try: http://deponie.yamagi.org/quake2/windows/quake2-7.02a.zip ?

**Comment by LethalManBoob** [comment]
Everything seems to have worked fine for me. No problems so far with the new binaries.

**Comment by Yamagi** [comment]
Nice. I've updated the download link on the homepage to the new binaries. Thank you!
