### ISSUE TITLE
Cant find vorbisfile.h in Vorbis.framework

### ISSUE THREAD

**Issue by JoshuaPettus** [yquake2/yquake2#246]
Normally when compiling using OSX frameworks, it's a bit of headache and I have to resort to all sorts of tricks to make it work (I try not to use dylibs, if I can help it).

It needs to be able to find the header in /Library/Frameworks/Vorbis.framework/Headers

Right now if I have both the Ogg.framework and Vorbis.framework in the system wide location
 I just get when running cmake:
-- Could NOT find OggVorbis libraries

The problem lies with the FindOggVorbis.cmake module.
Unfortunately I'm no expert with cmake so I couldn't say exactly what's wrong.

I did find an alternative module that seems to fix the issue in the Hedgewars repo
https://github.com/hedgewars/hw/blob/master/cmake_modules/FindOggVorbis.cmake

**Comment by Yamagi** [comment]
You can always use the Makefile. That one is much more tested... If that's really a problem someone needs to send a pull request with a fix because neither @DanielGibson nor I have a Mac.
