### ISSUE TITLE
cl_drawfps no longer functional?

### ISSUE THREAD

**Issue by lazycrypt** [yquake2/yquake2#247]
I've noticed that in the 7.02a release of Yamagi Quake II on Windows the command **set cl_drawfps "1"** no longer displays the game's framerate.

It doesn't matter if the command is entered into the config file or directly into the console.

**Comment by Yamagi** [comment]
And if you are entering it without set set into the console, e.g. `cl_drawfps 1`?

**Comment by lazycrypt** [comment]
Right, I should've been more specific. I have it as `set cl_drawfps "1"` in the config.cfg and I am entering `cl_drawfps 1` into the console, though neither option does anything. I'm using the OpenGL 3.2 renderer however it doesn't seem to work on OpenGL 1.4 either.

**Comment by Yamagi** [comment]
Okay, that was a problem with the scaling code. This morning I was unable to reproduce it since my gl_consolscale cvar was set to 1. New Windows binaries with the fix can be found here: http://deponie.yamagi.org/quake2/misc/quake2-4bfd1cb.zip

**Comment by lazycrypt** [comment]
The framerate display is back with the new binaries. I guess this issue can be closed now.

**Comment by Yamagi** [comment]
And another round of new Windows binaries: https://deponie.yamagi.org/quake2/misc/quake2-5447354.zip
