### ISSUE TITLE
Loading Saves

### ISSUE THREAD

**Issue by primecrew** [yquake2/yquake2#250]
You can save a game by simply typing:

save foobar

from the console.

Loading the savegame works like once, but then trying to re-load the same save from the console:

load foobar

doesn't seem to work correctly.

**Comment by Yamagi** [comment]
On what operating system does it happen and what's not working correctly?

**Comment by primecrew** [comment]
Windows 7 64bit Pro.
Using Disconnect FIRST then (re)loading savegame using the

load mysavegame

does work.

So it seems like the game is not receiving the disconnect command from the
load command first or is happening too fast and never received a disconnect
command

**Comment by DanielGibson** [comment]
can you describe exactly what you do when it doesn't work?
are you in the game?
do you go into the menu before opening the console to execute load?
or do you execute it via a keybinding?
do you press pause first?
etc

every step might be important (because we currently are unable to reproduce the problem)

**Comment by primecrew** [comment]
(also your port is looking for all the mcursor-1.pcx, mcursor-2.pcx; when
really they should be m_cursor0.pcx through m_cursor14.pcx in ./pics)
You seem to have a dash that doesn't belong.
For Xatrix, in my video you will not see an error because I created a
custom pak with a copy of the m_cursor pcx files and named them what your
port is expecting.

Appears to happen in baseq2. Also happens in Xatrix.
I can't even get a game to start in baseq2. I have to start it manually
from the console:

coop 0
deathmatch 0
skill 3
map base1

From the menu it won't initialize the game.

I'm attaching a video or 2.

Here's what I'm doing:

>
> Play for a bit.
>
> Goto Console:

save foobar

play for a bit

goto console:

load foobar

sometimes it works, sometimes it doesn't; shows that the server
(game/client) is running, but not really "in the game."

I can record a video for you (see below)

C:\Games\quake2\quake2.exe -nojoy -noipx -nocd +

Is the command to start

OR

C:\Games\quake2\quake2.exe +set game xatrix -nojoy -noipx -nocd +




You can download videos of this behavior:
https://drive.google.com/file/d/0B0OALdTzeCNtT1RObzFIYTNUem8/view?usp=sharing

**Comment by DanielGibson** [comment]
We updated the Windows build about 3 weeks ago to fix some problems, including with not-found cursors due to the dash (which is introduced because of a negative global time, which should never happen).
Can you try http://deponie.yamagi.org/quake2/windows/quake2-7.02a.zip ?

**Comment by primecrew** [comment]
MUCH better.
Works better. I think the only thing is the videos do not play back when
starting a new game (the cinematics). They only play for about 1.5 seconds.
