### ISSUE TITLE
the "dir" command

### ISSUE THREAD

**Issue by primecrew** [yquake2/yquake2#251]
The dir (directory) command needs some documentation.

in Quake2 3.20...

I could:

dir saves/
(or dir saves)

or dir demos

etc.

The syntax doesn't seem to work.  There are many multiple slashes ./\ // and such. What is the proper way to view the savegames of the game you're playing?

dir ./saves/* doesn't work
dir /saves/* doesn't work
dir saves/ doesn't work
dir \saves\* doesn't work

etc.

**Comment by Yamagi** [comment]
It's `dir save/*` :) Some directories may be listed twice. That's expected due to YQ2s complicated search path magic.
