### ISSUE TITLE
ogg music playback stops when using plugin playermodels with custom sounds.

### ISSUE THREAD

**Issue by JoseMengelez** [yquake2/yquake2#252]
when 4+ bots using various player models with custom sounds in a deathmatch the .ogg music begins to stutter then cuts out. Tried with various different player model combinations from all-players.zip (http://tastyspleen.net/quake/downloads/) to ensure the .wav files themselves weren't faulty, same result.  

Deleted custom sounds from playermodel folders and weirdly... same result.

A session with 10 bots using default skins and no custom sounds caused the ogg music to stutter but it never cut out.

Also tried the same bots/playermodels in kmquake2 without issue, the bug appears to be unique to yamagi.

**Comment by DanielGibson** [comment]
can you please tell us what hardware and software (incl. operating system) you're using?

**Comment by JoseMengelez** [comment]
i5 4570 
gtx 1080 
windows 7 (x64)

not experiencing any frame loss (seems capped at 90) and when the music cuts out (more like it gets stuck on a tone) simply toggling disable/enable ogg music in the options temporarily fixes it.

**Comment by Yamagi** [comment]
Hi,
Is that just the onboard soundcard or something special like a SoundBlaster?

**Comment by Yamagi** [comment]
And is that really version 7.02a and not 7.02? 7.02 had a nasty bug that only occured on some Windows installations.

**Comment by JoseMengelez** [comment]
onboard sound on an asus h87-plus

I installed version 7.02a but the console is only showing 7.02.

**Comment by JoseMengelez** [comment]
just tried a fresh install of quake 2 v3.20 and the yamagi 7.02a binaries and loaded up q2dm1 with 10 3zb2 bots using custom player models and the bug is replicable every time within a couple of minutes.

**Comment by Yamagi** [comment]
*hmpf* That would have been too easy... One last question: Can you test with `s_openal 0` followed by an `snd_restart`? That will tell us if Quake II or the OpenAL backend is the problem. There're some bugs with `s_openal 0` but it should work as long you set it in a running game (e.g. a map is already loaded) and don't enter the menu before you reset it to `s_openal 1`.

**Comment by DanielGibson** [comment]
you could also post the beginning of your My Documents\YamagiQ2\baseq2\qconsole.log (with `s_openal 1`), from "------- sound initialization -------" to "----- refresher initialization -----"
so we get some information about the OpenAL version you're using

**Comment by JoseMengelez** [comment]
setting `s_openal ` to 0 and after a `snd_restart` I couldn't replicate the bug. After setting it back to 1 and a further `snd_restart` music malfunctioned almost immediately.

**Comment by JoseMengelez** [comment]
------- sound initialization -------
LoadLibrary(openal32.dll)
...opening OpenAL device:ok
...creating OpenAL context: ok
...making context current: ok

OpenAL settings:
AL_VENDOR: OpenAL Community
AL_RENDERER: OpenAL Soft
AL_VERSION: 1.1 ALSOFT 1.18.2
AL_EXTENSIONS: AL_EXT_ALAW AL_EXT_BFORMAT AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_BFORMAT AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_EXT_SOURCE_RADIUS AL_EXT_STEREO_ANGLES AL_LOKI_quadriphonic AL_SOFT_block_alignment AL_SOFT_deferred_updates AL_SOFT_direct_channels AL_SOFT_gain_clamp_ex AL_SOFT_loop_points AL_SOFT_MSADPCM AL_SOFT_source_latency AL_SOFT_source_length AL_SOFT_source_resampler AL_SOFT_source_spatialize

Available OpenAL devices:
- OpenAL Soft on Speakers (Realtek High Definition Audio)
- OpenAL Soft on Realtek Digital Output (Realtek High Definition Audio)

Current OpenAL device:
- OpenAL Soft

Number of OpenAL sources: 31

Starting Ogg Vorbis.
OGG_LoadPlaylist: could not open playlist: No such file or directory.
20 Ogg Vorbis files found.
Sound sampling rate: 0
------------------------------------

**Comment by Yamagi** [comment]
Thank you. :) I understood what's going wrong. Fixing this is not that easy, though. It'll take several days.

**Comment by JoseMengelez** [comment]
glad to be of assistance and thanks for your patience :)

**Comment by JoseMengelez** [comment]
Issue appears to be completely resolved in 7.03pre build, nice work!

**Comment by Yamagi** [comment]
Cool. Thank you for testing this! :)
