### ISSUE TITLE
[Feature request] Opus codec support for audio track playback

### ISSUE THREAD

**Issue by DarkSwan86** [yquake2/yquake2#254]
Hi,

is it possible to add support for .opus audio along the OGG playback?
It has a better quality/compression ratio and it's already taking the lead as the better open source audio standard for audio playback, surpassing all the competitors (see https://opus-codec.org/ ).

Because it's only a minor improvement on the audio side treat this request as a very low one :)

Thanks!

**Comment by Yamagi** [comment]
This would require a lot of refactoring, we would need some kind of abstraction layer between different audio formats. So no, won't happen until someone sends a pull request.
