### ISSUE TITLE
FPS counter doesn't show up in 7.02a Windows release

### ISSUE THREAD

**Issue by pat0gen** [yquake2/yquake2#255]
I can't get the FPS counter to work in the 7.02a version. Cl_drawfps is set to 1. I checked the previous release and it works fine.

The system is Win7 x64, GeForce GTX 750 Ti, NV driver v384.76. I use 1366*768 resolution, but switching to other resolutions doesn't change anything. Also happens on both the old and the new renderer.

P.S. I've also had some seemingly random crashes on exit, I just can't figure out how to reproduce them :|

**Comment by DanielGibson** [comment]
the FPS counter problem is already fixed (see https://github.com/yquake2/yquake2/commit/4bfd1cb9d401e6d8d94dbdaba49562e665375d19), this will be part of the next release.

we are not aware of crashes on exit, but if you can figure out how to reproduce it we'll look at it of course :)

**Comment by Yamagi** [comment]
New Windows binaries with the fix can be found here: https://deponie.yamagi.org/quake2/misc/quake2-5447354.zip
