### ISSUE TITLE
Issue With OpenAL Disabled/Questions about 7.02 and OpenGL 3.2 cvars

### ISSUE THREAD

**Issue by deuxsonic** [yquake2/yquake2#258]
If s_openal is set to 0, the game will start, but pressing any key to try and open the main menu will cause the game to immediately crash with no mention of a problem in the log files. I'm running it on Windows XP 32-bit. OpenAL has always had some weirdness to it, like sounds being cut off and the volume of things fluxuating when multiple sounds are playing simultaneously and songs skipping or looping too early and the looping of songs causing the game to freeze for a moment.

I've tried to set up the new custom MSYS2 environment for tinkering, but it looks to be the 64-bit version of everything, so nothing works. I have a copy of the full 32-bit version on my system, so I could potentially copy things out of it if someone can let me know what I need to copy. I tried copying just the base executables and just got errors, so I must not have copied enough. Would the current stuff work on the old environment you provided that worked with 5.33?

When OpenGL 3.2 is enabled, do the old values for things like modulation and intensity (one for 2D surfaces as well?) line up with the new (as in creating the same intensity of colors and all that?) How does the value for overbrightbits factor into this? Also, what does particle_fade_factor add? Does retexturing deal solely with potential replacement textures? I've been messing with values trying to get the original look but taking advantage of OpenGL 3.2's better effiency.

**Comment by Yamagi** [comment]
> f s_openal is set to 0, the game will start, but pressing any key to try and open the main menu will cause the game to immediately crash with no mention of a problem in the log files.

That's already fixed and will be part oft the next release.

> I'm running it on Windows XP 32-bit. OpenAL has always had some weirdness to it, like sounds being cut off and the volume of things fluxuating when multiple sounds are playing simultaneously and songs skipping or looping too early and the looping of songs causing the game to freeze for a moment.

Win XP is EOL and no longer suppported. If it still works to some degree that's pure luck.

> When OpenGL 3.2 is enabled, do the old values for things like modulation and intensity (one for 2D surfaces as well?)

Have a look at https://github.com/yquake2/yquake2/blob/master/stuff/cvarlist.md

**Comment by Yamagi** [comment]
New Windows binaries with the OpenAL fix: https://deponie.yamagi.org/quake2/misc/quake2-5447354.zip
