### ISSUE TITLE
Movement weirdness

### ISSUE THREAD

**Issue by deuxsonic** [yquake2/yquake2#261]
When I move, frequently a movement will occur about a second after I am no longer supposed to be moving, as if my movement has been duplicated. I tried turning cl_async off thinking it was that, but it still happens, sometimes more than once.

**Comment by Yamagi** [comment]
You've set cl_maxfps and / or gl_maxfps too hight. cl_maxfps has a useable maximum of about 130 and gl_maxfps must not be higher than 1000. We've added some code to cap them to that values. It'll be part of version 7.10.

**Comment by Yamagi** [comment]
New Windows binaries with these changes can be found here: https://deponie.yamagi.org/quake2/misc/quake2-5447354.zip
