### ISSUE TITLE
Trying to get Gladiator bot running with Yamagi to no avail

### ISSUE THREAD

**Issue by NeonKnightOA** [yquake2/yquake2#264]
First of all, required data:
Yamagi version 7.1.0 pre, compiled from sources
OS - Linux Mint 17.3 Cinnamon (cannot update to 18.x because I use an ATI graphic card)
CC - gcc 4:4.8.2-1ubuntu6

While trying to get Gladiator bot (http://mrelusive.com/oldprojects/gladiator/download.shtml.htm) to work, the program regresses to baseq2 (output: `gamename is baseq2`) and doesn't let me use the mod.

Renaming gladiator/gamei386.so to gladiator/game.so in the pre-compiled Gladiator binaries throws this:
`LoadLibrary ($HOME/yamagiquake//gladiator/game.so): undefined symbol: _isnan`

Renaming gladiator/gamei386.so to gladiator/game.so in the compiled-from-source Gladiator mod (after fixing some errors) throws this:
`LoadLibrary ($HOME/yamagiquake//gladiator/game.so): undefined symbol: min`

In both cases it closes with
`ERROR: failed to load game DLL`

Any idea what I'm doing wrong?

**Comment by DanielGibson** [comment]
I never tried this myself, try the following:
* make sure to create a 32bit build of yamagi quake2 (but if it says undefined symbol instead of completely refusing to load the game.so you probably already did this)
* make sure to use the glibc version of gladiator (**not** libc5)
* make sure it links against libm (`-lm`): in gladiator's linux-386.mk, line 51, you should probably add `$(LDFLAGS)` after `$(CFLAGS)` (after all, LDFLAGS is defined in line 17 and includes `-lm`)

**Comment by NeonKnightOA** [comment]
Indeed, I'm using "7.10" pre, as Mint 17.3 comes with the old 5.21.

I'll try with that.

**Comment by NeonKnightOA** [comment]
Seems that whoever compiled the Gladiator code files forgot to include p_observer.c, which is vital for the mod. Googling it only finds a similarly named file for the DDay mod.
Omitting the file, compiles, but at runtime it outputs this:
`LoadLibrary ($HOME/yamagiquake//gladiator/game.so): undefined symbol: ClientDisconnect`

No luck, then. -.-

**Comment by DanielGibson** [comment]
I got it to build with this patch: [gladiator.diff.txt](https://github.com/yquake2/yquake2/files/1544299/gladiator.diff.txt)
I replaced `_isnan` with `isnan` and replaced min and max with `a < b ? a : b` like constructs and removed some "static" that shouldn't be there etc. and I removed p_observer.o from the makefile

no idea if it works, I didn't build a 32bit yq2 executable to test..

the error about ClientDisconnect is weird, that function is defined in p_client.c, which the makefile seems to use

**Comment by NeonKnightOA** [comment]
It compiles! And works!... somehow. At least it recognizes the mod. I can get to the menu and check the options, and even summon bots, so the mod works well.

Now, and I suppose this isn't Gladiator's or Yamagi Quake2's fault, while building .aas with newer versions of _bspc_ output "aas file is version 5, not 3", with the _bspc_ program provided in the Gladiator page it outputs a segment violation:

```
loaded ./gladiator/maps/base1.aas
(...)
Product:      Yamagi Quake II
Version:      7.10pre
Platform:     Linux
Architecture: i386
Compiler:     4.8.4
Signal:       11

Backtrace:
  ./quake2() [0x80a7f2a]
  ./quake2() [0x80a8108]
  [0xb7768c8c]
  [0xbfc4afb7]
```
The required files for the debug are here, if something is missing tell me: https://www.dropbox.com/s/349wfrabf6r2kux/yquake2.zip?dl=0

_bspc_ is the compiled _bspc_ from https://github.com/bnoordhuis/bspc
_bspci386_ is the pre-compiled _bspc_ from the Gladiator page.

**Comment by DanielGibson** [comment]
> bspc is the compiled bspc from https://github.com/bnoordhuis/bspc

as the page says, it's for Quake3, that's why it outputs a higher, incompatible AAS version.

I don't think we can do anything here, the bspc compiler is closed source, and so is the botlib - if it doesn't work we can't fix it.
And as Mr Elusive sadly passed away this January, I don't think the Quake2 gladiator and bspc code will ever be released.

BTW, the dropbox link doesn't work for me.

**Comment by NeonKnightOA** [comment]
Well, I'll see what can I do.

Thanks for the help and, again, keep up the good work with Yamagi! :)

**Comment by DanielGibson** [comment]
Good luck, let us know if (and how) you can get it to work after all!

**Comment by Yamagi** [comment]
Several years ago I was in contact with Mr Elusive. I asked him if he was willing to release the whole Gladiator source code under GPL but he declined. He mentioned some technical flaws with the closed source parts and wasn't even sure if he still got the rights to it or if they were signed over to id Software and later sold to ZeniMax. He suggested to backport the Quake III Arena botlib. But that would be a lot of work and I din't think that it would be worth the effort.

**Comment by NeonKnightOA** [comment]
Reopening. It turns out the problem wasn't bspc at all! The mod crashes just by spawning a bot, in any map. Here's the output. Try this link for the file: https://www.dropbox.com/s/pnd5wj4db3wta4j/yquake2.zip?dl=0

```
Product:      Yamagi Quake II
Version:      7.10pre
Platform:     Linux
Architecture: i386
Compiler:     4.8.4
Signal:       11

Backtrace:
  ./quake2() [0x80a7f2a]
  ./quake2() [0x80a8108]
  [0xb7735c8c]
  [0xbf802f07]
```

About the Q3 code, leileilol (project leader of OpenArena) told me once that the Q3 AI code is spread between the engine code, the game code and a bot library module. So yeah, it may be a bit complicated to port it. :/

**Comment by NeonKnightOA** [comment]
Closing this issue. I have created a repo for the Gladiator source so we can work directly there.

https://github.com/NeonKnightOA/quake2-gladiator-bot

**Comment by whipowill** [comment]
Did you ever get Gladiator to work?

**Comment by NeonKnightOA** [comment]
Nope. Not at all.
