### ISSUE TITLE
No way to disable HUD

### ISSUE THREAD

**Issue by iriyap** [yquake2/yquake2#265]
Consider adding an option to disable HUD, it's useful when taking screenshots (if you're showing off your new maps online people generally don't care about your health/armor counters) and some people prefer playing HUD-less for some extra immersion.

In the Quake 1 engine games you can usually press "+" ("sizeup") several times to reach the max value of "viewsize" at which point it would turn off all HUD graphics.  This is also done in the Build engine games and probably many others, so it could be a pretty straightforward way to implement this functionality. Failing that, you could add an extra cvar like "scr_draw2d".

**Comment by Yamagi** [comment]
That's already implemented. Just set `gl_hudscale` to 0.
