### ISSUE TITLE
Is gl3_intensity deliberately meant to be equivalent to gl3_overbrightbits?

### ISSUE THREAD

**Issue by rtollert** [yquake2/yquake2#267]
The GL3 backend GLSL fragment shader for lightmap rendering, in [fragmentSrc3Dlm](https://github.com/yquake2/yquake2/blob/master/src/client/refresh/gl3/gl3_shaders.c#L426),
proceeds in part like this:

    void main() {
        vec4 texel = texture(tex, passTexCoord);
        texel.rgb *= intensity;
        void4 lmTex=...
        lmTex.rgb *= overbrightbits;
        outColor = lmTex*texel;
        ... // gamma
    }
Ignoring alpha (which afaik here is irrelevant) this could be rearranged into

    vec4 texel=..., lmTex=...;
    outColor = texel*lmTex*intensity*overbrightbits;
In other words, it seems to me that gl3_intensity and gl3_overbrightbits are doing *literally* the exact same thing. This leads me to suspect that there's some bug floating around here between the intent of these cvars and their implementation. Or am I missing something?

It looks like gl3_intensity does more or less what gl_intensity did in the original source drop, except at runtime and without clamping, so I suppose that's ok. gl3_overbrightbits has no clear analogue.

Since I don't really know the intent that went into the design of these shaders, and the existing behavior is not strictly speaking *wrong*, I don't think I can recommend a specific acceptance criterion for fixing this issue, besides "gl3_overbrightbits probably ought to do something different from gl3_intensity, but gl3_overbrightbits_2d probably still ought to work". One option might be to merely use the inverse of gl3_overbrightbits. Another option might be to hardcode it to 2 (aka one overbright bit) so that the cvar could be removed altogether.

**Comment by DanielGibson** [comment]
In both gl1 and gl3 the overbrightbits are meant to make the lightmap less dark (in gl1 it could only be 1, 2 or 4 IIRC, in gl3 it can have any floating point value).
As the lightmap is just multiplied with the texture, for the lightmap fragment shaders overbrightbits and intensity seem redundant - but you'll notice that several other fragment shaders (e.g. `fragmentSrcAlias` for models and `fragmentSrc3Dsprite[alpha]` for sprites) the intensity is used but the overbrightbits are not.
So removing gl3_overbrightbits would mean that you couldn't make the lightmaps (shadows) brighter without making models (monsters, weapons, items, ...) brighter as well.
