### ISSUE TITLE
[Feature Request] Release Mouse Grab on Console Open

### ISSUE THREAD

**Issue by prg318** [yquake2/yquake2#271]
It would be nice if there was an option to allow the "mouse grab" to be detached when the console is opened.  This is how many modern doom and quake clients behave and it would be nice to be able to have that behavior in yamagi-quake2

EDIT:  Yamagi-quake2 does exhibit the proper behavior in windowed mode.  However, the mouse grab is never released in fullscreen mode.  Since fullscreen mode does not blank out other monitors in a multimonitor setup, it might make sense to also release mouse grab on console open in fullscreen mode as well

**Comment by Yamagi** [comment]
We had this once but there were some problem on Linux with X11. We'll have another look and maybe introduce another variant, maybe `in_grab 3`.

**Comment by Yamagi** [comment]
I've just pushed a commit that implements in_grab 3. As the commit message says: This may be unsafe, especially under X11 the fullscreen window may loose focus and is unable to regain it.
