### ISSUE TITLE
OpenGL 3.2: incorrect gamma

### ISSUE THREAD

**Issue by puleglot** [yquake2/yquake2#272]
The gamma is incorrect in GL 3.2 mode. The environment is too dark and the enemies and a player's hand are too bright. See screenshots below. This is on linux with mesa driver radeonsi, client version is 7.10.

OpenGL 1.4:
![gl1](https://user-images.githubusercontent.com/5680903/34915265-2bafda60-f934-11e7-996b-581cf0cf9a2b.png)
OpenGL 3.2:
![gl3](https://user-images.githubusercontent.com/5680903/34915266-2bdc0766-f934-11e7-95a9-26b2e3478307.png)

**Comment by Yamagi** [comment]
As a general note: Every Quake II renderer (Software, GL1 and GL3) has another look. Other than in modern games the look is highly depended on the render process and even small changes to it can have a huge impact.

But on your screenshot things are looking broken. As you said, the world is too dark and entities are too bright. Can you tell us what Mesa version you're using and try again with an empty / new configuration file to rule out broken settings?

**Comment by puleglot** [comment]
Thanks for the suggestion. Yes, this was caused by gl_modulate setting in my autoexec.cfg (I just copied baseq2 from my old quake2 folder used by another engine). gl_modulate works differently in GL1 and GL3 modes.

**Comment by Tarryem** [comment]
I've run into the same issue on Windows 10 using the latest Radeon drivers and it persists with a fresh install and with a fresh config file

**Comment by iButane** [comment]
Make sure you delete the config files in %userprofile%\Documents\YamagiQ2\baseq2 if a fresh install is what you're going for.

**Comment by Yamagi** [comment]
No reaction for 6 weeks.
