### ISSUE TITLE
Yamagi Quake 2 q2ded.exe gets detected as malware by windows defender

### ISSUE THREAD

**Issue by FragUPlenty** [yquake2/yquake2#274]
dont know why but windows defender detected q2ded.exe as malware and removed it. It was detected as 
Trojan:Win32/Azden.E!cl. I dont actually think I have a trojan on this computer am hoping this was just a false positive.

My computer is running windows 10 home with the latest definitions installed for windows defender as of 1/24/2018

**Comment by FragUPlenty** [comment]
an update I removed all of yamagi quake 2 from my computer then went to the website and windows defender actually blocked the zip file for the windows version from downloading so there is definetly some type of false positive issue.

**Comment by DanielGibson** [comment]
According to https://www.virustotal.com/de/file/c0532423a6f5c3eee290d0d96bfe91c85130d1178ea80906f4cfa460782744ee/analysis/1516798593/ no one (not even "Microsoft" - I guess that's Windows Defender?) detects q2ded.exe from our official 7.10 download as malware

No idea what's happening here - maybe Microsoft has already fixed the issue in the version they have and and you don't have the update yet?
I couldn't reproduce the issue on my Win10 machine (that updated Windows Defender signatures just a minute before I tested)

Did you download via http or https? Try https://deponie.yamagi.org/quake2/windows/quake2-7.10.zip to make sure the you get the unaltered archive

**Comment by DanKorell** [comment]
I just downloaded 7.10 from https://deponie.yamagi.org/quake2/windows/quake2-7.10.zip and when extracting it I got a virus error from Defender. I'm on Windows 10 Home x64 and Windows defender says it got the latest definition file at 24 January 2018 20:00 (36 minutes ago as I type this). The details it gives are as follows:

Trojan:Win32/Azden.A!cl

Alert level: Severe
Status: Quarantined
Date: 24/01/2018

Recommended action: Remove the threat now.

Category: Trojan
Details: This program is dangerous and executes commands from an attacker.

Affected items:
file: C:\Users\dan_k\AppData\Local\Temp\Rar$DRa0.627\quake2\q2ded.exe

**Comment by DanielGibson** [comment]
I had windows update the windows defender definitions again, and still it doesn't find any malware in q2ded.exe - very strange.

Can you tell me the sha256 or md5 checksum of q2ded.exe and quake2-7.10.zip?

**Comment by DanKorell** [comment]
Here's the MD5 checksum I have for quake2-7.10.zip
DC37E56F122E32F949DF35AA90AF7F05

I can't get the checksum for q2ded.exe as it's getting blocked by Windows Defender whenever I try to extract it, and I'm not yet going to add it to an exclusion folder as I'd rather wait for this to be investigated first just in case there is something strange with the file itself.

**Comment by DanielGibson** [comment]
the checksum is correct.

can you upload your quake2-7.10.zip at https://www.virustotal.com/#/home/upload and have them scan it?

**Comment by DanKorell** [comment]
It says no detections.
https://www.virustotal.com/#/file/0165be323184405b2c7e265b61556d6c5a53f27b9f1e57f25edab877748ea1e2/detection

**Comment by DanielGibson** [comment]
Good, thanks for trying!

False positive then - I really have no idea why your windows defender complains about that file and mine doesn't. Fucking snake oil.

**Comment by DanKorell** [comment]
I wonder how many other users get the detection though? FragUPlenty and myself so far, but where it isn't isolated there are bound to be other affected users.

**Comment by maraakate** [comment]
Are you guys on Windows 10?  I have Windows 7 with a laptop that has Windows Defender.  I could try it there.  32-bit or 64-bit?

**Comment by DanKorell** [comment]
Yep, I'm on Windows 10 Home x64 . Version 1709 Build 16299.192. Also, I literally just forced a check for updates on Windows Defender, and it updated definitions at 21:17, and I'm still getting the same trojan detection on q2ded.exe.

**Comment by maraakate** [comment]
I just tested it on Win 7 x64 with latest updates and nothing.

**Comment by FragUPlenty** [comment]
I tried it right now and it still false positives on the q2ded.exe

**Comment by DanielGibson** [comment]
The "Windows Defender Security Center" says that my definitions are 1.261.204.0 from January 24th 2018 19.35:47 (no idea which timezone they use there) - which version do you have?
(sorry I can't tell you how exactly to get there because my windows is German so I don't know the English names of things to click)

**Comment by FragUPlenty** [comment]
antimalware client version: 4.12.17007.18011
Engine Version 1.1.14500.5
Antivirus Version 1.261.204.0
Antispyware Version 1.261.204.0
Network Realtime Inspection Engine Version 2.1.14202.0
Network Realtime Inspection Signature Version 118.2.0.0

**Comment by DanielGibson** [comment]
I have the exact same versions - this really is super weird.

(I also have the same Win10 versions as @DanKorell: Version 1709 Build 16299.192 - but I have Win10 x64 Professional, but this really shouldn't make a difference here?!)

**Comment by DanKorell** [comment]
Just checked my Windows Defender definitions versions. I currently have 1.261.204.0, created 18:35:47 24th Jan 2018.

**Comment by DanKorell** [comment]
![image](https://user-images.githubusercontent.com/31672833/35362551-aea0732c-015d-11e8-88b2-aea93186f5ab.png)

**Comment by DanielGibson** [comment]
Yeah - just to be clear: I totally believe you two.

But I have no idea what to do about it, especially as I can't even reproduce it even though my Windows Defender should be the same as yours :feelsgood:

This is ridiculous - I really wonder how people develop (and support) software for Windows professionally without going insane. 

So.. have you considered trying Linux? :-P
[Ubuntu](https://www.ubuntu.com/) is kinda nice for beginners or [XUbuntu](https://xubuntu.org/) if your system is a bit older.

**Comment by maraakate** [comment]
Are you sure you don't have an actual virus on your machine and it likes to attach to certain files?  Try installing AVG Free or Avast Free temporarily and verify.

**Comment by DanKorell** [comment]
In all likelihood it is just a false positive. After all, it is only this q2ded.exe that is getting this issue, and affecting myself and FragUPlenty. I just so happened to download 7.10 today as I only just found out about it (I was using 7.02a) and got the issue with just the q2ded.exe, so I did a Google search and found this thread created today for the same thing. It just seems way too coincidental.

**Comment by DanKorell** [comment]
I've submitted it to Microsoft as a suspected false positive. Here are the submission details:

https://www.microsoft.com/en-us/wdsi/submission/b3a56fbe-f671-4fea-a095-f4e85a32bf5f

**Comment by DanielGibson** [comment]
Thank you!

Interestingly, it didn't detect any malware (at least in "Current detection")

**Comment by neozeed** [comment]
Im running Windows 10 Pro x64.
Microsoft Windows [Version 10.0.16299.192]

unzipped the quake2-7.10.zip and ran q2ded.exe without any issues....  I even ran a manual scan on the directory.  I have the defender update from 25/1/2018

**Comment by FragUPlenty** [comment]
So I have two laptops both which use windows defender. My Hp x360m netbook detects q2ded.exe as a virus. My acer laptop running windows 10 does not have a problem with it at all. My desktop running eset smart securirty also has no issues at all with it

**Comment by DanielGibson** [comment]
Now the "Final determination" for all files is "Not Malware" - does it help? Does Windows Defender shut up for you now?

**Comment by DanKorell** [comment]
Woot! Just updated my Windows Defender definitions (it's now on 1.261.244.0) and it no longer detects q2ded.exe as a trojan. It must have been a false positive detection that was for some reason only affecting Windows 10 Home, rather the Professional. Weird, but it seems to be solved now.

**Comment by DanielGibson** [comment]
Yay. Hopefully they don't fuck this up again when we release the next version..

Thanks everyone for reporting, testing etc!

**Comment by Ivan-Kouznetsov** [comment]
Just want to report that at the time of writing Avast will sometimes detect as malware and delete yquake2.exe. It falsely detects it as "IDP.Generic" , so in case anyone runs into this issue you can go to Protection > Virus Chest > then select Restore and add Exception

**Comment by DanielGibson** [comment]
according to https://forum.avast.com/index.php?topic=234761.0 one can report false positives in avast at
https://www.avast.com/false-positive-file-form.php
might be worth a try?

of course it sucks if that needs to be done for every new release, no idea if they actually fix their detection or just whitelist the specific executable

**Comment by Ivan-Kouznetsov** [comment]
I found out the reason Avast detects it as malware: it's the fact that it deletes stdout.txt in the Documents folder, so perhaps saving stdout.txt in the same directory as the executable is worth considering.

I also reported it as a false positive.

Hope that helps, great project by the way, I wouldn't be able to run Quake 2 on Windows 10 if it wasn't for Yamagi Quake II.

**Comment by DanielGibson** [comment]
> I found out the reason Avast detects it as malware: it's the fact that it deletes stdout.txt in the Documents folder

Interesting - it's rare that you actually get that kind of information!

> so perhaps saving stdout.txt in the same directory as the executable is worth considering.

The executable directory might not even be writable by the user (that's a problem a user ran into with dhewm3)..

Not sure how to fix this.. they probably expect programs to use the application data folder and not Documents/ for this, but we don't want to use that because it's hidden by default (IIRC?) so users would have trouble finding their screenshots, savegames, configs and, in also the stdout.txt if they want to report a bug...

**Comment by Ivan-Kouznetsov** [comment]
What about saving it to the Windows Temp folder (that is %TEMP%, ex: C:\Users\UserName\AppData\Local\Temp)?

**Comment by DanielGibson** [comment]
that's even harder to find
