### ISSUE TITLE
Crash on startup if software render selected

### ISSUE THREAD

**Issue by iButane** [yquake2/yquake2#280]
For some reason the game always crashes on startup when the software render is enabled regardless of resolution.  I have to go into config.cfg and remove the line 'set vid_renderer "soft"' so it'll start on the default GL Render and then switch it to software mode.

I'm using Windows 7, 64bit with a 1060 GPU.  Also, I disabled Nvidia overlay in case that was causing the issue.

![1](https://user-images.githubusercontent.com/20784457/36769396-09de8606-1c12-11e8-93af-3413141828e9.jpg)
![2](https://user-images.githubusercontent.com/20784457/36769400-0bc82cd8-1c12-11e8-9bc9-ac5ca93d2e25.jpg)

**Comment by 0lvin** [comment]
What version/commit do you use?

**Comment by DanielGibson** [comment]
I think he's using the latest Windows binaries (based on current Git status) from https://deponie.yamagi.org/quake2/misc/quake2-54f3b1b.zip

**Comment by 0lvin** [comment]
Code already had some fix for similar error 80616a418eeca176c07980be343316a82a0099ca, so maybe its already fixed if he has used version before fix from #275. 
I don't have windows so can't directly check it for now, i will try to reproduce error on linux.

**Comment by iButane** [comment]
Yeah, that's what I'm using. Fresh install.

**Comment by 0lvin** [comment]
Have you used quake2-54f3b1b.zip(from 2018-Feb-13 07:42) or quake2-ed54fe2.zip(from 2018-Feb-27 18:21) ?

**Comment by iButane** [comment]
I haven't tried those yet. I'll give them a shot tonight

**Comment by DanielGibson** [comment]
Oh damn, looks like I accidentally tweeted (and posted above) the wrong link to outdated binaries :-/

The most recent ones (based on the latest git commit) are https://deponie.yamagi.org/quake2/misc/quake2-ed54fe2.zip

Sorry!

**Comment by iButane** [comment]
Ok, I just tested with those latest binaries and it fixed the issue!
