### ISSUE TITLE
Software Render Glitching

### ISSUE THREAD

**Issue by iButane** [yquake2/yquake2#281]
Been testing out the software render... So far I've only noticed this 1 issue where the train model/texture glitches but only on higher resolutions.  
![20180303230925_1](https://user-images.githubusercontent.com/20784457/36942505-aa0bbd2e-1f41-11e8-89f1-bd340012786f.jpg)
![20180303230930_1](https://user-images.githubusercontent.com/20784457/36942506-ab53aaa2-1f41-11e8-8f92-61fb94b24efc.jpg)
After the train moves the issue is no longer there regardless of resolution.

Short video clips..

Before train moves: https://youtu.be/fA9_KGhoeTQ
After: https://youtu.be/6DEraxagW3U

**Comment by DanielGibson** [comment]
@0lvin can you take a look at this as well? :)

**Comment by 0lvin** [comment]
I will look.

**Comment by Yamagi** [comment]
Is there any progress in fixing the missing surfaces?

**Comment by 0lvin** [comment]
@Yamagi I have solutions for train, i am working on clean up changes. I am going to create pull request in week.

**Comment by Yamagi** [comment]
Cool! That's very good to hear!

**Comment by maraakate** [comment]
@0lvin I'd imagine, but didn't look too hard that raising the surf/edges limits fixed it?  I've ran into this problem before on large maps and high resolutions.

**Comment by 0lvin** [comment]
@maraakate We already allocate buffers on render init, so code will rellocate buffers in case "too small" and we will always will have enough space for any map size or count of vert's.

**Comment by maraakate** [comment]
OK.  But was that related to the problem with the disappearing surfaces?  I saw you redid some code related to it.  I totally forgot about that being such a thing in the original ref_soft (it was a CVAR originally) and would cause this type of problem.

**Comment by 0lvin** [comment]
Yes, you are fully right, surfaces disappeared because no space for it in buffers. 

Now you can run ```noclip``` and see full map at once. Also it fixed issues in other games where map have big free space levels.

**Comment by maraakate** [comment]
ref_gl has a similar problem with a max drawing distance if I remember correctly, but it's only relevant to huge "boomed" ports and probably not worth investigating for yq2.

**Comment by Yamagi** [comment]
This was fixed with version 7.30.
