### ISSUE TITLE
OSX yquake2-7.20 build

### ISSUE THREAD

**Issue by JoshuaPettus** [yquake2/yquake2#282]
Hi, I made another build for OSX 10.11+ with the latest 7.20 release.  I also put in new framework libraries with the latest SDL2 2.0.8 and OpenALSoft 1.18.2  for good measure.

https://www.dropbox.com/s/rj0n9ag35dby82q/yquake2-7.20-OSX-10.11%2B.dmg?dl=0

regards

**Comment by Yamagi** [comment]
I've uploaded the file to https://deponie.yamagi.org/quake2/osx/yquake2-7.20-OSX-10.11+.dmg. Thank you!
