### ISSUE TITLE
scale particles w/ resolution in software mode

### ISSUE THREAD

**Issue by buvk** [yquake2/yquake2#284]
![q2_0000](https://user-images.githubusercontent.com/2666951/37865962-06c7a172-2f41-11e8-9a03-877ec5e6b3b1.png)

when running software mode at a high resolution, particles from explosions/weapons look too big.  would it be possible to add a feature to reduce their size?

**Comment by DanielGibson** [comment]
@0lvin can you take a look at this? :)

**Comment by 0lvin** [comment]
@buvk Could please you check changes in #285 ?

**Comment by buvk** [comment]
Is there somewhere I can download a windows binary to test this?

**Comment by DanielGibson** [comment]
that branch has been merged, so this can be closed.
Thanks again!
