### ISSUE TITLE
Video offset at start of game

### ISSUE THREAD

**Issue by socketbox** [yquake2/yquake2#288]
I'm on macOS Sierra (10.12.6). The game runs beautifully, but it starts with the video at an offset from the top of the screen by roughly 55px (see black bar outlined in red at top of attached image).

If I toggle resolution options back and forth, I can fix the issue for that particular invocation of the game. By "toggle" I mean do the following:

1. Video -> enable _switch resolution_ ->  apply
2. Video -> enable _keep resolution_ -> apply
3. Video -> enable _swith resolution_ -> apply

... and the offset vanishes and player stats/vitals are visible.

Here's part of the logging that is displayed at the startup of the application:

```
----- refresher initialization -----
LoadLibrary(ref_gl3.dylib)
Byte ordering: little endian

Refresh: Yamagi Quake II OpenGL3 Refresher
Client: 7.21pre

Refresher build options:
 + Retexturing support

SDL version is: 2.0.8
SDL video driver is "cocoa".
setting mode 21: 1920 1080
Got 8 bits of stencil.
Successfully loaded OpenGL function pointers using glad, got version 4.1!

OpenGL setting:
GL_VENDOR: ATI Technologies Inc.
GL_RENDERER: AMD Radeon HD 6750M OpenGL Engine
GL_VERSION: 4.1 ATI-1.51.8
GL_SHADING_LANGUAGE_VERSION: 4.10
GL_EXTENSIONS: GL_ARB_blend_func_extended GL_ARB_draw_buffers_blend GL_ARB_draw_indirect GL_ARB_ES2_compatibility GL_ARB_explicit_attrib_location GL_ARB_gpu_shader5 GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_occlusion_query2 GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_subroutine GL_ARB_shading_language_include GL_ARB_tessellation_shader GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_texture_storage GL_ARB_texture_swizzle GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_texture_compression_s3tc GL_EXT_texture_filter_anisotropic GL_EXT_texture_mirror_clamp GL_EXT_texture_sRGB_decode GL_APPLE_client_storage GL_APPLE_container_object_shareable GL_APPLE_flush_render GL_APPLE_object_purgeable GL_APPLE_rgb_42Loading shaders succeeded!

Successfully loaded ref_gl3.dylib as rendering backend
```

Any idea why this is happening and how I can fix it?

![screen shot 2018-03-28 at 1 54 15 am](https://user-images.githubusercontent.com/1593835/38011963-85fd1046-322d-11e8-82a8-123b625a89c9.png)

**Comment by Yamagi** [comment]
So the "problem" is that the requested video mode is not available. SDL or the OS switch to a higher mode and SDL places the OpenGL viewport at the bottom left. That's kind of expected, Windows and Linux with X11 do the same. The only difference is that 1920x1080 is usually available... I don't think that there's much to do on Quake IIs side. The easiest work around is to use a supported resolution.

**Comment by maraakate** [comment]
I don't remember, but does YQ2 have a resolution setting?  It may be possible it's failing and rounding up to the next available mode.

**Comment by Yamagi** [comment]
I just had another at the code, it looks correct and is working on all other platform. I don't thing it's a problem on Quake IIs side. Just use the native resolution... If this really needs a fix someone with a Mac need to look into it and send a pull request.
