### ISSUE TITLE
100% CPU with Ubuntu Linux 16.04

### ISSUE THREAD

**Issue by plittlefield** [yquake2/yquake2#291]
Is there a way to see what's using 100% CPU or a debug log when running the game in XUbuntu?

Is there a different graphics renderer I can try?

It seems to run OK but my laptop fans go full blast and I'm concerned that it's not right...

Thanks,

yamagi quake2: 5.32
video resolution: 800x600
ubuntu linux: 16.04.4
kernel version: 4.16

**Comment by Yamagi** [comment]
Hi,
version 5.32 is rather old and missing a lot of bugfixes. Can you try an up to date version?

**Comment by plittlefield** [comment]
Yes, can do.

I am using the 16.04 repo and it's pulled in 5.32 without a custom PPA.

Is there a PPA I can use to get the latest version, or .deb file for the 2 latest packages?

Cheers.

**Comment by plittlefield** [comment]
Actually, I've just spotted the **compile from source** option, so doing that now :-)

**Comment by plittlefield** [comment]
Yay, problem solved!

Version 7.20 has fixed the 100% CPU usage.

Many thanks, and keep up the great work.

:-)

Paul

**Comment by DanielGibson** [comment]
Great, have fun! :-)
