### ISSUE TITLE
Underwater rendering in soft renderer broken in non 4:3 resolutions

### ISSUE THREAD

**Issue by DanielGibson** [yquake2/yquake2#292]
![q2_0073](https://user-images.githubusercontent.com/1216493/39095569-f0c9353e-4642-11e8-9df9-f9b5597025c0.png)
![q2_0074](https://user-images.githubusercontent.com/1216493/39095570-f0dfda46-4642-11e8-9dcc-30ade4c8898b.png)
The bars at top/bottom of the screen are not supposed to be there (at least they are not in 4:3 resolutions)

@0lvin can you take a look at this? :-)

**Comment by iButane** [comment]
I'm guessing this was his way of fixing (bypassing),the underwater crash at higher resolutions. If you lower the res the bars disappear. I think it's one of those gamebreaking bugs that is impossible to fix.

**Comment by 0lvin** [comment]
#293 Possible fix for warp. I am going also to fix "train" disappear bug #281, but have not finished yet.

**Comment by Yamagi** [comment]
This should be solves with the merge of pull request #293.
