### ISSUE TITLE
Music won't start playing until changing it's quality

### ISSUE THREAD

**Issue by fuzunspm** [yquake2/yquake2#296]
Yamagi: 7.20 with 3.20 patch
OS: macOS 10.13.4
Quake2: GOG quake 2 quad damage

Everything works perfect except music. It won't start playing until i change music quality from options menu back and forth every time it loads a level

**Comment by Yamagi** [comment]
This may be the same as issue #270. But still no clue what's causing it.

**Comment by Yamagi** [comment]
Is this still the case with our latest release 7.30? It had a lot of changed to the OGG stuff.
