### ISSUE TITLE
quake2.exe  wrapper and yquake2.exe not well documented.

### ISSUE THREAD

**Issue by fragmental** [yquake2/yquake2#297]
I'm using the prebuilt windows binaries and was confused about there being two quake executables, quake2.exe and  yquake2.exe.  Eventually I had a look at the code, and I see the quake2.exe is a just a wrapper for yquake2.exe.  That makes sense.  I just wish that had been documented in some sort of readme or something so I wouldn't have had to look at the code to find that out.  The prebuilt binaries don't have any sort of documentation in the zip file, at all.

**Comment by Yamagi** [comment]
Hi,
you're right, that should have been documented. I've added it to the README.md. 

>  The prebuilt binaries don't have any sort of documentation in the zip file, at all.

For release builds the documentation is included in the doc\ subdirectory. :)

Regards,
Yamagi
