### ISSUE TITLE
 (Feature request) color lighting in software renderer

### ISSUE THREAD

**Issue by AcceptableSpare** [yquake2/yquake2#298]
Is this even possible? I'm guessing no because of the color depth and possibly having to rewriting it, but I thought I'd ask anyway. 

edit: Mistakes ahoy. Btw I know it's not useful either I just like the way software based 3d engines look

**Comment by DanielGibson** [comment]
no, it's not.
but you can make the GL renderers look more like the software renderer with by setting
`gl_texturemode GL_NEAREST_MIPMAP_NEAREST`
and (in the GL3 renderer only)
`gl3_particle_square 1`

**Comment by AcceptableSpare** [comment]
Thank you for the tips, I'll close this then since it's not possible
