### ISSUE TITLE
dedicated server high cpu load

### ISSUE THREAD

**Issue by SiemensSchuckert** [yquake2/yquake2#299]
Version 7.20 uses much more CPU ( compared to 7.10 )
no clients connected, server on Ubuntu 16.04.3
q2ded 7.20 takes ~16%
q2ded 7.10 ~2%

![q2dcpu](https://user-images.githubusercontent.com/35631785/40267450-1ae27fc4-5b65-11e8-8afb-5324b14b24a2.png)

**Comment by Yamagi** [comment]
That's expected. You can set the `busywait` cvar to 1 to revert to the old behaviour. Busy waiting is somewhat imprecise, but at the server side of things it's not that bad.
