### ISSUE TITLE
Would yquake2 work with gladiator bot on OSX?

### ISSUE THREAD

**Issue by stefanhendriks** [yquake2/yquake2#305]
I can run Yamagi Quake 2 fine without the gladiator bot game. I tried extracting the `gladiator` game into my quake 2 folder. Booting up with `+game gladiator`. The console says it is running `game gladiator`. Yet, any commands I try to execute from that mod are not recognised. I tried the `dll` and both linux distributions offered by the download page of Gladiator.

I was wondering if there was any feedback when loading of a game goes wrong, or perhaps I do something wrong?

**Comment by DanielGibson** [comment]
the game.dylib (OSX equivalent of game.dll/game.so) for gladiator, which implements the commands, is missing.

as the gladiator bot source code is not available, unfortunately it can't be created either

**Comment by DanielGibson** [comment]
clarification: the gladiator game source is available at http://mrelusive.com/oldprojects/gladiator/download.shtml.htm, but it needs the bot DLL/lib whichs source is not.
your best chance of using the gladiator bot on OSX may be running the windows version with wine/crossover mac

**Comment by stefanhendriks** [comment]
thx for responding. Yes, I figured it was missing its OSX 'dll' (ie `dylib`). I was able to run the game with gladiator using `wine`. 

Too bad the bot source is not available. Thx for the heads up and the quick reply.

**Comment by Yamagi** [comment]
Last autumn I've put some effort in making 3zb2 somewhat 64 bit compatible. I've just pushed that branch to Github: https://github.com/yquake2/3zb2 I don't know how good it works in praktise, but it was stable enough to do some exaustive testing of our network code.

**Comment by NeonKnightOA** [comment]
The best thing we can do about gladiator is to backport the Q3A library to Q2. Unfortunately the botcode in Q3A is divided between the engine and the gamecode (well, kind of like Q2 Gladiator, split in two libraries...).

I have uploaded it to a gladiator-dedicated repository, but haven't had much luck with anything I've tried: https://github.com/NeonKnightOA/quake2-gladiator-bot/tree/master/source/q3botlib
