### ISSUE TITLE
Chat cursor blinking in the wrong spot

### ISSUE THREAD

**Issue by LucidusAtra** [yquake2/yquake2#306]
When I have the UI scaled to anything beyond 1x, any time I try to say anything in ingame, the blinking chat cursor appears next to the wrong line. It should appear next to the line I'm typing. In fact, it actually blocks any text that appears behind where it's blinking.
![quakebug](https://user-images.githubusercontent.com/24499862/41683311-19900fd6-748f-11e8-804b-9fa1afdd93ad.jpg)

**Comment by Yamagi** [comment]
This was a stupid typo. The scaling factor was added upon the chat cursors vertical offset and not multiplied with it. I've just pushed a fix. Thank you for the report!
