### ISSUE TITLE
Strogg Behaviour.

### ISSUE THREAD

**Issue by flesh420** [yquake2/yquake2#307]
When I use this source port the monster AI is just plain weird, constantly getting stuck on geometry and running in spot.  I'm using the latest version.

**Comment by Yamagi** [comment]
Hello,
I just hade a look and for me the AI is just working as expected. With both the latest release and the git HEAD. Can you give us some more information? On what platform are you playing? And can you describe or even better screenshot a place were a moster get's stuck?

**Comment by flesh420** [comment]
I tried to take multiple screenshots but it shoots my desktop, for some reason, not the game.
I hesitantly say it has something to do with me looking at an enemy, because it seems if I turn away from them while they're active (noticed me) occasionally they act bizarre when I look at them again.  
They seem to get stuck between tight spaces of geometry and on ledges.  On ledges instead of hitting the ledge and running a different direction for a second, they just run in place.  And do the same on like corners and stuff.

**Comment by DanielGibson** [comment]
The game has an integrated screenshot feature that should work, I think it's bound to F12 by default.
The screenshots should be saved in `My Documents/.yq2/baseq2/screenshots/`

**Comment by Yamagi** [comment]
Ah, the screenshots are very helpful. Thank you! I was on wrong track and suspected an AI bug, but after some testing I'm pretty sure that it's another weird softrenderer problem. For example the testcase in base1 is fairly easy to reproduce with the softrenderer, but not with GL3. And as soon as the guard crosses the area portal at stairs he suddenly reappears. 

@0lvin, can you have a look at it?

**Comment by DanielGibson** [comment]
To be sure, can you try if the bug really doesn't happen with the GL (1 or 3, shouldn't matter) renderers for you, @flesh420? 

If GL works better for you, I'd suggest using the GL3 renderer with `gl3_particle_square` set to `1` and `gl_texturemode` to `GL_NEAREST_MIPMAP_LINEAR` - it should look almost the same as the soft renderer.

**Comment by flesh420** [comment]
Those shots were from using GL1.


These are shots from gl3, but here's two things I've found.  Though I can't get them to act weird when breaking sight.  But these two are stuck, and I don't recall the one being stuck there with GL1.

![stillstuck](https://user-images.githubusercontent.com/6542008/42790104-1ac796aa-8937-11e8-8d5f-ec57f00857f2.jpeg)
![alsostuck](https://user-images.githubusercontent.com/6542008/42790108-1d92410a-8937-11e8-95b9-434c2a768c2f.jpeg)

**Comment by DanielGibson** [comment]
Some of the monsters (incl. the ones you're showing in the latest screenshots, I think) are supposed to remain at their spot. As long as they shoot at you it's ok.

Good to know that the software renderer is not to blame on this bug.

BTW, those ".jpeg" files you posted are actually TGAs (and thus Firefox can't display them) - something must have gone wrong with converting them ;-)
YQ2 can create jpeg screenshots itself (and also png), try `unbind F12` and then `bind F12 screenshot jpg` (or `bind F12 screenshot png` if you prefer PNGs) - afterwards F12 should write JPEGs (or PNGs) instead of TGAs.

**Comment by flesh420** [comment]
![q2_0002](https://user-images.githubusercontent.com/6542008/52156998-e22c2700-2659-11e9-9a24-583a73cbbe23.jpeg)


Hi.  I just got into Q2 again and can confirm that strogg being stuck persists.  I waited to post until I played for a while.  And I'm still using the Gl3 renderer.  I can confirm that this behaviour doesn't happen in other ports.  It's weird because if you shoot them when they're stuck and at a distance, they'll come toward you, but generally if you go around a corner where they have no sight they'll just run in spot after they've seen you.

The screenshot in question he's just running in spot after I shot at him once.

**Comment by Yamagi** [comment]
And I've finally understood the problem and managed to reproduce it. This is the key:

> but generally if you go around a corner where they have no sight they'll just run in spot after they've seen you

When the player and the monster are in different areas, the monster will find the player within seconds when playing with the original game.dll. In YQ2 they'll finally find the player but it'll take a while. That won't be easy to debug...

**Comment by Yamagi** [comment]
I took a deep look at the ai code and didn't find any obliviously differences between Vanilla Quake II and Yamagi Quake II. I'm afraid that I need some more information. I recorded a video of base2 (In window mode because AMDs crappy video driver can't record fullscreen OpenGL applications): https://deponie.yamagi.org/temp/q2_issue_307.mkv It's about 70MB. 

Does it show the enemy behavior that you're seeing?

**Comment by flesh420** [comment]
Okay.  I've figured out what it is and it's not a problem with your code.  The problem only occurs when using Coop or Die mod.  I just replicated your video with and without the mod and it's clear the problem lies with the mod.  

Lol I'm sorry for wasting your time.
