### ISSUE TITLE
Software Renderer suggestion

### ISSUE THREAD

**Issue by donizettilorenzo** [yquake2/yquake2#311]
-> https://github.com/qbism/Quake2-colored-refsoft

**Comment by Yamagi** [comment]
There's no point in it. You can get the look and feel of the software renderer with our OpenGL 3.2 renderer. It's much faster than the software renderer, it already has colored lighting and it's able to render the game without flickering or disappearing surfaces.

When we accepted the pull request of the software renderer last year we thought about it as an experiment. It has flaws but maybe, just maybe the community would be able to fix them. Until now there hasn't been much progress with that. It still has the surface problem, it still crashes sometimes and the code still looks horrible.  
If no one steps up and fixes it, we'll remove it again after the next release. Instead we'll add uncolored lighting to GL3 (and maybe GL1) and provide a "looks like the software renderer" profile through the menu.

**Comment by maraakate** [comment]
Plus, those coloured software renderers are horribly unoptimized.  They run terrible even on modern systems.

**Comment by DanielGibson** [comment]
I'd suggest using the GL3 renderer with `gl3_particle_square` set to `1` and `gl_texturemode` to `GL_NEAREST_MIPMAP_LINEAR` - it'll look like a soft renderer with colored lighting then :)
(We should add this to the README or sth)

**Comment by DanielGibson** [comment]
It'll look like this:
![q2-pseudosoft](https://user-images.githubusercontent.com/1216493/43084308-b6ead2c0-8e98-11e8-8469-2c837d964f94.jpeg)
