### ISSUE TITLE
Gl1 rendering error

### ISSUE THREAD

**Issue by Bathory1313** [yquake2/yquake2#312]
I thought it was something went wrong in the installation but is not, is something about rendering...

![screenshot_101](https://user-images.githubusercontent.com/41602800/43113705-cb9e2436-8ed1-11e8-99ec-46387bd06c72.png)

**Comment by DanielGibson** [comment]
Hi,

Please try starting the game not from steam but from the installation dir (just in case Steam screws something up there).

If that doesn't help, please tell us the contents of `My Documents/YamagiQ2/stdout.txt` and `stderr.txt` in the same directory.

**Comment by Bathory1313** [comment]
i tried from the exe but didnt work  but i found what makes the error on stdout.

https://imgur.com/k4oj8PR

https://imgur.com/ZI2y3Nj

the stderr.txt says the same error message from the image

**Comment by DanielGibson** [comment]
Ok, what version of windows do you have, what GPU (graphics card), what driver version?

And next time please post logs as text; note that github allows you to attach files (incl. images and text files) to comments :)

**Comment by Bathory1313** [comment]
should i share my dixdiag here?

**Comment by Bathory1313** [comment]
the problem to update my graphics driver is my enemy... windows 10!

i cant find the driver from my specific graphics card on windows 10 (maybe should i try install but the page says for windows 7 and 8 but idk maybe screws my PC). i guess is old... very old because is from the 2nd generation of graphics card acording to microsoft

**Comment by DanielGibson** [comment]
Wow, that really sucks!
So the problem is that apparently Intel doesn't provide a driver for Win10, and the driver that Microsoft provides (via Windows Update or whatever) doesn't properly support OpenGL (which we need).
In this thread someone seems to have the same problem, and possibly a solution: https://communities.intel.com/thread/120032 (a video is mentioned that is supposed to explain what to do)

If that doesn't work out, you could go back to Win8.1 or Win7 - or switch to Linux, which has a driver that supports OpenGL 3.3 for Intel HD 2000 and HD 3000.

**Comment by DanielGibson** [comment]
Oh, another idea: you could try using the software renderer. It's still a bit buggy but better than nothing I guess!
To use it, start the game with the commandline arguments `+set vid_renderer soft`

**Comment by svdijk** [comment]
I suppose it would be good to make yquake2 fallback to the software renderer if neither the gl3 nor the gl1 renderer can be loaded as well?

**Comment by Yamagi** [comment]
Yes, it's already on my list. In the last few days I've removed SDL 1.2 and I'm now in the process of refactoring the whole client <-> renderer interaction. The client side SDL stuff is done, the renderer side is next. After that vid.c will require some love:

* Clean fallback in case of error: GL3 -> GL1 -> Soft
* Remove the implicit vid_restart in some cases. It's annoying, inconsistent and unreliable.
* Don't abuse vid_fullscreen to communicate changes to the renderer options. I suspect that this hack is part of the fullscreen problems.

The work (unfinished and untested) can be found in the sdlremoval branch: https://github.com/yquake2/yquake2/tree/sdlremoval

**Comment by DanielGibson** [comment]
This change should be part of the latest release (7.30).

@Bathory1313 Can you try if it works for you? Does it use it automatically use the software renderer now? You can download it at https://deponie.yamagi.org/quake2/windows/quake2-7.30.zip
