### ISSUE TITLE
Music loop issue

### ISSUE THREAD

**Issue by MCHDaniel** [yquake2/yquake2#319]
Whenever a music track is about to finish, it cuts right off before looping again. This issue seems to be present only when "s_openal" is set to "1". Happens in the official mission packs as well. The tracks themselves (GOG version) play fine outside the game. Using the precompiled Windows binaries, version 7.21.

Video of the issue:
https://drive.google.com/open?id=1uwP6SPfw6OozzJLpCoy2-B8StnDKc8Ox

**Comment by Yamagi** [comment]
Hi,
You're right. We're flushing the playback queue as soon as we read the last samples from the input file. So we're never player the last ~12 seconds of a file. A possible fix is here: https://github.com/yquake2/yquake2/tree/issue319

Thank you for the the report! :)

**Comment by MCHDaniel** [comment]
You're welcome. Thanks for your help!
