### ISSUE TITLE
Disappearing gibs

### ISSUE THREAD

**Issue by StepanST** [yquake2/yquake2#323]
Hello. I see? there is some new gib life system. So gibs can be destroeyd by explosions and bfg10k. But when you gib enemy with rocket louncher or grenade louncher or witn another explosive weapon, gibs destroys right after they had spawn, so you can see only head and no another gibs. But when you gib someone with super shotgun, gibs spawn right. It will be great, if there will be some cvar, that allows you to disable new gib system, and play with vanilla gib system. You guys do great job. Thank you,

**Comment by Yamagi** [comment]
I've just rebased the fix to master. It'll be part of the next release. Thank you!
