### ISSUE TITLE
Crash in Sonic Mayhem mappack

### ISSUE THREAD

**Issue by AtifArshad1995** [yquake2/yquake2#324]
Hi Dev(s), have encountered a serious gamebreaking bug/crash when playing "Sonic Mayhem mappack". 

https://www.youtube.com/watch?v=LQBhZHZGIeM
For some reason whenever i try to go towards the path shown at 22:53 in video, my game crashes to desktop. I am using Yamagi Quake 7.21. I think this issue could be related to memory because this mappack is very very detailed.

EDIT: I just tried with Yamagi 7.30 and it still doen't work. Infact it now freezes and i cannot close it and i am forced to restart.

**Comment by AtifArshad1995** [comment]
The map pack can be downloaded from the description in the video i posted

To make things quicker for u i have attached my save game folder.
[save2.zip](https://github.com/yquake2/yquake2/files/2384169/save2.zip)

Additionally my pc specs are:
-Dell Inspiron 5570
-Windows 10 64-bit
-4 GB ram
-AMD radeon 530 (driver version 18.5.1)
-Intel core i5-8250U (1.6 GHz)

**Comment by jlanzobr** [comment]
Yamagi Quake 2 version 7.30 also crashes when loading the third map from Sonic Mayhem, tech3.

**Comment by 0lvin** [comment]
Could you check with fabda9ba3bc781f59100340ca383678f3bead7ac from #332?

It should fix load maps with 32k+ marksurfaces.

**Comment by AtifArshad1995** [comment]
@0lvin Thank you 0lvin, unfortunately i cannot test it as i don't have the tools (and maybe even the skills) to compile the source. Can u test the mappack whether it was crashing before and whether it is working now. Alternatively u can provide the compiled version to my mail at atifarshad1011995@gmail.com

@jlanzobr In my case the tech3 map does not crash at startup but that same map crashes after trying to go to a particular area (which i posted in my original comment).

**Comment by Yamagi** [comment]
A set of Windows binaries build from @0lvins Branch can be found here: https://deponie.yamagi.org/quake2/misc/quake2-0lvin-fabda9b.zip

**Comment by AtifArshad1995** [comment]
@Yamagi Thank you for providing compiled build. The game is no longer crashing for me. Now i will go on to complete sonic mayhem.👍

@jlanzobr can u try if it is working fine for u.

**Comment by Yamagi** [comment]
I've merged the pull request, the fix will be part of our next release.
