### ISSUE TITLE
[Feature suggestion] .ent/.override support.

### ISSUE THREAD

**Issue by NeonKnightOA** [yquake2/yquake2#328]
I've been trying to add this functionality to yq2, but I haven't had much success yet.

The idea is simple: r1q2 had support for .override files (normally .ent files), which are plain text files containing all of the entities on a map, and could be used to do trivial things such as modify, remove or add entities on a map (for example add CTF support or rogue/xatrix weapons to non-CTF/rogue/xatrix maps) without having to directly decompile/modify the map itself.

From what I saw just by looking at the code, the change was done in the **CM_LoadMap** function (in the file **common/collision.c** in yq2; in the file **qcommon/cmodel.c** in r1q2) but r1q2 also added another function called **CM_MapWillLoad** (right before CM_LoadMap) which also reference the .override files. However trying to port this function was not a good idea, as the code is very different in both r1q2 and yq2 and r1q2's CM_MapWillLoad function is also referenced in other parts of the r1q2 code.

Is there something I'm missing?

**Comment by maraakate** [comment]
https://bitbucket.org/neozeed/q2dos/annotate/master/qcommon/cmodel.c?fileviewer=file-view-default#cmodel.c-535

**Comment by NeonKnightOA** [comment]
Thano you! It helped a lot. Now adding the pull request, ofc it's open to changes.
