### ISSUE TITLE
Software mod large resolution problems

### ISSUE THREAD

**Issue by StepanST** [yquake2/yquake2#330]
Hello, found some new small issues. In large resolution waterwarp cicle is wrong. Like in 640x480 you have normal wavelength of waterwrap, but  then larger the screen resolution, then less wavelength of waterwrap. And in large resolution in software mode particles size is biger then they must be on average distance, but i think, that it is a default quake 2-1 software mode problem. Thanke you.

**Comment by 0lvin** [comment]
Have you tried with last 7.30 version? It has updated logic for particles sizes.

**Comment by StepanST** [comment]
Yes, now i see, there is no proplems with particles in 7.30.
