### ISSUE TITLE
Enforcer explosion death

### ISSUE THREAD

**Issue by StepanST** [yquake2/yquake2#331]
It is standart quake 2 problem, but it is sloved in Quake2 Unofficial v3.24 Patch. When you kill enforcer by not explosive weapon and he loose his head, the model of enforcer has normal bloody texture, but when you kill him with rocket launcher, for exaple, the model have normal not bloody texture, but enforcer has no head.  Thank you.

**Comment by Yamagi** [comment]
This was an easy one. We've pushed a fix, it'll be part of the next
release. :)

On Wed, 03 Oct 2018 08:44:51 -0700
Daniel Gibson <notifications@github.com> wrote:

> Closed #331 via f2a73b39199d1563ec891775ccf06b92106c1a63.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/yquake2/yquake2/issues/331#event-1882283516


-- 
Homepage: https://www.yamagi.org
Github:   https://github.com/yamagi
GPG:      0xeb1472e71d502515
