### ISSUE TITLE
[Feature suggestion] Stretching resolution to 32x240

### ISSUE THREAD

**Issue by StepanST** [yquake2/yquake2#335]
In port for Quake 1 - Mark V WinQuake there is a feature - you can stretch high resolution to 320x240, so you can play 320x240 without smoothing on modern OS's  as on Windows 95. I think it is very authentic, becouse many Q2 fans had first expereance of playing Quake 2 in low resolution :)

**Comment by StepanST** [comment]
And maybe you will add waterwrap effect to OpenGL mode? :)

**Comment by Yamagi** [comment]
Maybe we'll add water wrapping one day. But no resolution stretching. It would just add a lot of complexity to the already overcomplex viewport stuff for very little gain.
