### ISSUE TITLE
Echo message when push unbind mouse button

### ISSUE THREAD

**Issue by StepanST** [yquake2/yquake2#336]
It is very small issue. For exaple, If you push right mouse button, that have no bind, game displays massage "MOUSE2 is unbound, hit F4 to set". In unoffical KM 3.24 patch it is sloved.

**Comment by AtifArshad1995** [comment]
I get this message too if i accidentally press RMB (though i never cared much about it)

**Comment by Yamagi** [comment]
We once remove that message and the other half of the world complained. Since it was this way in the original client we'll leave things as they are.
