### ISSUE TITLE
Brightness problems and ability to disable ingame video filtering.

### ISSUE THREAD

**Issue by StepanST** [yquake2/yquake2#337]
![slamelava](https://user-images.githubusercontent.com/43229017/46573123-a094b380-c9ba-11e8-97e4-c082f809838f.jpg)
![brightness](https://user-images.githubusercontent.com/43229017/46573124-a094b380-c9ba-11e8-9fea-6040af3f0e8d.jpg)

Hope I did not bored you with reports, jast want to help with making project perfect :)
There is some small issues:
1) Some people want to have "software mode with colored lighting" expereance, so it will be good, if you add ability to disable filtering of ingame videos, like intro.
2) Quake 2 is too dark in gl mode by default. Tools that you  added, like gl3_intensity and gl3_overbrightbits is very usefull. But for exsample< with gl3_intensity "2.5" in places with a lot of lights bright textures become white and loose details, like on screenshots, that i attached. 
3) Slime and lava textures is fine in software mode, but in gl mode they are not. With normal brightness slime texture is too faded, and lava is too dark, compared with software mode. Setting gl3_intensity to value bigger then 2 sloves problem with lava, but makes bright textures white and less detaled. 

Thannk you for attention.

**Comment by StepanST** [comment]
And i think the last suggestion - is add option to stretch in game videos to fullscreen in large resolution, like 1980x1020, to remove black stripes on the sides of the screen.

**Comment by Yamagi** [comment]
First you'll to know that there never was the one look. The software renderer takes some shortcuts and doesn't use all available data, for example the lighting pass this much simpler than in the gl renderers. The old gl1 one renderer relies on the drivers blending implementation for combining textures, lightmaps and dynamic light. Depending on your driver you'll get a slightly different look. gl3 uses shaders and is driver agnostic, but always looks a little bit different than gl1.

When designing the gl3 look we followed 2 rules: 1) Quality before speed. gl3 renders the scene with higher quality than gl1. It's hard to see in detail but overall it just looks "better". 2) Stroggos is a dark and dirty place. Don't make the default settings too bright.  
The look was designed on a very high quality Eizo display with nearly full Adobe color space support. On other displays it may be too dark or to too bright, depending on the panel and it's settings. Just adjust the brightness slider (technically it adjusts the gamma) to match your needs. We won't make any changes to the overall look.

Liquids are a special case. For some reasons Quake II has no lightmaps for liquid surfaces, therefor liquids are always too bright or too dark. There's nothing we can do against it, the only question is  in wish way we do it wrong. In gl1 you can use the gl1_overbrightbits cvar to decide:

- 1: Old behaviour, link in the original client.
- 2: No overbright bits on the global scene but correcter lightning on warping surfaces.
- 3. Overbright bits on the global scene but not on warping surfaces.

In gl3 we don't fake the missing lightmaps, liquids are always a little bit too dark.

> Some people want to have "software mode with colored lighting" expereance, so it will be good, if you add ability to disable filtering of ingame videos, like intro.

You can set `gl3_particle_square` to `1` and `gl_texturemode` to `GL_NEAREST_MIPMAP_LINEAR` to get a software like look.

> Quake 2 is too dark in gl mode by default. Tools that you added, like gl3_intensity and gl3_overbrightbits is very usefull. But for exsample< with gl3_intensity "2.5" in places with a lot of lights bright textures become white and loose details, like on screenshots, that i attached.

See above. Adjust the gamma and only the gamma.

> Slime and lava textures is fine in software mode, but in gl mode they are not. With normal brightness slime texture is too faded, and lava is too dark, compared with software mode. Setting gl3_intensity to value bigger then 2 sloves problem with lava, but makes bright textures white and less detaled.

See above, it can't be done right. There're just no lightmaps on those surfaces.

> And i think the last suggestion - is add option to stretch in game videos to fullscreen in large resolution, like 1980x1020, to remove black stripes on the sides of the screen.

You can set `cin_force43' to `1`.

**Comment by StepanST** [comment]
Thank you very match, now i understand more :)
