### ISSUE TITLE
Not an issue with the client, but documentation

### ISSUE THREAD

**Issue by hfc2x** [yquake2/yquake2#341]
It's said in the documentation that most digital versions have to be patched beforehand, and also there are steps for the music folders and how to obtain the soundtrack. While it is mentioned that the GOG version comes with the soundtrack included in *.ogg format, that version at least comes patched to version 3.20, and includes the CTF gamemode, but also the Xatrix and Rogue mission packs.

Therefore, shouldn't the documentation be updated to match? There's no need to apply a patch to the GOG version, because it already comes patched to the version required by YQuake2, and includes all the optional content. Besides, in [ogg.c](https://github.com/yquake2/yquake2/blob/master/src/client/sound/ogg.c) there's already special handling for the GOG version, detecting the music in the folder it comes in by default in that version, so there's no need to move the music tracks to new folders inside each "game directory", since the client already detects the tracks and plays them accordingly.

**Comment by Yamagi** [comment]
We've updated the documentation. The section on setting up the GOG versions music is now clearer.
