### ISSUE TITLE
Problem playing custom SP campaign with Yamagi

### ISSUE THREAD

**Issue by Evilmantheone** [yquake2/yquake2#345]
Hi there !

So, the title pretty much explain the problem, for some reason I'm not able to play a specific SP Campaign with Yamagi, this one actually "World Without End": http://www.quake2.xf.cz/

You can download the campaign through the link on his site, a bit slow but it works.

Anyway, I unzipped the whole campaign content in a specific folder, everything is at the right place, start Yamagi, command line /game mod, but ... it fails to load. I either got a problem saying there's a skin that is too tall or something about bad lightings, anyway it doesn't work. It's apparently built with KMQuake2 in mind, I tried with it, it works, but in all honesty I do prefer using Yamagi for many reasons.

Is there any way to play it with Yamagi, and if so, how ? If there's no workaround I'll do it with KMQuake but I'd rather avoid if possible.

I'm not too familiar with the many Quake II source port availables and what incompatibilies there might be between them.

Posting my original thread from Steam Forums where I've reported the problem first btw, someone else confirm the problem:

https://steamcommunity.com/linkfilter/?url=https://github.com/yquake2/yquake2/issues

Thanks for your work and reading !

**Comment by maraakate** [comment]
If it requires KMQ2 then it's very likely there are custom skin sizes that are beyond what the typical Quake 2 engine supports and possibly even extended map sizes.  If that's the case then it will never work in YQ2 unless those additional changes are added.  I think it's safe to say that those types of changes won't be added as it's beyond the scope of this port.

**Comment by iButane** [comment]
This is the error message it spits out: 

>Lost Paradise
>Map: map1
>********************
>ERROR: Bad s_blocklights size
>********************
>==== ShutdownGame ====

Is this something that only KMQ2 supports?

**Comment by iButane** [comment]
Yeah I hear ya..

Think I'm gonna run through this MOD on KMQ2 to see what's so 'boom' about it because so far Yamagi has been able to run just about everything.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Yamagi** [comment]
The problem with this is, that's most likely not done by increasing some internal limits. That may work to some degree, but to be sure that everything's alright one needs to go through the code and make sure that it's able to keep up with the increased limits. That's a lot of work and not in our scope. So, if the campaign was designed for KMQ2 just play it with that. :)
