### ISSUE TITLE
VirtualAlloc commit failed

### ISSUE THREAD

**Issue by ricardosdl** [yquake2/yquake2#346]
I'm building from the source (master branch). I'm on windows 10 pro - 64 bits. I used the quake2_buildenv_20180815.zip build environment. I launched the mingw32.exe, and compiled with make. I had to add semicolon on this line to compile it:
https://github.com/yquake2/yquake2/blob/ee4135fd0a3307099dcb7177e4195912ea2c43e7/src/backends/windows/network.c#L727

After I launched yquake2.exe , everything seemed fine. But after I tried to start a new game in the first level I've got the message:
VirtualAlloc commit failed

Well, after a lot of printf's (starting the game as "yquake2.exe -portable" helped!), I found that the code was trying to allocate more memory than hunkmaxsize. This was happening when the level was being loaded in memory. Changing the value passed to Hunk_Begin in the function Mod_LoadBrushModel, allowed the level to load normally. I'm adding a diff file with my modifications, I hope this will help. Thank you.
[diff.txt](https://github.com/yquake2/yquake2/files/2606326/diff.txt)

**Comment by Yamagi** [comment]
Hmpf. Windows is a little bit undertested... This was an oversight on my side, I din't see the problem neither when I reviewed the initial pull request nor hit it while debugging some other memory allocation errors on Windows. Your patch is correct. I've just committed it. Thank you for the analysis! :)
