### ISSUE TITLE
Console response: Unable to rename files when downloading map files

### ISSUE THREAD

**Issue by tamburinglede** [yquake2/yquake2#348]
When I try to join a server for a multiplayer game, I'm not able to download textures and map files. I have tried to install in various locations and enquired with the nanoquake-discord - but I'm not able to figure out why. It seems that it might be related to my windows 10 username. I use an accented letter in my username, and I suspect that the quake 2 somehow gets things messed up because of this.
This is how things look when the map is opened: ![skjermbilde 4](https://user-images.githubusercontent.com/37292019/49926690-6a911580-febc-11e8-96c7-dd2d927998a7.png)

**Comment by Yamagi** [comment]
Hi,
thank you for the report. That's indeed another Unicode problem. I've pushed a fix into the experimental 'vurl' branch. It'll be part of the next release. :)

Thank you,
Yamagi

**Comment by Yamagi** [comment]
A set of experimental Windows binaries with this fix and support for HTTP downloads (Yeah!) can be found here: https://deponie.yamagi.org/quake2/misc/quake2-7b20020.zip
