### ISSUE TITLE
crashes-segfaults latest udpfallback branch

### ISSUE THREAD

**Issue by gribbs88** [yquake2/yquake2#362]
*******************************************************************************************************************************
Yamagi Quake II v7.31pre
========================
Client build options:
 + OpenAL audio
Platform: Linux
Architecture: x86_64
Byte ordering: little endian

Added packfile './baseq2/pak0.pak' (3386 files).
Added packfile './baseq2/pak1.pak' (279 files).
Added packfile './baseq2/pak2.pak' (2 files).
Added packfile './baseq2/pak3.pak' (11 files).

=======================================================

Yamagi Quake II crashed! This should not happen...

Make sure that you're using the last version. It can
be found at http://www.yamagi.org/quake2. If you do,
send a bug report to quake2@yamagi.org and include:

 - This output
 - The conditions that triggered the crash
 - How to reproduce the crash (if known)
 - The following files. None of them contains private
   data. They're necessary to analyze the backtrace:

    - quake2 (the executable / binary)

    - game.so (the game.so of the mod you were playing
      when the game crashed. baseq2/game.so for the
      main game)

 - Any other data which you think might be useful

Thank you very much for your help, making Yamagi Quake
II an even better source port. It's much appreciated.
                                                                                                                                   
=======================================================

Product:      Yamagi Quake II
Version:      7.31pre
Platform:     Linux
Architecture: x86_64
Compiler:     5.5.0
Signal:       11

Backtrace:
  ./quake2() [0x46d077]
  ./quake2() [0x46d1ee]
  /lib64/libc.so.6(+0x35480) [0x7f8ec7e57480]
  ./quake2() [0x448684]
  ./quake2() [0x448833]
  ./quake2() [0x448cf5]
  ./quake2() [0x44b954]
  ./quake2() [0x405317]
  /lib64/libc.so.6(__libc_start_main+0xf0) [0x7f8ec7e427d0]
  ./quake2(_start+0x29) [0x405399]

Segmentation fault
bash-4.3$ 

*****************************************************************************************************************************

**Comment by Yamagi** [comment]
That was - of course - my fault. I shouldn't have pushed some last minute changes without testing them... It's fixed now. Thank you!
