### ISSUE TITLE
Can't turn on OpenGL in Windows 10

### ISSUE THREAD

**Issue by Dealazer** [yquake2/yquake2#364]
Running Q2Pro says no hardware OpenGL detected.

I have the same problem with Nvidia 1050 Ti and AMD 360.

So running YQuake2.exe and trying to turn on openGL 3.2 or 1.4 does not work. But software works.

What kind of drivers do I need to install, or what is needed to make it work?

**Comment by Yamagi** [comment]
You need to install Nvidias official driver, the driver installed by Windows Update hasn't got proper OpenGL support: https://www.nvidia.de/Download/index.aspx If that doesn't help you Windows installation is likely broken.
