### ISSUE TITLE
[Feature Request] Expose gameplay related stuff as CVars

### ISSUE THREAD

**Issue by drogga** [yquake2/yquake2#365]
Similar to the Quake II citadel mod, the Knightmare Patch for RtCW, the SMC (Small Mod Compilation) for Quake 1, or Half-Life 1 & 2, give the player access to various gameplay elements over the console, preferably with the prefix sk_ (for skill), this includes things such as:
-Enemy & player starting/base health
-Player & enemy weapon damage
-Grenade & rocket splash radius
-Shotgun pellet count and hitscan weapon (horizontal/vertical or conical) spread
-Amount gained from health, armor, ammo or weapons, either absolute value or factor
-"Durability" of the silencer, as well as the duration of other powerups
-Armor absorption/protection in a range from 0.0 to 1.0 or 0 (%) to 100 (%)
-Inventory item + ammo carrying capacity (with or without bando or backpack)
-Probably other things I can't remember off the top of my head

whaddya say, is this out of scope of this project and better suited for a mod, or could this easily be implemented in the game.dll?

Thx in advance

**Comment by Yamagi** [comment]
That's a nice idea but it would be a lot of work to implement this. In Quake II nearly everything is hardcoded and scattered over the game.dll source code. One would need to go through it, identify all places were values with impact to the balancing are set and implement cvars around it. Without introducing new bugs... I'm afraid that neither @DanielGibson  nor me have the time and motivation for that.

If someone want's to try it I would suggest to fork the game.dll source into an own repo and start there. The source is found in src/game. A Makefile or CMakeLists.txt can be taken from one of the addons. The addons are licensed under the id Software SDK license which is not really an open source license and incompatible with the GPL, but the Makefiles were written by me and I don't really care for their license  (especially not for the SDK license) so feel free to reuse them.
