### ISSUE TITLE
Easy To implement tonemapping function you guys can use 

### ISSUE THREAD

**Issue by JiggelTime** [yquake2/yquake2#366]
Sorry if this is the wrong place to put this. I don't use github often. 
I scrolled through the code briefly to see how you guys were doing the temporal resolve, and I noticed you guys were using a Reinhard tonemapping operator. 
I have two tonemapping functions you guys can use (I recommend Uncharted 2) that look better in my opinion. I use these in my own custom engine. Should be super simple to implement in your shader.
 This is glsl code but if you guys are using hlsl it should be a matter of renaming vec3's to float3's. Here ya go:

vec3 uncharted2Tonemap(vec3 color)
{
	const float A = 0.15f;
	const float B = 0.50f;
	const float C = 0.10f;
	const float D = 0.20f;
	const float E = 0.02f;
	const float F = 0.30f;
	const float W = 11.2f;
	return ((color * (A * color + C * B) + D * E) / (color * (A * color + B) + D * F)) - E / F;
}

//https://knarkowicz.wordpress.com/2016/01/06/aces-filmic-tone-mapping-curve/
vec3 acesFilmTonemap(const vec3 color)
{
    const float a = 2.51f;
    const float b = 0.03f;
    const float c = 2.43f;
    const float d = 0.59f;
    const float e = 0.14f;
    return clamp((color * (a * color + b)) / (color * (c * color + d ) + e), 0.0f, 1.0f);
}

**Comment by DanielGibson** [comment]
what is a Reinhard tonemapping operator and where are we using it?

**Comment by JiggelTime** [comment]
yquake2/src/client/refresh/pathtracer.glsl line 754

**Comment by DanielGibson** [comment]
oh, you're talking about @eddbiddulph's pathtracing renderer - which is not part of the official code in this repo, but can be found at https://github.com/eddbiddulph/yquake2

**Comment by JiggelTime** [comment]
Oh, I apologize. Goes to show how much of a Github noob I am xD. Should I make a suggestion there instead?

**Comment by DanielGibson** [comment]
theoretically: yes, but it seems like Edd disabled the issue tracker and I'm not sure he's even still working on it (the last commit changing code was in August 2017, apart from that there's only one commit from last December that doesn't change any code but only fixes a problem with building it)
