### ISSUE TITLE
[Suggestion] Support for MP3 soundtrack

### ISSUE THREAD

**Issue by voodoo84** [yquake2/yquake2#367]
Hello,

As you may know, all Fraunhofer patents for MP3 expired two years ago and you can now use it wherever you want (as long as you have a free or non-commercial encoder/decoder implementation such as libmp3lame, libmpg123 or similar).

Technically, Vorbis is better codec but could you consider adding support for MP3 too for the sake of completion? (SDL2 allows it as far as I know).

Also, QuakeSpasm (for Q1) allows both Ogg and MP3 (and plain PCM WAV).

**Comment by DanielGibson** [comment]
SDL2 neither supports ogg nor mp3, it doesn't do any audio decoding.

I don't see a point in supporting MP3. There are two ways to legally get the Q2 soundtrack:
1. From GOG (they use .ogg)
2. Rip it yourself from CDs (you can as well rip it as .ogg then)

If there were a legal download version that supplied the soundtrack as MP3 it *might* make sense, but there isn't so it doesn't.

**Comment by voodoo84** [comment]
I have both GoG release (with pre-ripped Oggs in the music folder) and the physical discs, but I tend to rip Quake OSTs by myself. But it is OK if you think there is no point in adding MP3, this was just a suggestion.

**Comment by Marat-Tanalin** [comment]
Indeed, support for another _lossy_ format would unlikely make sense.

Support for a _lossless_ format such as FLAC or Wave (issue #418) would provide the original CD-Audio quality, and Yamagi is open to a corresponding patch.

**Comment by voodoo84** [comment]
Actually, 12 years ago I wrote similar thing for the original Quake 2 v3.21 source code:

https://sites.google.com/site/ivantodorovic/quake2musicfromhdd

It was merely a replacement of CD audio routines in win32\cd_win.c with Win32 generic PlayAudio calls. Thus, it's not portable and doesn't use DirectSound or similar acceleration, but I remember it worked.

I may provide a patch for Yamagi but I suspect it won't be accepted, due to said nature of it.

**Comment by DanielGibson** [comment]
We have a perfectly working ogg/vorbis backend, just use that.
Vorbis is superior to MP3 in all regards, also the Q2 soundtrack has only ever (legally) been distributed as CD and as .ogg (by GOG).

**Comment by Marat-Tanalin** [comment]
@voodoo84
> I may provide a patch for Yamagi but I suspect it won't be accepted, due to said nature of it.

A Windows-only implementation would cover major number of gamers. So it could probably be OK as long as integrated in a seamless way unified with the current Ogg Vorbis support, including support for controlling music volume via game settings.

@DanielGibson
> Vorbis is superior to MP3 in all regards

Afaict, that 12-years-old implementation is for Wave, not MP3. It’s just Windows-specific.

**Comment by DanielGibson** [comment]
Windows-specific is even less interesting for us than any other kind of MP3 or .wav backend.
