### ISSUE TITLE
http downloads not d/ling all files

### ISSUE THREAD

**Issue by iButane** [yquake2/yquake2#370]
When connecting to the custom coop server maraakate.org, Yamagi doesn't download all the necessary files. It downloads 106 files but when I use q2pro it downloads 128 files.  I deleted the coop folder a few times and retried-- always the same.  https://imgur.com/a/0ix1NNA Does Yamagi not download .PAK files? As you can see in that image, Q2pro downloads a pak0.pak file but not Yamagi.

In the multiplayer download options, everything is set to YES.
The only error I saw in the console was 'HTTP download: /.filelist - File Not Found' but other than that everything queued and downloaded fine.

**Comment by DanielGibson** [comment]
please tell us which server this happens on so we can reproduce it

**Comment by iButane** [comment]
172.86.181.38

**Comment by Yamagi** [comment]
> The only error I saw in the console was 'HTTP download: /.filelist - File Not Found' but other than that everything queued and downloaded fine.

Does q2pro download a filelist? if yes, what's it's path?

**Comment by iButane** [comment]
> > The only error I saw in the console was 'HTTP download: /.filelist - File Not Found' but other than that everything queued and downloaded fine.
> 
> Does q2pro download a filelist? if yes, what's it's path?

Yeah, I believe it's coop.filelist. First few lines in console before file downloads begin says:

[HTTP] coop.filelist [10 bytes, 30 bytes/sec]
[HTTP] Filelist is requesting a .pak file 'pak0.pak'

**Comment by Yamagi** [comment]
Okay, we generated a wrong URL to the filelist in case that a mod is running. I've just pushed a fix. Do you need Windows binaries for this?

**Comment by iButane** [comment]
Yeah, I wouldn't mind a download link to Windows binaries with this fix.

Thanks

**Comment by Yamagi** [comment]
Here they are: https://deponie.yamagi.org/quake2/misc/quake2-b49f2b.zip

**Comment by iButane** [comment]
Sweet... that fixed the issue.

But there is another one (which was present before as well) but I didn't bother mentioning it coz I was hoping it was related to the original.

I noticed that when a server doesn't have a certain player model/sound etc file which a player is using, the Yamagi http download gets stuck in an endless loop of trying to get that file and doesn't connect to the server: https://youtu.be/NP4ZbAotxq8
