### ISSUE TITLE
some troubles with output image in pt_enable

### ISSUE THREAD

**Issue by awesomesoftwaremaker** [yquake2/yquake2#376]
![quake2_2019_03_08_15_46_54_850](https://user-images.githubusercontent.com/36794071/54022121-fbc21080-41bb-11e9-8e48-dadbecfb23e8.png)
![quake2_2019_03_08_15_46_52_452](https://user-images.githubusercontent.com/36794071/54022122-fc5aa700-41bb-11e9-83a0-b60ad22c3416.png)
*sorry for bad eng, isn't my native*
It become anyway i start game in pt_enabled 1
gpu: AMD radeon 580 8gb
cpu: e3 1240v2 oc (read as i7-3770@3.6)
12gb ram
Any other games work correctly (except Q2VKPT((( )

**Comment by Yamagi** [comment]
Hi,
`pt_enabled` sounds like you're at the wrong project. We're Yamagi Quake II, Q2VKPT is here: https://github.com/cschied/q2vkpt :)

**Comment by awesomesoftwaremaker** [comment]
Thanks for answer, but, those screenshots can't be from Q2vkpt, which requires RTX video card:
![xsLouxS](https://user-images.githubusercontent.com/36794071/54332269-9d77b080-4647-11e9-8f69-cbe46cfb2151.png)
There are no other projects on this topic, this is exactly yquake2.

**Comment by Yamagi** [comment]
But YQ2 doesn't have the `pt_enabled` cvar, because we don't implement path tracing.

**Comment by DanielGibson** [comment]
This is probably about https://github.com/eddbiddulph/yquake2
We're not involved in that project though, it's just based on Yamagi Quake II.
