### ISSUE TITLE
"VirtualAlloc commit failed" when loading rmine2.

### ISSUE THREAD

**Issue by Yamagi** [yquake2/yquake2#377]
I received this e-mail:

----

Hi there,

I'm having trouble running the secret map *Mine Engineering* (rmine2) in
Ground Zero. Entering the map as the final secret of the previous map, or
manually from the console produces the error *Virtuall Alloc commit failed*
and game exits to Windows. Any ideas?

- using Yamagi Quake II v7.40 precompiled installer
- Win7 x64
- followed installation procedure

Thanks, JP

----

That's 100% reproduceable, loading `rmine2` crashes the games by memory allocation failures.

**Comment by DarkSwan86** [comment]
I've tried it on Linux  (using the console and manually loading the level) and works fine (using latest 2.05 version of Ground Zero). Probably it only affect Windows?

**Comment by DanielGibson** [comment]
it only affects 32bit builds

we're working on a proper fix

**Comment by DanielGibson** [comment]
I just pushed fixes for this to master, there will be new windows binaries containing this fix in the next days.

**Comment by Yamagi** [comment]
A new build can be found here: https://deponie.yamagi.org/quake2/misc/quake2-3b296c4-20190318.zip
