### ISSUE TITLE
Problems compiling from source in Xubuntu with checkinstall

### ISSUE THREAD

**Issue by CamJRP** [yquake2/yquake2#378]
Fir of all i want to thank the developers for Yamagi. I can't express enough how much i enjoy to play the games of my infancy, like Quake I, II, Doom and others.
Here comes my problem:
Im trying to compile from source the latest version of Yamagi. Im running Linux in my old laptop, the distro of choice is Xubuntu 18.04. 
Using checkinstall, im getting the next output in the terminal:

camilo@camilo-S400CA:~/Downloads/quake2-7.40$ sudo checkinstall
[sudo] password for camilo: 

checkinstall 1.6.2, Copyright 2009 Felipe Eduardo Sanchez Diaz Duran
           This software is released under the GNU GPL.

The package documentation directory ./doc-pak does not exist. 
Should I create a default set of package docs?  [y]: y

Preparing package documentation...OK

Please write a description for the package.
End your description with an empty line or EOF.
>> Modern engine for Quake2
>> 

*****************************************
**** Debian package creation selected ***
*****************************************

This package will be built according to these values: 

0 -  Maintainer: [ root@camilo-S400CA ]
1 -  Summary: [ Modern engine for Quake2 ]
2 -  Name:    [ quake2 ]
3 -  Version: [ 7.40 ]
4 -  Release: [ 1 ]
5 -  License: [ GPL ]
6 -  Group:   [ checkinstall ]
7 -  Architecture: [ amd64 ]
8 -  Source location: [ quake2-7.40 ]
9 -  Alternate source location: [  ]
10 - Requires: [  ]
11 - Provides: [ quake2 ]
12 - Conflicts: [  ]
13 - Replaces: [  ]

Enter a number to change any of them or press ENTER to continue: 

Installing with make install...

========================= Installation results ===========================
**make: *** No rule to make target 'install'.  Stop.**

****  Installation failed. Aborting package creation.

Restoring overwritten files from backup...OK

Cleaning up...OK

Bye.

Any help would be much appreciated.

**Comment by DanielGibson** [comment]
I don't really know what checkinstall is, but your problem here is that we don't implement `make install`.
The binaries created by running `make` are in `quake2-7.40/release/`, in case you wanna copy them somewhere manually

**Comment by CamJRP** [comment]
Thanks for clarifying me that.
Sorry for the ignorance, but the the instructions for compilling are no clear enough for me. 
After compiling the program with make install, what should i do in order to play quake ii with Yamagi.
I have the game installed with steam and properly patched. 
Thanks in advance

**Comment by CamJRP** [comment]
Thanks for the reply.
So, after compiling the program with "make", what should i do exactly to be able to play QuakeII with Yamagi.
I have the game installed via Steam. Im using Xubuntu 18.04.
Thanks in advance

**Comment by DanielGibson** [comment]
Did you read https://github.com/yquake2/yquake2/blob/master/doc/02_installation.md ?

**Comment by Yamagi** [comment]
This is all described in the documentation: https://github.com/yquake2/yquake2/blob/master/doc/01_index.md

**Comment by CamJRP** [comment]
I did read it, there is something that i'm not getting right. Maybe because English is not my main language and cause i'm new linux user, but thanks anyway

**Comment by DanielGibson** [comment]
So what's your current state?
Do you have a directory with the game data in it, from the patch and steam? should look like
```
quake2/
quake2/baseq2/
quake2/baseq2/pak0.pak
quake2/baseq2/pak1.pak
quake2/baseq2/pak2.pak
quake2/baseq2/players/
  - containing crakhor/ cyborg/  female/  male/ subdirectories that contain lots of files
quake2/baseq2/video/
  - containing several .cin files
quake2/baseq2/music/ 
  - optional; containing 02.ogg - 11.ogg
```
In addition to these files, you should put the stuff you compiled, from `quake2/release/` in there:
```
quake2/quake2 (from release/quake2 - this is the game executable)
quake2/q2ded
quake2/ref_gl1.so
quake2/ref_gl3.so
quake2/ref_soft.so
quake2/baseq2/game.so
```

**Comment by CamJRP** [comment]
Thanks a lot!

**Comment by CamJRP** [comment]
I will take the chance of asking too many questions and seem to be almost disrepctful with dumb questions, but i prefer to do it instead of not playing Quake2.
So... after copying these files to the Q2 directory, how should i execute the game with Yamagi?

**Comment by DanielGibson** [comment]
you can probably double-click quake2 (the executable)
otherwise open a terminal in that folder and execute `./quake2` in the terminal

**Comment by CamJRP** [comment]
Thaanks buddies! from the extreme south of Chile, im going to play Quake2 in this cold rainy day :+1:

**Comment by DanielGibson** [comment]
From northern Germany, where it's cold and rainy most of the time: Have fun, mate! :) 
:boom: :gun: :godmode:
