### ISSUE TITLE
Possibility of having accurate aiming?

### ISSUE THREAD

**Issue by mjr4077au** [yquake2/yquake2#379]
This is more of a feature request than a bug fix.

I know the vanilla engine is like it, but I was wondering if an aiming fix such as what's described [here](http://quakegate.ru/forum/topic870/) could possibly be added in as a boolean or toggle of some kind?

I had this fixed DLL file for the original engine some time ago, now the link suffers from rot and is not obtainable.

There's a lot of hacks people do, such as just turn the crosshair off or change the HUD to hidden so the aim is horizontally centre (but not vertically). I think the community would appreciate it.

Apologies in advance, but I don't have the programming chops to submit a patch with my request.

**Comment by Yamagi** [comment]
Nope, that won't happen. That completely orthogonal to Quake IIs inner working, projectiles are always spawned from the players origin and their vector is calculated from it. Changes to that code aren't easy and have a very high probability of (subtile) breaking things.
