### ISSUE TITLE
Possibility to set monitor refresh rate

### ISSUE THREAD

**Issue by dezo2** [yquake2/yquake2#380]
Hi Yamagi, is it possible to add some cvar for setting monitor refresh rate in addition to selecting resolution? Like in quakespasm or other quake 1/2 ports. Now the game uses refresh from desktop, which is OK in most cases, but selecting different rates would be useful. Consider scenario when desktop uses lower refresh than games. Even ancient games like RTCW have r_displayRefresh to play with.

PS: It took me a while to figure out how to set smooth movement in the new build. I had to set the cvar vid_displayrefreshrate to far more than monitor refresh rate (126 or above for refresh 120Hz in my case). I think that the refresh rate detection isn't that reliable...

**Comment by Yamagi** [comment]
Implementing that is not as easy as it sounds, because it would require another iteration of the API connecting the renderer DLLs with the client. And likely another refactoring of the crude and complicated SDL backend, Quakes requirements and SDLs design decisions are somewhat different. But we'll consider it.

> I think that the refresh rate detection isn't that reliable...

It may be one frame off if the GPU driver is rounding down. That's unavoidable, the question is just in which direction the timings break. But what do you mean with "smooth movement"?

**Comment by dezo2** [comment]
Thanks for the response. By smooth movement I mean in sync with display refresh. I got 120 Hz screen recently and using latest YQ2 build with VSync the framerate was locked to 111. I then deleted old config so a new one with default values was created and then I increased vid_displayrefreshrate by one until the FPS jumped to 120 (monitor refresh). That was for 126 in that cvar. I can set it to 240 and forget it, so its not a problem for me, but I think that by default it should not limit framerate so hard when VSync is enabled. Btw I am on win7 x64, fullscreen 2560x1440, aero off.

**Comment by Yamagi** [comment]
Can you try this very experimental build: https://deponie.yamagi.org/quake2/misc/quake2-ed5ba0d-20190401.zip It may help to get 120 FPS with `vid_displayrefreshrate` set to `-1`. And is it an AMD, an Intel or a Nvidia GPU?

**Comment by dezo2** [comment]
Its nvidia GTX1080 and with that build I get stable 120FPS on 120Hz refresh without altering that cvar (default value -1). So it seems to be fixed now, thank you.

**Comment by Yamagi** [comment]
Very good. I just pushed a more generalized version of this to master. It'll be part of the next release.
