### ISSUE TITLE
Strange output on console on map Waste Disposal (Quake 2 Ground Zero MP)

### ISSUE THREAD

**Issue by DarkSwan86** [yquake2/yquake2#383]
When you start the map Waste Disposal (map rsewer2) on Ground Zero, at the very beginning, if you wait enought (usually 2-5 minutes) on the console will appear the message "**G_PickTarget: target t215 not found**". 

It seems harmless but I wanted to report it, just to be sure :)

Latest stable version of YQ2 (7.40) and Ground Zero (2.05) both x64, Manjaro Linux, Mesa Driver 18.3.4 (Intel Sandybridge HD 3000)

**Comment by Yamagi** [comment]
That's harmless. It's a hint to the map designer, an entity references a nonexistent target. Since the map is working as it should there's no need not hack around it. Ground Zero has also many, many "Entity starts in solid" messages. They're also harmless.
