### ISSUE TITLE
vid_fullscreen is initialized instead of vid_gamma in VID_Init

### ISSUE THREAD

**Issue by m-x-d** [yquake2/yquake2#385]
https://github.com/yquake2/yquake2/blob/3b296c43a05ef0e9971522a7cd5fe2c7cee75c07/src/client/vid/vid.c#L495

This doesn't look right.

**Comment by DanielGibson** [comment]
haha, looks like a copy&paste fail =)

it doesn't matter because the line after vid_fullscreen is initialized properly, but still wrong, of course

**Comment by Yamagi** [comment]
Fixed. Thank you!
