### ISSUE TITLE
lighting issue on gl3 renderer

### ISSUE THREAD

**Issue by Rikoshet-234** [yquake2/yquake2#386]
![image](https://user-images.githubusercontent.com/34555340/55426887-279ba080-5586-11e9-91ad-a59ef58ace1d.png)
![image](https://user-images.githubusercontent.com/34555340/55426901-308c7200-5586-11e9-80c2-fd95ad86d46e.png)
![image](https://user-images.githubusercontent.com/34555340/55427012-629dd400-5586-11e9-9b36-16544b2a2998.png)

I think this is due to the fact that the light source is below the floor.
here, the other screens https://drive.google.com/file/d/1ebP6Jp9VLi5gysBuq4T_ZbPyaWHdDck6/view?usp=sharing
I'm using the latest version 7.40
and yet, the shadows on this render does not work

**Comment by Rikoshet-234** [comment]
I think this is due to the fact that the light source is below the floor

**Comment by Rikoshet-234** [comment]
here, the other screens  https://drive.google.com/file/d/1ebP6Jp9VLi5gysBuq4T_ZbPyaWHdDck6/view?usp=sharing

**Comment by Rikoshet-234** [comment]
I'm using the latest version 7.40

**Comment by DanielGibson** [comment]
Hmm I'd generally consider it a feature that lights below the floor don't light it, but maybe we need some tolerance there if the lightsource of explosions is indeed below the floor.

**Comment by DanielGibson** [comment]
Ok, the lights are not below the floor, but the shader has a line that multiplies the light intensity used to brighten the scene there that apparently becomes about 0 if the light is close to the floor (=> the angle between floor and a line between the potentially lighted pixel and the like source is small).

In case you wanna experiment with it (=> if you compile yq2 yourself), it's in src/client/refresh/gl3/gl3_shaders.c about line 491:
```c
	// also factor in angle between light and point on surface
	fact *= max(0, dot(passNormal, lightToPos/distLightToPos));
```
commenting out that line (just prepend `//`) will make it look more like gl1
replacing it with `fact *= max(0.3, 0.3+dot(passNormal, lightToPos/distLightToPos));` is somewhere in between the current gl3 look (which has smoother transitions between light and dark for dynamic lights which generally looks better, IMO, especially visible when just shooting the blaster and looking at the dynamic lights at the floor/walls/celing) and the gl1 look - you could also test 0.5 instead of 0.3 etc

**Comment by Rikoshet-234** [comment]
Wow! it works ) thank you man !
![image](https://user-images.githubusercontent.com/34555340/55491389-b0bde080-5635-11e9-8ace-5ceda7b6b7db.png)
![image](https://user-images.githubusercontent.com/34555340/55491544-f5497c00-5635-11e9-8ae1-e1d4da5a2984.png)

**Comment by Rikoshet-234** [comment]
one more question, how to strengthen or simply to adjust the intensity of the light ?

**Comment by DanielGibson** [comment]
`fact *= 3.0;` (or some other number)
will affect all dynamic lights though, not just the one from the explosion

**Comment by Rikoshet-234** [comment]
![image](https://user-images.githubusercontent.com/34555340/55494335-d699b400-563a-11e9-91cf-b0c017a851c6.png)
this and this ?

**Comment by DanielGibson** [comment]
you could change those values, or you just add another line below, like the one I wrote.
`fact` is a factor that's multiplied with the lights value (brightness) which then is added to the lightmap texture's value at that point, thus making it brighter.
so the `bigger` fact is, the brighter the pixels will be

**Comment by Rikoshet-234** [comment]
![image](https://user-images.githubusercontent.com/34555340/55494889-fed5e280-563b-11e9-9d1c-04d71c0a3fbd.png)
![image](https://user-images.githubusercontent.com/34555340/55494915-0bf2d180-563c-11e9-9393-6cbe06063ce3.png)
![image](https://user-images.githubusercontent.com/34555340/55494944-1ca34780-563c-11e9-810a-338742caf0e8.png)
hmm 0.5 it starts to look quite interesting

**Comment by DanielGibson** [comment]
too bright IMO - I think I like the look of 0.3 best, esp. for the blaster (but grenades/rockets still look ok)

however, somehow when testing lots of different values at some point it all starts looking the same to me =)

**Comment by DanielGibson** [comment]
Hmm I also tried a completely different approach: moving the position of the lightsource a bit above the surface (for that dot calculation), like:

```c

	float fact = max(0, intens - distLightToPos - 52);

	// add passNormal to move the light source a bit further above the surface
	lightToPos += passNormal*32.0; // <- this line is new (and the comment above)

	// also factor in angle between light and point on surface
	fact *= max(dot(passNormal, normalize(lightToPos)), 0.0); // <- this line is changed

```
doesn't look bad either

**Comment by DanielGibson** [comment]
I just pushed the change I proposed last, it seems to work well and doesn't change the general look of the GL3 renderer much
