### ISSUE TITLE
Support for simple weapon wheel for controllers

### ISSUE THREAD

**Issue by blargelJim** [yquake2/yquake2#387]
Hi Yamagi guys,

I've enjoyed Quake2 through Yamagi on the retropie a lot, but one thing is missing for a better experience using a controller. Im using a PS4 controller and I think it could be easy to add support for quickly jumping between at least 8 weapons.
I've downloaded the code myself and I think I already sort of have a solution for it (I coded in so I can press SHIFT + "some key" in cl_keyboards.c to switch). Perhaps it would be nice to be able to map it like prev/next weapons too I could probably try something like that too.
I don't want a graphical GUI wheel popping up - they are clumpsy and should have no place in a FPS - just hold a shoulder button on the controller + the UP/DOWN/LEFT/RIGHT to do it.
Any chance of getting that in? Is there like some retropie yamagi quake 2 repo I should do it in?
I would really like to have a go at it myself. I've been working as a C++ dev for like 7 years so this should be no problem and it would be fun to have contributed.

/Jimmie

**Comment by DanielGibson** [comment]
Feel free to do it and create a pull request :)

**Comment by blargelJim** [comment]
Alright, cool thanks! I'll have to figure out how to build it for the retropie and try it out, never built for retropie but I guess it should'nt be to complicated.
Thanks for letting me have a go at it!

**Comment by DanielGibson** [comment]
Everyone is welcome to implement their improvements and create pull request here :)

Of course we'll review them and might ask for changes (if we think the feature could be implemented in a better way) or even reject it if we don't like the feature (but this doesn't happen often).

**Comment by blargelJim** [comment]
Hi Daniel/Yamagi guys.
I setup a fork of the repo and pushed in my very small fix to it (it sits at https://github.com/blargelJim/yquake2). Its basically a "one-liner" in cl_keyboard.c
I've tried it out on my retropie at home and it works fine.
I dont know if you guys are into the retropie repos at all but I will want to push a change to them to adding a simple "bind HAT_UP/DOWN/LEFT..." for the first 4 weapons then add this fix to reach an additional 4 weapons.  I think this would be the way to add support for this as there is no way to bind KEY_X + KEY_Y to some action in the .cfg file (as far as I know) and this is really the only convenient way to get some sweet action of quickly switching weapons in the game using the controller.
Let me know what you think of the fix and I will have a chat with the retropie guys and see if I can update the retropie .cfg file where they have made a binding for the other keys.

**Comment by DanielGibson** [comment]
I don't think it's generally useful like this.
One major problem is that `keydown[K_JOY6]` - this could be any button on different devices (or even the same device on different operating systems/different drivers)..
Also not sure if hardcoding the weapon names is a good idea, might not work with mods that have different weapons (and people might want to bind other weapons, like the super shotgun)

**Comment by blargelJim** [comment]
I was thinking the same thing about keydown[K_JOY6] - one would really like to have the possibility to bind which key is the "weapon selector" button. But I'm not sure if it is feasible to bind a "selector" key yet, seeing how K_SHIFT is hardcoded in there. I'll have a browse around in the code see if there is some more elegant way to do it. If you have some idea yourself then ofc tell me :)

**Comment by blargelJim** [comment]
Hi Daniel,
I made a change so that you can rebind the "weapon wheel selector" to whatever you want. 
You can check it in my repo, I've only tried it on the PC so far but my guess is that it will work on the retropie just as well.

Since Im not familiar with the quake 2 code, it might be the wrong way going about it but I tried to follow the pattern in cl_input.c looking at (for example) in_klook.
My idea was introduce a new command, weaponselector. Add it to the menu, so you can bind a key to it. Then check the if that key is being pressed down in the Key_Event by looking at keybindings.
Im unclear on what the effect of the stuff that happens in my IN_WeaponSelectorDown/IN_WeaponSelectorUp as I just copied these and they just seem to maniuplate that kbutton_t struct that I setup myself but never look at. Perhaps my IN_WeaponSelectorDown/IN_WeaponSelectorUp can just be empty and the Cmd_AddCommand in CL_InitInput is all that is needed?
Any input and help is appreciated :)

**Comment by DanielGibson** [comment]
can you create a pull request for your changes?
it would make it easier to look at the changes and comment on them

**Comment by blargelJim** [comment]
Yeah sure, I will make a pull request, traveling all day today but I will try and do it tomorrow.

**Comment by blargelJim** [comment]
Hi,

I've created a pull request. I did a couple of improvments and I think should be a pretty good fix.
You can now change the "selector" key to your liking and it can support mods with different weapon names through the use of cvars.
I've built and tested it on my computer and on the retropie and it works fine.
I will ofc reach out to the retropie guys to update their version of config.cfg so we add default bindings in the retropie version so players dont need to do this themselves.
Let me know what you think and have a nice weekend!
/Jimmie

**Comment by blargelJim** [comment]
Accepted fix in issue https://github.com/yquake2/yquake2/pull/392
