### ISSUE TITLE
q2 chaos mod

### ISSUE THREAD

**Issue by meddev-code** [yquake2/yquake2#39]
I forcefully request launching chaos mod at yquake2! I am managing cybercafe, and this game is perfect suprice for my clients. 

At yamagi.org it is mentioned, that:
- Compatible with most mods (as long as their source is available)

there is source to download at
http://chaoticdreams.org/q2chaos-download/

but I dont know how to use it,
please! help me

**Comment by Dr-Flay** [comment]
I notice someone has put the Chaos source here in github and seems to have done some changes relating to makefile and yquake. This may be of use to Linux users.
https://github.com/fwittekind4/chaosdm

Also I see the official site has another alternative download that has updates and fixes since the last official release..
Possibly this is more compatible out of the box with yquake.

**Comment by justusranvier** [comment]
It would be great for this issue to be revisited, especially since there's a 3.2b version with updated source code: https://chaoticdreams.org/q2chaos-download/

Chaos was my favorite mod back in ancient times.

**Comment by 0lvin** [comment]
3.2b link is broken. In same time old 1.12 is alive, but could this code be relicensed to GPL to include to other projects? 

Original license provides limitation to contribute to this code, as it requires asking all contributions to get rights to reuse parts of code in other projects. Look to https://github.com/yquake2/xatrix/issues/96 as reference.

**Comment by justusranvier** [comment]
The most recent version seems to be this repository: https://github.com/QwazyWabbitWOS/chaos

According to the Chaos forums: https://forums.chaoticdreams.org/viewtopic.php?p=75678#p75678

**Comment by Yamagi** [comment]
At least under Linux the code in https://github.com/QwazyWabbitWOS/chaos works with YQ2. It's properly the same under Windows.

**Comment by 0lvin** [comment]
I suppose @justusranvier like to have compiled version of mod or some instructions how to compile it and install. Could you please correct me if I am wrong, and you have some other issue?

**Comment by 0lvin** [comment]
I have checked little bit QwazyWabbitWOS, I have renamed Chaos/gamex86_64.dll to chaos/game.dll and checked with latest yquake2 master, everything looks good as for me.

[![chaos](https://img.youtube.com/vi/LyVZiHp4cko/0.jpg)](https://youtu.be/LyVZiHp4cko)

I have also tried to build code with mingw64, it has small issues with Q_tolower function inlining, but nothing critical.

**Comment by Dr-Flay** [comment]
The Chaos team treat @MrG-DRGN as the semi official source for the updates. He has been very helpful over the years and I'm sure that submitting an issue will be welcome if it means fixing something he missed.
You can also use the official Chaos discord where some of the old players can be found.

**Comment by MrG-DRGN** [comment]
@Dr-Flay thanks for Tagging me. The version at https://github.com/QwazyWabbitWOS/chaos is were my Current Repo is setting I enlisted QuazyWabbit's assistance with some porting to other non-windows systems and gameplay bugs related to CTF updates to bring Chaos totally current with Quake II 3.21. And as Psyco will attest I even found some old remaining bugs in the process. I would send folks there with my blessings! Thank you!

**Comment by NeonKnightOA** [comment]
I wasn't aware that Chaos was still update for Q2! That's awesome!

I had LOADS of fun with the UT version. (And I still have to document both CUT and CUT2E in the Unreal Wiki, but I can't do everything alone... :'))
