### ISSUE TITLE
gl3_particle_square 1 doesn't work on Intel HD 4000 on Windows

### ISSUE THREAD

**Issue by damontgomery** [yquake2/yquake2#391]
I have just tried this out and the game is restarting with OpenGL 1.4 whenever I select OpenGL 3.2 from the menu.

I have Windows 10 Home 64bit laptop with an integrated graphics card, Intel HD 4000 which supposedly supports OpenGL versions 4.x. I just downloaded and installed the latest drivers from Intel which are from September 2018. I understand this isn't a great computer, but it seems to work OK for games released in the 90's and was putting out decent quality at 1920 x 1080 on my external monitor.

I'm running Yamagi 7.40.

OpenGL seems fine so far (played a few levels), but I've never played the game before to know one way or another.

Thank you.

**Comment by DanielGibson** [comment]
Hmm, I *think* this should work - can you tell me what CPU this is (especially wondering if it's Ivy Bridge or Haswell generation)?

Also, can you do the thing again (select OpenGL 3.2 and apply etc) and afterwards get the `My Documents/YamagiQ2/stdout.txt` file and post it here (attach it to a post, see "Attach files" right below the field for writing a comment)?
It should hopefully contain some information why the GL3 renderer fails on your system.

Thanks!

**Comment by damontgomery** [comment]
I have some positive news and a question.

OpenGL 3.2 will stick if I edit `config.cfg` to set `gl3_particle_square 0`. I had set this to 1 because I wanted to have square particles and it must have broken at that point. I can leave the default circle particles.

However, I can't get the object shadows to show up with `gl_shadows 1` on OpenGL 3.2. They do show up on OpenGL 1.4 and I might keep playing with that mode since I like the shadows.

This is the first time I've played Quake II and I can't tell if the game looks any different between versions or how it looked originally. I am using `GL_NEAREST_MIPMAP_LINEAR` for the texture mode since I don't like the look of the blended textures.

Thank you again for your work and for following up with my question!

My information:

This is a i5-3317u which says is an Ivy Bridge.

https://ark.intel.com/content/www/us/en/ark/products/65707/intel-core-i5-3317u-processor-3m-cache-up-to-2-60-ghz.html

My message when I try to use OpenGL 3.2 and `gl3_particle_square 1`

[stdout.txt](https://github.com/yquake2/yquake2/files/3100932/stdout.txt)

Seems to be related to
```
Probing for OpenGL extensions:
 - Anisotropic Filtering: Max level: 16x
 - OpenGL Debug Output: Supported (but disabled with gl3_debugcontext = 0)
WARNING: Couldn't find uniform block index 'uniCommon'
WARNING: Failed to create shader program for rendering particles!
Loading shaders failed!
ERROR: Loading ref_gl3.dll as rendering backend failed!
```

**Comment by DanielGibson** [comment]
Ok, I guess this is a driver bug; I'll try to reproduce it on my Win10 that has an Intel Iris Pro 5200 GPU - it is only one generation newer than yours, has a different driver download on intels homepage though. We'll see..
Can you attach your `My Documents/YamagiQ2/baseq2/config.cfg`, just in case another setting besides gl_shadows and gl3_particle_square plays a role here.
I can reproduce the broken gl_shadows problem even on Linux+nvidia, I'll investigate it (this used to work...)

**Comment by damontgomery** [comment]
Thanks. Here are my files.

[config.cfg](https://github.com/yquake2/yquake2/files/3101386/config.txt)
[autoexec.cfg](https://github.com/yquake2/yquake2/files/3101387/autoexec.txt)

**Comment by DanielGibson** [comment]
I pushed a fix for the shadow problem to master, thanks for reporting! :)

About the gl3 renderer failing to load with gl3_particle_square: Unfortunately I can't reproduce it on my system. 99.999% sure this is a driver bug, but as I can't reproduce it I can't even try to write a workaround..
Intels GPU (esp. OpenGL) drivers for Windows aren't too great, and the older your GPU is the shittier the drivers are :-/
In case you also have Linux installed on your machine (or feel like trying it out), the (open source) Linux drivers for Intel GPUs are **a lot** better and don't have any known problems with Yamagi Quake II.

**Comment by damontgomery** [comment]
Thanks again!

Let's mark this done.

**Comment by DanielGibson** [comment]
Hmm I might have an idea for a workaround for the other issue.. I'll try to give you an updated ref_gl3.dll for testing later/tomorrow.

**Comment by DanielGibson** [comment]
Hey @damontgomery can you try this:
[yq2_ref_gl3.zip](https://github.com/yquake2/yquake2/files/3114506/yq2_ref_gl3.zip)

If it still doesn't work, please post the corresponding stdout.txt
Thanks! :)

**Comment by damontgomery** [comment]
Thanks, @DanielGibson. With that version, both the shadows and the square particles work. Thanks again!

**Comment by DanielGibson** [comment]
Great, thanks for testing, I just pushed the commit to master.

**Comment by Yamagi** [comment]
A new set of Windows binaries (let's call it 7.41-RC1) with this fix included can be found here: https://deponie.yamagi.org/quake2/misc/quake2-298cb05-20190513.zip
