### ISSUE TITLE
Incorrect weapon lighting.

### ISSUE THREAD

**Issue by m-x-d** [yquake2/yquake2#393]
SURF_DRAWSKY flag is never assigned in GL1/GL3 renderers, yet the code in RecursiveLightPoint and LM_CreateSurfaceLightmap checks for it.

In some setups this can result in incorrect weapon lighting. For example, you can get this ([close to the ground](https://i.imgur.com/N6MM4jg.jpg), [hovering slightly higher](https://i.imgur.com/LN0sqY8.jpg)) at the beginning of the first map of Q2MP2 (rmine1). Looks like Rogue devs used brushes with "light", "nodraw" and "sky" flags to light the maps, and the code in RecursiveLightPoint can pick surfaces form such brushes.

**Comment by Yamagi** [comment]
That's a very nice find. This may explain some other lighting issues in the Rogue levels. We'll look into it.

**Comment by Yamagi** [comment]
I just had a deeper look. You're right, the SURF_DRAWSKY checks can be removed. The flag is never set, so it can never be true. But removing them doesn't change anything, of course. The lighting problems you're seeing are likely caused by badly placed dlights, but I'm not 100% sure.

**Comment by m-x-d** [comment]
The lighting problems are likely related to this:
1. LM_CreateSurfaceLightmap() call is skipped in Mod_LoadFaces(), because the logic checks surf->texinfo->flags for SURF_SKY flag (which is present).
2. Fullbright lightmap is created in R_BuildLightMap / GL3_BuildLightMap.
3. The resulting surface is not skipped by RecursiveLightPoint(), because it checks surf->flags for SURF_DRAWSKY (which is never set) and lightmap presence (which is present).

**Comment by Yamagi** [comment]
Ah, I thought the wrong way. I think we'll need something in the lines of this: c765cbf

Without the fix:
![q2_0001](https://user-images.githubusercontent.com/1224576/57031159-36d64280-6c47-11e9-8cbd-9b407464b471.jpg)

And with the fix:
![q2_0000](https://user-images.githubusercontent.com/1224576/57031183-4b1a3f80-6c47-11e9-864e-b6363af29f35.jpg)

@DanielGibson, you're okay with it?

**Comment by DanielGibson** [comment]
I mean it looks more correct, but maybe that effect was intended?
I can't imagine the addon level designers using the SW renderer to check the looks of their maps (because it has no colored lights) - I guess we should check what it looked like in the vanilla client with its old GL renderer, because that's probably how the creators intended things to look like.

**Comment by m-x-d** [comment]
An alternative solution could be to check surf->texinfo->flags for SURF_NODRAW flag in RecursiveLightPoint(), with the logic being "if it's not supposed to be rendered, it probably shouldn't affect model lighting as well".

**Comment by Yamagi** [comment]
Vanilla Quake II had the bug. While Vanilla Quake II and Yamagi Quake II with GL1 look nearly the same, it's much more pronounced with our GL3 renderer. Screenshots below. What about wrapping the fix the with a cvar, `gl_fixsurfdrawsky` or something like that?

Vanilla Quake II:
![vanilla](https://user-images.githubusercontent.com/1224576/57085491-980c1d80-6cfc-11e9-96b0-00b7bdd4e422.jpg)

Yamagi Quake II GL1:
![gl1](https://user-images.githubusercontent.com/1224576/57085527-a6f2d000-6cfc-11e9-9ab2-9e36bddcf47e.jpg)

Yamagi Quake II GL3:
![gl3](https://user-images.githubusercontent.com/1224576/57085545-af4b0b00-6cfc-11e9-9b06-56b909592bd1.jpg)

**Comment by Yamagi** [comment]
We've just committed the fix. It can be enabled by setting `gl_fixskysurf` to 1, followed by a `vid_restart`. A new set of Windows binaries with the fix and some performance optimizations for AMDs broken OpenGL driver can be found here: https://deponie.yamagi.org/quake2/misc/quake2-d84bc47-20190504.zip

**Comment by DanielGibson** [comment]
and even without `gl_fixskysurf` the GL3 renderer won't look as bright as before in those scenes, but more like the GL1 renderer
