### ISSUE TITLE
Dedicated server remote stop

### ISSUE THREAD

**Issue by SiemensSchuckert** [yquake2/yquake2#394]
q2ded on linux too easy to shutdown:

command from client console:
`download sound/.`

client console messages:
`Downloading sound/.`
`Server fatal crashed: FS_Read: 0 bytes read from 'sound/.'`

server console messages:
`==== ShutdownGame ====`
`Error: FS_Read: 0 bytes read from 'sound/.'`

It seems related to fseek() behavior.
tested with this code:
```
#include <stdio.h>

int FS_FileLength(FILE *f)
{
    int pos;
    int end;

    pos = ftell(f);
    fseek(f, 0, SEEK_END);
    end = ftell(f);
    fseek(f, pos, SEEK_SET);

    return end;
}

#define path "/var/."

void main(void)
{
    FILE *fp;
    int fsize;

    fp = fopen(path, "rb");
    if (fp)
    {
	fsize = FS_FileLength(fp);
	printf("size: %d\n", fsize);
	fclose(fp);
    }
    else
    {
	printf("File not found...\n");
    }
}
```

**Affected:**

    Ubuntu 16.04	ARM64
    (result "size: 4096")

**Not affected:**

    Ubuntu 16.04	x86_64
    (result "size: -1")

    NetBSD 8	amd64
    (result "size: 512")

> no error on NetBSD - fread() reads something from *directory file* and return value is not zero

**Comment by Yamagi** [comment]
You're right. The virtual filesystem should check if the requested file is really a file and not a directory, otherwise the game will shutdown on filesystems that distinguish between files and directories. The good old UFS doesn't.

**Comment by Yamagi** [comment]
We're unable to reproduce this. Did you try it with an older YQ2 version, by chance? But nevertheless we've pushed a possible fix, the game now disallows fopen() on everything that's not a file. Can you give it a try?

**Comment by SiemensSchuckert** [comment]
Fix works, no more exits on directory path downloads like
'download sound/world'
'download maps/.'

Thank you!
