### ISSUE TITLE
Incorrect Hostname field cursor behaviour

### ISSUE THREAD

**Issue by m-x-d** [yquake2/yquake2#396]
In some cases Multiplayer -> Start network server -> Hostname field cursor is positioned incorrectly.

How to reproduce:
1. Start the game, go to "Start network server" menu and select Hostname field. The cursor is positioned at the start of the field (expected: after the last char in the Hostname field).
2. Type some chars into the field, go to previous menu, then enter Start network server menu again. The text changes are reverted, but the cursor position isn't.

**Comment by Yamagi** [comment]
This was a missing strlen(). Thank you for the report. :)
