### ISSUE TITLE
Incorrect weapon position on software renderer

### ISSUE THREAD

**Issue by Rikoshet-234** [yquake2/yquake2#398]
the position of the weapon is closer than on other renders. when I come home I will shoot a few screenshots

**Comment by Yamagi** [comment]
That's a known limitation of the software renderer. See e4665547a8ae0f6e7f806e5a28e74a6bab03635a for details.

At the moment the gun isn't drawn with a field of field independent of the global scene, the model is just scaled to more or less match the field of view given by `r_gunfov`. That's enough to avoid distortions on widescreen resolutions, but misses the necessary z offset used to mitigate the different perspective between the global scene and the gun.  
To solve that problem someone needs to implement real support for different projections matrices (like R_MYgluPerspective() in GL1) into the software renderer. Pull requests are welcome.

**Comment by Rikoshet-234** [comment]
![q2_0146](https://user-images.githubusercontent.com/34555340/57179559-5eafeb00-6e7f-11e9-8bb0-3f588af5a9c2.png)
![q2_0147](https://user-images.githubusercontent.com/34555340/57179560-5eafeb00-6e7f-11e9-8556-38b04bbf1ef1.png)
ok, no problem. this is how it looks

**Comment by Rikoshet-234** [comment]
it's with gun fov 90

**Comment by Rikoshet-234** [comment]
but with gunfov 106.26 it looks normal 
![image](https://user-images.githubusercontent.com/34555340/57179648-52785d80-6e80-11e9-836c-cc9958412b77.png)

**Comment by Rikoshet-234** [comment]
it seems that the values for renders are disproportionate

**Comment by Yamagi** [comment]
They are. The GL renderers are correct, the highly limited software renderer just emulates their behavior by scaling the weapon more or less to the right size. As said, the software renderer needs some love in that regard but neither @DanielGibson nor me will invest time into that. Send pull requests if you want to have it fixed.

**Comment by Rikoshet-234** [comment]
and if you try to port another render ? like the one used in vkQuake2 ? perhaps there will not be such problems ?

**Comment by DanielGibson** [comment]
Why don't you want to use the GL renderers?

**Comment by Rikoshet-234** [comment]
I play GL1-3 most of the time. the problem appeared recently. in version 7.40 there was no such problem. so I decided to find out

**Comment by Rikoshet-234** [comment]
and thanks for respond )

**Comment by Yamagi** [comment]
7.40 didn't have some fixes to the software renderer regarding the gun fov. It assumed a 4:3 aspect ratio, leading to a distorted gun at widescreen resolutions.
