### ISSUE TITLE
Redundant checks in Info_ValueForKey and Info_RemoveKey.

### ISSUE THREAD

**Issue by m-x-d** [yquake2/yquake2#401]
https://github.com/yquake2/yquake2/blob/c57befe80d7e044bc9d48f72ff4c377e948f6ad7/src/common/shared/shared.c#L1245

https://github.com/yquake2/yquake2/blob/c57befe80d7e044bc9d48f72ff4c377e948f6ad7/src/common/shared/shared.c#L1310

These two checks seem redundant.

**Comment by Yamagi** [comment]
Why do you think that they're redundant?

**Comment by m-x-d** [comment]
`while (*s != '\\' && *s) // <- checks for *s
{
	if (!*s) // <- checks for !*s, which should never happen because the above check.
	{
		return;
	}

	*o++ = *s++;
}`

**Comment by DanielGibson** [comment]
ahh, that's what you mean - we somehow assumed you mean it's redundant that it's checked in both functions =)
I agree that this `if(!*s)` check is redundant

**Comment by Yamagi** [comment]
Committed, thank you.
