### ISSUE TITLE
gl_shadows 1 not working on OpenGL 3.2

### ISSUE THREAD

**Issue by iButane** [yquake2/yquake2#403]
Just noticed gl_shadows 1 isn't working with Render OpenGL 3.2 (it works on 1.4) on Yamagi 7.40 and 7.41pre. Not sure how long ago it stopped working or if it's just on my system (Windows 7)

**Comment by DanielGibson** [comment]
Are you sure?
It was broken at some point (maybe even in 7.40), but it has been fixed weeks before the latest snapshot.
Are you using https://deponie.yamagi.org/quake2/misc/quake2-298cb05-20190513.zip (that one works for me) ?
Are you sure you replaced the ref_gl3.dll as well?

**Comment by iButane** [comment]
>Are you using https://deponie.yamagi.org/quake2/misc/quake2-298cb05-20190513.zip (that one works >for me) ?

ok, this one works.. 

I was using https://deponie.yamagi.org/quake2/windows/quake2-7.40.zip

**Comment by DanielGibson** [comment]
ok, you said you also tested 7.40pre so I thought it might have been the one I linked, but maybe it was another older snapshot

glad it works now :)
