### ISSUE TITLE
Save files taking abnormally long to load?

### ISSUE THREAD

**Issue by drogga** [yquake2/yquake2#404]
Everytime I quickload the game, it takes a few seconds. I know it's completely different, but the only engine I can compare to right now is KMQuakeII, where it loads instantly. In addition, when the game finally starts, a few seconds will always have been passed, unless I open the console or the menu via Esc during loading.
Example: I save right when an enemy spots me. After loading he already landed a few shots on me.
I've had this happen in Heretic 2 too, where if I save on a moving platform and reload, the game would put me in midair, making me fall to my death.
Here's my quickload output with developer set to 1:

-===================================-

 Ammo Depot
stufftext: cmd configstrings 719677097 0

Configstrings() from julien
stufftext: cmd configstrings 719677097 8

Configstrings() from julien
stufftext: cmd configstrings 719677097 114

Configstrings() from julien
stufftext: cmd configstrings 719677097 189

Configstrings() from julien
stufftext: cmd configstrings 719677097 208

Configstrings() from julien
stufftext: cmd configstrings 719677097 296

Configstrings() from julien
stufftext: cmd configstrings 719677097 334

Configstrings() from julien
stufftext: cmd configstrings 719677097 366

Configstrings() from julien
stufftext: cmd configstrings 719677097 397

Configstrings() from julien
stufftext: cmd configstrings 719677097 546

Configstrings() from julien
stufftext: cmd configstrings 719677097 1065

Configstrings() from julien
stufftext: cmd baselines 719677097 0

Baselines() from julien
stufftext: cmd baselines 719677097 62

Baselines() from julien
stufftext: cmd baselines 719677097 145

Baselines() from julien
stufftext: cmd baselines 719677097 185

Baselines() from julien
stufftext: cmd baselines 719677097 236

Baselines() from julien
stufftext: cmd baselines 719677097 269

Baselines() from julien
stufftext: cmd baselines 719677097 310

Baselines() from julien
stufftext: cmd baselines 719677097 349

Baselines() from julien
stufftext: cmd baselines 719677097 400

Baselines() from julien
stufftext: cmd baselines 719677097 453

Baselines() from julien
stufftext: cmd baselines 719677097 507

Baselines() from julien
stufftext: precache 719677097

Map: bunk1
                                     
pics
                                     
maps/bunk1.bsp
                                     
models/weapons/v_blast/tris.md2
                                     
models/objects/gibs/sm_meat/tris.md2
                                     
models/objects/gibs/arm/tris.md2
                                     
models/objects/gibs/bone/tris.md2
                                     
models/objects/gibs/bone2/tris.md2
                                     
models/objects/gibs/chest/tris.md2
                                     
models/objects/gibs/skull/tris.md2
                                     
models/objects/gibs/head2/tris.md2
                                     
models/items/ammo/shells/medium/tris.
                                     
models/items/ammo/bullets/medium/tris
                                     
models/objects/debris1/tris.md2
                                     
models/objects/debris2/tris.md2
                                     
models/objects/debris3/tris.md2
                                     
models/objects/barrels/tris.md2
                                     
models/items/keys/power/tris.md2
                                     
models/items/healing/medium/tris.md2
                                     
models/weapons/g_chain/tris.md2
                                     
models/weapons/v_chain/tris.md2
                                     
models/items/ammo/grenades/medium/tri
                                     
models/weapons/v_handgr/tris.md2
                                     
models/items/armor/jacket/tris.md2
                                     
models/monsters/berserk/tris.md2
                                     
models/deadbods/dude/tris.md2
                                     
models/items/healing/large/tris.md2
                                     
models/items/healing/stimpack/tris.md
                                     
models/items/quaddama/tris.md2
                                     
models/monsters/soldier/tris.md2
                                     
models/objects/laser/tris.md2
                                     
models/monsters/infantry/tris.md2
                                     
models/monsters/flipper/tris.md2
                                     
models/weapons/g_shotg2/tris.md2
                                     
models/weapons/v_shotg2/tris.md2
                                     
models/monsters/float/tris.md2
                                     
models/weapons/g_shotg/tris.md2
                                     
models/weapons/v_shotg/tris.md2
                                     
models/weapons/g_machn/tris.md2
                                     
models/weapons/v_machn/tris.md2
                                     
models/weapons/g_launch/tris.md2
                                     
models/weapons/v_launch/tris.md2
                                     
models/objects/grenade/tris.md2
                                     
images
                                     
client 0
                                     
sky
                                     
Begin() from julien

**Comment by maraakate** [comment]
The reason KMQ2 loads very fast (and Daikatana as well) is because MAX_MSGLEN has been raised for Single Player.

**Comment by DanielGibson** [comment]
on my machine loading a savegame takes about 1-2 seconds - yeah, it's not instantaneous, but fast enough IMHO.

**Comment by maraakate** [comment]
Changing MAX_MSGLEN for Single Player is okay, but you will have to write some sort of if/else to trap capping it to 1400 MTU for Multi Player, you will also have to modify the MAX_MSGLEN / 2 problem in configstrings, etc. loading on the server side.

I have also found out from Daikatana, that allowing it load instantly can cause some triggers not to fire on map start unless this is dealt with in a modified code way.  So for YQ2, I'd imagine it's best not to touch it.

**Comment by DanielGibson** [comment]
yeah, sounds like it's not worth the trouble - it's not like it takes half a minute or so (which would be painful enough to try and fix it)

**Comment by Yamagi** [comment]
It may be a good idea to finally have a look at the good, old "The game advances when loading a savegame" problem. That has been on my TODO list since I reworked the savegame system years agos... During savegame load the code needs to forward the world a few frames for spawning the entities in, to establish the trigger->target connections, etc. I've already written comments on at least some places. During a normal load the game states changes, when loading from console (so the game is paused) it doesn't. It should always behave like the savegame was loaded from the console.
