### ISSUE TITLE
[Rogue] [Request] Reintroduce the Disruptor/Disintegrator

### ISSUE THREAD

**Issue by drogga** [yquake2/yquake2#408]
Right now, typing "give disruptor" results in "item cannot be given". It would be awesome if you could add it back into the game. I don't know about vanilla, but it works in KMQuakeII. I can't recall where, but I've read that it was fully functional, albeit commented out in the Ground Zero source code. The maps are said to still have entities for ammo and the weapon itself, at least in multiplayer.

**Comment by Yamagi** [comment]
Fixes, see rogue issue #17 for details.
