### ISSUE TITLE
Yellow Armor wrong amount?

### ISSUE THREAD

**Issue by drogga** [yquake2/yquake2#409]
So: Green, Yellow & Red Armor give 25, 50 & 100 points respectively on their own.
But if you wear yellow armor, green armor will give 12 points (25/2 = 12.5 rounded down)
If you wear red armor, yellow will give 37 (50/1.333 ≈ 37) and green will give 6 (25/4 = 6.25 rounded down)

Shouldn't yellow armor give 25 instead of 37 when wearing red armor? I could swear it was different in the original game. But if not, then this issue can be closed

**Comment by Yamagi** [comment]
Good question. 

Our code is here: https://github.com/yquake2/yquake2/blob/master/src/game/g_items.c#L923
The original code is here: https://github.com/id-Software/Quake-2/blob/master/game/g_items.c#L607

Looks the same. How much armor you get depends on the armor you're wearing and what's left of it. If you've got a red armor and picking up a yellow armor we're running in the case at line 647: ` 50 + (0.80 / 0.60)  * $rest_of_red_armor`

**Comment by Yamagi** [comment]
I've tested it with Vanilla Q2 and don't see a difference. If there's one we need a testcase.
