### ISSUE TITLE
ogg starts playing at track's end (OSX 10.9)

### ISSUE THREAD

**Issue by ellmo** [yquake2/yquake2#41]
I'm using a precompiled 5.11 on OSX 10.9.3.

I thought the game didn't load oggs, but when I typed `ogg_status` this is what I saw:

`Playing file 8 (music/09.ogg) at 157.37 seconds.` – just when I started the map. The `09.ogg` file is 2:37 long, which means the game starts reading the music at the file's end.

I also don't have sound in the cinematics (even the rusty *id* logo makes no sound).

**Comment by Yamagi** [comment]
OS X support was dropped.
