### ISSUE TITLE
"Cvar Operations" commands from q2pro

### ISSUE THREAD

**Issue by josestefan** [yquake2/yquake2#414]
q2pro introduced many new commands. In particular I'm interested in the Cvar Operations,
as shown in their man page here:
https://skuller.net/q2pro/nightly/client.html

They have various commands for manipulating cvars that are very convenient when making scripts, and shouldn't be hard to implement. It would also make scripts and binds designed for 1 source port, more compatible with the other. 

There are command from other sections that may also be of interest (like different types of screenshots)

**Comment by josestefan** [comment]
The relevant code should be here:
https://github.com/skullernet/q2pro/blob/master/src/common/cvar.c

These commands are also in Quake II RTX (by inheritance)

**Comment by Yamagi** [comment]
The CVars itself might be non-portable, both q2pro and YQ2 diverged a lot from the original code... But the CVar operations look like a good idea and shouldn't be too hard to port over. I'll look into it.

**Comment by Yamagi** [comment]
I've ported the `dec`, `inc`, `reset`, `resetall` and `toggle` operations from q2pro. It's already in master and  will be part of the next release.
