### ISSUE TITLE
Support lossless music (FLAC or Wave)

### ISSUE THREAD

**Issue by Marat-Tanalin** [yquake2/yquake2#418]
It would be nice to support music in a lossless format, preferably FLAC for saving drive space, but the generic uncompressed Wave (*.wav) would be sufficient.

Yamagi Quake II currently supports Ogg Vorbis music, but this format is lossy, so the experience can’t be 100% authentic compared with playing with a real game disc. FLAC in the Ogg container does not work, so the only current way to go is apparently lossy. Thanks.

**Comment by Marat-Tanalin** [comment]
Fwiw, [quake2xp](https://sourceforge.net/projects/quake2xp/) supports Wave format along with Ogg Vorbis, so the Wave-support code could probably be borrowed from it given that the both projects are licensed under the same GPL2.

**Comment by DanielGibson** [comment]
Even the hardcore audiophiles at https://hydrogenaud.io/ consider Ogg Vorbis at oggenc `-q 5` mode [transparent](https://en.wikipedia.org/wiki/Transparency_(data_compression)), see [here](http://wiki.hydrogenaud.io/index.php?title=Recommended_Ogg_Vorbis#Recommended_Encoder_Settings) and [here](http://wiki.hydrogenaud.io/index.php?title=Vorbis).

And oggenc goes up to `-q 10`, so it allows for a lot better quality than that (at higher bitrates).
So the experience will be 100% authentic, though you might have to use cheap crappy headphones/speakers for the real 90s experience.

**Comment by Marat-Tanalin** [comment]
@DanielGibson Thanks, but lossy is not an option regardless of what some audiophiles think.

**Comment by 77Mynameislol77** [comment]
at 500kbps, the ogg vorbis format is indistinguishable from lossless when it comes to human hearing.
Maybe if the original Quake II CDs were lossy in the first place, then this would've been a good idea.

**Comment by DanielGibson** [comment]
> @DanielGibson Thanks, but lossy is not an option regardless of what some audiophiles think.

Ok, then you'll have to use another source port - we're not doing any work based on esoteric beliefs.

**Comment by Marat-Tanalin** [comment]
> Ok, then you'll have to use another source port - we're not doing any work based on esoteric beliefs.

No problem. I was probably wrong about the purposes of the project.

I would still like to note that the only esoteric thing mentioned in this thread was “transparency”.

Lossless has no quality loss while lossy has. That’s a _fact_ that doesn’t depend on _subjective_ feelings of _some_ audiophiles.

If a lossy format sounds more “tranparent” than another _lossy_ format, the only thing this means is that that one lossy format (e.g. Ogg Vorbis) is probably preferable over the other lossy format (e.g. MP3). And even if some audiophiles consider that a lossy format has a “transparency” _similar_ to a lossless format, that doesn’t mean at all they wouldn’t prefer lossless one if it was _available_.

Lossless _objectively_ has the _highest_ quality possible, that’s beyond controversy. Thanks for your attention.

P.S. And 90s have _nothing_ to do with the authenticity I mentioned. I meant the _quality_ of a lossy format compared under the same conditions with a _physical CD_ that could be inserted into an optical drive _today_, just with some inconveniences like the drive forced to be the first optical drive in the system.

**Comment by maraakate** [comment]
I've found that life is too short for giving a shit about lossless audio quality of a 20 year old game where the sound quality on the CD-ROM wasn't very good to begin with.  This is coming from someone who enjoys quality audio.

With that said, if you really care about it that much, check out Q2DOS.  I have a Windows port, and it can read WAV.  The reason for this is not because of audio quality, but the target platforms are older machines so decoding OGG and MP3 rob CPU cycles.  Streaming a WAV is practically "free".

**Comment by Marat-Tanalin** [comment]
Considering all those “crappy” and “shit”, you guys unlikely love the subject game you are talking about in such a way, so I’m not sure why you pay _any_ attention to the game in the first place. ;-)

Thanks for the Q2DOS info, Frank.

**Comment by Yamagi** [comment]
I consider myself a 'controlled audiophile'. Over the years I spend a lot of money on high end audio equipment, used it for some time and sold it again. The question if lossy or lossless codecs are the better way to store music is just not the point, in fact it exhibits a fundamental missunderstanding of the challenges connected with high end sound reproduction.

The first and foremost point is, that the human ear isn't that good. Diplomatically said. Our hearing range is limited to 20kHz at maximum, perception is highly dependent on frequency and sound pressure and the ability for spartial hearing is much lower than on most other mammals. There's no human on earth that can here the difference between a 256kbit/s mp3, a -q6 Vorbis, an 192kbit/s AAC, a 128kbit/s Opus, an uncompressed FLAC or CD-Audio.

Now there'e the 2 esoteric arguments that often arises in discussions over digital audio. The first one is the missbelive that sampling leads to quality degradation. It can be answered with a single link: https://en.wikipedia.org/wiki/Nyquist%E2%80%93Shannon_sampling_theorem Nevertheless, there're people that still think that a vinyl record made from digital masters sounds better than a digital copy made from the same masters. Regardless of the fact, that digital copies have a much higher dynamic range, are inherently jitter free, don't wear out, etc.

The second one is even more obscure. People that on the one hand consider themselfs audiophiles and strive for a 100% correct reproduction, but on the other hand say that digital audio is missing "warmth" or "character". Two points that are the outcome of limited dynamic range, wearout, dust and jitter.

No, the digital area is the golden age for audiophiles. Were our parents needed record players, tape drives and more obscure formats worth of thousands of dollars, we can stick to 10$ microcontroller to decode the digital data and 2$ DAC. In the digital age 99% of correct reproduction is down to:

* The speakers or headphones. Good speakers aren't that expensive, for example here in Europe you can get the Dali Zensor 1 for under 300€. But good speakers need good surroundings and alignment and next to no one, including me, has that. We want to live in our rooms and not just listen to music, we have furniture, carpets, wooden ceiclings, etc. In fact, I don't think that it's possible to combine a gaming rig with perfect speaker alignment. With headphone the surroundings are ruled out, but high resolution headphones need high quality drivers. And who combines a high quality headphone with a high quality driver that's galvanic isolated from the soundcard? :)
* The masters. Not all but most popular music is made from low quality masters. The mixing is bad, the result dynamically compressed until it's dead, etc. Not without reason a lot audiophiles are classic or jazz fans. The best example is one of my all time favorites, Running Wilds Pile of Skulls album. It sound good, as long as it's played on el cheapo equipment hiding the flaws. On high end equipment it sound like crap.

Quake IIs soundtrack is of very low quality. To the point that even compressing it int 128kbit/s mp3 can't hurt it much. The ingame assets are available as 11kHz mono waves. So there's just no point in doing all the work to support FLAC. Even if you've got a nearly perfect speaker alignment and surroundings or high quality headphones with a high quality driver, you're still limited by the overall quality of the soundtrack and assets.

And it would be a lot of work. We would have to separate the Vorbis frontend into a generic and a specialized part, implement fallback logic, etc. And is there even a header only FLAC implementation available? So, if anyone is really interested in it, pull request are always welcome. As long as they don't add new external dependencies.

**Comment by Marat-Tanalin** [comment]
> is there even a header only FLAC implementation available?

As I said, the generic Wave (*.wav) format would be sufficient. FLAC would just save about 35% of drive space. The Wave-support code could probably be borrowed from [Quake2xp](https://sourceforge.net/projects/quake2xp/) mentioned by me or [Q2DOS](https://bitbucket.org/neozeed/q2dos/) mentioned by Frank (@maraakate).

_(The substantive part of this comment ends here.)_

> There's no human on earth that can here the difference between a 256kbit/s mp3, a -q6 Vorbis, an 192kbit/s AAC, a 128kbit/s Opus, an uncompressed FLAC or CD-Audio.

_(Feel free to skip this part of the comment up to the end.)_

I’m not an audiophile at all, I don’t like vinyl and warmth, I like digital audio. And Fwiw, I don’t like jazz and prefer precomposed music to improvisation and prerecorded studio music to live performances.

All what matters in terms of lossless/lossy is that lossless has higher quality than lossy _by definition_. With lossless, we have the _original_ quality (no matter how subjectively high or low it is), while with lossy, we have quality degraded compared with the original quality.

Quality losses are _cumulative_. For example, if we transcode from one lossy format to another one, then to a third one, and so on, 100 times, we eventually get noticeable artifacts even if differences between “sibling” encodings are almost unnoticeable. If the original audio has not perfect quality, compressing it to a lossy format _adds_ quality loss to whatever quality the original audio had.

Lossy formats have (actually most _had_) their own purposes, e.g. saving space in a player (not needed anymore), bandwidth in TV broadcasting (not actually needed anymore though still used) or traffic in internet (though even web browsers today support lossless audioformats — both Wave and FLAC), or intentionally creating a worse-sounding _preview_ variant of a _commercially_ available _lossless_ one.

It totally doesn’t make sense to listen to lossy when it’s _possible_ to listen to lossless and there are _no bandwidth or traffic limitations_.

Music in this specific game is what defines at least 50% of its atmosphere (_this_ specific music, _this_ specific game). The “Quake 2” soundtrack is musically one the best soundtracks of all times, and even Sonic Mayhem themselves didn’t compose anything comparable since then. It deserves to have the original CD quality.

“Yamagi Quake II is an enhanced client for id Software's Quake II” is what stated in the project readme. Going from lossless to lossy is certainly not an enhancement. Thanks.

**Comment by Pickle** [comment]
SDL_mixer could be added and that would provide support for many formats
automatically (including flac and ogg).
But I see Yamagi does not want to add any more library dependencies.

**Comment by maraakate** [comment]
Q2 supports wave, obviously, but it does not normally support stereo wave files and it also does not support streaming them.

**Comment by Yamagi** [comment]
> But I see Yamagi does not want to add any more library dependencies.

Yes, we want to keep the number of dependencies as low as possible. Currently we've got a hard dependency on SDL2 and soft dependencies on OpenAL, libGL and cURL. As soon as there is a viable alternative to cURL we'll likely replace it.

Dependencies aren't a problem on Linux, but they're a PITA on Windows and to a lesser extend on OS X. Especially on Windows it's a pain to hardlink the MinGW compiled code  against arbitrary libs, avoid the annoying  Visual C++ Redistribute and keep the crappy Windows Defender happy. One of the points is usually possible, two are problematic and all three impossible. Our Windows port became so much more maintainable as we removed all the hardlinked libs a few years ago...

And to say it again: I'm not against supporting other music formats, as long as they don't add new dependencies. I simple Wave decoder wouldn't, https://github.com/yui0/slibs has single header implementations for several formats and I'm sure that there're others.  
I just won't implement it by myself, because a good implementation would require to split the Vorbis code into a generic part (the glue code to the sound systems frontend, the integration into the OpenAL backend and track mappings) and a specialized part for each format. That's a lot of work, several hours for the initial implementation, some more hours to fix all the obvious bugs (Quake II is still a crappy mess with a lot of interesting hacks and side effects) and even more to fix the obscure bugs... I have a day job, other projects and hobbies, the time I can spend on Quake II is limited. And I don't want to spend that limited time on rather esoteric features but on features and bugfixes that benefit all users.

**Comment by Marat-Tanalin** [comment]
@Yamagi

> would require to split the Vorbis code into a generic part [...] and a specialized part

Wouldn’t it be much easier to _replace_ the current Ogg-Vorbis code entirely with the music-playback code from Quake2xp that already supports _both_ Ogg-Vorbis and Wave?

> That's a lot of work, [...] I have a day job, other projects and hobbies

I see. It’s totally up to you what to spend time on. I appreciate the work you already did anyway.

**Comment by Marat-Tanalin** [comment]
@maraakate

> Q2 supports wave, obviously, but it does not normally support stereo wave files

What does “normally” mean? Does the game support a Wave-format _subset_ limited to mono?

> it also does not support streaming them.

If you mean streaming from a drive, it’s probably not necessary with the current RAM sizes. The largest uncompressed CD-Audio track in the Wave format in Quake 2 (Ground Zero) is 47 MB and it could probably be just copied entirely to RAM at once (like one-shot assets from the `baseq2\players` folder).

**Comment by maraakate** [comment]
Yes, the game normally (as in the original codebase) supports mono (not stereo) wave files.  The game will warn and complain when you try to use stereo wave files.

**Comment by DanielGibson** [comment]
The way normal soundfiles (gunshots and other sound effects) are handled is completely independent of how music is handled, so it doesn't help that it already supports some kinds of wav files.
I didn't look it up now, but it might indeed be limited to a subset, and for normal ingame sounds only mono makes sense anyway because they're played with a position (and the volume on each ear depends on the position relative to the player).

We did so many changes to the sound backend of the years (and I'm sure so did the other source ports) that one can not just copy over code from another source port without major adaptions.

**Comment by Yamagi** [comment]
And I don't think that quake2xp supports custom track mapping which are a requirement to be compatible with the gog.com release.

**Comment by Marat-Tanalin** [comment]
Could you provide details about how exactly such custom track mapping works (other than just stating that this path is for GOG release, and these paths are for regular versions), and what exactly makes the GOG release special, and how exactly yquake2 determines whether it’s GOG release or not.

Quake 2 and Ground Zero contain all the needed music, other expansions contain the same music reordered and their music is unneeded and redundant as a separate thing. Do I understand correctly that the GOG version just contains tracks from Quake 2 and Ground Zero in the same order as the tracks are on CDs, and Ground Zero track numbering (12-21) just starts where basic Quake 2 track numbering (02-11) ends? Can I use such numbering with a regular (e.g. Steam) version of Quake if I would like to prevent music-file duplication? Thanks.

**Comment by Yamagi** [comment]
GOG ships a deduplicated set of Vorbis files in the top level directory, in *music/* next to *baseq2/* and not in it. When searching for music YQ2 first looks into *$moddir/music/*. If it find the files, it uses them. If not, it it looks into *music/* and turns the GOG mapping on. The mapping is here: https://github.com/yquake2/yquake2/blob/master/src/client/sound/ogg.c#L71 

You can't specify a custom mapping but you can put the normal files into *music/* and save some space.

**Comment by Marat-Tanalin** [comment]
[vkQuake2](https://github.com/kondrak/vkQuake2) uses the [miniaudio](https://github.com/dr-soft/miniaudio) library for supporting _FLAC_ and _Wave_ along with _Ogg Vorbis_ and _MP3_.

The miniaudio library is a dual-licensed (Public Domain and MIT) single-file library written in C.

**Comment by Marat-Tanalin** [comment]
Looks like there is a one-file Wave-parsing implementation in Surge (GPL-3.0):

[common/WavSupport.cpp](https://github.com/surge-synthesizer/surge/blob/master/src/common/WavSupport.cpp)

**Comment by Marat-Tanalin** [comment]
QuakeSpasm supports [a bunch of formats](https://sourceforge.net/p/quakespasm/code/HEAD/tree/trunk/quakespasm/Windows/codecs/include/) including FLAC and Wave.

**Comment by DanielGibson** [comment]
use quakespasm then.
