### ISSUE TITLE
game files for 'snap' version

### ISSUE THREAD

**Issue by demoth** [yquake2/yquake2#422]
Hi 
I have installed snap version (https://snapcraft.io/yamagi-quake2-beidl) on ubuntu 19.04
I did not find instruction how to configure snap version to use game files (steam)

I got the same error all the times: `Error: Couldn't load pics/colormap.pcx`
I tried the following:

- run from location where steam game is located ~/.steam/steam/steamapps/common/Quake 2/
- link game files to ~/snap/yamagi-quake2-beidl/40/.yq2/baseq2/
- create ~/.y2q/baseq2/ with links to packs

the steam version (3.20) runs fine (through steamplay, proton-4.6)

I think installation guide is missing the `snap` version hints.
If I got to run the game i can add PR to documentation

**Comment by DanielGibson** [comment]
You should contact the creator of the snap (apparently "Alfred E. Neumayer (beidl)") about this, this is the first time I even heard about a snap of YQ2

**Comment by demoth** [comment]
@DanielGibson I thought about it at first, but then I decided to ask community first

**Comment by DanielGibson** [comment]
https://github.com/fredldotme/yamagi-quake2-snap/issues he even has an issue tracker

**Comment by DanielGibson** [comment]
Also note that the snap is outdated (it's Yamagi Quake II 7.20, we're at 7.41 now) and Ubuntu provides a proper package you can install with **apt** which is less outdated (the one for Ubuntu 19.04 provides YQ2 7.40, see https://packages.ubuntu.com/disco/yamagi-quake2)

**Comment by demoth** [comment]
The solution is to copy files instead of linking.
