### ISSUE TITLE
Resolve issues found by PVS

### ISSUE THREAD

**Issue by demoth** [yquake2/yquake2#426]
Hi

I have run PVS against the code. Attaching the report

https://docs.google.com/spreadsheets/d/1OfSbXinZYwMBbFaYqe5kkO_6qUDOir2-RA0h6YKF4hM/edit?usp=sharing

**Comment by DanielGibson** [comment]
Cool, thanks!
I made a copy of that file that Yamagi and me can edit (to add comments on the issues):
https://docs.google.com/spreadsheets/d/1tJrb3rX3BlKfg4AQM9Y9DklP15hc9PEGG7B7b0JP2Is/edit#gid=2040338039

See also the [pvs-studio-fixes](https://github.com/yquake2/yquake2/tree/pvs-studio-fixes) branch for the current state

**Comment by m-x-d** [comment]
As open-source devs using Git, you can get [a free 1 year pvs-studio license](https://www.viva64.com/en/open-source-license/), which doesn't require adding specific comments to every source file to work.

**Comment by DanielGibson** [comment]
btw, I started fixing those in the following branch: https://github.com/yquake2/yquake2/tree/pvs-studio-fixes

**Comment by coltongit** [comment]
Some if not all of these have been sent to the main branch already.

**Comment by Yamagi** [comment]
I've just merged the last round of changes to master. With this YQ2 itself, both addons and Zaero have all the problems found by PVS studio fixed. Many thanks to all who helped with this. :)
