### ISSUE TITLE
Doesn't compile with MinGW64

### ISSUE THREAD

**Issue by StroggVorbis** [yquake2/yquake2#428]
At least on my end, compiling the master branch with the Windows build environment crashes on startup with an 0xc000007b error. Compiling with MinGW32 works fine, however.

My specs:
GTX 970
i7-4790k
16GB RAM
Windows 7 x64 Home Premium

Edit: Likewise, trying to compile rogue-master with MinGW64 results in every rogue entity missing and the console being flooded with notifications about unknown spawnflags upon starting the expansion.

**Comment by Yamagi** [comment]
An educated guess: You're combining 32 bit libs with 64 bit binaries and vice versa. For a 64 bit build you need a 64 bit SDL2.dll, an openal32.dll and a curl.dll. And an 64 bit mod dll needs a 64 bit yquake.exe binary.
