### ISSUE TITLE
[Bug] Berserker stands around when angered (fix suggestion included)

### ISSUE THREAD

**Issue by BjossiAlfreds** [yquake2/yquake2#433]
I have noticed this happening very occasionally, where a Berserker sees me and plays his anger sound but just stands in place and never attacks.

I believe I found the source of the problem. First notice that in M_MoveFrame, the frame think function is called 'after' the AI function. Berserker's stand move calls berserk_fidget on the first stand frame. If he discovers an enemy at this exact frame and he decides to fidget, the fidget move will override the run move that was instructed earlier in ai_stand->FindTarget->FoundTarget->HuntTarget, causing him to get stuck standing and never attacking since only AI_STAND_GROUND monsters attack while standing.

A quick fix for this should be to return from berserk_fidget without doing anything if the Berserker has an enemy.

**Comment by Yamagi** [comment]
That's a good find and an even better analyzes. I've implemented your suggested fix in berserker branch. At a very test it looks good. Nevertheless, I need to play a little bit with it before I can merge it into master. I need to be sure that it doesn't break anything else.

**Comment by Yamagi** [comment]
I've merged it to master. And I'll commit the change to both addons. Thank you!
