### ISSUE TITLE
Enemy behavior in mission packs is different from the original non-Yamagi behavior

### ISSUE THREAD

**Issue by Marat-Tanalin** [yquake2/yquake2#435]
Stumbled upon a _third-party_ russian-language [comment](https://www.gamesrevival.ru/games/Quake_2/Yamagi_Quake_II/) describing an issue with mission packs when using “Yamagi Quake II” compared with when the same mission packs are played using the original non-Yamagi executables.

Can’t confirm or deny it or provide details on it (I didn’t even ever played mission packs), but thought it may be interesting for “Yamagi Quake II” developers.

Here is a translation of the original Russian-language text as far as I understand it (the text in square brackets is mine for extra clarity):

> In addons, the enemies act totally not how they should. They should have an improved [in mission packs compared with the non-addon “Quake II”] behavior there, e.g. iron girls in Reckoning have homing missiles which are missing here [in “Yamagi Quake II”]; the tanks should quickly shoot missiles after laser instead of slowness in the original [non-addon “Quake II”] game, this is not the case here [in Yamagi Quake II] again.

The original Russian text for completeness:

> в аддонах враги действуют совсем не так, как должны. У них там должно быть улучшенное поведение, например железные девы в Reckoning имеют самонаводящиеся ракеты, здесь их нет, танки резко выстреливают ракетами после лазера вместо своей заторможенности в оригинале, здесь этого опять же нет.

**Comment by Yamagi** [comment]
Hmm.. There might be difference in enemy behavior due to merge errors, wrongly placed sanity checks and slightly different code interpretation between the old MSVC6 and modern gcc / clang compilers. There are usually easy to fix if we know were to look. Does he mention which addon has the problem?

**Comment by Marat-Tanalin** [comment]
> iron girls in **Reckoning**

The tanks’ issue is probably in Reckoning too. I added a russian question comment there and referred to this GitHub issue. If the original reporter speaks English, he will probably come here and answer.

**Comment by Yamagi** [comment]
Okay, I found a difference in the homing missile code. It broke the Iron Maidens homing missiles, the normal ones were working as expected. The nearly untested fix is here: https://github.com/yquake2/xatrix/commit/787d66272e7e3270e2c1503e9a3e46319e219646

I didn't found a difference in the Tanks animation sequences and in the attack code. But that doesn't mean that there isn't a problem. I'll have a deeper look in the next few days.

**Comment by Yamagi** [comment]
The fix is wrong. I'll have another look in a few days.

**Comment by Yamagi** [comment]
The homing missiles are now working again. And I think that I found a similar bug (from a code perspective) in the gekk.

**Comment by Maelstrom-rl** [comment]
Tank may have a behavioral bug, not animation.

**Comment by Yamagi** [comment]
Yeah. I did some tests with the first Tank in refinery.bsp, so far I was unable to see a difference. The next step is to test against the original game.dll from 1998, to rule out the compiler. If that doesn't help it would be nice if someone could point me to a location were it happens.

**Comment by Yamagi** [comment]
So far I'm unable to see any difference in tank behavior between vanilla rogue and our version. This doesn't mean that there aren't any, we had a lot of obscure AI bugs that happened only in very specific situations. For example the one that triggered only for monsters that stood elevated to an bunny hopping player... I need a example to debug this. At least a location were it happens and how to trigger it. Often a video showing the problem is very helpfull.
