### ISSUE TITLE
[Bug] Monsters hunting for sound target cannot see the enemy (fix suggestion included)

### ISSUE THREAD

**Issue by BjossiAlfreds** [yquake2/yquake2#436]
This is an original AI bug but also exists in yquake2. It also affects xatrix and rogue.

To reproduce:
1. Go to level bunk1 (Ammo Depot), starting room
2. Make sure notarget is OFF and give yourself machinegun and bullets
3. Kill the machinegun guard by the first door
4. Start firing the machinegun constantly and jump down to the lower floor with the other guard and the super shotgun
5. Do not stop firing the machinegun and do not hurt the guard
6. Notice that the guard hears your machinegun fire and runs to you but does not see you

What is happening is that PlayerNoise() makes a sound target every single frame when you fire the machinegun, so when the monster calls FindTarget() it will always hunt the sound target, never seeing you or other players even in plain sight. This is a starvation problem, where one event (sound) gets all attention and others are ignored (sight).

The simplest fix, I believe, is to set a short time-out on generating sound targets. For example you can add in PlayerNoise() "if (level.framenum <= (level.sound_entity_framenum + 3)) return;" right before SELF or WEAPON noise is created, and similar check for IMPACT and level.sound2_entity_framenum. This makes it so no new sound targets are created until 3 frames have passed since the last one, giving monsters 2 frames to see the enemy before they hunt the next sound target.

I have tested this change and it seems to work well, monsters see me when I am visible to them, even while firing the machinegun.

**Comment by Yamagi** [comment]
Cool. Thank you for the report and the fix suggestion. If implemented it and committed the change to master. I'll do the same for both addons.
