### ISSUE TITLE
[Bug] Attacking monster AI freezes if enemy becomes NULL or not in use (fix suggestion included)

### ISSUE THREAD

**Issue by BjossiAlfreds** [yquake2/yquake2#438]
To reproduce:
1. Go to map jail3
2. Make the Icarus by the lava pit fight a Flyer in the starting area
3. If the Icarus kills the Flyer, he becomes frozen in place until you hurt him

This happens because ai_run() returns if !self->enemy or !self->enemy->inuse, which happens for the Flyer because his death function calls G_FreeEdict(). These checks are incorrect because the AI needs to discover it has no enemy and change its state, for example to stand or hunt their old enemy, which is done in checkattack(). Removing !self->enemy || !self->enemy->inuse from the if-statement should do the trick.

**Comment by Yamagi** [comment]
This is the crap with Q2s spaghetti code. Fixing (or at least trying to do so) introduces another one... I've implemented your suggested fix. I'm 90% sure that it's correct. If the game crashes with `self->enemy` being `NULL` we've got another bug somewhere. I'll merge it also into both addons.

**Comment by BjossiAlfreds** [comment]
Yes I'm currently not aware of any situation where enemy becomes NULL or not-in-use while monster is running to a combat point or sound target, both of those entity types are never freed by G_FreeEdict. If that scenario does happen then something is definitely wrong and may be tricky to discover without extensive flow analysis.
