### ISSUE TITLE
[Bug] Monsters rarely fight back when attacked by Parasites (fix suggestion included)

### ISSUE THREAD

**Issue by BjossiAlfreds** [yquake2/yquake2#440]
To reproduce:
1. Go to a map with a Parasite, like jail2
2. Get a ranged monster to accidentally hit a Parasite
3. You will most likely observe that the monster lets the Parasite drain it to death without fighting back

This is caused by viewheight. The Parasite is a very small monster, so the hard-coded viewheight given to monsters in walkmonster_start_go() (25) is actually above the Parasite's bbox whose maxs[2] value is 24. This causes traces like in visible() to overshoot the Parasite at a lot of angles.

One way to fix this is to (in walkmonster_start_go()) put "self->viewheight = 25;" inside an if-statement: "if (!self->viewheight)". This allows for giving monsters specific viewheight values in their respective spawn functions. I think a "correct" viewheight would be around 8-16 but as long as the value is lower than maxs[2] it should be fine.

I checked other small monsters for this and it seems only the Fixbot in Reckoning has the same problem, where flymonster_start_go() sets viewheight to 25 but Fixbot has maxs[2] of 24 like the Parasite. You can apply the same fix there and it should do the trick.

**Comment by Yamagi** [comment]
Thank you. Fixed an commited. Would be nice if you could send such things as pull request, if you already have the code it's easier and less error prone to just merge it and not applying it by hand.

**Comment by BjossiAlfreds** [comment]
Sure, I will do that for anything else that might come up in the future. These issues I report to you these days I actually discovered, debugged and fixed over a longer period of time through developing my own Q2 gamex86 mod. I decided to share my findings with this project so that these improvements to the game reach a large player base, since I am the only one who will ever play my own mod.

**Comment by Yamagi** [comment]
> I decided to share my findings with this project so that these improvements to the game reach a large player base, since I am the only one who will ever play my own mod.

And that's very cool. All of those are long standing bug I didn't knew about or I never had the motivation to look into. :)

Have you ever experienced the 'empty models' bug in Ground Zero? Medic commanders spawning a lot of monsters, with a little probability the spawned monster will get stuck before the bbox is applied. The result is an non-moving monster without clipping, just standing around and doing nothing. I have never found what causes it. The only thing I can say for sure is that the entity for the spawned monster is send to the client, something happens in the game and the client is left with an entity no longer present in the game and server.

**Comment by BjossiAlfreds** [comment]
Hmm, I don't remember experiencing that before, sounds very strange because monsters receive their bbox and solidity in the spawn function, before any thinking needs to be done. But at the same time it isn't that surprising, rogue's minion spawning code for the bosses and medic commander is very hacky and makes it obvious the game code did not anticipate this mechanic, so who knows where it is breaking...

What may be possible is to do before/after debugging, where you put before and after code at key locations to catch the entity in a good state before and the bad state after. Then you slowly push the before and after code together, in small steps, until you narrow it down to a single function call or statement. This is how I found the exact moment where the Parasite gets stuck in the world. It may not necessarily show you the source of the bug, but it may give an important clue or a workaround.
