### ISSUE TITLE
[Bug] Parasites get stuck in the floor and fall through on death (workaround suggestion included)

### ISSUE THREAD

**Issue by BjossiAlfreds** [yquake2/yquake2#443]
There are no exact steps to reproduce this, just fight a Parasite with a weapon with kickback and you should eventually see it happen, where the Parasite gets stuck in the floor, and once it dies and finishes the death animation it falls into the floor and disappears. For example this happens very frequently to me with the first 2 Parasites in base3 or the Parasites behind the red key door in jail2.

I have memories of encountering this bug when I originally played the game 20+ years ago and perplexes me to this day, still seeing it happen in yquake2. Though it is worth mentioning that this only affects baseq2 and xatrix, rogue added their own method of fixing entities going into the world geometry, in G_RunEntity() I believe.

Through extensive debugging I was able to pinpoint the exact line of code that places the Parasite inside the level: in g_phys.c:, SV_FlyMove(): VectorCopy(trace.endpos, ent->s.origin);

For some reason I can not explain, the trace end position goes slightly into the level geometry, and stranger still, it only seems to happen to the Parasites, I have never seen this happen to any other monster or object. My best guesses are that either this is a bug in the collision-detection system that has to do with the Parasite's specific bbox size, or some Parasite-specific code in the gamex86 is causing the entity to go into a bad collision state. Either way I'm not at all familiar with Q2's collision-detection system so am ill equipped to debug and fix this properly.

But there is a simple workaround that can be applied on the gamex86 side, at the cost of 1 extra trace. 
Before the call to SV_FlyMove(), copy the entity's current origin to a local temporary vector variable:

```
...
VectorCopy(ent->s.origin, oldorig);

SV_FlyMove(ent, FRAMETIME, mask);
...
```

And right after the call ends, compare the current origin to the oldorig one. If they are different, perform a point trace and if the trace is startsolid, copy oldorig back into the entity's origin.

```
...
SV_FlyMove(ent, FRAMETIME, mask);

if (!VectorCompare(ent->s.origin, oldorig))
{
	tr = gi.trace(ent->s.origin, ent->mins, ent->maxs, ent->s.origin, ent, mask);

	if (tr.startsolid)
	{
		VectorCopy(oldorig, ent->s.origin);
	}
}

gi.linkentity(ent);
...
```

Since applying this workaround in my own code I have not seen the Parasite get stuck or fall through the floor so it seems to work well. Though of course a proper fix would be preferable, if you feel up for the task to debug the trace that puts the Parasite inside the world.

**Comment by Yamagi** [comment]
> I have memories of encountering this bug when I originally played the game 20+ years ago and perplexes me to this day, still seeing it happen in yquake2.

Because I never had the motivation to look into it. :)

> Either way I'm not at all familiar with Q2's collision-detection system so am ill equipped to debug and fix this properly.
The collision detection is very complicated. I had understood it years ago. or at least I thought so. But I've forgotten most of it. Anyway I don't think that it's good idea to change anything in the collision detection code, even bugfixes would have a very high probability to break things... Most assets are build around the buggy code.

**Comment by BjossiAlfreds** [comment]
Yes you are right, some code is just best left alone. The workaround will not inflict any noticeable performance impact even on older computers any ways (rogue were using traces very liberally even back in 1998...).
