### ISSUE TITLE
[Bug] listentities sometimes crashes the game when class is anything other than 'all'

### ISSUE THREAD

**Issue by StroggVorbis** [yquake2/yquake2#444]
The new commands are great, thanks for adding!
But I have a bug to report:
Every class except 'all' crashes the game after reloading a save or revisiting a level in a hub.
Also, the two commands aren't shown when hitting tab yet.

Edit: The crash isn't related to reloading or reentering. It worked fine again in the second hub even after multiple quicksaves and -loads and then suddenly didn't again. I'd attach a log, but stderr.txt is empty and stdout.txt only contains console history, :/

Edit #2: Dunno if it can be of use, but here's stdout: https://pastebin.com/amWWP8ih

**Comment by BjossiAlfreds** [comment]
Looking at the code I see immediately that entity inuse isn't checked in the print loop, so the game is probably crashing due to calling strncmp with NULL classname.

**Comment by Yamagi** [comment]
Yeah, that was a stupid oversight. I've pushed a fix.
