### ISSUE TITLE
[Original bug(?)] Monsters often play wrong sound if killed by shotguns (detailed discussion)

### ISSUE THREAD

**Issue by BjossiAlfreds** [yquake2/yquake2#448]
I would have done a pull request for this but I actually don't have it implemented in YQ2, only my own gamex86 mod, plus I don't know if you'd actually see this as a bug, and one worth fixing. So I'll just describe it and then discuss how I fixed it.

The most obvious way to reproduce it is to kill monsters with the shotgun. You will notice that most of the time they play a pain sound instead of a death sound, and pain or death sound instead of a gibbing sound. The pain sound replacing the death sound I didn't mind so much, but it's when the gibbing sound gets replaced that I find it jarring and anomalous.

This happens because monster damage reaction is not aggregated - it is (partially) executed every damage event, so once for every shotgun pellet. And since gi.sound() doesn't override an already scheduled sound event for a given channel, the first scheduled sound gets played. A fix would have been to implement damage aggregation for monsters. While it wouldn't be complicated, it would mean gameplay changes because monsters would start playing their high-damage pain moves when hurt by shotguns, like berserker falling to the ground.

A more relaxed fix that only addresses the sound issue is what I did in my own mod:

1. In every monster pain and die function, instead of calling gi.sound() directly for pain/death/gibbing, you assign the sound index and attenuation to self's edict, I went with self->sounds and self->attenuation since those are unused by monsters (you can add new variables for this if you prefer, of course). This ensures that the most up-to-date sound gets scheduled, so if the first shotgun pellet hurts the monster but the 13th gibs it, the gibbing sound will be the scheduled sound that gets played.

2. Inside G_RunFrame() in g_main, add a 2nd loop after the G_RunEntity() loop. This loop is a sort of post-frame loop where you can aggregate results after running all the entities. This loop is where you check if a monster entity has a sound event scheduled, and if that is the case, call gi.sound() using the stored sound and attenuation (don't forget to clear the variables after calling gi.sound()!).

3. It is worth mentioning the insane marines specially. You may have to add a check in their moan and scream functions for whether there is a scheduled sound, otherwise their moan/scream will often override it.

This is fairly straight-forward but can be error prone due to having to modify every pain/die function for every monster, but if you forget a couple it won't have any bad effects (simply means they would still play the wrong sound like they do now).

**Comment by BjossiAlfreds** [comment]
Hmm if I read into this right, the sort always starts at the next sound, so the first sound is never challenged. (I have actually never looked at the client sound code so this is all new to me, btw)

One could argue that making the most recently scheduled sound take priority, but this may not always be what the user (game.dll) wants. If you fix this at the client it would most likely not have any negative effects elsewhere, but it is worth keeping the possibility in mind at least, documenting it in a comment.

**Comment by bibendovsky** [comment]
I think this sorting put "death" sound before "pain" ones because their begin time (field "begin") are equal.

In the end S_IssuePlaysound overwrites channel's audio data (field "sfx") with "pain" sound, since all those sounds have the same entity (for simplicity we assume all pellets hit only one target) and voice channel.

**Comment by BjossiAlfreds** [comment]
Well you could try change < to <= and see what happens, that would reverse the order in which equal begins appear in the pending list.

**Comment by bibendovsky** [comment]
Fixed with "less-or-equal" solution Windows builds.

[yquake-win32-448-001.zip](https://github.com/yquake2/yquake2/files/3611045/yquake-win32-448-001.zip)
[yquake-win64-448-001.zip](https://github.com/yquake2/yquake2/files/3611047/yquake-win64-448-001.zip)

**Comment by BjossiAlfreds** [comment]
Can confirm that this works, didn't notice any negative side-effects from this change either.

**Comment by BjossiAlfreds** [comment]
Crusified insane marines need special handling though, since their pain move plays a moan sound in the first frame. Simply moving that sound to the 2nd frame should avoid this, I don't think anybody would notice that 0.1 second delay...

**Comment by bibendovsky** [comment]
> Crusified insane marines need special handling though, their moan sound is overriding the pain sounds.

This is a game specific issue.

**Comment by Yamagi** [comment]
I'm answering only here and not at pull request #450 to keep the discussion in one place.

I never noticed that problem. Now, after I've been pointed to it, it's obvious. I like the fix suggested by @bibendovsky better, because it's much less invasive and it works for all game.dll. The big questions is: Has any unwanted side effects? At a very first look I think that @bibendovsky  is right, there aren't any.

I'll do some more testing later today or tomorrow. If I don't see any problems I'll merge the pull request.

**Comment by BjossiAlfreds** [comment]
Agreed, changing < to <= is a heck of a lot simpler. I only went with the gamex86-centric workaround in my mod so that it would work across engines, but obviously that is not a problem with YQ2.

**Comment by Yamagi** [comment]
I've played through the first two units and it sound okay, so I've merged the pull request.
