### ISSUE TITLE
Autoexec.cfg key bindings not working correctly

### ISSUE THREAD

**Issue by Q3BFG10K** [yquake2/yquake2#453]
This is for the Ground Zero expansion (Rogue).

**Autoexec.cfg (inside \Rogue) contains:**
bind w "use prox launcher"
bind t "use etf rifle"
bind r "use plasma beam"

**I start the game with:**
+set game rogue +disconnect -portable

**But for the last binding, Yamagi is doing:**
bind r "use plasma beam set game rogue"

It looks like one of the launch parameters is incorrectly added to the key binding.

In case it makes any difference, I have no config or autoexec in \baseq2 as I never launch the vanilla game.

**Comment by Yamagi** [comment]
That's likely another bug in this [censored] command line / config file parser crap. Are you on Windows, Linux oder MacOS?

**Comment by Q3BFG10K** [comment]
Win7-64.

**Comment by Yamagi** [comment]
This look Windows specific, it's easily to reproduce on Windows but so far I can't reproduce it on Linux. And it happens only if the autoexec.cfg doesn't end with an empty new line. We'll see if we can come with a fix but it'll take a few days.

**Comment by Yamagi** [comment]
This was a stupid bug and it was already in the original code. The command parser splits commands at newlines. When a file doesn't end with one it combines it's last line withe the first line of the next file or the first command given on the command line, depending on how the game was started. We fixed this by injection a newline at the end of each file.
