### ISSUE TITLE
[Original bug] Technician (floater) melee zap attack always hurts the enemy

### ISSUE THREAD

**Issue by BjossiAlfreds** [yquake2/yquake2#454]
To reproduce:
1. Find a technician to annoy
2. Get him to start his melee zap attack
3. Quickly open the console and use the teleport command to teleport to another part of the level (you can use the entitylist command to choose co-ordinates)
4. Notice that the attack still hurts you even if the technician is in another part of the level

This happens because the zap attack function does not check for angle, range or visibility, it always calls T_Damage regardless of those things.

Possible fixes would be to replace T_Damage call with fire_hit, or use range(), infront() and visible() to guard the call to T_Damage. Opinions?

**Comment by Yamagi** [comment]
So this happens always if the player manages to get away, e.g. strafes to the side, jumps backward, etc.?

**Comment by BjossiAlfreds** [comment]
Yes the damage is dealt unconditionally so regardless of your location in the level you take the damage. The only way to prevent it is to hurt or kill him to cancel the move before the damage frame plays out.

For the longest time I never noticed this but once I did I got curious and investigated what the code is doing.

**Comment by Yamagi** [comment]
Okay, I had a deeper look. `fire_hit()` won't work because it's for melee damage (DAMAGE_NO_KNOCKBACK)  and the floaters zap attack applies energy damage (DAMAGE_ENERGY) . The easiest way to fix this would be a call to `range()` and to apply the damage only if RANGE_MELEE is applied. This would be consistent to the flyer / chick.

Something like this (untested):
```
diff --git a/src/game/monster/float/float.c b/src/game/monster/float/float.c
index 1cb651a7..423d9b0a 100644
--- a/src/game/monster/float/float.c
+++ b/src/game/monster/float/float.c
@@ -665,9 +665,12 @@ floater_zap(edict_t *self)
        gi.WriteByte(1); /* sparks */
        gi.multicast(origin, MULTICAST_PVS);
 
-       T_Damage(self->enemy, self, self, dir, self->enemy->s.origin,
-                       vec3_origin, 5 + randk() % 6, -10, DAMAGE_ENERGY,
-                       MOD_UNKNOWN);
+       if (range(self, self->enemy) <=  RANGE_MELEE)
+       {
+               T_Damage(self->enemy, self, self, dir, self->enemy->s.origin,
+                               vec3_origin, 5 + randk() % 6, -10, DAMAGE_ENERGY,
+                               MOD_UNKNOWN);
+       }
 }
 
 void
```

**Comment by BjossiAlfreds** [comment]
That is pretty much identical to how I ended up fixing it in my codebase.

Though when I think about it, it may be desirable to also add visible() and infront(). Visible so that you can hide behind thin walls of cover or around corners, and infront so that you don't take damage at weird angles while you are in melee range (though I doubt it is possible to do this since ai_charge turns the monster towards its enemy very quickly).

**Comment by Yamagi** [comment]
I've committed the fix.
