### ISSUE TITLE
[Original bug] Triggered spawn monsters don't walk to path_corner markers

### ISSUE THREAD

**Issue by BjossiAlfreds** [yquake2/yquake2#458]
Discovered this one while doing ent scripting. Basically if a monster is triggered to spawn (spawnflag 2), it will just stand in place despite having a target pointing to a valid path_corner marker.

I provide an ent script example with this bug report, security.ent. When you load it, use notarget and move forward until you reach the T-section. You will see a blaster guard walking back and forth, and a shotgun. The shotgun spawns another guard in the other corridor and he is supposed to start walking the same way as the other guard but simply stands still.

Here is the ent script (since github is dumb I had to rename it to .txt, please rename to .ent again to use it in-game).
[security.ent.txt](https://github.com/yquake2/yquake2/files/3638459/security.ent.txt)

I can provide a pull request that fixes this issue with explanation on why this happens.

**Comment by Yamagi** [comment]
I've merged all three pull requests. Thank you and keep up the good work!
