### ISSUE TITLE
Icon trademark

### ISSUE THREAD

**Issue by Eonfge** [yquake2/yquake2#462]
Last week, I created a package for Flathub so that Yamagi Quake 2 can be run on any linux distribution: https://github.com/flathub/flathub/pull/1174

There is only one problem for which I do not have a proper solution at the moment: Do you have a non-trademarked logo for Yamagi? Right now, you're using the actual Quake 2 logo, which is legal property of Bethesda Softworks, which also happens to be a company with a strong legislative culture, so we do not want to use the actual Quake 2 logo on Flathub.

https://bethesda.net/en/document/legal-information
https://www.polygon.com/2018/6/28/17511658/bethesda-lawsuits-fallout-elder-scrolls-prey

 I'm no good with Inkscape though, else I would have made my own riff. If somebody, you or other, could provide us with a logo that's not the same (or to similar) to the official logo, then we can use that in the package.

**Comment by Eonfge** [comment]
@deuxsonic you made the original icon. Perhaps you got something to add to the discussion?

**Comment by Yamagi** [comment]
So far we don't have a custom logo. But if someone has a suggestion we're happy to adopt it. :)

Also keep in mind that both addons were never released under the GPL. They're released under the crappy SDK license and aren't really open source: https://github.com/yquake2/rogue/blob/master/LICENSE

**Comment by Eonfge** [comment]
This is about the most that I can do:

![org yamagi YamagiQ2](https://user-images.githubusercontent.com/33983090/65688521-97897000-e06b-11e9-827b-40807098c630.png)

Mind you, it's not bad if the logo references Quake 2, but it can't be the same logo. ezQuake has a pretty good logo in my opioning: It's Quake related, but not quake itself: https://ezquake.github.io/

**Comment by Yamagi** [comment]
The problem with your suggestion is, that the Quake II logo is still part of it. And the Strogg emblem might not be a registered trademark, but it's still protected by copyright law. Anyway... Since even Debian ships our icons and a low resolution Quake II icon was released as part of the GPL code, we'll stick with what we've got.
