### ISSUE TITLE
Force menu off after load quick.

### ISSUE THREAD

**Issue by apartfromtime** [yquake2/yquake2#473]
I often use "load quick" (default key F9) to load a save game and noticed that when the menu is pushed to screen a "load quick" command doesn't force the menu off, similar to say the console. Not sure what the fix suggestion would be.

A last save quick, load quick slot in the load game menu would also be a nice feature to add, so players can see their last save quick point.

**Comment by Yamagi** [comment]
Forcing the menu off when a savegame is loaded through the console or a keybinding might be next to impossible. The savegame stuff is at server side, the menu at client side and we can't alter the protocol between them. Maybe we could hook into the `put the game into pause mode while the savegame is loaded`-magic I added some weeks ago. But that wouldn't work in all cases, only for local single player games. I'll need to ponder over it.

Adding the standard quicksave slot the menu isn't hard and it's a good idea. I think we'll do that.

**Comment by apartfromtime** [comment]
Pull request #476.

**Comment by Yamagi** [comment]
I've added the quicksave slot to the load and save menus. And I've decided against forcing the menu off after savegame load, because it's a user visible behavior chance and hard to implement in a reliable way.
