### ISSUE TITLE
Loading times

### ISSUE THREAD

**Issue by DwarfFighterCleric** [yquake2/yquake2#487]
It's not really an "issue" but I figured I would have a quicker response here, and not having to create account on different forums out there... So is it normal for the Yamagi Quake2 to take a long time reloading savegames? "Long time" meaning 5 seconds for a save to load... I thought the engine cached stuff so it would be readily available on memory. Is there a config to remedy this?

**Comment by Yamagi** [comment]
Hi,
I'm afraid that's normal. The "problem" here is that loading a savegame restarts the server. That flushes the caches and the client needs to reload everything. Some source ports like r1q2 work around it by some kind of lazy loading, they're only loading what's necessary before the game startes and everything else at a later time. While that improves loading times, the player may / will see some missing assets plopping up. Therefor we never implemented that.

Regards,
Yamagi
