### ISSUE TITLE
MSAA 16x not applied

### ISSUE THREAD

**Issue by mgtroyas** [yquake2/yquake2#488]
When choosing 16x as MSAA on video options, and selecting apply, option is reset to "no" and no MSAA is applied. 2x - 8x is working  ok.

**Comment by DanielGibson** [comment]
then probably your GPU or driver doesn't support 16x

**Comment by mgtroyas** [comment]
I use a rx 580, and can sucessfully enable 16x on other games and ATI Control Panel. With my old HD5830 the maximum option shown was 4x.

**Comment by Yamagi** [comment]
Like @DanielGibson said: This is a problem with the GPU driver not supporting the 16x MSAA mode.
