### ISSUE TITLE
GL_TEXTUREMODE ignored on vid_restart

### ISSUE THREAD

**Issue by mgtroyas** [yquake2/yquake2#489]
If GL_TEXTUREMODE is set for instance to GL_NEAREST_MIPMAP_NEAREST and you execute vid_restart, textures are filtered as if GL_LINEAR_MIPMAP_LINEAR was the value set.

If you close the client and run it again, the correct option is used again.

**Comment by DanielGibson** [comment]
you're right, the cvar is not used to set the default texture mode, I'll have to fix that, see also #491

**Comment by mgtroyas** [comment]
Great, thank you!

**Comment by DanielGibson** [comment]
suggested fix in #494

**Comment by mgtroyas** [comment]
Fixed, it now maintains the texturemode after vid_restart.
