### ISSUE TITLE
HUD elements ignore GL_TEXTUREMODE when using OpenGL 3.2

### ISSUE THREAD

**Issue by DenisBelmondo** [yquake2/yquake2#491]
HUD elements don't seem to respect the gl_texturemode cvar when using OpenGL 3.2. May be related to #489?

**Reproduction steps:**
Open the video menu, set the renderer to Open GL 3.2 and apply. Then, open the console and set gl_texturemode to "GL_NEAREST", exit the game and start it up again (since #489 says that vid_restart may not work), and observe the HUD elements as they are still drawn with linear filtering.

**Comment by DanielGibson** [comment]
I guess this is a feature, already exists in the original GL1 code (or at least our GL1 code).
2D elements and skies are ignored when changing gl_texturemode cvar - no idea why.
(As you have probably observed, changing the cvar changes the filtering of world and model textures immediately, without vid_restart or anything)

However, there definitely is a bug with the default filter modes not being set from the cvar when starting the GL3 renderer, I'll have to fix that.

No idea about 2D elements ("pics") and skies, we'll have to do some digging and try to guess why they're explicitly ignored in R_TextureMode()/GL3_TextureMode().

**Comment by DanielGibson** [comment]
Looks like this behavior (pic and skies being ignored for texturemode) was indeed already present in vanilla Q2: https://github.com/id-Software/Quake-2/blob/master/ref_gl/gl_image.c#L226

"// change all the existing mipmap texture objects" sounds like it's only supposed to done for textures with mipmaps - maybe they assumed the others wouldn't get filtered anyway?
And for GUI textures it was probably true: **We** added menu/HUD/... scaling, so before they would've been renderered in original size and needed no filter
But the sky.. while it's always rendered at the same distance from the player, so IMO it would make sense to set a filter?

HOWEVER, I just tried removing the check for `it_sky` and `it_pic` and then, when I change the filtering mode to one with "_MIPMAP_" in the name, the HUD and sky textures turn black. just GL_LINEAR and GL_NEAREST work though.
However, checking if a texture is pic/sky and in that case using `gl_filter_max` for `GL_TEXTURE_MIN_FILTER` (like it's also done ~100 lines below in `GL3_Upload32()`) fixes that.

So anyway, I'll clean up my fixed code later and commit it.

**Comment by DanielGibson** [comment]
suggested fix in #494

**Comment by DenisBelmondo** [comment]
Awesome! Just pulled and recompiled. The changes work for the HUD and sky as advertised. Minor bug: but when switching renderers from GL3, to GL1, and then back to GL3, the texture mode is no longer respected :( when this happens, gl_texturemode in the console still reports as user setting (GL_NEAREST in my case) and the texture mode is still not respected after a vid_restart. Restarting the game does end up having it display the textures with the correct texture mode, though.

As a side note, the "THE END" screen seems to be immune to the gl_texturemode setting in both GL renderers. Should I submit these in separate bug reports?

![Untitled3](https://user-images.githubusercontent.com/8296741/70515626-e3887480-1af2-11ea-9872-3386629d4929.png)

**Comment by DanielGibson** [comment]
I think the "THE END" screen is a video, or do I misremember?
Anyway, I'll look into the filter mode used there; I'll also look into the GL3->GL1->GL3 behavior

**Comment by Yamagi** [comment]
If I remember correctly the THE END screen is a pcx image file.

**Comment by DanielGibson** [comment]
I fixed video rendering (or anything else using `Draw_StretchRaw()`) respecting gl_texturemode, I didn't have time to check whether this also fixes "THE END" though.

I couldn't reproduce the issue with GL3->GL1->GL3.
