### ISSUE TITLE
Minor typo in ogg.c:getMappedGOGtrack()

### ISSUE THREAD

**Issue by voodoo84** [yquake2/yquake2#504]
Hi all,

There is a small (and potentially confusing) comment typo in function "getMappedGOGtrack" within yquake2/src/client/sound/ogg.c:

line 100: case  5: return 7;  // baseq2 6

The comment should say "baseq2 7" instead.

Other than this, the remapping logic for xatrix soundtrack is good (I checked it against the real xatrix CD vs my GOG copy of the game, just in case).

**Comment by Yamagi** [comment]
Thank you! I've commited the fix.
