### ISSUE TITLE
liquid shaders in GL mode

### ISSUE THREAD

**Issue by StepanST** [yquake2/yquake2#508]
I dont think this is bug, but in OpenGL mode liquid shaders has borders between sectors on one textured place. In software mode there is no borders. In different versions of Quake 1 port (dont remember witch one, QuakeSpasm or DirectQ) was different shaders of liquids, one of them was with borders and another without. Is it possible to make liquid shaders in GL mode like in software or it is more deep thihg?

**Comment by DanielGibson** [comment]
Can you add a screenshot that demonstrates this? Not 100% what you mean

**Comment by StepanST** [comment]
![Без имени-1](https://user-images.githubusercontent.com/43229017/73506884-9d240780-4409-11ea-8231-5bcb86094193.jpg)
This is first map of Groun Zero addon, but in original Q2 it although appears

**Comment by Yamagi** [comment]
This should be fixed by merging #569.
