### ISSUE TITLE
Glass flickering, gl_zfix

### ISSUE THREAD

**Issue by StepanST** [yquake2/yquake2#512]
Cvar gl_zfis is working, but in some places, where is destructible glass, there is flickering. But not all glass has it issue. I dont remember, where is this places in Q2 and Q2-Reckoning (I realized that I must post this after some time after walkthrow), but this can be seen in Zaero addon on map zdef1 (some steps at the begining of the map). Screenshots;

![q2_0000](https://user-images.githubusercontent.com/43229017/73589489-70571980-4509-11ea-93d2-607e0aeec3f9.jpg)
![q2_0001](https://user-images.githubusercontent.com/43229017/73589490-70571980-4509-11ea-9718-a3a19d26e6f0.jpg)
![q2_0002](https://user-images.githubusercontent.com/43229017/73589491-70571980-4509-11ea-906c-7a5bd5c772c1.jpg)
![q2_0003](https://user-images.githubusercontent.com/43229017/73589492-70571980-4509-11ea-832d-daf6bbe9b270.jpg)
![q2_0004](https://user-images.githubusercontent.com/43229017/73589493-70efb000-4509-11ea-9884-6c17d9dd36e6.jpg)

**Comment by Yamagi** [comment]
`gl_zfix` is an evil hack. Flickering surfaces happen when the mapper put 2 surfaces exactly in the same place. The `gl_zfix` hack tries to detect such surfaces and a little gap between them. That helps in some places and makes things worse in other... I don't think that it can be made any better, unless someone has as a idea how to implement a better heuristic.

**Comment by StepanST** [comment]
Anyway, dont think this is important issue. There are only few places with this effect, and this is not not striking :)

**Comment by Pickle** [comment]
What about using the existing multitexture support (which is used for lightmaps)?
Another idea would be to render both textures  to texture (fbo)  and render the final texture.

**Comment by DanielGibson** [comment]
I don't think this case is common enough to invest that amount of time in it.
I'd say it's a map bug..

BTW, which renderer were you using for these screenshots?

**Comment by StepanST** [comment]
I Use OpenGL 3.2
