### ISSUE TITLE
How do I set a custom resolution 480x320(windowed mode for now)?

### ISSUE THREAD

**Issue by kubast2** [yquake2/yquake2#518]
Hey, I will have a small screen of a size of 480x320. It is going to end up being a small pocket device, my question is how can I set the size of the screen to said custom resolution? It either fails for me or it is doesn't actually get set and reverts to stock 640x480, Yamagi Quake 7.42 - Software/Opengl 1.4/Opengl 3.2 renderers

**Comment by DanielGibson** [comment]
https://github.com/yquake2/yquake2/blob/master/doc/040_cvarlist.md#graphics-all-renderers
`r_customWidth` and `r_customHeight` with `r_mode` set to `-1`

**Comment by DanielGibson** [comment]
No, works for me with r_customWidth/Height:
![image](https://user-images.githubusercontent.com/1216493/74570935-6e676e80-4f7d-11ea-9349-1ed213aeeae5.png)

**Comment by kubast2** [comment]
Oh I see the video modes go on mine upto 5120x2880, after that is auto and after that is custom I get it now
