### ISSUE TITLE
[Bug] Nearby monsters see players with back turned at the start of a level

### ISSUE THREAD

**Issue by BjossiAlfreds** [yquake2/yquake2#525]
Steps to reproduce:
1. Open map base2
2. The machinegun guard sees you even with his back turned

This is different behavior than in the original game where the machinegun guard is unaware of you until you do something to get his attention.

The problem is with a check in FindTarget(): (client->show_hostile < (int)level.time). In the original code show_hostile is implicitly cast to float since level.time is a float, but here level.time is cast to int, meaning the expression is an int and thus for the first second of a level (when level.time < 1) the expression evaluates to false since show_hostile == 0 && (int)level.time == 0, causing the monster to see you as if show_hostile was set.

Any particular reason why show_hostile was turned into an int rather than a float? Originally it was qboolean which is clearly wrong, but int seems just as wrong to me, since in the code it is used to store values offset from level.time.

Changing it to a float and dropping the (int) casts would be the best fix in my opinion. Should be safe for savegames too, as monsters that have show_hostile set generally don't live very long, and even then interpreting binary data of an int as a float is not going to have long-term effects in this context.

**Comment by Yamagi** [comment]
You're right, the integer is wrong. I don't remember why I didn't use a float in the first place. I'll commit a fix shortly.
