### ISSUE TITLE
Invert Mouse option keeps resetting

### ISSUE THREAD

**Issue by Q3BFG10K** [yquake2/yquake2#529]
Each time you launch the game, invert mouse is turned off. The setting sticks only as long as the game is running. 

The bug seems to be new to 7.43.

Win10-64 1909.

**Comment by Yamagi** [comment]
You're right, the cvar wasn't marked as `CVAR_ARCHIVE`. So it wasn't saved to the config. I've pushed a fix, new Windows binaries are here: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20200316-a5eb0b1.zip
