### ISSUE TITLE
Physics breaking using configuration guide

### ISSUE THREAD

**Issue by ConHuevosGuey** [yquake2/yquake2#530]
Hello.  I am running Yamagi Quake II v7.43 and I used the timing guide in the documentation and followed these steps:

> `Precise timing at the cost of tearing:

    busywait set to 1.
    r_vsync set to 0.
    cl_maxfps set to 60.
    vid_displayrefreshrate set to the displays refresh rate plus 1.
    vid_maxfps set to the desired frame rate.

My monitor refresh is 60, so I set that to 61.  However, setting vid_maxfps to 120 causes the physics to break.  For instance I can jump on the boxes at the beginning of map base2.  It's my understanding using these timings the physics are supposed to be decoupled from the renderer.  cl_async is currently set to 0.  

Is this by design, a bug, or is this a misunderstanding on my part that it's possible to run at a high video frame rate without breaking the physics?  Thank you.

**Comment by Yamagi** [comment]
> cl_async is currently set to 0.

That's your problem. With `cl_async 0` every renderer frame is a client frame, like it was in the original Quake II. If your `vid_maxfps` is set to more than about 90 you'll run into the 125hz bug. Set `cl_async 1` and everything should be okay. :)

**Comment by ConHuevosGuey** [comment]
This worked perfectly, thank you.  I think the documentation has an error in this case.

`And there's always the option to disable the asynchronous client all together by setting cl_async to 1. In that case cl_maxfps and vid_maxfps are tied together, just like with the original client each renderframe is also a clientframe. `

It states setting cl_async to 1 will cause the physics issue which is why I had it set to '0'.  Thanks again, and thank you for making such a great port.
