### ISSUE TITLE
64 bit binaries for Windows (release and test builds)

### ISSUE THREAD

**Issue by donizettilorenzo** [yquake2/yquake2#533]
Please add a prebuilt binaries package with the 64 bit version for Windows too! (MinGW or MSCV or both)
Thanks!

**Comment by Yamagi** [comment]
Why? It would be a lot of work - we need to build and to test them, we would likely get bug reports due to incompatible savegames and mods, etc. - for next to not advantage.

**Comment by donizettilorenzo** [comment]
You're right but the same for Linux systems. So you can't simply use MinGW to crosscompile&build for Windows?

**Comment by Yamagi** [comment]
I course, our Windows build environment supports 64 bit builds and we had some internal test builds. In fact, everybody who's interested in it can build their own 64 bit binaries. But Windows 64 Bit is still another platform that needs work and has disadvantages:

* The binaries need to be build (that's easy), tested (that's not so easy), uploaded, etc. Neither @DanielGibson nor me have much time to spend for Quake II these day - we have our jobs,  families and a life - every minute we spend on Windows 64 bit would be a minute less for fixing bugs, merging pull requests and so on.
* Unix 64 bit has the LP64 data model, Windows 64 bit has LLP64. I don't think that it'll make any problems, but with Quake II you'll never know. There may be bugs and currently Windows specific problems are hard to debug.
* Windows 64 bit isn't compatible with existing mods, 32 bit savegames can't be loaded on 64 bit builds and vice versa. On the other hand there's no advantage in having a 64 bit build, Quake II is far away from any 32 bit limitations. A 64 bit build would be inferior and likely only a small amount of user would use it.

So no, official 64 bit Windows builds won't happen any time soon. It's just not worth the effort. But MSVC support is on our long term todo list. It shouldn't be too hard and would open the way to a working debugger on Windows, generally better integration into the platform, etc. After that we can reconsider releasing 64 bit binaries.
