### ISSUE TITLE
In-game map and texture download speeds are extremely low

### ISSUE THREAD

**Issue by kai4785** [yquake2/yquake2#539]
On a 1Gb network link where I can regularly transfer data at 100+MiB/s, downloading a 1MiB map took well over a minute, instead of under a second.

Reproduction steps.
1) Use pakextract and extract q2dm1.bsp to ~/.yq2/baseq2/maps
2) Start a server and set the map to q2dm1
3) Connect a qyuake2 client with the demo pak0.pak installed.
4) Count the bits as they travel across the wire.

**Comment by DanielGibson** [comment]
This is a limitation of quake2's networking protocol which is not really built to transfer files, and even less at high speeds.
For this reason we (and several other sourceports) support http downloads: The multiplayer server sends a base http URL and yamagi quake2 (if built with libCURL support) tries to download missing files from that http server.

**Comment by kai4785** [comment]
Awesome, thanks for the info. I somehow missed this document in my googling.
