### ISSUE TITLE
armv7 & aarch64

### ISSUE THREAD

**Issue by paulwratt** [yquake2/yquake2#540]
is it possible to provide `armv7` and `aarch64` (Debian based?) linux builds of `yquake2` on:
[https://www.yamagi.org/quake2/](https://www.yamagi.org/quake2/)

**Comment by Yamagi** [comment]
Why don't you use the official Debian package? - https://packages.debian.org/search?keywords=yamagi&searchon=names&suite=unstable&section=all

**Comment by paulwratt** [comment]
its not in my package repos, and Raspian is one of the biggest (well stocked) non-x86 distros around, which means its probably not in any other Arm distros.

Its fine, for some reason I thought there were linux x86 packages on the page as well, nm

**Comment by Yamagi** [comment]
We once shipped Debian packages, but it wasn't worth the effort. It's a lot of work to maintain a third party packages, there're a lot more distros out there, etc. YQ2 is rather easy to compile from source, so we decided to no longer build and maintain any packages besides the Windows binaries.

**Comment by DanielGibson** [comment]
I'm surprised Raspbian doesn't have YQ2 packages, because debian and Ubuntu do have them.
(You're right though, I just checked on my RPi4)
You could try to contact Raspian and ask to provide packages, based on the debian ones that shouldn't be much work for them.

**Comment by paulwratt** [comment]
I think it was initially a GL related issue, hense the 2 different
efforts to use EGL, before the final inclusion of RPi code into
yquake2. According to what I just read recently, full GL (removed
`experimental`) is Stretch onwards

**Comment by DanielGibson** [comment]
At least YQ2 GL1 works pretty well with current Raspbian on both RPi4 and RPi3 B+ (I think? We tested on some newer RPi3 at least).
The GL3 renderer doesn't work at all currently, though there's a half-finished (and not merged) port to OpenGL ES3.0 that makes it work on RPi4.

**Comment by tojestzart** [comment]
definitley would be interested as package (server side) for openwrt
