### ISSUE TITLE
black areas when using software renderer on macOS

### ISSUE THREAD

**Issue by jboekesteijn** [yquake2/yquake2#541]
Since version 7.42, black areas are visible when using the software renderer on macOS. This happens both in the menu and in the game:

<img width="640" alt="quake2-menu" src="https://user-images.githubusercontent.com/29773435/78019671-5fcbef80-7350-11ea-9b7c-25c03e3d699f.png">

<img width="640" alt="quake2-game" src="https://user-images.githubusercontent.com/29773435/78019714-6c504800-7350-11ea-815f-f83f8baefd2b.png">

Version 7.41 does not have this issue. Based on the changelog, it looks like this happened in the changes related to #415 and/or #416. Commit 60f9af27 still works fine, without any visible black areas, just like in version 7.41.

This is still an issue in the current master 07859967. Tested on macOS 10.14.6 (18G4032). My builds were made with clang version 11.0.0 (clang-1100.0.33.17).

Maybe @0lvin can help with this?

**Comment by 0lvin** [comment]
Could you try to replace parameters CopyFrame call in sw_main.c::RE_FlushFrame ?
 https://github.com/yquake2/yquake2/blob/QUAKE2_7_43/src/client/refresh/soft/sw_main.c#L2112 
```diff
-  RE_CopyFrame (pixels, pitch / sizeof(Uint32), vmin, vmax);
+ RE_CopyFrame (pixels, pitch / sizeof(Uint32), 0, vid.height * vid.width);
```

**Comment by jboekesteijn** [comment]
> Could you try to replace parameters CopyFrame call in sw_main.c::RE_FlushFrame ?

Yes, the full frame is visible again after this change.
