### ISSUE TITLE
Porting old mod?

### ISSUE THREAD

**Issue by ulatekh** [yquake2/yquake2#544]
It seems like Weapons Of Destruction v6.09 (the last one I worked on, before handing it off) mostly works with the latest YQ2, except for two issues.

One, trying to load a saved game generates "ReadLevel: function pointers have moved", either immediately, or when moving to another level in a group (e.g. between base1 and base2).

Second, the command to fire/retract the grappling hook, i.e. "+hook", is somehow not recognized. A YQ2 build I did around 14-Jun-2014 (it reports itself as version 5.23) didn't have this problem. It seems the current YQ2 CTF grapple doesn't work this way at all.

YQ2's current baseq2 DLL source is so thoroughly reformatted and reorganized compared to the original game 3.20 source, and I'd really rather not hand-rebase the whole thing when it's mostly unnecessary. Hopefully you can point me in the right direction.

**Comment by Yamagi** [comment]
Hi,
I don't think that you need to rebase onto our code. We tried our best to keep the game API compatible with 3.20, when a mod doesn't work that's a bug on our side... We did a lot of bugfixes to the game logic, bit most of them were rather obscure corner cases or general stability improvements. If Weapons Of Destructions work fine, you don't need them.

> One, trying to load a saved game generates "ReadLevel: function pointers have moved", either immediately, or when moving to another level in a group (e.g. between base1 and base2).

This is the broken savegame system of Vanilla Quake II. The vanilla client just dumped all entity and movement structs onto the disk and relied on functions ending up at the exactly same address after a restart. That worked with the rather primitive Win9x memory system and broke with Win XP and later. There were some hacks in 3.21 to mitigate the problem, but the only solution that really works is to port our savegame system or implement something similar: https://github.com/yquake2/yquake2/blob/master/src/game/savegame/savegame.c It has the nice side effect, that savegames will never break again, as long as you don't alter the entity and movements structs and some small other things like the player state structs.

> Second, the command to fire/retract the grappling hook, i.e. "+hook", is somehow not recognized. A YQ2 build I did around 14-Jun-2014 (it reports itself as version 5.23) didn't have this problem. It seems the current YQ2 CTF grapple doesn't work this way at all.

This sounds like a problem on our side. We'll look into it but it might take a few days.

**Comment by Yamagi** [comment]
The savegame tables are generated with this crappy tool: https://github.com/yquake2/extractfunctions More bug than software but get the job done.

**Comment by DanielGibson** [comment]
(but if your mod doesn't have many new functions that are needed there it might be easier to just use our tables from game code and add your functions, if any, manually)

**Comment by ulatekh** [comment]
Thank you for being willing to help! I tried to port the new save system, and I had to run extractfuncs, and I think I'm close, but I finally got a mysterious error I couldn't debug. When trying to save, it crashes with "ERROR: Game Error: WriteField1: function "use" not in list, can't save game". (I modified the message to show field->name.) There's an edict_s function-pointer field called "use" in g_local.h, but of course that's not in tables/gamefunc_list.h, but there's a reference to "use" in tables/fields.h. Any idea what I may have messed up? I apologize if this is a stupid question.

**Comment by Yamagi** [comment]
Yeah, static functions cannot work because they're unreachable outside their translation unit. That's a little bit unfortunate but there's not much that can be done against it. Anyways, it's cool that you've got it to work. :) Since the new savegame system is in the game.dll it'll even work for every other source port and even Vanilla Q2.



> Note that using the very old aliases for the grappling hook get it to work, i.e.:
> 
> alias +hook "hook action; wait; hook shrink"
> alias -hook "hook stop"

Hmm... Maybe we have removed some code that was flagged unused by some analyzer but it's needed by the `hook` commands.

**Comment by ulatekh** [comment]
Let me know when you think you've fixed +hook, and I'll test it.

FYI, I was going to do a mingw build, but got stopped cold...i686-w64-mingw32-ld (running under Fedora Core 30) literally crashed with "corrupted size vs. prev_size". Not sure what I'm supposed to do with that. :-)

**Comment by BjossiAlfreds** [comment]
> > One, trying to load a saved game generates "ReadLevel: function pointers have moved", either immediately, or when moving to another level in a group (e.g. between base1 and base2).
> 
> This is the broken savegame system of Vanilla Quake II. The vanilla client just dumped all entity and movement structs onto the disk and relied on functions ending up at the exactly same address after a restart. That worked with the rather primitive Win9x memory system and broke with Win XP and later. There were some hacks in 3.21 to mitigate the problem, but the only solution that really works is to port our savegame system or implement something similar: https://github.com/yquake2/yquake2/blob/master/src/game/savegame/savegame.c It has the nice side effect, that savegames will never break again, as long as you don't alter the entity and movements structs and some small other things like the player state structs.

Vanilla 3.20 didn't rely on addresses being identical, only the offsets from the base address. The function pointer check is purely a version check, you can safely remove it. Writing a fancy savegame system would be best but if there are no plans to develop the mod further, removing the function pointers check from g_save is good enough.

**Comment by ulatekh** [comment]
> removing the function pointers check from g_save is good enough to fix this specific issue.

Thank you for your advice, but I already ported WoD to the new save-game system.

Re: the problem I've been having with the grappling hook...it seems the problem is that weapons/autoexec.cfg doesn't get run. If I start yquake2, type "set game weapons", then start a game, weapons/autoexec.cfg needs to run in order to set up the aliases for +hook and -hook. Qcommon_ExecConfigs() only does that at "game startup" time, which apparently doesn't happen if I switch to a different game.

**Comment by Yamagi** [comment]
You're right. `+hook` is an alias defined in autoexec.cfg. @DanielGibson: Do you still remember why we restricted processing autoexec.cfg to the client startup and skip it when executing the `game` command?

**Comment by DanielGibson** [comment]
no idea. did we do this? does git blame know anything?

**Comment by Yamagi** [comment]
We fixed the `game` command and added the function. It's f0e21e2.

**Comment by DanielGibson** [comment]
Hmm no idea - I guess we somehow assumed that whatever happens in autoexec.cfg is supposed to only happen once during engine startup or something?
Is there anything someone would do in an autoexec.cfg that doesn't make sense to do again if the engine is already running?

**Comment by ulatekh** [comment]
Renaming weapons/autoexec.cfg to weapons/default.cfg makes it work.
I'm fine with that solution.

I think that's everything! Feel free to link to my mod in your README.md :-)

**Comment by Yamagi** [comment]
I've changed the code, autoexec.cfg is now processed everytime `game` is changed. Vanilla Quake 2 did the same. Let's see if anythings breaks. :)
