### ISSUE TITLE
Run port with scaling screen resolution on Windows 10 x64.

### ISSUE THREAD

**Issue by StepanST** [yquake2/yquake2#548]
If you run game in Windows 10 with scalin resolution on desktop (125% in my case), game will run in tray and you must click on Yamagi window to expand it. Althow not big issue, but many exes run normaly with scaling.

**Comment by Yamagi** [comment]
Does this happen with quake.exe, yquake2.exe or both?

**Comment by StepanST** [comment]
Everything is good now. Problem was on my side. Just when you change scaling in Win10, you must restart system. Now port works well :) Microsoft...
