### ISSUE TITLE
Game starts directly without choosing difficulty

### ISSUE THREAD

**Issue by rg3** [yquake2/yquake2#55]
I'm running the game on slackware64-current as of today, using SDL 1, and I'm experiencing weird keyboard issues like the game starting directly without the difficulty menu after selecting "GAME" in the main menu, or not being able to return to the game once I press Escape while in play, with the pause menu staying on screen.

I've bisected the bug and it seems commit 30fa1c54075bd21970928706c7fb7815b6739f37 is the one to blame.

**Comment by rg3** [comment]
After some more minutes looking at this, I get the impression the problem is sometimes a key press is interpreted as several keypresses. So when I press Enter on "GAME", it reads Enter on the following menu too, or when I press Escape in the pause menu, it reads Escape again in the game and comes back to the pause menu.

**Comment by Yamagi** [comment]
As you said. Special keys were processed twice. First as char event and then again as key event. It could only happen with SDL 1.2. Fixed. Thanks. :)

**Comment by rg3** [comment]
Thanks for the quick fix!
