### ISSUE TITLE
Opengl not entering fullscreen mode on old laptop

### ISSUE THREAD

**Issue by tojestzart** [yquake2/yquake2#550]
https://pastebin.com/PZxQNYrU

As above its not entering fullscreen on opengl 3.2, on opengl 1.4 its not working always.
https://pastebin.com/hdGaLKt4

 - quake2 (the executable / binary) - untouched
 
    - game.so - untouched

gdb -> https://pastebin.com/4LkVXHWq

behaviour-> https://youtu.be/7cxvtkrc-bY

Graphics:  Device-1: Intel Mobile 4 Series Integrated Graphics vendor: Dell driver: i915 v: kernel bus ID: 00:02.0 
           chip ID: 8086:2a42 
           Display: x11 server: X.Org 1.20.5 driver: modesetting unloaded: fbdev,vesa compositor: kwin_x11 
           resolution: 1280x800~60Hz 
OpenGL version string: 2.1 Mesa 19.2.8
kubuntu 19.10 x64

**Comment by tojestzart** [comment]
just a update during super moon from stellarium

`Detected: OpenGL "2.1"
Driver version string: "2.1 Mesa 19.2.8"
GL vendor is "Intel Open Source Technology Center"
GL renderer is "Mesa DRI Mobile Intel® GM45 Express Chipset "
GL Shading Language version is "1.20"
MESA Version Number detected:  19.2
Mesa version is fine, we should not see a graphics problem.
GLSL Version Number detected:  1.2
This is not enough: we need GLSL1.30 or later.
You should update graphics drivers or graphics hardware.
Else, please try to use an older version like 0.12.9, and try there with --safe-mode
You can try to run in an unsupported degraded mode by ignoring the warning and continuing.
But more than likely problems will persist.
Aborting due to OpenGL/GLSL version problems.
lsd@lsd-Latitude-E5400:~$ 
`

**Comment by DanielGibson** [comment]
If your driver only supports OpenGL 2.1, the GL3 renderer won't work, of course.

Try setting it to "OpenGL 1.4" in the video menu and also select the correct resolution there.
As far as I can tell from a quick look at the logs, you try to make it use OpenGL 3, which then fails so it falls back to OpenGL 1.x at 640x480 (that's the safe default)

**Comment by Yamagi** [comment]
Exactly. and the screen resolution stays at 1280x800 because `vid_fullscreen` ist set `1` aka keep resolution.
