### ISSUE TITLE
Binoculars in dday mod are too small and FOV is too high.

### ISSUE THREAD

**Issue by InFerYes** [yquake2/yquake2#553]
Okay, this one is another specific bug, but in the DDay mod you can use binoculars. When using yamagi as client these binocs look too small.

in software mode:
![https://i.imgur.com/buEuzCR.png](https://i.imgur.com/buEuzCR.png)

in opengl 3.2 and 1.4:

![https://i.imgur.com/vtz4Rr2.png](https://i.imgur.com/vtz4Rr2.png)

in r1q2 (taken by someone else for me):
![https://i.imgur.com/jskCXoq.png](https://i.imgur.com/jskCXoq.png)

Also in DDay the FOV is locked and unchangeable by the players. This is to prevent cheating as some weapons, like the pistol are very accurate, and aiming down the sights also changes the FOV.

in software mode:
![https://i.imgur.com/fWNO8Lc.png](https://i.imgur.com/fWNO8Lc.png)
![https://i.imgur.com/dwdYalA.png](https://i.imgur.com/dwdYalA.png)

in opengl 3.2 and 1.4:

![https://i.imgur.com/aoer907.jpg](https://i.imgur.com/aoer907.jpg)
![https://i.imgur.com/nnCpcyz.png](https://i.imgur.com/nnCpcyz.png)

Software mode appears to be better but still not correct when compared to someone else:

![https://i.imgur.com/aTKgvvx.png](https://i.imgur.com/aTKgvvx.png)
![https://i.imgur.com/7Uxu8m2.png](https://i.imgur.com/7Uxu8m2.png)

**Comment by InFerYes** [comment]
The FOV values for the game are defined in [`g_defines.h`](https://github.com/InFerYes/dday/blob/master/g_defines.h#L192)

```C
#define	SCOPE_FOV			25
#define STANDARD_FOV		85
#define	TS_FOV				78
#define	MAX_FOV				160
```

**Comment by Yamagi** [comment]
This is likely caused by our changes to the fov calculations. If you set `horplus` to `0` you get (mostly) the original behavior.

**Comment by InFerYes** [comment]
It doesn't really solve the problem with the models, the FOV changes indeed, but the models stay the same.

![https://i.imgur.com/Ptr1bm2.png](https://i.imgur.com/Ptr1bm2.png)
![https://i.imgur.com/TVjl5CZ.png](https://i.imgur.com/TVjl5CZ.png)

![https://i.imgur.com/nnDFlPm.png](https://i.imgur.com/nnDFlPm.png)
![https://i.imgur.com/bpLqUMc.png](https://i.imgur.com/bpLqUMc.png)

**Comment by DanielGibson** [comment]
I guess this is because we introduced `r_gunfov` which separates general FOV from gun FOV so the gun doesn't look distorted when changing the FOV

**Comment by InFerYes** [comment]
Alright, it's possible to tweak the `r_gunfov` setting and get it right enough for the weapons, but the binocs need a low value of `r_gunfov 20` while aiming to look right. 

And there's also a huge difference between software mode and opengl mode in terms of FOV values.

**Comment by Yamagi** [comment]
I've just pushed a possible fix. It's now possible to set `r_gunfov` to `-1`, which draws the gun with the global fov. For the software renderer you'll also need `sw_gunzposition` set to `0`. Can you give it a try?

**Comment by InFerYes** [comment]
These 2 new settings fix all the issues regarding FOV in the DDay mod.

**Comment by Yamagi** [comment]
Perfect. :)
