### ISSUE TITLE
Portable configs?

### ISSUE THREAD

**Issue by DwarfFighterCleric** [yquake2/yquake2#559]
Hey there :)
Is there a way to keep all the configs and savegames inside Yamagi's directory instead of using the C:\Users\My Documents path?

**Comment by buvk** [comment]
Excerpt from doc\01_index.txt:

* Yamagi Quake II saves its configuration, savegames and screenshots
  to *~/.yq2* (unixoid platforms) or *My Documents\YamagiQ2* (Windows).
  If Yamagi Quake II is started with the `-portable` switch all data
  is saved in the same directory as the executables.

As mentioned in https://github.com/yquake2/yquake2/issues/276, please consider making Yamagi portable if *portable.txt* or *portable.cfg* is detected.  That way users will not need to launch with `-portable`, and will not need to create a batch file or shortcut.

**Comment by DanielGibson** [comment]
no, use `-portable`, as Yamagi mentioned in the other issue you can create a .bat file that calls `yquake2.exe -portable`

**Comment by buvk** [comment]
> no, use `-portable`, as Yamagi mentioned in the other issue you can create a .bat file that calls `yquake2.exe -portable`

Some users launch directly from Steam.  You can add the argument via Steam as a launch option, but this option is lost if you have to re-install for whatever reason.  Just a minor annoyance for the few of use who prefer portable.

In any case, I respect your decision.  Just thought I would provide a scenario.
