### ISSUE TITLE
Still having some problems with the keyboard

### ISSUE THREAD

**Issue by rg3** [yquake2/yquake2#56]
Running the latest version on slackware64-current, SDL1. The keyboard stops responding properly after the following sequence is followed, for example.

* Start the game.
* Press Escape to bring the game menu.
* Down with the arrow keys to options, Enter.
* Arrow keys to "Go to console", Enter.
* Keyboard appears to respond normally.
* Type "vid_restart", Enter.
* Keyboard is no longer responding in the console.

After that, I cannot type normally in the console, and while I can Escape to the main menu, start a game and apparently play as usual, I cannot exit the game either because the "Y" key on the confirmation screen to quit the game is not working either. The only option is to kill the process from another terminal.

**Comment by DanielGibson** [comment]
I'm so looking forward to removing SDL1 :-D
(But I guess it's too early at this point)

**Comment by Yamagi** [comment]
Far too early. :( The problem is, that SDL_EnableUNICODE(SDL_TRUE) needs to be called somewhere after the render windows was recreated. I'll have a look.

**Comment by Yamagi** [comment]
Like Github detected: Should be fixed now. And while debugging it I found an other bug :)

**Comment by rg3** [comment]
Excellent! Thanks.
