### ISSUE TITLE
Screen tearing?

### ISSUE THREAD

**Issue by buvk** [yquake2/yquake2#560]
I have 240hz gsync monitor.  In Yamagi, I have vsync disabled and vid_maxfps set to 240.  With these settings, I notice there is screen tearing.  It is especially noticeable when firing the chaingun.  Lowering vid_maxfps reduces the problem, but does not eliminate it.  To eliminate the issue, I have to enable vsync.

Is this normal?  I was under the impression that as long as I am not going over 240fps, I should not notice any tearing with gsync enabled.

**Comment by DanielGibson** [comment]
Hmm probably we should support `r_vsync -1` for adaptive vsync (`SDL_GL_SetSwapInterval(-1)`)

Not 100% sure though if that's how you "support" FreeSync or G-Sync from OpenGL, but I don't know how else it should work.
I googled the topic briefly but didn't really find anything specific

**Comment by buvk** [comment]
If I enable vsync with vid_maxfps 240, cl_showfps shows my framerate fluctuate between 239.xx-240 fps.  My monitor refresh rate is locked at 240.

If I have vsync disabled, I can confirm that my monitor refresh rate syncs to the framerate.  For example, if I lower vid_maxfps to 200, my refresh rate drops to 200.  When vid_maxfps is set to 240, framerate fluctuates between 239.xx-240 fps, similar to when vsync is enabled.  My monitor refresh rate is mostly sitting at 240, but it does drop to 239 periodically.

Hopefully that makes sense.

**Comment by DanielGibson** [comment]
So what's the problem with enabled vsync?
Having 240fps with 240Hz (the minimal fluctuation by <1fps is probably just measuring inaccuracy) sounds optimal

**Comment by buvk** [comment]
I was under the impression that using vsync introduced some input lag.  In any case, I don't have an issue using vsync.  I'm just not used to seeing tearing with gsync enabled.  Thought it might be a bug.

**Comment by DanielGibson** [comment]
Ok
I have no experience with gsync (my display doesn't support it or freesync), but I *think* it needs vsync enabled to work. Might be wrong though, no idea.

I don't think vsync creates input lag.
Input might feel more responsive on a 60Hz display if the game is running at a higher framerate than that - though I'm not even sure that is really the case - but I think at 240Hz (and 240fps) that should definitely not happen, regardless of vsync.

**Comment by buvk** [comment]
Blur Busters recommends turning vsync on in Nvidia control panel, and disabling vsync in game.  I did this, and do not notice any tearing.

https://blurbusters.com/gsync/gsync101-input-lag-tests-and-settings/14/

I wanted to point out something I noticed though.  With these settings, if vid_maxfps is 200, the framerate in game is around 240fps.  If I set vid_maxfps to 125, in game framerate is 156 fps.  If I set vid_maxfps to 85, in game framerate is 106 fps.

Any idea what might be causing this?

**Comment by Yamagi** [comment]
> Probably we should support r_vsync -1 for adaptive vsync (SDL_GL_SetSwapInterval(-1))

I've implemented it in 19214d6. This is untested (non of my systems does support it) and it may have a small impact on the internal timings.

>  With these settings, if vid_maxfps is 200, the framerate in game is around 240fps. If I set vid_maxfps to 125, in game framerate is 156 fps. If I set vid_maxfps to 85, in game framerate is 106 fps.

This may be caused by external vsync messing up the internal time keeping. But that's just an educated guess, I don't know.
