### ISSUE TITLE
[7.44pre] Discussion around `bind F5 "menu_startserver"`.

### ISSUE THREAD

**Issue by mjr4077au** [yquake2/yquake2#563]
While playing the game and wanting to save, I accidentally bumped F5 instead of F6 like I meant to and immediately killed the server with "ERROR: couldn't find maps.lst". In additon to this, I had to resort to the console to unbind the key.

Opinions will vary of course but should this key be bound to this command by default? For the average single player user, it's probably not desirable, especially with a number of games using F5 for the quick save key.

**Comment by Yamagi** [comment]
The good, old maps.lst issue again... The maps.lst is special. The original retail version or some later patch shipped a maps.lst in one of the paks, id software later hacked a special case into the code to ignore that file and always use the file in file in baseq2/maps.lst: https://github.com/yquake2/yquake2/blob/master/src/common/filesystem.c#L394

We had that problem already several times and tried several approaches to hack around it. The only solution that works in all cases is that you need the file baseq1/maps.lst or you'll get the error. If you have the file and getting the error anyways there's still some bug somewhere in the menu code.

> Opinions will vary of course but should this key be bound to this command by default?

Don't you have the baseq2/yq2.cfg special configuration file? :) Without it you'll get all those nasty default bindings.

**Comment by mjr4077au** [comment]
Let's call this a "distro packaging issue" :wink:.

I'm on Arch Linux and as per [Line #56 in the PKGBUILD file](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=yamagi-quake2-git#n56), they stick yq2.cfg under /usr/share/doc/yamagi-quake2.

Never noticed this in Windows as the file is included in the baseq2 folder of course. Only on Linux at the moment because I found it easier to work on the PRs I've sent through.

Thank you for indulging me and sorry for wasting your time :smile:.
