### ISSUE TITLE
fullscreen : keep resolution / switch resolution

### ISSUE THREAD

**Issue by crmb** [yquake2/yquake2#565]
Hello
The setting (set from the video options) doesn't seems to be saved.
If i set it to "switch resolution", it will works, but will come back to "keep resolution" after restarting the game. (and the game will overflows from the screen)

In my case when the game resolution is higher than desktop (not very common i guess).

**Comment by Yamagi** [comment]
What value does `vid_fullscreen` have after the restart?

**Comment by crmb** [comment]
after game restart, vid_fullscreen says "1"

**Comment by Yamagi** [comment]
Hmm... I don't see how this can happen. At least not in the current git master branch, it may different in the 7.43 release. And I can't reproduce it on Linux. Did you see it with 7.43 on Windows?

**Comment by crmb** [comment]
yes i will try with another pc asap
