### ISSUE TITLE
OGG_PlayTrack error

### ISSUE THREAD

**Issue by goodjaerb** [yquake2/yquake2#568]
I just set up a new install of Ubuntu and installed yquake2 and I'm getting error "OGG_PlayTrack: '/opt/quake2//baseq2/music/09.ogg' is not a valid Ogg Vorbis file (error 20).
free(): double free detected in tcache 2" output when I try to play a new game. I've used these .ogg files before, they play fine in VLC, and vkQuake2 plays them fine. yqkuake2 starts OK when I delete the files.

**Comment by DanielGibson** [comment]
Sounds like an incompatibility with stb_vorbis, probably?
How did you create them/where did you get them? (The GOG Quake2 .ogg files are known to work, for example)
Can you send us one of the files (for example, put it in a .zip and attach it in a response here)?

**Comment by goodjaerb** [comment]
Here you go.

Like I said, I've used these files forever, including with yquake2 in the past. They play fine in VLC and vkQuake2. I believe the baseq2 music files I possibly created myself from my actual quake2 CD.

[09.ogg.zip](https://github.com/yquake2/yquake2/files/4572551/09.ogg.zip)

**Comment by DanielGibson** [comment]
Hmm, looks totally normal in VLC, just like my own old rip that works.
This file:
![image](https://user-images.githubusercontent.com/1216493/80975574-8df69080-8e22-11ea-8b0d-828b7c23490a.png)
My file: 
![image](https://user-images.githubusercontent.com/1216493/80975700-b9797b00-8e22-11ea-99cc-eab1208ae959.png)

We'll have to debug this, must be some issue with stb_vorbis (apparently it works with libvorbis which we used before and which other source ports and VLC use, as far as I know)

**Comment by DanielGibson** [comment]
Turns out just updating stb_vorbis seems to fix the issue, can you try again with the latest code from git master?

**Comment by Yamagi** [comment]
Am up to date set of Windows binaries is here: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20200504-3492dff.zip

**Comment by goodjaerb** [comment]
I has music! Thanks!

**Comment by DanielGibson** [comment]
Nice, thanks for reporting and testing!

**Comment by goodjaerb** [comment]
FYI this was caused by Comment tags being present in the ogg metadata, which was resolved by the newer stb_vorbis header you updated. The NVIDIA Q2RTX repo has the same issue and I might just update it and send a pull request.
