### ISSUE TITLE
Windows XP support?

### ISSUE THREAD

**Issue by adelpha** [yquake2/yquake2#570]
This is a question rather than a bug report.

It appears that Windows XP support was dropped in version 7.20. Was this a deliberate change or is it a byproduct of something else?

I'm only asking because there's no mention of it in the changelog.

**Comment by some0nebad** [comment]
Version 7.30 is the latest that runs on Windows XP.

**Comment by Yamagi** [comment]
Yeah. We haven't broken Win XP on purpose. We just didn't test against it anymore. If someone can figure out what exact is broken, we can see if we can fix it.
