### ISSUE TITLE
[Original bug] Gunner can get stuck idling

### ISSUE THREAD

**Issue by BjossiAlfreds** [yquake2/yquake2#571]
This is the very same bug as https://github.com/yquake2/yquake2/issues/433. Basically the idle move can override the run move if the Gunner is angered in exactly the same frame he decides to idle (fidget the gun).

I will do PRs to address this. The fix method is also the same as with the berserker bug.

**Comment by Yamagi** [comment]
As always: Thank you the PRs and keep up the good work. :)
