### ISSUE TITLE
Default resolution scaling issues on Mac OS 10.15 Catalina

### ISSUE THREAD

**Issue by pettyalex** [yquake2/yquake2#577]
As noted here: https://github.com/ioquake/ioq3/issues/422 the renderer by default is only drawing to the lower left quadrant of the screen. This is not that big a deal because when you set the resolution to match your display, it uses the whole screen just fine. This seems to be an issue with SDL2 and Mac OS 10.15, not anything specific to yquake2.

![Screen Shot 2020-05-21 at 9 21 59 PM](https://user-images.githubusercontent.com/3219141/82624810-26be3780-9ba9-11ea-9cc0-c5a3a7bccfb5.png)

I'll see if I can address this. It looks like the fix that ioQuake3 used was in the Mac .app bundle, which yquake 2 does not get packaged as an .app right now so I'll investigate where we can put the config during the build process.

**Comment by Yamagi** [comment]
Does this also happen if `vid_fullscreen` is set to `2`? If yes that's some problem in SDLs resolution switch magic.
