### ISSUE TITLE
SiN Gold Support for Yamagi Quake?

### ISSUE THREAD

**Issue by MasterO2** [yquake2/yquake2#578]
Apparently, NightDive is working on a Remaster of SiN Gold:

https://github.com/NightDive-Studio/sin-ex-game

Can this be added to YamagiQuake or no?  I was under the impression SiN Gold originally used the Quake 2 engine.

**Comment by bibendovsky** [comment]
> 
> 
> Apparently, NightDive is working on a Remaster of SiN Gold:
> 
> https://github.com/NightDive-Studio/sin-ex-game
> 
> Can this be added to YamagiQuake or no? I was under the impression SiN Gold originally used the Quake 2 engine.

Still there is a missing component - engine source code.

**Comment by DanielGibson** [comment]
Yeah, seems to be just the SDK code which has always been available (probably modified a bit for Sin Ex).
The license has changed a bit (less verbose), but it's still incompatible with the GPL which probably doesn't make porting it to YQ2 easier..

I wish someone would release the actual engine source under a sensible license :-/

**Comment by maraakate** [comment]
Tell Burger to give it a proper GPL license and I could release my fixed 
SiN engine that I've been sitting on for many years...

In all seriousness, the engine is different.  It has a complex script 
system for parsing the scripted events.  The animations are handled 
entirely differently mostly on the client side.  It would be a large 
undertaking to clean room reverse-engineer it.

Frank

**Comment by mjr4077au** [comment]
@maraakate, just wondering how you've come into posession of the engine? I know you mostly from the work undertaken on Daikatana. Were you around in the old days or just on good terms with others who worked on the game?

An open source release would be a dream come true.

**Comment by Yamagi** [comment]
There're several other games which could be supported by YQ2. Heretic II for example. But I don't think that it would happen in this repo, because it would require a lot of optional cases scattered all over the code. It would be better to fork the repo and do the work there...
