### ISSUE TITLE
Have any way to visualize the realtime performance??? :P 

### ISSUE THREAD

**Issue by Soldy** [yquake2/yquake2#579]
Maybe a good idea to implement a way to monitoring the performance.

**Comment by Yamagi** [comment]
Hi,
what so you mean by "monitoring the performance"? There's already the `cl_showfps` cvar. When set to `3` it gives rather detailed information about the frame timings. And there's the good, old `r_speeds` which prints the scene complexity.

**Comment by Soldy** [comment]
I thinking about to build some performance graph if it is not already existing.

**Comment by Yamagi** [comment]
No, Quake II cannot draw performance graphs. This has several reasons. It starts with the fact that the data is not so easy to collect. Also, Quake II doesn't have a system for drawing generic overlays, which makes adding something like this complicated. It's just not worth the effort... When I need some kind of performance graph, I use the good old RivaTuner.
