### ISSUE TITLE
macOS X Binary

### ISSUE THREAD

**Issue by arivega** [yquake2/yquake2#580]
[Yamagi Quake 2 7.43 MacOS X Version.zip](https://github.com/yquake2/yquake2/files/4796333/Yamagi.Quake.2.7.43.MacOS.X.Version.zip)
Here is a macOS binary built using this guide here https://github.com/yquake2/yquake2/issues/542
I also noticed there weren't any game.dylib files in rogue or xatrix so I put them there so they should work now 
Plus a new CTF folder

**Comment by Yamagi** [comment]
Cool, thank you for the build. I've uploaded it to: https://deponie.yamagi.org/quake2/osx/Yamagi.Quake.2.7.43.MacOS.X.Version.zip

**Comment by jboekesteijn** [comment]
@arivega Thanks for the dmg! However, did you follow all the steps from #542? The uploaded `quake2` binary still contains a reference to `/usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib` and it fails to launch if this file does not exist on the user system, like this:
```
> ./quake2 --help
dyld: Library not loaded: /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib
  Referenced from: /Applications/Quake 2.app/Contents/Resources/./quake2
  Reason: image not found
```
I think you should include a local copy of `libSDL2-2.0.0.dylib` in the `Resources` directory and use `install_name_tool` to replace the absolute path with a relative path.
