### ISSUE TITLE
 "Cbuf_AddText: overflow" error (autoexec.cfg > 8 kbytes)

### ISSUE THREAD

**Issue by gribbs88** [yquake2/yquake2#582]
That error is received for bigger autoexec. Any possibility to enable support for larger autoexec.cfg?

Thx,

**Comment by Yamagi** [comment]
That's a good idea. I've bumped the buffers to 32 kilobytes. That should be enough for the next 22 years. ;)

**Comment by gribbs88** [comment]
Heheh, thank you sir!
