### ISSUE TITLE
Suggestion: Issue a warning in NET_Init

### ISSUE THREAD

**Issue by apartfromtime** [yquake2/yquake2#584]
https://github.com/yquake2/yquake2/blob/9136c8705ac66ba1e7e3e581ac284cb6cf88c7ab/src/backends/windows/network.c#L1272-L1275

Every game in the series (including doom3) issue a warning and return on failing to initialize winsock. My suggestion is to do the same.

**Comment by DanielGibson** [comment]
This code issues a warning ("Winsock initialization failed.") and then terminates the game - do you think that's wrong?

**Comment by maraakate** [comment]
I think he's trying to say that it should ERR_DROP instead of 
ERR_FATAL?  I just checked Daikatana and Quake 2.  They both do 
ERR_FATAL and not ERR_DROP.  Even R1Q2 does an ERR_FATAL.

However, he is right, Doom 3 just prints a warning to console and returns.

**Comment by DanielGibson** [comment]
As far as I understand it from https://docs.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-wsastartup, this just should not (be able) to fail, unless the system is broken (any Windows released after 1993 should support Windows Sockets 1.1, which we  request).

Or am I missing something and you indeed have seen this fail, @apartfromtime?

**Comment by apartfromtime** [comment]
I've never known it to fail, I'm making the suggestion that it isn't ERR_FATAL. Looking at the return codes of WSAStartup would suggest this also. You could as @maraakate said ERR_DROP, or print a warning or leave as is.

**Comment by Yamagi** [comment]
The network.c for Windows is rather broken and has some rather obscure problems. For example changing the IPv6 broadcast addresses breaks the IPv4 codepath. And then there's the IPX stuff complicating things... Because the code somehow works and as Daniel pointed out `WSAStartup()` should never fail on modern Windows I'll leave thinks as they are until we rework the code.
