### ISSUE TITLE
Invert mouse keeps getting resetted.

### ISSUE THREAD

**Issue by antdude** [yquake2/yquake2#587]
Every time I exit and relaunch Yamagi Quake II v7.43 (https://deponie.yamagi.org/quake2/windows/quake2-7.43.zip) in my decade old, updated 64-bit W7 HPE SP1 PC. It keeps my other settings though! 

C:\Users\ant\Documents\YamagiQ2\baseq2\config.cfg doesn't seem to have an invert mouse line? I tried manually adding set in_mouse "1" line into my config.cfg, but it didn't work. I even typed that in console. It doesn't change. Why? A bug?

Nice works! :D Thank you for reading and hopefully answering soon.

**Comment by Yamagi** [comment]
Him
can you try an up to date build? - https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20200818-1f3f796.zip I've fixed several settings not getting saved and it's likely that this one was part of it. If not I'll look into it.

**Comment by antdude** [comment]
Perfect and thanks. Nice work on your Yamagi Quake II.  :)

**Comment by antdude** [comment]
Perfect and thanks. Nice work on your Yamagi Quake II.  :)

**Comment by Yamagi** [comment]
Thank you for testing!

**Comment by antdude** [comment]
You're welcome, Yamagi. I hope to see more updates and features soon. :)

**Comment by antdude** [comment]
You're welcome, Yamagi. I hope to see more updates and features soon. :)

**Comment by igorpupkinable** [comment]
`in_mouse 0`
The mouse is normally grabbed for controlling the game.  Setting this to 0 will give the mouse back to the desktop.

https://github.com/id-Software/Quake-2/blob/372afde46e7defc9dd2d719a1732b8ace1fa096e/rhapsody/rhapqw.txt#L33

So this setting has nothing to do with inverted mouse.
