### ISSUE TITLE
Q2 mission packs oryginal source code.

### ISSUE THREAD

**Issue by Mulligan81** [yquake2/yquake2#590]
Hello.
I'm a real big fan of of Quake 2 game.
I have the following questions regarding Yours yquake2 project:

1.) Where can i get the official, the original Q2 mission packs (The Reckoning, Ground Zero, Zaero) source code? (without Yours modifications).

2.) Where did You get the original source code for that add-ons?

Thx for Help:-)

**Comment by Yamagi** [comment]
Him
the source code for the addons was released some time after the retail version hit the shelf (sometimes ind 1998) on id Softwares long gone FTP server. I still have a local copy of the original archives, I've uploaded them here: 

* Quake II 3.20 GPL release: https://deponie.yamagi.org/quake2/idstuff/q2src320.exe
* The Reckoning 3.20, released under the Quake II SDK license: https://deponie.yamagi.org/quake2/idstuff/xatrixsrc320.exe
* Ground Zero 3.20, release under the Quake II SDK license: https://deponie.yamagi.org/quake2/idstuff/roguesrc320.exe

That are some kind of self extracting archives. Neither `unzip` nor `bsdtar` can read them, so maybe some proprietary crap.

**Comment by DanielGibson** [comment]
http://www.gamers.org/pub/idgames/idstuff/quake2/source/ also has the SDK source as .shar.Z 

(the original ftp.idsoftware.com seems to be down, though I had that impression before and then later it worked again after all)

**Comment by Yamagi** [comment]
Interesting. `.Z` files (created by `compress`) use the LZC algorithm which was patent by Sperry / Unicom until 2003. It's the same patent that covered `.gif` files.

**Comment by Mulligan81** [comment]
Thx friend:-)   
I really needed this orginal srcs. My question now is how to get the Zaero addon src?  
  Dnia 19 sierpnia 2020 15:03 Yamagi   napisał(a):  
 Interesting.  .Z  files (created by  compress ) use the LZC algorithm which was patent by Sperry / Unicom until 2003. It&#39;s the same patent that covered  .gif  files.

**Comment by Mulligan81** [comment]
Hello friend:-)
Is there a way to get the Zaero addon src code?

**Comment by DanielGibson** [comment]
Looks like http://ftp-archive.freebsd.org/pub/FreeBSD-Archive/ports/distfiles/quake2-zaero/ has a copy
(originally it was hosted on planetquake/fileplanet - see http://web.archive.org/web/20070319193326fw_/http://teamevolve.planetquake.gamespy.com/products/index.html - but PQ is dead and fileplanet something else now - no idea if it's still supposed to have all the old files, but I couldn't find this at least)

**Comment by Mulligan81** [comment]
Thx again!:-)  
            
          
     
      
       
        Dnia 19 sierpnia 2020 18:10 Daniel Gibson &lt;notifications@github.com&gt; napisał(a):
       
    
       
         
 Looks like  ftp-archive.freebsd.org ftp-archive.freebsd.org  has a copy  
(originally it was hosted on planetquake/fileplanet - see  web.archive.org web.archive.org  - but PQ is dead and fileplanet something else now - no idea if it&#39;s still supposed to have all the old files, but I couldn&#39;t find this at least)
