### ISSUE TITLE
Invert mouse setting not being saved on exit

### ISSUE THREAD

**Issue by chbrehm** [yquake2/yquake2#594]
When I set "invert mouse" to "yes" in the game menu, the setting is not being saved to the config.cfg file when I exit the game. So I have to reset it each time I start the game.

I also tried adding `m_pitch "-0.022"` to the config.cfg manually. It works for one startup of the game, but when I exit it, the line gets removed from the file.

Other settings (like key bindings, video mode, ...) seem to be saved fine.

(I'm using Yamagi Quake 7.43 and the GOG release of Quake II)

**Comment by Yamagi** [comment]
Him,
thank you for report. I'm pretty sure that this is already fixed in the git version. An up to date set of Windows binaries can be found here: http://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20200831-56ddda7.zip

**Comment by chbrehm** [comment]
Thanks for your reply.
I tried the test build and it is fixed indeed.
