### ISSUE TITLE
eGPU on macOS Catalina

### ISSUE THREAD

**Issue by pmthexton** [yquake2/yquake2#601]
I have recently gone with an eGPU setup on my 2018 model Mac mini (mainly for photo and video post processing, to be fair) and thought I'd give quake2 a blast as it's probably my favourite FPS ever.

I can't seem to get the game to use the eGPU though, I have a Radeon RX 5700 XT connected via Thunderbolt 3 and can get other games purchased via Steam to work with the card, but on startup yquake2 always reports gl_renderer as being Intel UHD Graphics 630

Are there any configuration tricks I can use to force the selection of the eGPU, or is this not a supported configuration/use case at the moment?

**Comment by Yamagi** [comment]
It could be something with this plist stuff, but I really don't know. This is something that must be solved by someone who actually has a Mac and and maybe some development with MacOS. :/ Maybe @jboekesteijn or @arivega can have a look?

**Comment by pmthexton** [comment]
Hey. I've actually just been playing with this this evening, and it actually works if I connect the display to the eGPU directly rather than using the HDMI from the Mac mini.  There are a couple of other apps/games that also seem to work better with this configuration as well, where-as I have others which don't seem to require it (Forsaken remastered for example is happy to use the eGPU for acceleration when not directly connected to display).

Perhaps it's one for the documentation/readme.
