### ISSUE TITLE
yquake2 forgets control bindings

### ISSUE THREAD

**Issue by vext01** [yquake2/yquake2#602]
Hi,

Tried yquake2 on OpenBSD recently. Thanks, it's great.

I notice that it sometimes forgets my custom bindings. For example, I bind mouse wheel up and down to weapon change and invert the mouse.

It seems it *always* forgets inverse mouse between restarts, but only *sometimes* forgets keyboard bindings.

Thanks

**Comment by Yamagi** [comment]
Thank you for the report. This is already fixed in git head. Windows build with the fix included can be found here: https://deponie.yamagi.org/quake2/windows/testbuilds/ We'll do a new release with that and other fixes soon.
