### ISSUE TITLE
Add new model formats: MD3, IQM

### ISSUE THREAD

**Issue by VinnyVicious** [yquake2/yquake2#607]
- [ ] IQM support
- [ ] MD3 support

Adding IQM model support would be great for custom games. Adding support for the MD3 model format would be great for mods, specially ones that use Quake 3 assets from the community.

IQM reference: http://sauerbraten.org/iqm/
MD3 reference: https://github.com/mczero80/KMQuake2/blob/87c984801eae94b82c1874558f4818d196ce1c87/renderer/r_model.c#L2129

**Comment by Yamagi** [comment]
This is out of scope for YQ2. And it would be a lot of work with a very limited gain. I'm not even sure if new model formats could be supported without altering the game API or the network protocol... Thank you for the suggestion, but it ain't gonna happen.
