### ISSUE TITLE
NAT Punchthrough

### ISSUE THREAD

**Issue by VinnyVicious** [yquake2/yquake2#608]
Playing online with friends right now is a bit convoluted and the easiest way out is using something like Hamachi. In FTEQW `sv_public 2` uses TCP to connect to the master server instead of UDP, which allows the client and server to exchange address information.

https://sourceforge.net/p/fteqw/code/HEAD/tree/trunk/engine/server/sv_main.c#l120

**Comment by Yamagi** [comment]
After some pondering we won't implement this. Some kind NAT punch through require a considerable amount of code changes with questionable gain. For full stack internet connections routers with configurable port forwarding are cheap. Carrier grade NAT isn't required to map all UDP packages to the same external address, making NAT punch through unreliable or impossible. In that case an el cheapo VM somewhere is a better solution.
