### ISSUE TITLE
Client prediction

### ISSUE THREAD

**Issue by VinnyVicious** [yquake2/yquake2#609]
For multiplayer to be a pleasant experience, client-side prediction is important. I think Q2 MP gameplay could improve by implementing something like this:

https://www.quakewiki.net/archives/code3arena/tutorials/tutorial41.shtml
https://www.ra.is/unlagged/

**Comment by maraakate** [comment]
That code is for Quake 3, a different engine.  Plus, I would say that going all out and extending the protocol, etc. is beyond the scope of YQ2.

**Comment by Yamagi** [comment]
Yeah, that would need changes to the network protocol if done right and is at least partly orthogonal to single player. This is out of scope for YQ2. I don't know it, but maybe some of the ports with multiplayer focus and improved network protocols have something like this?
