### ISSUE TITLE
v5.24 client sceen much darker than v5.23

### ISSUE THREAD

**Issue by ppsspp-gamer** [yquake2/yquake2#61]
in function R_Upload32Native() of r_image.c didn't apply R_LightScaleTexture() as R_Upload32Old(), that made screen darker than v5.23 as picture below:

v5.23 screen
![quake2-1](https://cloud.githubusercontent.com/assets/8726272/6654808/fd2a94b6-cb17-11e4-818c-3684c34b6fd6.png)

v5.24 screen
![quake2-2](https://cloud.githubusercontent.com/assets/8726272/6654810/0cfd5ab8-cb18-11e4-91d7-bcc96e73bf51.png)

possible fix:

qboolean
R_Upload32Native(unsigned *data, int width, int height, qboolean mipmap)
{
	// This is for GL 2.x so no palettes, no scaling, no messing around with the data here. :)
	int samples;
	int i, c;
	byte *scan;
	int comp;

	c = width * height;
	scan = ((byte *)data) + 3;
	samples = gl_solid_format;
	comp = gl_tex_solid_format;
	upload_width = width;
	upload_height = height;

	R_LightScaleTexture(data, upload_width, upload_height, !mipmap); // this line is missing

	for (i = 0; i < c; i++, scan += 4)
	{
		if (*scan != 255)
		{
			samples = gl_alpha_format;
			comp = gl_tex_alpha_format;
			break;
		}
	}
    glTexParameteri(GL_TEXTURE_2D, GL_GENERATE_MIPMAP, mipmap);
	glTexImage2D(GL_TEXTURE_2D, 0, comp, width,
			height, 0, GL_RGBA, GL_UNSIGNED_BYTE,
			data);
    glTexParameteri(GL_TEXTURE_2D, GL_GENERATE_MIPMAP, false);
	return samples == gl_alpha_format;
}

**Comment by Yamagi** [comment]
Thank you :)
