### ISSUE TITLE
Game is Crashing or slowing down with old custom maps and mods

### ISSUE THREAD

**Issue by Screamerofstars** [yquake2/yquake2#612]
Something that i noticed recently and is happening with old maps and mods, but it has no issues with other source ports like KMQuake2
https://www.doomworld.com/forum/topic/93627-knee-deep-in-the-dead-mod-for-quake-2/
it crashed with ThyFleshConsumed

For other maps, mods, if not the largest ones, there are slowdowns and crashes.
https://www.youtube.com/watch?v=gSOVFFFx5pk

Martyr for an example it slows at the 1st map and the mountainside toxic waste.

**Comment by maraakate** [comment]
Depends on the mod.  Some maps require unofficial 3.24 (which is mentioned in that video and is also made by Knightmare) which has extended limits in the engine to allow for larger maps.  I don't believe YQ2 has "boomed" these engine limits, so crashes and odd behaviour are to be expected.

**Comment by Yamagi** [comment]
>  I don't believe YQ2 has "boomed" these engine limits, so crashes and odd behaviour are to be expected.

Nope, we haven't and won't bump the internal limits. Everything that was supported by Quake II 3.20 should be supported in Yamagi Quake II, as long as it doesn't do evil things like calling OpenGL from the game. Lazarus did that, for example. Anything that is out of the bounds of the original client is uncharted territory. It may work or it may crash. Nevertheless I'll Thy Flesh Consumed a try to see what the problem is.

**Comment by 0lvin** [comment]
I have played several seconds ThyFleshConsumed, looks like it works without issues for me. I have tried on linux (so without game.dll), maybe crash in some way related to it? Could you please try without game.dll?

About Martyr, it works with soft render ;-) Other renders(gl1/gl3/vulkan) have issues with distance of view.

**Comment by DanielGibson** [comment]
we have a cvar to increase view distance: `r_farsee 1`

**Comment by 0lvin** [comment]
> we have a cvar to increase view distance: r_farsee 1 (that's the one internal limit we do - optionally - bump)
@DanielGibson Good thing for improve vulkan render :-)  I will add such to next PR. Thank you :-)
