### ISSUE TITLE
Feature Request: Server browser

### ISSUE THREAD

**Issue by jlanzobr** [yquake2/yquake2#613]
Please add an in-game server browser, similar to that of q2pro. Data could be grabbed from http://q2servers.com/ or a similar service.

**Comment by Yamagi** [comment]
This was already requested at least once and we had a look: Out cURL code (for asset downloads over HTTP) is build around the multi handle, the handle is "owned" by the asset download code. Adding support for downloading arbitrary files would require a lot of refactoring in the asset down load code or implementation of the normal single handle into the backend. Besides that downloading a file with arbitrary content, parsing it and generating menu entries from sounds very scary considering the general code quality of Q2. So, it's agood idea but won't happen unless someone sends a good(!) pull-request doing all the dirty work.
