### ISSUE TITLE
Map name auto-completion is case-sensitive

### ISSUE THREAD

**Issue by themuffinator** [yquake2/yquake2#621]
There are a number of maps with capitalized names which don't get listed unless you type in capitals... q2pro has the same issue. Shouldn't it search case-insensitive and return all names converted to lowercase?

**Comment by maraakate** [comment]
Depends on the platform, on Windows, yes it make sense to be case insensitive, everything else no.

**Comment by Yamagi** [comment]
I've just pushed some changes to the map name autocompletion implementing this.
