### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by themuffinator** [yquake2/yquake2#622]
Every time without fail when I close yquake2 I get an application error pop up: "The instruction at 0x000000005F4E47D3 referenced memory at 0x0000000077ABE675. The memory could not be read."

Edit: Running Win 10 if that is relevant.

**Comment by Yamagi** [comment]
What renderer are you using, what's your GPU does it happen with a clean config?

**Comment by Yamagi** [comment]
No answer for 10 days, I'm unable to reproduce this and asan doesn't trigger (albeit on Linux) -> Closing. Feel free to reopen if this is reproduceable.
