### ISSUE TITLE
Black Screen when running on macOS

### ISSUE THREAD

**Issue by kamleshgk** [yquake2/yquake2#624]
Hey guys,

When i run, i get a black screen, i can listen to the Menu sounds, as i move the arrow keys (possible menu selection sounds), but i'm the dark. 
Also my monitor throws a message says that the resolution of the app is not 1080p.

I did read that in Windows, people have solved this problem by using a command line argument (vid_renderer "gl1") in autoexec.cfg 

In macOS, Do we have a file where we write the command line arguments?
I did try typing the command line argument in the 'add command-line options' in the start, yet i see no change - black screen and i need to force quit the app.

Is there a way where we can configure the Open GL video settings and resolution on macOS? 
Thanks in advance.

**Comment by Yamagi** [comment]
I can't answer the question because I don't have a Mac. Just a general auswer: The GL1 renderer is the default. Even if GL3 is choosen for some reason the game will fall back to GL1 if the renderer. You can always force a renderer by editing the config file, wherever Mac OS stores it.

**Comment by Yamagi** [comment]
Stale for 6 weeks -> Closing. Feel free to reopen if you have questions or new informations.
