### ISSUE TITLE
Strange texture wrapping in highres pack

### ISSUE THREAD

**Issue by Jarvik7** [yquake2/yquake2#63]
The texcoords seem broken when using the highes models pack mentioned in the readme. Only health and ammo crates seem affected. I suspect that this might be caused by the recent non-power-of-2 commit. Can anyone confirm if this is something that predates that?

![quake02](https://cloud.githubusercontent.com/assets/6679920/6764391/ee0e9044-cff0-11e4-820c-72ac2099caf4.png)
.

**Comment by Yamagi** [comment]
That was always this the way. The high resolution model skins in the retexturing pack don't match the original .md2 files. Is far as I know no one has ever build matching textures :/

**Comment by Yamagi** [comment]
For example:
![example](https://cloud.githubusercontent.com/assets/1224576/6770249/d9b991a0-d0ba-11e4-9e80-69c3b425b08b.png)
