### ISSUE TITLE
Video option "keep_resolution" (Fullscreen Window Desktop) not scaling to window size in OpenGL and Vulkan.

### ISSUE THREAD

**Issue by apartfromtime** [yquake2/yquake2#637]
Software scales the resolution properly to the window size, but OpenGL and Vulkan display the images shown below. Should they too be scaled to the output resolution? or is this intended?

OpenGL (1.4 and 3.2)
![q2_0001](https://user-images.githubusercontent.com/42292382/102981483-20d46e80-455d-11eb-9dce-aa60736916ca.png)

Vulkan
![q2_0002](https://user-images.githubusercontent.com/42292382/102981488-229e3200-455d-11eb-84df-502070612975.png)

**Comment by DanielGibson** [comment]
yes, this is expected.
you can either use real fullscreen (instead of desktop fullscreen) which will switch the display resolution accordingly, or use the resolution that matches your current display resolution
