### ISSUE TITLE
Issues with the resolution

### ISSUE THREAD

**Issue by posixrails** [yquake2/yquake2#645]
For some reason the game starts with the 640x480 resolution. The terminal says: 
`setting mode 4: 640 480`
`Real display mode: 1280x720@60 (vid_fullscreen: 1)`
I tried changing the resolution in game's video settings but for some reason I just can't. Any suggestions on how to play with a normal resolution?

**Comment by Yamagi** [comment]
Look like the game falls back to safe mode for some reason. Can you send us the full log? That's the terminal output under Linux and other unixlike systems or *C:\Users\$username\Documents\YamagiQ2\stdout.txt* on Windows.

**Comment by posixrails** [comment]
https://pastebin.com/WzMSjW4f

**Comment by DanielGibson** [comment]
Can you try setting the resolution in the menu (remember you gotta select `apply` afterwards) and then send us the terminal output of that?
Hopefully it'll contain an error message for the failed resolution change then

**Comment by posixrails** [comment]
Sure, I will see that. But I think it's somehow related to the double slash in the PAK files' paths (example: `Added packfile '/home/posixrails/.yq2//baseq2/pak0.pak'`)

**Comment by DanielGibson** [comment]
I'm 99,999999% sure't it's not related to the double slashes.
If it would mind that it wouldn't start at all.

**Comment by DanielGibson** [comment]
Normally you should be able to select "video mode" in the "VIDEO" menu with the up/down cursor keys and select a resolution with the left/right cursor keys. Afterwards select "apply" with the up/down cursor keys and press enter.

**Comment by posixrails** [comment]
> Normally you should be able to select "video mode" in the "VIDEO" menu with the up/down cursor keys and select a resolution with the left/right cursor keys. Afterwards select "apply" with the up/down cursor keys and press enter.
Nothing really happens. It just plays a sound when I am trying to change something.

**Comment by posixrails** [comment]
Maybe it's somehow related to the config files but there aren't any mentions of the 640x480 resolution there.

**Comment by DanielGibson** [comment]
So the displayed resolution in "video mode" doesn't change when pressing left/right there?

What happens if you open the console (Shift+Esc) and enter `r_mode 14` (this should set the resolution to 1280x720; you can get a list of the standard resolutions by entering `vid_listmodes`)?

**Comment by posixrails** [comment]
> So the displayed resolution in "video mode" doesn't change when pressing left/right there?
> 
> What happens if you open the console (Shift+Esc) and enter `r_mode 14` (this should set the resolution to 1280x720; you can get a list of the standard resolutions by entering `vid_listmodes`)?

Now it works! Thank you!
