### ISSUE TITLE
Vulkan renderer  scaling issues  when  vid_fullscreen = 1

### ISSUE THREAD

**Issue by j4reporting** [yquake2/yquake2#648]
vulkan renderer uses only smaller portion of available screen for game content when vid_fullscreen =1 and r_mode  is not desktop resulution
the console, rendered movies and the HUD is as expected, only the actual rendered image is way to small.

configure game resolution smaller than desktop resolution  (e.g.  game 1920x1080 /  desktop 2560x1440 )  and set vid_fullscreen = 1

1920x1080
![q2_0002](https://user-images.githubusercontent.com/45177907/104823361-e30bf280-5849-11eb-8c75-eabaf428000d.jpg)

1280x960
![q2_0003](https://user-images.githubusercontent.com/45177907/104823370-eacb9700-5849-11eb-8888-46a1069588a4.jpg)

1024x768
![q2_0004](https://user-images.githubusercontent.com/45177907/104823376-f1f2a500-5849-11eb-8eca-d9b51d06feec.jpg)

**Comment by Yamagi** [comment]
That's expected. When `vid_fullscreen 1` the resolution is changed and SDL2 doesn't implement scaling (yet). So the game windows is placed somewhere, depending of render API and GPU driver, in a black background. As I wrote in the other PR we'll change the semantics aif `vid_fullscreen` and add this to the doku.

**Comment by j4reporting** [comment]
Please take a another look at the screenshots.  It's not the usual  vid_fullscreen=1 bug report.
The screenshots only show the game resolution. Desktop is much larger and not included in any quake2 screenshots. Look at the fps counter in the upper right corner or the crosshair positioned in the middle of game screen. The HUD elements are also correctly placed at the bottom of game screen,  VK renderer uses only roughly a quarter of the available game resolution.

**Comment by DanielGibson** [comment]
you're right.
