### ISSUE TITLE
GL/GL3 settings not saved in config  when vulkan renderer active

### ISSUE THREAD

**Issue by j4reporting** [yquake2/yquake2#649]
most GL custom settings are lost when game quits while vid_render is  "vk".

only setting saved in config.cfg are

set gl1_stereo "0"
set gl1_stereo_convergence "1.4"
set gl1_stereo_separation "1"
set gl_anisotropic "0"
set gl_msaa_samples "0"

how to reproduce:
start game and select vulkan renderer, start/load a game   than quit game  and view config.cfg.

**Comment by j4reporting** [comment]
ah this also happens with vk_* settings when GL renderers are selected  **if**  you start and quit yquake  w/o loading the vulkan renderer ( in this case).
Is there a way to load and preserve the settings for other renderers  if they exist in config.cfg?

**Comment by Yamagi** [comment]
This is annoying. But it is how the (buggy= cvar system works and can't be fixed. The game know about a cvar as soon as it is registered and only known cvars can be written to config files. The renderer cvars are registered at renderer load. So when you start with with VK, make some changes and switch to GL3, both the vk_* and gl3_* cvars are known and written to the config file. When you start the game the next time with GL3, the vk_* cvars are unknown and lost.
