### ISSUE TITLE
Software renderer crashing when changing modes

### ISSUE THREAD

**Issue by Yamagi** [yquake2/yquake2#660]
Hi,
I've noticed that the software renderer crashes sometimes when changing modes. I'm not 100% but it might be related to a cinematic playing during mode change. This is more or less easy to reproduce: Start the game with `vid_fullscreen 1` and `r_mode -2` -> Switch to a lower resolution while the id logo is playing, for example `r_mode 23` -> Switch back to the native resolution with `r_mode -2` -> the game errors out printing "Error: RE_Draw_StretchPicImplementation: bad coordinates".

@0lvin, can you have a look?

**Comment by 0lvin** [comment]
I will look. 

By first check - looks like resolution is changed in between of begin/end of frame in some cases.  As result buffers are allocated for previous resolution but frame rendered with new resolution.

**Comment by 0lvin** [comment]
@Yamagi Could you check with #663? I have added code for save buffer size and compare with that instead vid.width/vid.height, that can be changed without reallocate buffers.

**Comment by Yamagi** [comment]
I've merged the pull request. Look like it's working now.
