### ISSUE TITLE
r_anisotropic:  lowest possible setting differ in GL and Vulkan

### ISSUE THREAD

**Issue by j4reporting** [yquake2/yquake2#662]
In vulkan renderer  r_anisotropic  0  is accepted, and it's needed with Intel Windows drivers, because any setting > 0 enables texture filtering, ignoring VK_TEXTUREMODE. 

the GL renderer resets r_anisotropic 0  to 1.

**Comment by rg3** [comment]
This one should be fixed now after #681.
