### ISSUE TITLE
No footsteps sound

### ISSUE THREAD

**Issue by Mitradis** [yquake2/yquake2#666]
No footsteps sound... only if press two key (W (forward) + A (step left) || D (step right)). I use custom controls (WSAD). Original game have this bug too.

**Comment by Yamagi** [comment]
You want to say that no foodstep sound are played when more than one movement key is pressed? I'm so far unable to reproduce that, as long a the player moves on ground I'm hearing the sounds.

**Comment by Mitradis** [comment]
if press W and move - no sound. If press WA or WD - have footsteps sound
https://youtu.be/ABEGj03Yes8

**Comment by Yamagi** [comment]
Ah, now I see what you mean. Footsteps are only generated if you're faster than 225 units per whatever. If you're walking you're too slow, but if you're running or strafe-walking you're fast enough. The code is here: https://github.com/yquake2/yquake2/blob/master/src/game/player/view.c#L1029 So this isn't a bug, it's some kind of feature. And at least in theory the distance were the player can be heard by monster is shorter of the player is moving and / or uses the silencer.

**Comment by Mitradis** [comment]
@Yamagi so if player press W+A||D then speed more then 225? But why if pressed only one button W\S\A\D speed less than 225?

**Comment by j4reporting** [comment]
https://en.wikipedia.org/wiki/Strafing_(video_games)#Straferunning

**Comment by Mitradis** [comment]
@Yamagi then this is bug. Becouse no sound from footsteps if press one way key.

**Comment by Mitradis** [comment]
if player moved on slope surface sound from footsteps played. But if player move smooth surface no sound.

**Comment by Mitradis** [comment]
@Yamagi footsteps sounds always must be played.

**Comment by Yamagi** [comment]
> @Yamagi footsteps sounds always must be played.

No, they must not. Read the source. Footsteps sounds are played when the player is on the ground and faster than 255 in whatever metric. A walking player is slower than that -> no foodsteps.  Strafing, jumping, walking over slopes, running and so on add to the players velocity (that's how strafejumps are working). The player gets faster than 255 -> foodsteps are played. One could argue that a walking player should never generate foodsteps, but Vanilla Quake II behaves the same as YQ2, so this is correct.

**Comment by DanielGibson** [comment]
Just set "Options" -> "always run" to "yes".

**Comment by Yamagi** [comment]
I've added a new cvar `g_footsteps` to Q2 itself and both addons:

1: The Vanilla Quake II behaviour, footsteps are generated when the  player is faster than 255.
0: Footstep sounds are never generated.
2: Footstep sounds are always generated.

I defaults to `1` and is cheat protected to `1`.

**Comment by Mitradis** [comment]
@Yamagi if set to 2, the sound of footsteps is rare. It is not as frequent as when pressing W+A/D. you can make it with a value of 2 as fast as when you press W+A/D?
