### ISSUE TITLE
The "Crate Gladiator Incident" 2021

### ISSUE THREAD

**Issue by Bainelf** [yquake2/yquake2#667]
Dont know if its relevant to you:

https://steamcommunity.com/app/2320/discussions/0/3111395113763982000/?tscn=1614009215

Anyway thx for the job guys.

**Comment by Yamagi** [comment]
Oh, wow. You guys found a map bug that was unknown to me. At a first glance your analysis looks correct; the gladiator spawns regardless of skill and triggers only on hard. I'll need to decompile the map to be sure. After that I can come up with a fix. Likely something in the lines of the monster count fix in city3: https://github.com/yquake2/yquake2/blob/master/src/game/g_spawn.c#L665-L678 The minimal fix is if the best, fiddeling with the map logic in code has a high probability of side effects.

This will take a few days.

**Comment by Yamagi** [comment]
I've just pushed fixes for this and for #668. They were both the same, the monster is spawned but never triggered. The fix is to lower the monster count. That corrects only the help computer, the monster is still spawned.

**Comment by Froyd1** [comment]
Can confirm that this bug is fixed. Tested it on medium and hard.
