### ISSUE TITLE
When switching graphics mode mouse is no longer locked to game

### ISSUE THREAD

**Issue by WielkiZielonyMelon** [yquake2/yquake2#67]
Hi!
I am running yamagi-quake2 5.24 on Arch Linux (64-bit) 3.19.2-1. The pak I use for the game are from Steam. My window manager is awesome 3.5.6

1) I cannot start the game in fullscreen mode. If I do, my desktop is switched to (I suspect) 800x600, sometimes I see part of the quake, sometimes not. I have to quit, edit the config.cfg to disable the the fullscreen mode

2) If I switch the graphics mode, the mouse is no longer locked to the Quake window, which means I can look left/right/up/down and after some moment the mouse is no longer "in the game" but on my desktop (which seems like a normal awesome behavior as the window is active if mouse is over it)

**Comment by DanielGibson** [comment]
Hi,

can you try the latest code from git?

**Comment by WielkiZielonyMelon** [comment]
Hey,

I'll try that tomorrow (12 hours?). BTW, normally the mouse jumps out of the window. If I start the new game, the mouse is locked. As soon as I switch the graphics mode, the mouse is able to escape. To fix this behavior I need to start a new game.

**Comment by DanielGibson** [comment]
This could be the same problem as https://github.com/yquake2/yquake2/issues/64

we changed some things to fix that, I guess/hope those changes would also help you :-)

(And ideally you use SDL2, not SDL1.2)

**Comment by Jarvik7** [comment]
Based on a comment in the OSX PR thread, SDL1 compilation seems broken now anyways :P (due to the recent mouse/key changes I think)

**Comment by DanielGibson** [comment]
At least on Linux SDL1.2 still builds and works.

But SDL1.2 is not really actively developed any more and might be buggier.

**Comment by Jarvik7** [comment]
I haven't tried myself, but if it's not being maintained maybe it's time to remove?

**Comment by DanielGibson** [comment]
There are still supported Linux distributions without SDL2 (e.g. Debian 
Wheezy, it only has SDL2 in backports and Ubuntu 12.04LTS), so it's too 
early to drop SDL1.2.
We should make sure that it at least works with Linux (and similar like 
the BSDs), but for Windows and OSX demanding SDL2 should be acceptable.

**Comment by WielkiZielonyMelon** [comment]
Hi,

Issue is no longer reproducible with. Tested on commit d2f7d. Closing.

**Comment by DanielGibson** [comment]
Am 09.04.2015 um 06:44 schrieb WielkiZielonyMelon:
> Hi,
>
> Issue is no longer reproducible with. Tested on commit d2f7d. Closing.
>

Great!
I guess we should make a new release soon(ish)

**Comment by WielkiZielonyMelon** [comment]
Hope more soon(ish) that later(ish)
