### ISSUE TITLE
Undefined behaviour in console scroll speed command variable

### ISSUE THREAD

**Issue by apartfromtime** [yquake2/yquake2#671]
An issue I found reading through my own q2 source mod, is if the player sets "scr_conspeed" command variable to any negative value the result produces undefined behaviour. The source of the issue can be found here, 

https://github.com/yquake2/yquake2/blob/d7139446813cbe3376a57d1c376c7c9cba9e91aa/src/client/cl_screen.c#L500

In my own source I wrapped the command variable values in a call to fabs(), but a better solution might be to add some overload to the cvar system flags for signed\unsigned types since the client expects these values to be positive.

**Comment by Yamagi** [comment]
Hi, thank you for the report. I've pushed a fix.
