### ISSUE TITLE
Windows, Vulkan: map Main Gate  water texture drawn incorrectly when player rotates/moves

### ISSUE THREAD

**Issue by j4reporting** [yquake2/yquake2#673]
Map Main Gate,  enter first door  and look down at the water below. Then start to rotate 
Using latest windows test build 

![q2_0007](https://user-images.githubusercontent.com/45177907/109738131-8da45e80-7bc7-11eb-81cd-ba342805be79.jpg)

Edit:  this is caused by a texture from https://deponie.yamagi.org/quake2/texturepack/q2_textures.zip   
   r_retexturing 0   is fine

**Comment by Yamagi** [comment]
There's also #670. Looks like vk still has some problem with custom game data.

**Comment by Yamagi** [comment]
This should be fixed in the latest test build: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20210407-26bda18.zip

**Comment by j4reporting** [comment]
I can confirm that this is indeed fixed. Kudos to all involved.
