### ISSUE TITLE
Missing one enemy in Unit 09 - Lower Palace

### ISSUE THREAD

**Issue by Froyd1** [yquake2/yquake2#674]
I've been on and off playing this game. Another bug to report, that I'm unable to find the last enemy in Lower Palace on medium and hard difficulties. Even after I finished the main objective, I went back to look some more and found nothing. I no clipped through the walls, ceiling, and ground to look everywhere, no enemy found. I also looked on walk through videos on YouTube and the same result, one enemy missing in this level. So it's another known bug in this game.

**Comment by Yamagi** [comment]
Hi, I think you wrote me the mail reporting this bug and the other one. I typed an answer, only to get blocked by Hotmail with "unappropriated content"... I wonder why the enemy is missing on hard difficulty. I thought we fixed all these problems on hard. As with the other missing enemies I'll to find were it is, decompile the map and understand what's going on.

**Comment by Froyd1** [comment]
That is correct, I did send you an email a few days ago, and I never received your message back. So it's my email itself that blocked your message. I don't know why, but I'm really sorry that has happened. :(

Thanks for replying here and I hope you can fix these bugs. By the way I ordered brand new Quake 2 The Reckoning & Ground Zero off Ebay. If I find bugs in those, like this or other, I will let you know. :)

**Comment by Yamagi** [comment]
The missing monster is a monster_floater at 192.000000 -216.000000 -616.000000.

**Comment by Yamagi** [comment]
It's a technician, on the right floor above the data spinner / data cd console. Right before the door to the staircase. You can get a list of all remaining monsters - alive or revivable - with `listentities monsters` and teleport to the monster with `teleport x y z`. That's a real teleport, if the monster is already spawned, it will be telefragged as long as the player isn't in `noclip` mode.

This technician is spawned when target t54 is called. But there's no corresponding trigger in the map. So yeah, it's another map bug, present in medium and hard difficulty. As with the other unreachable monster I will lower the monster counter by one. The monster is still spawned in, but not counted.

**Comment by Yamagi** [comment]
Fixed in the latest build: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20210310-2a18f02.zip This will not work for existing savegames, since the help computer state including the monster count is read from the savegame.

**Comment by Froyd1** [comment]
Thanks for this, but I will wait until you fix the background sound bug.

**Comment by Froyd1** [comment]
Can confirm that this bug is fixed. Tested it on medium and hard.

**Comment by 2mg** [comment]
There are also 73/75 enemies in Upper Palace, The Cooling Facility has an enemy that is killable only on Hard, and there is a Secret that might not trigger in Pumping Station 2, just mentioning it for posterity and possible fixes.

**Comment by Yamagi** [comment]
You need to install the entity files to get fixes for map bugs: https://github.com/yquake2/yquake2/blob/master/doc/020_installation.md#fixed-map-data-files

**Comment by DanielGibson** [comment]
You just need to add those .ent files to your game data to get fixed maps.
It doesn't make sense to implement all those fixes in the yq2 source code, instead yq2 has code to load those .ent files to get them.
