### ISSUE TITLE
 r_fixsurfsky   should be  0  per default

### ISSUE THREAD

**Issue by j4reporting** [yquake2/yquake2#677]
apparently r_fixsurfsky 1  does have some nasty side effects.  Maybe  we should leave this disabled by default?
It's documented in cvarlist.md  that r_fixsurfsky is default 0  but this does not seem to be the case. 
map  is  'comm satellite' 

![q2_fixsurfsky](https://user-images.githubusercontent.com/45177907/110550517-22f9a280-8134-11eb-9844-d623aab539aa.png)

![q2_fixsurfsky2](https://user-images.githubusercontent.com/45177907/110550904-d367a680-8134-11eb-9fe0-242df60659ec.png)

**Comment by Yamagi** [comment]
You're right. We should switch it to `0` as default. That'll break some places in the addons, especially 'Waterfront Storage' in Ground Zero, but is the Vanilla Q2 behavior and more "correct".

**Comment by Yamagi** [comment]
Fixed in the latest build: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20210310-2a18f02.zip

**Comment by j4reporting** [comment]
Would it be feasible to change r_fixsurfsky  before an affected map is loaded?  If I start the map  'outer hanger'   with fixsurfsky 1  and change the setting to 0 while playing the map and then enter  'comm satellite'  the enemy is rendered correctly without  vid_restart.
