### ISSUE TITLE
[Android]Keep connection alive when minimized.

### ISSUE THREAD

**Issue by tojestzart** [yquake2/yquake2#679]
It happpens when game is minimized to background .
Can someone reproduce?

Not sure is "Open Touch" bug or its related directly to Yamagi
Opentouch developer informed

Android 9 Galaxy S9 +

**Comment by Yamagi** [comment]
Sound like the game / app is stopped when put in background. That would cause the server to drop the client after a few seconds. Nothing we can do on our side, it must be solved somehow within the Android wrapper app.
