### ISSUE TITLE
Reversed test for sdl2 causes build failure with only sdl1 available. Patch included for 5.30

### ISSUE THREAD

**Issue by omegageek** [yquake2/yquake2#68]
diff -ruN quake2-5.30.org/src/backends/sdl/input.c quake2-5.30/src/backends/sdl/input.c
--- quake2-5.30.org/src/backends/sdl/input.c    2015-04-11 21:16:47.000000000 +0200
+++ quake2-5.30/src/backends/sdl/input.c        2015-04-13 02:05:14.000000000 +0200
@@ -415,7 +415,7 @@
 
                                break;
 
-#if !SDL_VERSION_ATLEAST(2, 0, 0)
+#if SDL_VERSION_ATLEAST(2, 0, 0)
                        case SDL_WINDOWEVENT_FOCUS_LOST:
                                Key_MarkAllUp();
 #endif

**Comment by omegageek** [comment]
Pardon the crap formatting above. First time here.

**Comment by DanielGibson** [comment]
adding three backticks (<code>```</code>) in a line before and after the pasted code helps.

about the issue.. strange, I think I built the code with SDL1.2 just recently. but the code is wrong anyway - in SDL1.2 SDL_WINDOWEVENT_FOCUS_LOST doesn't exist, in SDL2 it's not a valid value of `event.type`, but of `event.window.event`, and only when `event.type == SDL_WINDOWEVENT`

so thanks for reporting the problem, but I think the fix needs to look a little different :-)

**Comment by DanielGibson** [comment]
can you try again with the latest git code? :-)

**Comment by omegageek** [comment]
Seems to have done the trick, thanks. Builds & behaves nicely with sdl 1.2.14 here
