### ISSUE TITLE
Missing enemies in the following levels of Ground Zero

### ISSUE THREAD

**Issue by Froyd1** [yquake2/yquake2#684]
Finally playing through the second expansion, Ground Zero on medium difficulty. My guess again is, its just an enemy who fails to spawn on a surprise attack or something. I have scoured the levels over and over again and I can't find the rest of the enemies in these levels listed below.

Unit 2

Waterfront Storage

Kills 123/129

![20210324185158_1](https://user-images.githubusercontent.com/80136749/112740315-d8986400-8f30-11eb-86d6-86a2582b6aee.jpg)

Unit 3

Maintenance Hangars

Kills 73/74

![20210327111843_1](https://user-images.githubusercontent.com/80136749/112740338-0f6e7a00-8f31-11eb-824b-c22a1493dbe6.jpg)

Unit 4

Munitions Plant

Kills 59/60

![20210327182237_1](https://user-images.githubusercontent.com/80136749/112740350-28772b00-8f31-11eb-9de6-b0f54c473e91.jpg)

**Comment by BjossiAlfreds** [comment]
I remember there being cases of monsters in GroundZero being set to a triggered spawn but not having a targetname. If Yamagi wants I could make the game print a console warning when this situation happens, and possibly remove the triggered flag so those monsters spawn normally.

**Comment by Yamagi** [comment]
What about: Don't spawn the monster be default, because that's what the developers released. And add a cvar that forces such monsters to be spawned?

**Comment by BjossiAlfreds** [comment]
Sure, that's reasonable. The only downside would be that if you want to spawn the monster and haven't set the cvar, you have to set it before the level loads initially, unless we do something more fancy like listening to the cvar value in G_RunFrame and force-activate the affected monsters.

**Comment by Yamagi** [comment]
That the cvar must be set before the level is initially loaded sound okay. I would assume that most players set the cvars once when configuring the game after it was started the first time.

**Comment by BjossiAlfreds** [comment]
I have made 3 PRs. The console warning is always printed so the player is aware of the problem, and there is a g_fix_triggered cvar with default value 0 that when set to 1 will remove the triggered flag inside monster_start(). Check it out and see what you think.

**Comment by Froyd1** [comment]
I ran the "listentities monsters" command in the following levels.

Waterfront Storage only showed four monsters in the console, instead of six for some strange reason.

`monster_soldier: 32.000000 -2824.000000 920.031250`
`monster_soldier_ss: 2544.000000 -1952.000000 -6724192.000000`
`monster_soldier: 3454.737061 71.828529 1176.031250`
`monster_soldier_ss: -556.799988 -2656.000000 792.031250`

Maintenance Hangers

`monster_turret: -576.000000 1526.000000 416.000000`

Munitions Plant

`monster_soldier: -2008.000000 248.000000 1560.000000`

**Comment by BjossiAlfreds** [comment]
The turret in Maintenance Hangar does spawn and is active, it's just in a closed-off space. Set noclip on and try to teleport to its co-ordinates with the "teleport x y z" command, see if that space is opened.

**Comment by Froyd1** [comment]
I found the turret and it's right behind this wall, and it's supposed to blow open. So it looks like a bug here. It may blow open on hard difficulty, however.

![20210328171304_1](https://user-images.githubusercontent.com/80136749/112773184-e52cc300-8fe9-11eb-897b-fd2b75c7293f.jpg)
![20210328171634_1](https://user-images.githubusercontent.com/80136749/112773194-ed84fe00-8fe9-11eb-88b8-0e0db512f357.jpg)

**Comment by BjossiAlfreds** [comment]
There is a func_door there with targetname t332, but seems there is no entity with that target, guess some event in the area was supposed to trigger it.

**Comment by Froyd1** [comment]
I wish I had the expertise for this, but I don't, sorry. I was hoping you guys can fix these bugs, that's why I posted these missing enemies topics. I really enjoy playing Quake 2 + expansions.

**Comment by BjossiAlfreds** [comment]
Extract this archive into rogue/maps folder (full path will be: rogue/maps/rhangar2.ent). It will make the turret door open when you press the console.
[rhangar2.zip](https://github.com/yquake2/yquake2/files/6222654/rhangar2.zip)

**Comment by Froyd1** [comment]
Thanks, just tested it, and it works! This should be put in the next version of this source port, with other bug fixes of missing enemies.

**Comment by Yamagi** [comment]
I've merged the pull request.
