### ISSUE TITLE
Missing enemy triggers on "Research Lab" [skill: easy]

### ISSUE THREAD

**Issue by moobaa** [yquake2/yquake2#687]
After collecting blue key & pressing the keyboard to activate the Maintenance Bridge, the Medic that is below the floor in the room with the Bridge activation switch does not trigger.

Also, the two Parasites in the roof that should be dropped when rounding the nearby corner (with the three Brains) don't get dropped.

All three enemies remain in the map, in their little hidey-holes ;)

Have only noticed this on Easy; will update if it also happens on higher difficulty levels.

**Comment by BjossiAlfreds** [comment]
There is a trigger_once with target t308 that won't spawn on Easy, it is supposed to get the medic into the level for you to fight. It was probably an oversight of the level creator to not set the spawnflags of those monsters correctly.

**Comment by BjossiAlfreds** [comment]
Here is a fix for the lab level, extract to baseq2/maps. See if the monster kill counts match on easy and medium.
[lab.zip](https://github.com/yquake2/yquake2/files/6225365/lab.zip)

**Comment by moobaa** [comment]
That worked (on Easy; I haven't tried Medium) - thanks :)

I get your point about map errors being outside the scope of the project; I just couldn't recall any such discrepancies back-in-the-day.

Should I close this item now? Or leave it (and re-frame it) as a catch-all for any other map issues?

**Comment by Yamagi** [comment]
We could ship the entity files somewhere under stuff/. A pull request would be appreciated. And - I know, I sound demanding - it would be nice if someone could have a look at the monster bug in baseq2: https://github.com/yquake2/yquake2/blob/master/src/game/g_spawn.c#L660

**Comment by moobaa** [comment]
@Yamagi  - I don't know whether your "pull request" comment was directed to @BjossiAlfreds or myself :} I'm happy to keep my eyes out for other errors & can endeavour to provide fixes, though my knowledge of Q2 scripting is non-existent. The code (& entity script) was pretty straightforward, though, and I suspect that a Q2 map editor will reveal entities and triggers :)

I have just encountered another issue: Inner Hanger, there's a Berzerker in a room at the level start that never gets triggered on Easy. Here's the "listentities monsters" that I remembered to grab this time. Let me know if these map errors should be broken into their own Issues, or just kept under one issue.

Thanks for the hard work!

![image](https://user-images.githubusercontent.com/81551227/112939925-0ae7d280-9178-11eb-88ee-ab3a385b57d3.png)

**Comment by BjossiAlfreds** [comment]
I'll see about moving the map hacks in g_spawn into ent files, and take a look at Inner Hangar berserker.

Also @Yamagi, I'll do a PR and documentation once we got more work done on this.

**Comment by BjossiAlfreds** [comment]
So I dug into city3. The map hack comment is not correct. The hidden room next to the security pass is a deathmatch-only room that contains a grenade launcher and grenades. The 2 missing monsters are actually 2x monster_chick standing in front of one of the blue forcefields. Their targetname is t125 which isn't targeted by any entity. I set it to t257 instead (after activating the data spinner sequence).

When I do the PR for this, I'll have to remove the map hacks to make sure the monster counts are correct.

**Comment by BjossiAlfreds** [comment]
@moobaa I checked out the Inner Hangar issue. Judging by the co-ords it's the berserker inside the monster closet right by the big stack of crates. His door has a targetname of t138 which is targeted by a stmpack health pickup at the other side of the room, and that seems to spawn on all difficulty modes, I was able to open the door and fight him by picking it up. Make sure you grab all the stimpacks in the starting area and report back if he's still not coming out of the closet.

**Comment by Yamagi** [comment]
> When I do the PR for this, I'll have to remove the map hacks to make sure the monster counts are correct.

Or the same solution as always: Hide the monster count correction behind a cvar, when users don't want to use the entity files they can set it to 1.

**Comment by Yamagi** [comment]
> Also @Yamagi, I'll do a PR and documentation once we got more work done on this.

Can I merge #685 or shall I wait?

**Comment by BjossiAlfreds** [comment]
The 3 PRs I did can be merged yes, they are not directly related to the work I've been doing with the ent files.

As for the code backs, I recommend removing them entirely for 3 reasons:
1. Having both solutions doubles the chance of players making mistakes with the configuration
2. Almost all players won't be able to tell the difference during gameplay, let alone be upset by 1 or 2 extra enemies to kill.
3. The code hacks are incomplete and faulty, so we'd have to go through the effort of replicating all the new issues we've fixed in the ent files as well as migrating the baseq2 hacks to xatrix and rogue. Not fun stuff. The lab hack isn't even correctly done, it only works on Medium, not Easy.

**Comment by Yamagi** [comment]
> As for the code backs, I recommend removing them entirely for 3 reasons:

Okay, I see. It's better to remove them.

**Comment by moobaa** [comment]
Guys - thanks for even humouring this "Bug" :)

The last issue I found on my Easy playthrough was in Outer Courts; three unspawned entities:

![image](https://user-images.githubusercontent.com/81551227/113461167-3bc15380-9467-11eb-904f-4410cd5dc54d.png)

After my last embarrassing mistake (in my defence, who needs to pick up stim packs on Easy? ;) ) I did do a bit of map spelunking... discovered that the entities are t222, t265, and t271. The last two appear to be triggered off a timer "hv1", which I couldn't find a reference for... this would presumably affect all skill levels. I totally concede that I may have not dug the entities correctly, though :}

**Comment by BjossiAlfreds** [comment]
I just played Outer Courts and killed all of the hovers. Did you go back to the starting area after triggering the alarm? Some extra hovers and medics spawn there.

**Comment by Yamagi** [comment]
I've merges the pull request.

**Comment by moobaa** [comment]
Awesome, thanks guys :)
