### ISSUE TITLE
Juggernaut, area inescapable or inaccessible, and one enemy missing

### ISSUE THREAD

**Issue by Froyd1** [yquake2/yquake2#689]
I want to give a heads up in this level of Juggernaut, that this area in The Heart Of Darkness level, is inescapable or inaccessible, without cheats. Also a missing enemy which is this one:

`monster_soldier_ss: -720.000000 -504.000000 -319.000000`

In this video I show you where the problem is, and it shows the enemy is stuck in the wall underwater somewhere, shooting at you as your health declines. I'm not sure this major bug can be fixed, as it seems this expansion pack was rushed to begin with.

https://www.youtube.com/watch?v=eXevvAWs5og

**Comment by Yamagi** [comment]
And the source code was never released. It might be possible to fix the maps, but everything that requires source code changes is impossible. :/

**Comment by Froyd1** [comment]
Oh I see, that's a shame about the source code not being released for this expansion pack. Do your best to fix the maps and bugs for Juggernaut. Thanks for your hard work. :)

**Comment by DanielGibson** [comment]
What Yamagi meant is: We only fix such bugs in addons/mods that we have the source code of (like the official addons or maybe Zaero), we don't work on other addons and generally avoid modifying any game data.

**Comment by BjossiAlfreds** [comment]
As far as I know Juggernaut didn't ship with a gamex86.dll, it is purely a map pack with some reskins of Quake 2 assets. At least that is the case for the CD copy I own that I bought back in 1999. So we could actually just fork or use the baseq2 game.dll for it.

Though to be honest here, is this mission pack even worth salvaging? :-)

**Comment by DanielGibson** [comment]
Hmm I thought it had its own gamex86.dll, but I'm not sure at all and I don't think I've ever played that addon (I heard it's not very good).
Maybe the gamex86.dll was available as/in a patch?
I found this patch: http://www.markshan.com/thesinraven/juggernaut_patch_06-Jul-99.htm but I wasn't able to extract any useful data on Linux and didn't try to actually install it on Windows.

Also, according to https://ogdb.eu/index.php?section=article&articleid=470 there were apparently two versions of Juggernaut: A "Deluxe Edition" that was a scam (only contained 11 levels instead of the full 21), installed in the `JUG/` directory which was 46.9MB, and the normal/proper/full version, which contained 21 levels, installed into `JUGFULL/` and was about 133MB.
Seems like the "Deluxe version" was some kind of demo or beta version or IDK, but nevertheless was sold in boxes (no idea if by the original developers or others), which IMO qualifies as scam.

Anyway, maybe only the full version had a game DLL?

**Comment by Yamagi** [comment]
I'm pretty sure that there was at least some executable code included in the full version. I have an ISO somewhere, I need to dig it up to have a look. Anyways, Juggernaut is out of @DanielGibson and my scope. We stick to baseq2 and the official addons.

**Comment by BjossiAlfreds** [comment]
The only executable code in my copy of the full version is a small frontend for quake2.exe, that I never use, I just launch straight from quake2.exe or yquake2.exe.

**Comment by Froyd1** [comment]
> 
> 
>Juggernaut is out of @DanielGibson and my scope. We stick to baseq2 and the official addons.

Understood, and it's too bad Juggernaut was a rushed game, instead of it having better maps and being bug free. If the source code came with it, this would've got fixed along with other bug fixes a while ago?

**Comment by BjossiAlfreds** [comment]
Extract this archive into jugfull/maps. Should at least put the soldier into the level. I'm not sure how to make that area accessible though, the texturing in this game is so bad it's hard to tell doors from walls at times.
[jug19.zip](https://github.com/yquake2/yquake2/files/6239991/jug19.zip)

**Comment by Froyd1** [comment]
Thank you very much, for the fix! I was wondering if you can move these enemies out of the water, since I found them dead already.

`monster_soldier_ss: -607.999817 -480.000000 -359.968750`
`monster_soldier_ss: -586.399780 -440.000000 -359.968750`

![20210331182455_1](https://user-images.githubusercontent.com/80136749/113232196-836e9200-9251-11eb-9847-69a1d6cb561a.jpg)

Yeah, do your best to fix that map at least, to make that area accessible. Maybe removing that wall, which leads to the door that requires a power cube? Put the power cube in some room, like where the commander's head is? Move the commanders head to that area, if you can make it accessible, where there is a tall ladder, and put it at the top of the platform?

**Comment by BjossiAlfreds** [comment]
The only level geometry that can be removed via the entity string are inline models (func_wall, func_door, func_explosive...). I couldn't find any of those in the room with the power cube door. Using teleportation might be a way but that's effort I'm not willing to go into I'm afraid.

**Comment by Froyd1** [comment]
I see, didn't know it can be that difficult. Maybe add a ladder to the window, if its possible? The way you come in the other way, so you can leave the same way.

**Comment by BjossiAlfreds** [comment]
Can't be done, ladders are level geometry, not entities.

**Comment by BjossiAlfreds** [comment]
For the sake of my own curiosity I removed the power cube door and added a teleporter. To give that sled area some purpose I added a special treat to the top of that ladder. See what you think of this... artistic interpretation.
[jug19-2.zip](https://github.com/yquake2/yquake2/files/6242220/jug19-2.zip)

**Comment by Froyd1** [comment]
Thanks again, for the big fix, this time for this level as you can now get out of that area by using the teleporter! I used that power armor at the end, when faced with the tank boss, so thanks for that too! This fix will also help other players in the future, when its merged with this source port, if its possible? :D

**Comment by Yamagi** [comment]
I can create a new repository yquake2/juggernaut and commit the entity files into it.

**Comment by Froyd1** [comment]
Okay, sounds good to me. :)

**Comment by BjossiAlfreds** [comment]
Do you want each game repo to have its own stuff/mapfixes folder then? I was planning to push everything into yquake2/stuff/mapfixes, including rogue and xatrix, but I can create stuff/mapfixes in yquake2/rogue and yquake2/xatrix instead, if you prefer.

**Comment by Yamagi** [comment]
I guess it's better to have everything that belongs to a mod in it's repository. What about this: Put rogue into the rogue repository, the same for xatrix and ctf. baseq2, juggernaut and possible other mod without repository are put into yquake2.

**Comment by Yamagi** [comment]
I've merged the pull request.
