### ISSUE TITLE
in_filter cvar not functioning

### ISSUE THREAD

**Issue by davidneely** [yquake2/yquake2#69]
When I try to adjust the in_filter cvar from inside the console, it makes me speak, as it does not recognize it as a command. It also does not show up in cvarlist.

**Comment by DanielGibson** [comment]
hmm maybe it's indeed called `m_filter`, at least a cvar with that name exists and seems to do something with mouse input.

I guess we should fix the Readme

**Comment by davidneely** [comment]
Ah, that works, thanks!
