### ISSUE TITLE
[Low-priority feature suggestion] True "nightmare" mode.

### ISSUE THREAD

**Issue by NeonKnightOA** [yquake2/yquake2#692]
It's the reason why I've introduced #503 in the first place. ;) I'll try to start implementing stuff as a personal project ASAIC, if this can be greenlit. Not sure if I can implement everything, though.

Nightmare would be even harder than Hard+ (which would go back to its previous name) and would comprise improvements for the monsters. It would include the following changes:

* Soldiers (including the TR variants), Enforcers, Berserkers, Parasites, Gunners and Iron Maidens being able to jump. (Port from KMQuake2) Possibly the Sentien from Zaero as well.
* Enforcers shooting instantly instead of readying their weapon. (Port from GZ/TR)
* Gunners and Parasites being able to aim vertically. (Port from KMQuake2)
* Berserkers (re)gaining all their cut attacks such as the "slam attack", "running club attack", and the "jumping slam attack" (which could be used instead of a regular jump if the player is close enough to a wall). (See 2:45 in [this video](https://www.youtube.com/watch?v=7aBJ0fw-43s))
* Brains (re)gaining the "walking tentacles". (See 4:20)
* Barracuda Shark (re)gaining the "tail whip". (See 4:40)
* Flyers being able to strafe and avoid attacks. (See 5:40)
* Gunners being able to shoot grenades while running. (See 6:50)
* Brains (4:35), Flyers (6:35), Enforcers (8:36) talking half the damage while covering themselves.
* Super Tanks being able to fire backwards (9:25) fire their hull mortars (9:39) and retreating (9:50).
* Parasites having a longer range for their attack.
* Any other idea?

**Comment by Yamagi** [comment]
What about forking the *src/game/* directory into a stand alone mod and doing the changes there? It not that I'm against a true nightmare mode, I would like to get Quake II at least a little bit harder. But these changes are rather invasive to the game logic, with a high probability to introduce new, hard to find bugs. Hiding all the changes behind the `skill` cvar effectively introduces a lot of new code paths, making things even worse... A stand alone mode could integrate all these changes without introducing new bugs into YQ2 or caring about backward compatibility.

**Comment by NeonKnightOA** [comment]
Noted.
