### ISSUE TITLE
Caps lock mapped to control does not work as +attack

### ISSUE THREAD

**Issue by adamflott** [yquake2/yquake2#70]
My ~/.y2q/baseq2/config.cfg has

    bind CTRL "+attack"

And my caps lock key has been re-assigned to be a left control via 

    Section "InputClass"
            Identifier "system-keyboard"
            MatchIsKeyboard "on"
            Option "XkbOptions" "ctrl:nocaps,apple:alupckeys"
    EndSection

And X is properly acknowledging it is control:

    KeyPress event, serial 39, synthetic NO, window 0x1e00001,
        root 0x2ce, subw 0x0, time 260084, (1,51), root:(3429,498),
        state 0x0, keycode 66 (keysym 0xffe3, Control_L), same_screen YES,
        XKeysymToKeycode returns keycode: 37
        XLookupString gives 0 bytes: 
        XmbLookupString gives 0 bytes: 
        XFilterEvent returns: False
    KeyRelease event, serial 39, synthetic NO, window 0x1e00001,
        root 0x2ce, subw 0x0, time 260156, (1,51), root:(3429,498),
        state 0x4, keycode 66 (keysym 0xffe3, Control_L), same_screen YES,
        XKeysymToKeycode returns keycode: 37
        XLookupString gives 0 bytes: 
        XFilterEvent returns: False

However, I am unable to fire. This is on X.Org X Server 1.17.1 under Arch Linux in windowed mode.

**Comment by DanielGibson** [comment]
Which SDL version are you using (try SDL2)?

Can you try https://gist.github.com/DanielGibson/12041b57a540cbbfbaf9 
and tell us what SDL2 keycode and scancode you get when pressing capslock?

**Comment by adamflott** [comment]
$ pacman -Q |grep sdl
    sdl 1.2.15-7
    sdl2 2.0.3-1
    sdl_image 1.2.12-3

    $ ./sdl2test 
    Warning: No joysticks connected!
    SDL_KEYDOWN: Keycode: CapsLock (1073741881) Scancode: CapsLock (57)
    SDL_KEYUP: Keycode: CapsLock (1073741881) Scancode: CapsLock (57)
    SDL_KEYDOWN: Keycode: CapsLock (1073741881) Scancode: CapsLock (57)
    SDL_KEYUP: Keycode: CapsLock (1073741881) Scancode: CapsLock (57)

How odd! For the record, it's on an Apple Aluminum Wired Keyboard

**Comment by adamflott** [comment]
And I used this https://aur.archlinux.org/packages/ya/yamagi-quake2/PKGBUILD to build the binary.

**Comment by DanielGibson** [comment]
Well, looks like a SDL2 bug then.
You could try the latest SDL2 code from https://hg.libsdl.org/SDL/ maybe 
they already fixed the bug, otherwise you should probably report it at 
http://bugzilla.libsdl.org

Cheers,
Daniel

**Comment by adamflott** [comment]
Being tracked at https://bugzilla.libsdl.org/show_bug.cgi?id=2978

**Comment by DanielGibson** [comment]
Great, thanks.
However, you should probably not just tell them to look here but just paste that snippet from your xorg.conf, that output that said that X11 recognizes it as Ctrl and maybe a link to my test program with the information that the sdl2 keynum and scancode are capslock instead of ctrl.

BTW, I just tried to bind capslock in quake2 in `Options` -> `customize controls` and was surprised that it doesn't work. I think I found out why and will probably push a fix later.  
I guess for playing in q2 it doesn't make much difference for you whether the key is recognized as capslock or as ctrl

**Comment by DanielGibson** [comment]
I just pushed a fix to git, feel free to pull the latest code and try again :-)

**Comment by DanielGibson** [comment]
Oh, and you may wanna try the latest SDL2 code from https://hg.libsdl.org/SDL, maybe they've already fixed the bug after release 2.0.3

**Comment by adamflott** [comment]
You are my hero. Thank you so much!
