### ISSUE TITLE
mod switching on gl3 refresher

### ISSUE THREAD

**Issue by echoline** [yquake2/yquake2#708]
mod switching doesn't work correctly with gl3 refresher

**Comment by Yamagi** [comment]
Can you be a little bit sore specific? What doesn't work?

If you're on a current gut checkout or testbuild you'll need an explicit `vid_restart` after changing `r_mode` or `vid_fullscreen`, these cvars aren't special anymore.

**Comment by echoline** [comment]
after switching mods in the menu with the gl3 renderer, 2D graphics seem to not work (cinematics are a black screen, menu and HUD doesn't work...)

**Comment by Yamagi** [comment]
Ah, now I understand. Looks like that somtimes the game DLL isn't switched. I'll need to figure out what commit broke that.

**Comment by Yamagi** [comment]
I can't reproduce this. With mod does is happen and can I have a full console log? On unxiod systems that's the terminal output, on Windows it's %DocumentsFolder\YamagiQ2\stdout.txt.
