### ISSUE TITLE
Reshade issues with GL3.2

### ISSUE THREAD

**Issue by Screamerofstars** [yquake2/yquake2#710]
I asked this at Reshade forums, and im asking here too, if its an issue at crosire's his side too.
Reshade has issues with OpenGL 3.2 when selecting some shaders like MXAO and even other shader filters.

With GL 1.4 all of them works flawlessly, even RadiantGI shader, but with 3.2 all i get is a black screen.

this is a very old issue, and recently after experimenting a bit more, i think its time to address it.

**Comment by Yamagi** [comment]
We won't change the renderer for fishy third party tools. This needs to be fixed in ReShade.

**Comment by Screamerofstars** [comment]
Necroing this for a moment, but is it possible to enter in contact with crosire at reshade forums.
https://reshade.me/releases/8046-5-2

the newest updates seems to have broken Q2's Particles under OpenGL 3.2 once more

Also i had the chance to test under vulkan, which i couldn't due to my pc having issues.
And under that, it works wonderfully, not only is smooth but it feels more faster than GL3.2

**Comment by DanielGibson** [comment]
Yamagi Quake 2 is open source, feel free to send a patch that improves compatibility with reshade (as long as it doesn't break anything on our side).

We don't have time or motivation to get familiar with reshade an figure out why it doesn't play nice with the GL3 renderer.
