### ISSUE TITLE
Wrong player position after loading auto save file

### ISSUE THREAD

**Issue by ChristianPervoelz** [yquake2/yquake2#711]
When returning from Lost Station to Comm Center the game auto saves.

After loading that auto save, player's body stucks in the elevator and dies slowly.
No chance to leave the elevator and no chance to rescue. :(

I'm using yquake2 7.45a

**Comment by BjossiAlfreds** [comment]
Can confirm this. It seems to be a problem outside the gamex86, as I swapped game.dll for the original 3.20 1998 one and the same happened, but original game exe works (almost) fine - you spawn on top of the elevator roof and have to run out to avoid damage.

I suspect this is a timing issue. The game has several issues with moving brushes and level transitions, a small offset to server frame advancements could break that sensitive system.

**Comment by Yamagi** [comment]
Does it also happen with `cl_loadpaused 0`?

**Comment by BjossiAlfreds** [comment]
cl_loadpaused 0 seems to fix the problem. It looks identical to what I see with the original quake2.exe - I spawn on top of the elevator and can run out of the elevator shaft.

I do wonder though, why does the level transition put the elevator in its original position but not the autosave? Do these events advance different amount of server frames?

**Comment by Yamagi** [comment]
> cl_loadpaused 0 seems to fix the problem. It looks identical to what I see with the original quake2.exe - I spawn on top of the elevator and can run out of the elevator shaft.

Looks like we found the one corner case that breaks, when the game is put in pause mode during savegame load.

> I do wonder though, why does the level transition put the elevator in its original position but not the autosave? Do these events advance different amount of server frames?

That's a very good question. Maybe this construct: https://github.com/yquake2/yquake2/blob/master/src/server/sv_init.c#L158 If we're not loading a savegame (`sv.loading` is false), the world is advanced by 100 frames.

**Comment by BjossiAlfreds** [comment]
I have a hunch this is an oversight by id, autosaves should probably do 100 frames as well. I'd experiment with that, and make cl_loadpaused only pause manual saves. I would try this myself but I don't have the setup needed to build the client at the moment.

**Comment by Yamagi** [comment]
I've implemented the first option. When an autosave (a savegame named *save0* or *current*) is loaded, the world is advanced by 100 frames. This can't be fixed by forcing `cl_loadpaused` to `0` because the cvar is in the client and the savegame loading code in in the server.
