### ISSUE TITLE
Scripting issue in Supply Station

### ISSUE THREAD

**Issue by ChristianPervoelz** [yquake2/yquake2#712]
Hi,

There seems to be an issue with scripts.

**Location**
Supply Station
Room with the circling crate coming out of the secret area.

**Case 1**
The crate comes out of the secret area, moves until the rectangle (visible on the floor) and immediately goes back to its hiding location without circling the rectangle.

**Case 2**
The crate circles around the rectangle and circles and circles and circles, but does not go back.
(happens less often than case 1)

afaik this didn't happen in original Q2.

**Comment by BjossiAlfreds** [comment]
It is random which direction the box chooses, it was always like that, I just tried it in the original game dll and it some times does 2+ circles in a row or goes to the door 2+ times in a row.

You do raise a good question though, was it intended for it to not be random? Either way it would probably be better for gameplay to remove the randomness.

**Comment by BjossiAlfreds** [comment]
I made an ent file that should remove the randomness of the loop. Give it a try (extract the zip into baseq2/maps folder).
[ware1.zip](https://github.com/yquake2/yquake2/files/6444863/ware1.zip)

**Comment by ChristianPervoelz** [comment]
Much better.
Thank you very much.

Sorry for the delay in answering.
