### ISSUE TITLE
Compilation crash when building Vulkan

### ISSUE THREAD

**Issue by TheEpicNoobZilla** [yquake2/yquake2#713]
I am trying to compile Yamagi on Debian 10 (Virtual Machine) and it crashes during building Vulkan renderer. It's not the problem with VM, because i've compiled a few other quakes source ports (quake3e, qss, ioquake3) and they all compiled without any errors.

Shortened compile output:

 `src/client/refresh/vk/vk_util.c: In function ‘memory_type_print’:
src/client/refresh/vk/vk_util.c:74:13: error: ‘VK_MEMORY_PROPERTY_DEVICE_COHERENT_BIT_AMD’ undeclared (first use in this function); did you mean ‘VK_MEMORY_PROPERTY_HOST_COHERENT_BIT’?
  if((prop & VK_ ##r) != 0) \
             ^~~
src/client/refresh/vk/vk_util.c:83:2: note: in expansion of macro ‘MPSTR’
  MPSTR(MEMORY_PROPERTY_DEVICE_COHERENT_BIT_AMD, mem_prop);
  ^~~~~
src/client/refresh/vk/vk_util.c:74:13: note: each undeclared identifier is reported only once for each function it appears in
  if((prop & VK_ ##r) != 0) \
             ^~~
src/client/refresh/vk/vk_util.c:83:2: note: in expansion of macro ‘MPSTR’
  MPSTR(MEMORY_PROPERTY_DEVICE_COHERENT_BIT_AMD, mem_prop);
  ^~~~~
src/client/refresh/vk/vk_util.c:74:13: error: ‘VK_MEMORY_PROPERTY_DEVICE_UNCACHED_BIT_AMD’ undeclared (first use in this function); did you mean ‘VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT’?
  if((prop & VK_ ##r) != 0) \
             ^~~
src/client/refresh/vk/vk_util.c:84:2: note: in expansion of macro ‘MPSTR’
  MPSTR(MEMORY_PROPERTY_DEVICE_UNCACHED_BIT_AMD, mem_prop);
  ^~~~~
make[1]: *** [Makefile:699: build/ref_vk/src/client/refresh/vk/vk_util.o] Błąd 1
make[1]: Opuszczenie katalogu '/home/debian/yquake2'
make: *** [Makefile:690: ref_vk] Błąd 2
`

Full compile output:

[yquake2crash.log](https://github.com/yquake2/yquake2/files/6446154/yquake2crash.log)

**Comment by j4reporting** [comment]
This is not a crash, but a compilation error, because the Debian system is missing the Vulkan header files. You need to install the appropriate Vulkan SDK files. 
You can also skip building the Vulkan renderer by defining  WITH_REFVK=no
Take a look at the Makefile.

**Comment by TheEpicNoobZilla** [comment]
Ok mate. How to do it.

**Comment by TheEpicNoobZilla** [comment]
Also how i could compile quake3e which uses both OpenGL and Vulkan if i am missing Vulkan headers?

**Comment by TheEpicNoobZilla** [comment]
succesfully compiled on Ubuntu 21.04

**Comment by j4reporting** [comment]
What is the version of the installed vulkan-headers package on the debian system?  It must be quite old and outdated because it does not define the AMD extensions / properties.

**Comment by TheEpicNoobZilla** [comment]
sid and unstable tree should have latest version of the package
