### ISSUE TITLE
Suggestion: increase limit for tracks count in music folder

### ISSUE THREAD

**Issue by leohub2016** [yquake2/yquake2#714]
Steps to reproduce the problem:
1) Add 40 different ogg tracks to music folder (for example from track02.ogg to track41.ogg) 
2) turn on "shuffle" in quake 2 options menu
3) try to restart any map for example 15-30 times ("map base1" in console)

Problem: only tracks from track02 to track31 are played
Idea: increase this count for example to 99 or 9999 or unlimited

Why: I want to stream Q2 on Yamagi port, and want to use Q1, Q2, Q3 music and also music from other games. But for now, with current "30 tracks max" restriction, I forced to combine several tracks into single ogg tracks in sound editor (this way it will be possible to play Q2 with 70 music tracks, but with a lot of pain in ass, and with not natural random)

Thank you in advance

**Comment by Yamagi** [comment]
I've bumped the limit to 128 files

**Comment by leohub2016** [comment]
You are the best, can't wait to stream this! 

I need to do some preparations before stream:
1) I need to add music tracks
2) I need to scan this https://www.amazon.com/Official-Quake-II-Strategies-Secrets/dp/0782122124 book to PDF, so I'll read it between missions to increase my (and viewer's) Nostalgia to 80 lvl

Also, when I tried yamagi-q2 at first time, I had some issues with "game is very dark, hard to reconnize what's going on", but let me spend some more time with settings and reading documentation/wiki, so if I can't fix this by myself, I'll contact you

P.S. How I can contact you outside github comments? To avoid offtopic in comments like this

**Comment by BjossiAlfreds** [comment]
Regarding the darkness issue, these are the things I know of to make the game easier to see:
1. Set brightness slider in the options
2. Set the rendered to software, makes the game way uglier but way easier to see imo
3. r_modulate cvar, higher values seem to make items and monsters brighter so they stick out more

Good luck with your stream and prep, btw!

**Comment by leohub2016** [comment]
>(did my first runs of the game this way in the 90s, at 320x240...)

Same for me (did it in 90s on 486 on software at 320x240 with extremely low fps, but with good book at least:) )

Also I notices, that software and opegl are completely different in Q2: software is with "green-grey" color palette, and opengl is with yellow/brown/orange/red palette. During that time I thought about "why it is not possible to change green color to yellow in software by devs" :)

> 
> 
> Regarding the darkness issue, these are the things I know of to make the game easier to see:
> 
>     1. Set brightness slider in the options
> 
>     2. Set the renderer to software, makes the game way uglier but way easier to see imo (did my first runs of the game this way in the 90s, at 320x240...)
> 
>     3. r_modulate cvar, higher values seem to make items and monsters brighter so they stick out more

thanks for he info

> 
> 
> Good luck with your stream and prep, btw!

thanks, be ready for additional feature suggestions from me and bugreports with links to exact timings of stream recordings
