### ISSUE TITLE
Suggestion: pause music when pause game

### ISSUE THREAD

**Issue by leohub2016** [yquake2/yquake2#715]
1) Pause music when player press Pause key. Unpause music when resume game (pressing pause again)

2) Don't pause music when player press ESC. So, if player want to pause game, but don't want pause music, he will press ESC (or ~ for console), and if he want to pause music, he will press Pause

3) Add option "pause all sounds/music and freeze the game when window is inactive"

This is useful when you streaming and want temporary pause music without changing music volume to zero

**Comment by SirYodaJedi** [comment]
> 1. Pause music when player press Pause key. Unpause music when resume game (pressing pause again)
> 2. Don't pause music when player press ESC. So, if player want to pause game, but don't want pause music, he will press ESC (or ~ for console), and if he want to pause music, he will press Pause

I think it would be less convoluted to just have a `ogg_pausemusicwithgame` cvar that pauses the music when the game is paused (except maybe during demo playback, to avoid pausing the "title screen music"). 

It also probably would be a good idea to have a `ogg_mutemusic` cvar, so that music can be quickly muted without having to reset the volume to unmute. This way, music could be "paused" independently of the game.

> 3. Add option "pause all sounds/music and freeze the game when window is inactive"

This is a very good idea, though.

**Comment by leohub2016** [comment]
> 
> I think it would be less convoluted to just have a `ogg_pausemusicwithgame` cvar that pauses the music when the game is paused (except maybe during demo playback, to avoid pausing the "title screen music").
> 
> It also probably would be a good idea to have a `ogg_mutemusic` cvar, so that music can be quickly muted without having to reset the volume to unmute. This way, music could be "paused" independently of the game.
> 
> > 3. Add option "pause all sounds/music and freeze the game when window is inactive"
> 
> This is a very good idea, though.

agree with you

**Comment by apartfromtime** [comment]
> 3. Add option "pause all sounds/music and freeze the game when window is inactive"

Pausing all the sounds was the default behaviour in quake2, though the game was never paused.

There is an issue around how temporary entities generate their sound (and another related issue that I mentioned in #897), but can be worked around.

**Comment by apartfromtime** [comment]
Could probably close this issue now.
