### ISSUE TITLE
[bug] map Base3 in campaign contains explosive boxes cut.

### ISSUE THREAD

**Issue by Shockblast** [yquake2/yquake2#726]
![image](https://user-images.githubusercontent.com/5357217/123049617-5dc2d600-d3c5-11eb-96fa-7d2f93e563f4.png)
This is a quite old bug, it is displayed in the original port, yquake2 (8.00) and q2pro (in any render).

I think few noticed it since the enforcer runs to press the explode button, except if you use cheats for explore stuff (notarget 👁️ ),
but the player is fast enough to kill him before he presses the button and sees that box cut off

**Comment by Yamagi** [comment]
This is map bug, the lower part of that explosive crate is missing. Good to see here:
![q2_0001](https://user-images.githubusercontent.com/1224576/123395181-33794000-d5a0-11eb-8299-3ba44085e2e2.jpg)

The crates are not part of the world mode, so maybe one of the map hack magicians like @BjossiAlfreds can fix that.

**Comment by BjossiAlfreds** [comment]
These are func_explosive that reference inline models. The buggy model is *17. It may be possible to use one of the other 3 and apply an origin offset, I'll experiment with that.

**Comment by Shockblast** [comment]
![image](https://user-images.githubusercontent.com/5357217/123477111-35a0c600-d5c3-11eb-8eeb-3c11fa72acfe.png)
looks very well to my, NICE 😎

**Comment by Yamagi** [comment]
Committed here: https://github.com/yquake2/yquake2/blob/master/stuff/mapfixes/baseq2/base3.ent Thank you for the fix!
