### ISSUE TITLE
How to make the installation portable?

### ISSUE THREAD

**Issue by Tasosgemah** [yquake2/yquake2#728]
By having the settings in the Documents/YamagiQ2, it means the program is not portable and you have to keep track of 2 locations, this and the installation folder.

Is there any way to have these files in the installation folder?

**Comment by DanielGibson** [comment]
Yes, by passing the `-portable` commandline argument to the YQ2 executable, see https://github.com/yquake2/yquake2/blob/master/doc/040_cvarlist.md#command-line-arguments

**Comment by Tasosgemah** [comment]
Thank you :)
