### ISSUE TITLE
[Feature] Sequential playback mode starting from default level music (like in PSX)

### ISSUE THREAD

**Issue by lafoxxx92** [yquake2/yquake2#729]
When entering the level, its default song is played, which is good (The track is basically "level theme").
It's Repeated when Shuffle is disabled, which is not good (same music track all over gets too irritating).
When Shuffle is enabled, default song no longer plays when you enter the level, which is bad  (The default track is basically "level theme").

Suggestion:
Add new play mode ("Sequential") -- play default level track, but when it ends -- play Next track (for example -- Track05 after Track04, etc) (like in PSX Quake)
or
Always play default track when entering the leve, but Next track will be Random (Shuffle is enabled)

**Comment by apartfromtime** [comment]
I've implemented this in pull request #986, and added an additional "play once" feature along with the requested "sequential" feature, "shuffle" remains unchanged except renamed to "random" in the menu control and now any two tracks should not repeat. I've tested all the features with the base quake2 soundtrack, I don't have the xatrix or rogue soundtracks so I'll have to defer testing of those to anyone that does.

**Comment by protocultor** [comment]
Just in case, your PR does seem to work with Xatrix, with the soundtrack in GOG format (Track02.ogg to Track21.ogg in their own "music" directory).

**Comment by Yamagi** [comment]
I have merged the pull request. I test build with the changes included can be found here: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20230416-f67b65c.zip

**Comment by apartfromtime** [comment]
Could probably close this issue now.
