### ISSUE TITLE
cant move after spawning (-O3 -flto=auto)

### ISSUE THREAD

**Issue by shoober420** [yquake2/yquake2#731]
When I start a new game, I cant move after spawning. I've included a video for reference.

https://www.youtube.com/watch?v=daBDT5rkyvQ

**Comment by Yamagi** [comment]
Hmm... It's unlikely that this was caused by yesterdays commits. They're just a small change / bugfix in the pak file loading. They change 2 things: On case insensitive platforms (Windows) numbered paks are recognized even if the file name is in caps or mixed case. And paks starting with the string *pak* not followed by a number are now supported. They weren't before, because of two different logics used to detect numbered paks.

It looks like you're stuck in the world model. That's strange and I can't reproduce it. Can you retry with a clean config (rename *~/.yq2*) and if it persist send me the complete terminal out from YQ2 start to quit?

**Comment by shoober420** [comment]
I should have worded that better. I havent actually compiled yamagi-quake2 in quite some time, so im not sure when this could have happened. I've started the game with a fresh config, and this still happens to me. Here is the console output.

[qconsole.log](https://github.com/yquake2/yquake2/files/6923060/qconsole.log)

**Comment by shoober420** [comment]
I got it! Its how i build yamagi. I normally use "-Ofast -flto=auto" to build all my programs. This combination is what is causing the bug. When i build yamagi with "-O2 -flto=auto", the game still runs. Its the combination of "-Ofast -flto=auto" that causes the bug. I also should mention that it occurs using "-O3 -flto=auto" as well.

**Comment by Yamagi** [comment]
Let me guess, gcc 9 or higher. Quake II isn't really compatible with higher optimization modes than `-O2` and it likely never will. The code is too old and relies on features considered bad practice nowadays like aliasing. Especially everything related to floating point is rather fragile. Unfortunately, the gcc developers have this habit of interpreting the C standard extremely strictly. Thus, at higher optimization levels, they like to break code that previously worked. Just stick to the default CFLAGS and be happy. The game is no longer CPU limited anyway. :)

**Comment by shoober420** [comment]
Yes, I'm using GCC 11.2 on Gentoo. I'll stick with normal optimization levels. I ironically also noticed that -fassociative-math causes tyrquake to crash in certain spots on maps.

**Comment by DanielGibson** [comment]
Never use `-Ofast`. It implies `-ffast-math` which is **not** standards compliant and tends to break shit (yes, even more than GCC's overly-strict standards-conformance abuse in `-O3`).
If this really is the "normal" optimization level on Gentoo, then Gentoo developers don't know what they're doing and you should switch to another distro.

**Comment by shoober420** [comment]
Gentoo uses "-O2" by default. These are my custom ricer build flags I use on my system personally. Some programs I have installed have issues with -O3 and -flto as well. I've made a little she'll script that will adjust flags for certain programs that aren't compatible.

https://github.com/shoober420/rootscripts/blob/main/etc/portage/package.env#L5

I have very wacky ricer build flags.

https://github.com/shoober420/rootscripts/blob/main/etc/portage/makeradeon.conf#L7
