### ISSUE TITLE
[Suggestion] Walking/Running wobbling weapon/view movement option

### ISSUE THREAD

**Issue by LukasThyWalls** [yquake2/yquake2#735]
Hello.

I'm asking about this because i was searching some kind of mod to do this, but i didn't find it. I'm guessing in Quake it's something that should be supported by the engine and by default it's not (i see other ports that seems to do something, but they are very heavily changed from the vanilla experience in anything and i wanted something more original).

Taking to the point, i'm talking about adding some sort of wobbling to reflect the movement player. Normally in FPS games is made adding some swinging to the player hand and weapon, and maybe some movement to the player viewport.

In yquake2 and vanilla quake 2, you have what i call a "magic carpet" movement. It's like the player is going on wheels and the only movement you can see is the hand/weapon animation what is making automatically:

https://user-images.githubusercontent.com/1467366/129444881-5a11bf0c-e62e-492c-8d6c-73822449e49a.mp4

I don't know if there is any hand movement when turning, or it's only my imagination seeing the video, but for sure there isn't any walking/running movement. The movement going up stairs is not like going in a ramp, but feels more like the engine sticking the player to the ground and making the movement sticking to it, however it feels fine.

To take a comparation, in Quake 1 you have that effect, but because the weapon is in the middle the walking movement in the weapon is going back and forward, and also there is a slightly up and down movement in the entire viewport when walking:

https://user-images.githubusercontent.com/1467366/129445020-0b46144f-e0a3-49a2-a06e-89cebd7e8b74.mp4

You can see the difference with some versions of WebQuake (i think this is 0.9, but i don't know what is the last one), it haven't implemented any of that and the movement feels very different and more similar to Quake 2 (but without any animation except the firing one, so this is "magic carpet" walking as its finest):

https://user-images.githubusercontent.com/1467366/129445071-edea8d32-c58e-4bdb-a822-0ce1844a04ec.mp4

Some points to think about:

- It can be done? If yes, via mod or there is need some code changes? (That is, without changing the vanilla feeling and without changing the entire models).
- When running, the effect could be going a bit faster and wider in the movement.
- It can be done as an option, to please the purists, or maybe as a slider to taking off or exaggerate the effect (whatever it is). I'm aware a heavily movement can be annoying but a bit of customization can please more tastes.
- Or (or and) add the ability to "program" the movement effect to add it to make differents mods with different behaviours.

Thanks for the work!

**Comment by BjossiAlfreds** [comment]
It isn't your imagination, there is actually a subtle bobbing effect on the held weapon, done from player/view.c:SV_CalcGunOffset. It is easy to see it when the gun is still but the player plays the idle gun anims while moving so that makes the effect harder to see.

Adding a scaling cvar to amplify the effect would be easy enough. I wouldn't hope for anything more than that though, as the gun animation system is extremely barebones, all we got is just a list of a few dozen numbered frames managed through weapon_think callbacks. Making the gun stay still while moving would be doable, but rigging animations to transition smoothly to that still frame when you start/stop moving? Good luck with that.

**Comment by LukasThyWalls** [comment]
> 
> 
> It isn't your imagination, there is actually a subtle bobbing effect on the held weapon, done from player/view.c:SV_CalcGunOffset. It is easy to see it when the gun is still but the player plays the idle gun anims while moving so that makes the effect harder to see.
> 
> Adding a scaling cvar to amplify the effect would be easy enough. I wouldn't hope for anything more than that though, as the gun animation system is extremely barebones, all we got is just a list of a few dozen numbered frames managed through weapon_think callbacks. Stopping the idle anims while moving so the bobbing is more visible would be doable, but rigging animations to transition smoothly to that still frame when you start/stop moving? Unless framelerping does the work for you, good luck with that.

I read the gun animation is pretty rough, that's why i'm asking this.

Also what you are saying about the turning movement, it's pretty suttle so it's hard to see, but also like you said, the animation breaks any because it adds to the animation itself doing weird things. Should it better only use the idle animation when it's idle?

But i need to rectify myself: There is a running movement for the weapon. It very hard to see with the blaster, but with the supershotgun it's noticiable. It also feels weird when the weapon animation pop up. It's more like a swing as like a pendulum and it's very slow, it doesn't fit a "run" movement and more like a "walk" movement.

That's why i'm asking this, i don't know what is allowed to do via mods, what should be changed in the port itself, but without changing everything and trying to keep an original feel.

**Comment by Yamagi** [comment]
The movement and animation is in the game, https://github.com/yquake2/yquake2/tree/master/src/game in this repo. It could be done in our code (if it's well implemented and hidden behind a cvar, doing it for the addons would be nice), but also in a mod by forking the game code. If it's done in a mod I would highly recommend to start with the YQ2 game code and not with the official SDK or some other lib. That way you get all the small and big bugfixes we've done over the years.

**Comment by BjossiAlfreds** [comment]
> Also what you are saying about the turning movement, it's pretty suttle so it's hard to see, but also like you said, the animation breaks it because it adds to the animation itself doing weird things. Should it better only use the idle animation when it's idle?

One could argue it's an oversight, but maybe others would argue the idle anims give the wobbling a more natural look, like a human is holding the gun while running rather than a robot.

> It also feels weird when the weapon animation pop up. It's more like a swing as like a pendulum and it's very slow, it doesn't fit a "run" movement and more like a "walk" movement.

The wobbling offset is calculated from the footstep events, so it is perfectly synced with your footstep sounds. I find it easiest to see this while holding the hyperblaster as it has the least amount of idle movement.

Also, it looks like a pendulum because the wobbling offset is purely angular, so the gun is being rotated around an origin instead of being actually moved around.

I do notice though, that the wobbling some times seems to pause, I see it a lot with the super shotgun fx. That is something that would be interesting to look into.

> That's why i'm asking this, i don't know what is allowed to do via mods, what should be changed in the port itself, but without changing everything and trying to keep an original feel.

We address bugs and clear oversight issues, other stuff is either optional or left alone entirely. At the time of writing this I see no signs in the code that the wobbling is buggy, just shoddily put together, likely due to time shortage or lack of caring on id's part.

I will say, I do think this is an interesting subject that you brought up and I'm tempted to look into it further and experiment. However this is a voluntary effort and I have a life to live so I can not promise anything.

**Comment by LukasThyWalls** [comment]
> The wobbling offset is calculated from the footstep events, so it is perfectly synced with your footstep sounds. I find it easiest to see this while holding the hyperblaster as it has the least amount of idle movement.

I don't know if i'm doing something wrong, but i need to point it out: Playing the game, if i walk (no Always Run, no Running button [Shift]) straight using only Walk Forward Button [W], there isn't any footsteps sounds. If i run (with Always Run Setting or the Running button [Shift]) there are footstep sounds (and a noticiable movement, but maybe a little slow for run IMHO, maybe will fit better for a walk, but that's something i point out earlier i just see).
BUT, i walk (no Always Run, no Running button [Shift]) walking straight using Walk Forward Button [W] AND pushing the strafe buttons ([A] and [D]) to go in zig zag, there are footsteps.
It's intended there is no footsteps sounds when walking in a straight line or is something broken here?

> The wobbling offset is calculated from the footstep events, so it is perfectly synced with your footstep sounds. I find it easiest to see this while holding the hyperblaster as it has the least amount of idle movement.

About the Hyperblaster, not only it's the one that the weapon movement when running seems fine, also it is the one weapon what the turning movement response is more noticiable. But when walking, i don't know how to describe it, it's like it's shivering, i don't know...

> One could argue it's an oversight, but maybe others would argue the idle anims give the wobbling a more natural look, like a human is holding the gun while running rather than a robot.

Yes, i like the hand animations, but like i point out in the videos above, it seems more like the player is on wheels. That is more like a robot than other thing...

> We address bugs and clear oversight issues, other stuff is either optional or left alone entirely. At the time of writing this I see no signs in the code that the wobbling is buggy, just shoddily put together, likely due to time shortage or lack of caring on id's part.

I know, thats why i put the "Suggestion" tag in the title. There is nothing wrong with this in the port, as its seems like similar or exactly the same in the Quake 2 vanilla game.
But it's something bothering me since the first time i played, but when you play other games and compare with this its more noticiable. I don't know why can be adressed at some point.

I did some research of how other ports do this, only to reference. In Quake 2 RTX seems they changed all of this directly and look like similar to other games:

https://user-images.githubusercontent.com/1467366/131717535-ccf76621-54b0-4750-9db1-388b854ff2be.mp4

I tried to record Quake 2 XP, but that one is a bit weird, in some gameplays looks like the weapon is swinging, but the animation stops abruptly when turning, moving the mouse or strafing, i can record more than a second with the movement so i didn't.

**Comment by Yamagi** [comment]
> I don't know if i'm doing something wrong, but i need to point it out: Playing the game, if i walk (no Always Run, no Running button [Shift]) straight using only Walk Forward Button [W], there isn't any footsteps sounds. If i run (with Always Run Setting or the Running button [Shift]) there are footstep sounds (and a noticiable movement, but maybe a little slow for run IMHO, maybe will fit better for a walk, but that's something i point out earlier i just see).

Not the footsteps again. Please! :) The footstep generation in Vanilla Quake II is somewhat questionable. Footstep are generated only if the player is moving faster than a certain speed and on a ground entity. I've hacked `g_footsteps` to configure the footstep generation but neither option is perfect: https://github.com/yquake2/yquake2/blob/master/doc/040_cvarlist.md#general

**Comment by BjossiAlfreds** [comment]
I think I found why the wobbling pauses. When the player state is being written to clients, the net message will only contain PS_WEAPONFRAME segment if the gunframe actually changed from the old player state, thus discarding gunoffset and gunangles even if they changed that frame.

There is an easy way to observe this. Wait for a gun to pause its idle movement, then open the console and set gun_z cvar value to 10. You will see that this change will not be applied until the gun animation starts moving again.

An easy way to fix this would be to always send gunoffset and gunangles to clients regardless of the gunframe changing, as long as the gunindex is non-zero (there is actually a weapon being held). Basically, always put PS_WEAPONFRAME segment unless gunindex is 0. There might be implications to this but off the top of my head I think this could work.

**Comment by LukasThyWalls** [comment]
> > I don't know if i'm doing something wrong, but i need to point it out: Playing the game, if i walk (no Always Run, no Running button [Shift]) straight using only Walk Forward Button [W], there isn't any footsteps sounds. If i run (with Always Run Setting or the Running button [Shift]) there are footstep sounds (and a noticiable movement, but maybe a little slow for run IMHO, maybe will fit better for a walk, but that's something i point out earlier i just see).
> 
> Not the footsteps again. Please! :) The footstep generation in Vanilla Quake II is somewhat questionable. Footstep are generated only if the player is moving faster than a certain speed and on a ground entity. I've hacked `g_footsteps` to configure the footstep generation but neither option is perfect: https://github.com/yquake2/yquake2/blob/master/doc/040_cvarlist.md#general

Sorry to bring you nightmares again, i didn't know it is something that give you some headaches in the past-

But anyway, learning about `g_footsteps`, i see if you use `g_footsteps 2` the footsteps sounds always, what is for me fine but that's what i want to test.

Reading above about the weapon movement is synced with the footsteps, when walking the footsteps sounds every one second or almost a second. For me it seems a bit low cadence of walking, and if the weapon movement it's synced with that, the movement it's pretty slow too, and then there is something here related to the topic.

Is there any (easy) way to speed up the cadence of walking/footsteps? Although it breaks the running speed, only for testing.

**Comment by Yamagi** [comment]
> Is there any (easy) way to speed up the cadence of walking/footsteps? Although it breaks the running speed, only for testing.

Yes, the code is simple: https://github.com/yquake2/yquake2/blob/master/src/game/player/view.c#L1043

**Comment by LukasThyWalls** [comment]
Hello

I don't want to be a nuisance with this, and for sure i'm repeating myself (there are a few months since my last post) but i need to point this out.

Maybe i'm contradicting myself, but in these months i beated Quake II and all its official expansions with Yamagi, and i think the weapon movement for running was fine for all weapons then, and they still are with 8.01. However, the walk and crouch movement is other thing. 

The fix #751 makes all the weapons wobble, as opposite than with 8.00 for walking. However, i still see issues with the step cadence.

As i have `g_footsteps 2`, you can see and hear the steps easily (i see 8.01 fixes the dive/fly sound steps). And they match the weapon wooble as it should be.

I did a little count with the corridor in the first level: It has a bit more than 10 tiles from the entrance to the corner, and i think as a realistic vision, i put each one is at least 0,75 m (2,5 feet) of side. If the player run from the entrace to the corner, you hear 4 footsteps (and you see 4 movement left/right from the weapon), so in one running step it moves 2.5 tiles, or the player stride length is 2,25 m (7.5 feet), which is a very long stride but it's a videogame, etc, etc. but feels fine with the speed of the movement.
The issue comes when walking, because walking that corridor you still hear (and the weapon movements reflects it too) that the player does also 4 steps. So every step is also 2,25 m (7.5 feet) with a slower speed, which is not realistic in any means.
Also other thing that reflect that the footsteps (and consequently the weapon wooble movement) is not right, is when you are crouching, the footsteps and weapon movement goes over the place, as it sound likes that the player is doing tap dance. I know i'm using `g_footsteps 2` and i normal circunstances you don't hear those sounds, but the weapon wooble follows that cadence so you can see it.

I don't want to be annoying, maybe it's only an opinion, or something stupid that doesn't matter, i don't know. Maybe it's for open other issue as the main thing here is fixed.

I choose that example of the corridor because you can see with that what feels weird when the player walks now, that can be debatable, of course. In my opinion, the running movement/steps are fine, the walking should be the half of the running cadence, and the crouch, the same as the walking (and not that tap dance thing). Also mention that i'm aware that a lot of steps or weapon wobble can be distracting (in fact, it's something that happens in Dark Forces 2 with existing mods and patches) but the right amount make the game look cooler.

Thanks.
