### ISSUE TITLE
Compiling for noobs (Windows)

### ISSUE THREAD

**Issue by Mitradis** [yquake2/yquake2#736]
as stated in the instructions
https://github.com/yquake2/yquake2/blob/master/doc/020_installation.md
iam download quake2-buildenv-20210607.7z and unpack him into C:\ and rename buildenv folder to MSYS2
after that my adventures were over:
I could not find C:\MSYS2\msys32.exe
at startup C:\MSYS2\msys32.exe I didn't understand what to do

I downloaded the sources using the commands:
cd C:\Build
git clone https://github.com/yquake2/yquake2.git --branch master --single-branch yquake2 --depth 1
through the command line i tried to run the file Makefile but it failed.

please tell us step by step what and how you need to do to compile.

**Comment by j4reporting** [comment]
current MSYS2 installations can be started with the provided msys2_shell.cmd script.

for MSYS2 maintenance:  msys2_shell.cmd -msys 
MInGW 32-Bit:   msys2_shell.cmd -mingw32
MInGW 64-Bit:   msys2_shell.cmd -mingw64

see https://www.msys2.org/   for more details.

**Comment by Mitradis** [comment]
nothing is clear, I do not understand how to run the Makefile through msys2_shell.cmd

**Comment by j4reporting** [comment]
I think you don't undestand yet what MSYS2 is.  It's a  UNIX like posix environment.
You start the 32-Bit environment with   "msys2_shell.cmd -mingw32".
This will open a new window and gives you a bash shell, with access to most of the usual UNIX  commands and binutils.
Shell is chrooted  to your MSYS2 folder e.g.   C:\MSYS2\   with your $HOME  as /home/<userid>   found in C:\MSYS2\home\<userid>  etc.
To access files and directories outside of the chroot,  you need to use a path line   /d/src/<something>  ( this translates to D:\src\<something>
Some UNIX know-how is certainly helpful here.

**Comment by Yamagi** [comment]
The documentation is really up to date. I need to give it some love. @j4reporting already explained it. A more "mechanical" recipe:

1. Download the preconfigured build environment from https://deponie.yamagi.org/quake2/windows/buildenv/quake2-buildenv-20210607.7z and extract it. The path doesn't matter, MSYS2 is self contained.
2. Start it through `buildenv\ming32.exe` (for a 32 bit build). That's a wrapper executable which puts the 32 bit MinGW distribution into the $PATH variable.
3. Navigate to your sources and type `make` to compile them.
