### ISSUE TITLE
[Suggestion] ATI TruForm Support

### ISSUE THREAD

**Issue by Screamerofstars** [yquake2/yquake2#740]
So this is something that im leaving here thanks to Dege, the Creator and developer of DgVoodoo2 Wrapper managing to reconstruct the ATI TruForm/Hardware RealTime Tesselation Technique back to his wrapper, which many games back in the 2000's even quake supported it.

https://www.vogons.org/viewtopic.php?f=59&t=83037
https://www.vogons.org/viewtopic.php?f=63&t=83000

it would be possible for you guys to check this out at vogons? it would be a interesting gimmick for Yq2 once this finally comes out and with some tweaks.

**Comment by DanielGibson** [comment]
This: https://www.youtube.com/watch?v=vr07XyAQv_g ?

Looks horrible - like all the models are made of rubber and inflated too much O_o

**Comment by Screamerofstars** [comment]
Its due to how the tesselation works on the model itself. 
https://www.youtube.com/watch?v=MYCN2Bb55oU
This in case from what i saw, wasn't tweaked since this Q2 Implementation was a experimental test out of using Q3A and RTCW code, the second thread has more info on this, plus other forums who tested this back in the 2000's, along with some youtube videos .
Plus, TruForm Q3A, DeusEX, UT and RTCW had some impressive results

The idea would be using the using the wrapper to make the calls into the OpenGL and Vulkan drivers and tweak its implementation to not leave it out as it was shown there, mainly with guns.

But since DgVoodoo2 makes Directx Calls, idk how it would be.
Its mostly a suggestion, but it would be interesting to see this concept sort it out if you could chose to make the monsters make full use of it since the code was released.

**Comment by Yamagi** [comment]
YQ2 has support for external render libs maintained by third parties. So one could fork one the renderers and add TruForm or some other tessellation  technique to it...

**Comment by Screamerofstars** [comment]
Per Luck, he released a WIP build today, everyone is free to test it on ATI TruForm games that supports or patches for it and give feedback.

https://www.vogons.org/viewtopic.php?p=996742#p996742

Morrowind as He used for instance, has an option to chose which set of models can receive the Graphical improvements by using its FPS Optimizer program that enables it, Back when ATI introduced this API gimmick, it really improved the game's graphics but it put the game into its knees, something that could be used if implemented to keep the ingame range of meshes like items, barrels as so on out of it.

Half Life and Deus Ex made good use of it too as ATI worked to patch many of the popular games of its time.

**Comment by Screamerofstars** [comment]
> @Screamerofstars Do you have link to source patch with TruForm support? By quick look, i have found only compiled version of the gl render.
> 
> It look same as [CurvedPNTriangles](https://github.com/SaschaWillems/Vulkan/blob/master/examples/tessellation/tessellation.cpp), I have tried to check it but without any useful results.

Check with the FTEQW devs they still support TruForm.
Also the VOGONS page with the list has more info https://www.vogons.org/viewtopic.php?f=63&t=83000

it  still would be better to check there, as people are testing the other truform games

**Comment by 0lvin** [comment]
I have made small investigation FTE QuakeWorlds has support of TruForm like functionality by gl_ati_truform_type and r_tessellation_level. And it looks as it requires additional hacks for models, because guns and barrels are horrible, enemies are not so bad. And tessellation should be disable for guns and only enabled for "approved" models.

Look to: https://sourceforge.net/p/fteqw/code/HEAD/tree/trunk/engine/client/renderer.c#l370 

![fte-20210905155808-0](https://user-images.githubusercontent.com/73573/132127782-ed7cdc3e-1a27-4db2-9378-07e1bd2bb786.png)
![fte-20210905155539-0](https://user-images.githubusercontent.com/73573/132127798-20d2de68-4ecc-4ad0-9192-4d38af80719e.png)

**Comment by Screamerofstars** [comment]
Its pretty much what Morrowind does when using the N-Patch per FPS optimizer, a good way would be using Q2's native folders as direction for it.

like r_tessellation_models_Weapons 0 for the entire folder

**Comment by Screamerofstars** [comment]
Also something i noticed too is how fubar the tessellation strength is to the monster models.

with some work it would be great, but to do so, by the looks of it, Q2 would need to ditch vertex animations for the same technique Quake remastered used for its models, which is Md5 format with Bones animations and some high poly tweaks.

**Comment by DanielGibson** [comment]
See, this is impossible so it's not gonna happen.
We're neither gonna introduce MD5 support nor create new models.

(And if someone created new models, they could be created with more details so TruForm would be pointless)

**Comment by turol** [comment]
In theory it would be possible to conversion from frame-based to bone-based models automatically at runtime

https://github.com/electronicarts/dem-bones

**Comment by apartfromtime** [comment]
Either re-authoring the models or training a neural net, with all the available information would be a best approach. Looking at a problem from a singular point of view, is not the proper way to solve it (in my opinion). The first isn't within the scope of the project and the latter doesn't exist. Even if the latter did exist some re-authoring of the models would still be required as there is bound to be some anomalies.

**Comment by Yamagi** [comment]
We won't add ATi TruForm to YQ2. If anyone want's to take up the task, it can be done in an external renderer. So I'm closing here.
