### ISSUE TITLE
Feature request : add cvar to disable machine gun recoil in single player

### ISSUE THREAD

**Issue by De-Seppe** [yquake2/yquake2#741]
Is it possible to add a cvar to disable machine gun recoil in single player.
I am able to "fix" this by compiling the code myself and commenting out the lines responsible for this, but this would be a nice thing to have as a cvar.

**Comment by Yamagi** [comment]
If you send a pull request I'll be happy to merge it. Don't forget to add that cvar to the docs in https://github.com/yquake2/yquake2/blob/master/doc/040_cvarlist.md an - if possible - to port it over to at least the *rogue* and *xatrix* addons.

**Comment by De-Seppe** [comment]
I tried to implement it as good as possible.
This is my first contribution to a git open source project.
Feel free to mention all things that are wrong with my pull requests, this way I'll learn from it.

https://github.com/yquake2/yquake2/pull/747
https://github.com/yquake2/xatrix/pull/67
https://github.com/yquake2/rogue/pull/84
