### ISSUE TITLE
Game opens, runs in taskbar only.  Stops responding

### ISSUE THREAD

**Issue by DaveBilling** [yquake2/yquake2#75]
Yamagi Quake II 5.30 is not working at all on my system.  It opens in the taskbar, but fails to initialize correctly.  Instead it just freezes and stops responding.  I have no idea why.

**Comment by DanielGibson** [comment]
and neither do we. for us it works :-P

you could enhance the chances of us trying to fix it by giving more information, like what operating system, what version of SDL, what GPU (what driver?) etc you're using.  
and by describing the issue a bit more (is there even a window? what does it show?)  
the qconsole.log might also be of interest.

**Comment by DaveBilling** [comment]
Windows 7, Nvidia GeForce 640m GPU, driver version 344.75 (which is deliberately out of date).  And it doesn't show anything.  The tab in the task bar appears but nothing else.  The only way to get it to close it via the task manager.

**Comment by DanielGibson** [comment]
does `...<Username>\Documents\YamagiQ2\baseq2\qconsole.log` exist? any information in it?

**Comment by DaveBilling** [comment]
Nothing unusual in the console log.

Here's a copy of it below for your reference.


Winsock Initialized
Console initialized.

------- sound initialization -------
LoadLibrary(openal32.dll)
...opening OpenAL device:ok
...creating OpenAL context: ok
...making context current: ok

OpenAL settings:
AL_VENDOR: Creative Labs Inc.
AL_RENDERER: Software
AL_VERSION: 1.1
AL_EXTENSIONS: EAX EAX2.0 EAX3.0 EAX4.0 EAX5.0 EAX3.0EMULATED 
EAX4.0EMULATED AL_EXT_OFFSET AL_EXT_LINEAR_DISTANCE AL_EXT_EXPONENT_DISTANCE

Available OpenAL devices:
- Generic Software on Speakers (Realtek High Definition Audio)
- Generic Software on E2350 (Intel(R) Display Audio)

Current OpenAL device:
- Generic Software

Number of OpenAL sources: 31

Starting Ogg Vorbis.
OGG_LoadPlaylist: could not open playlist: No such file or directory.
No Ogg Vorbis files found.
Shutting down Ogg Vorbis.
Sound sampling rate: 0
------------------------------------

----- refresher initialization -----
Byte ordering: little endian

Refresher build options:
  + Retexturing support
  - Gamma via X11
Refresh: Yamagi Quake II OpenGL Refresher
SDL video driver is "windows".
setting mode 21: 1920 1080
Got 8 bits of stencil.
Using hardware gamma via SDL.

OpenGL setting:
GL_VENDOR: NVIDIA Corporation
GL_RENDERER: GeForce GT 640M/PCIe/SSE2
GL_VERSION: 4.4.0 NVIDIA 344.75
GL_EXTENSIONS: GL_AMD_multi_draw_indirect 
GL_AMD_seamless_cubemap_per_texture GL_ARB_arrays_of_arrays 
GL_ARB_base_instance GL_ARB_bindless_texture GL_ARB_blend_func_extended 
GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture 
GL_ARB_color_buffer_float GL_ARB_compatibility 
GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth 
GL_ARB_compute_shader GL_ARB_compute_variable_group_size 
GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_debug_output 
GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture 
GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_indirect 
GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced 
GL_ARB_enhanced_layouts GL_ARB_ES2_compatibility 
GL_ARB_ES3_compatibility GL_ARB_ES3_1_compatibility 
GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location 
GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport 
GL_ARB_fragment_program GL_ARB_fragment_program_shadow 
GL_ARB_fragment_shader GL_ARB_framebuffer_no_attachments 
GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB 
GL_ARB_geometry_shader4 GL_ARB_get_program_binary GL_ARB_gpu_shader5 
GL_ARB_gpu_shader_fp64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex 
GL_ARB_imaging GL_ARB_indirect_parameters GL_ARB_instanced_arrays 
GL_ARB_internalformat_query GL_ARB_internalformat_query2 
GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment 
GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect 
GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query 
GL_ARB_occlusion_query2 GL_ARB_pixel_buffer_object 
GL_ARB_point_parameters GL_ARB_point_sprite 
GL_ARB_program_interface_query GL_ARB_provoking_vertex 
GL_ARB_robust_buffer_access_behavior GL_ARB_robustness 
GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map 
GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects 
GL_ARB_shader_atomic_counters GL_ARB_shader_bit_encoding 
GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote 
GL_ARB_shader_image_load_store GL_ARB_shader_image_size 
GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_query_buffer_object 
GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine 
GL_ARB_shader_texture_lod GL_ARB_shading_language_100 
GL_ARB_shading_language_420pack GL_ARB_shading_language_include 
GL_ARB_shading_language_packing GL_ARB_shadow GL_ARB_sparse_texture 
GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader 
GL_ARB_texture_border_clamp GL_ARB_texture_buffer_object 
GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range 
GL_ARB_texture_compression GL_ARB_texture_compression_bptc 
GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map 
GL_ARB_texture_cube_map_array GL_ARB_texture_env_add 
GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar 
GL_ARB_texture_env_dot3 GL_ARB_texture_float GL_ARB_texture_gather 
GL_ARB_texture_mirror_clamp_to_edge GL_ARB_text

**Comment by maraakate** [comment]
Can you click on the tab and try hitting ctrl+enter.  Does it try to toggle a full screen mode?  It may have started up windowed and the window is actually off screen.

If you click on the taskbar and type something like "map q2dm1" does it start loading anything?

**Comment by Yamagi** [comment]
I'm still unable to reproduce this and haven't had any other report.
