### ISSUE TITLE
8.00 doesn't open a listening socket when creating server

### ISSUE THREAD

**Issue by astro** [yquake2/yquake2#754]
Hi! Just tried the latest version but none of us (NixOS/x86_64-linux and Windows/x64) were unable to join the other's server. We fixed by reverting the server to 7.43.

Is this already known? Can you reproduce?

**Comment by SergeyLatyshev** [comment]
I had the same problem too with 8.00 (on Debain and Arch), but 8.01 works fine.

**Comment by astro** [comment]
> I had the same problem too with 8.00 (on Debain and Arch), but 8.01 works fine.

Thank you for reporting here. I can confirm that it's fixed.

**Comment by Yamagi** [comment]
Which is interesting, because there were no changes to the network code between 8.00 and 8.01...
