### ISSUE TITLE
windows xp support

### ISSUE THREAD

**Issue by puntja** [yquake2/yquake2#756]
is there a yamari version that works with windows xp? I tried 8.00 but I can't get it to run

**Comment by maraakate** [comment]
If you require Windows XP support with HTTP downloading and other nice stuff try Quake 2 v3.24 or Q2DOS for Windows.

http://kmq2.toastednet.org/downloads/q2-3.24-x86-full-ctf-1.5.exe
https://bitbucket.org/neozeed/q2dos/downloads/q2dos_20210722_win32.7z

Note that neither port has HUD scaling.  But if you're vintage gaming I doubt you need this feature.

**Comment by Yamagi** [comment]
Listen to @maraakate :) While we don't break support for older Windows versions on purpose, we don't test against them either. And I'm pretty sure that at least the `openal-soft` library dropped Win XP support years ago. Maybe SDL2 also did something like that.

**Comment by puntja** [comment]
I just wanna play single player campaign :) I found out through trial and error that 7.30 is the last version that runs on windows xp :)

But I have another issue. I am stuck at 64fps. I tried various console commands mentioned in the configuration guide, but I can't get it above 64 :-\ How can I run it at 120fps/hz?

**Comment by maraakate** [comment]
You probably have Vsync turned ON in your video card options somewhere.

**Comment by puntja** [comment]
I actually don't, because that's the first thing I checked :) and all other games run fine

**Comment by maraakate** [comment]
OK.  I don't know what the CVAR is in YQ2 v7.30 for Vsync.

**Comment by maraakate** [comment]
Try

r_vsync 0
vid_maxfps 125
cl_maxfps 125

**Comment by puntja** [comment]
no change. still 64 fps though :-\ 

it doesn't matter if I use open gl 1.4, 3.2 or software rendering. it doesn't go above 64fps.

**Comment by maraakate** [comment]
May I ask why you are on Windows XP?  Is this for a vintage gaming computer or is this your main PC?

I don't remember if v7.3.0 of YQ2 was named properly.  Windows App-Compat explicitly breaks things with Quake 2.  Rename the game binary to yquake2.exe and run that if it hasn't already been done.  I remember there was a stubloader made at some point to get around this issue in windows but can't remember what build it was.

**Comment by puntja** [comment]
yeah It's a vintage gaming pc :) It's not my main one :) 

the file is already named yquake2.exe

**Comment by maraakate** [comment]
An easy way to tell if Windows is secretly applying the App-Compat fix for Quake 2 is trying to alt+tab.  If that fails it's applying fixes in the background.  As long as it's not named Quake2.exe it should fool the App-Compat.

**Comment by maraakate** [comment]
What video card is it?  You may need to create a profile in the video card control panel explicitly for YQuake2.exe to force vsync off.

**Comment by puntja** [comment]
It's a Nvidia GTX 750 ti. 

I created a new profile and forced vsync off for yquake2.exe

still only 64 fps. 

And I can't alt-tab back to windows

on my main windows 10 pc version 8.00 runs with the maximum framerate

**Comment by maraakate** [comment]
Are you explicitly double clicking the yquake2.exe or running that quake2.exe stub loader?

If you're explicitly running yquake2.exe I am unfortunately out of ideas at this point.  You could try renaming it to yq2.exe and see if that fixes it.  Maybe the Nvidia XP driver itself is just checking to see if it has quake2.exe anywhere in the name.

**Comment by puntja** [comment]
I'm explicity running yquake2.exe and I tried renaming it. Same issue. 

I tested Q2 V3.24 now and it works like a charme with the disered framerate I want

**Comment by Yamagi** [comment]
I've just compiled a 7.30 under Linux. The frame cap works like in 8.00: If `cl_async 1` (the default) and `r_vsync 0` the game renders `vid_maxfps` frames. If `r_vsync 1` it renders as many frames as the display can show. There were still small bugs in the timing code and the internal statistics (used by the frame counter) but nevertheless it should work that way. If it doesn't something from the outside is limiting the frames rendered per second. Or you're hitting a bug in SDL.
