### ISSUE TITLE
5.30 fails to launch on OS X 

### ISSUE THREAD

**Issue by spinkham** [yquake2/yquake2#76]
Launcher comes up with "choose game to start", and when I hit start the program closes. Have attached what I believe is the most relevant info, let me know if there's other info that would be helpful.

uname -a
Darwin Steven-Pinkhams-MacBook-Pro.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64

From system.log
May 27 15:05:41 Steven-Pinkhams-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.cocoaDialog.17514): Failed to bootstrap path: path = /Applications/Quake 2.app/Contents/Extra/cocoaDialog.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle, error = 20: Not a directory
May 27 15:05:41 Steven-Pinkhams-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.cocoaDialog.17514): Failed to bootstrap path: path = /Applications/Quake 2.app/Contents/Extra/cocoaDialog.app/Contents/Frameworks/Growl.framework/Versions/A/Growl, error = 20: Not a directory
May 27 15:05:42 Steven-Pinkhams-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000025.q2-launcher.sh[17507]): Service exited with abnormal code: 127

**Comment by DanielGibson** [comment]
@Jarvik7 any idea about this?

**Comment by Jarvik7** [comment]
Those errors are both from the cocoadialog.app (third party APIs in that app to be specific), which I haven't touched and the addition predates my work on the OSX build. When I get home I can check if the app template zip somehow got corrupted, but I suspect it's something on spinkham's end.

I've mentioned this in a few other issues, but moving forward I think that mod directory selection should be moved into the in-game menu. It would allow cocoadialog.app to be eliminated completely.

**Comment by DanielGibson** [comment]
couldn't mod selection be done like on all other operating systems - with the appropriate commandline argument (`+set game rogue`, for example)?

**Comment by Jarvik7** [comment]
That already works on OSX as well I believe, but cocoadialog acts as a frontend to let you do it (select q2 or the mission packs) without using the terminal.

**Comment by Yamagi** [comment]
Even on Windows - the GUI based operating system number one, for years even without an usable cmd interface - we force users to drop into the command line or to create special shortcuts. Therefor I say: Throw that wrapper script into the dustbin. Who's able to copy the game data into place should be able to open a terminal and type 2 or 3 commands..
