### ISSUE TITLE
Guard pain skins

### ISSUE THREAD

**Issue by drakonorodny** [yquake2/yquake2#761]
Hi, 
As in Vanilla QII, the guard enemy does not display pain skins while alive. This is apparently due to `max_health` (from which the threshold for changing the skin is determined) not being set for this enemy because it exists in 3 'flavours' (or 6 in xatrix), each with different starting health (20, 30, 40). A quick hack would be to set the variable manually for each, but perhaps there is a better solution. Any ideas?

**Comment by Yamagi** [comment]
@BjossiAlfreds, what do you think?

**Comment by Yamagi** [comment]
> Do you want me to do a PR or can you tackle it? It's a fairly simple fix.

Simple after the problem was analyzed and understood. Were you deep understanding of the game code is really helpfull. I've comitted a fix. Thank you for your help.

**Comment by BjossiAlfreds** [comment]
Glad to be of assistance. This affects rogue and xatrix as well btw.

**Comment by Yamagi** [comment]
Mkay. I'll do another round tomorrow when I'm not tired.

**Comment by Yamagi** [comment]
Done. I've moved `self->health` and `self->gib_health` above the function call and committed it to both addons.
