### ISSUE TITLE
stb_image.h and stb_image_resize.h updates break renderer libs on windows

### ISSUE THREAD

**Issue by j4reporting** [yquake2/yquake2#762]
It seems that commit 67f22cce17c059dd76deb6e62bfbc2a77085a3f1   and  5bae9145f42dc336b0334be5f9cd001b9f32cc1e  ( ref_vk)   break all renderer libs  on Windows. 
System runs WIn10 21H1   with Intel GPU and driver version 27.20.100.9466 installed.

```
stderr:    Error: No usable renderer found!

stdout:
----- refresher initialization -----
Loading library: ref_vk.dll
Sys_LoadLibrary failed: LoadLibrary returned 126 on e:\games\yquake2_pre_own_msys_builds\ref_vk.dll
Loading ref_vk.dll as renderer lib failed!
Retrying with gl3...
----- refresher initialization -----
Loading library: ref_gl3.dll
Sys_LoadLibrary failed: LoadLibrary returned 126 on e:\games\yquake2_pre_own_msys_builds\ref_gl3.dll
Loading ref_gl3.dll as renderer lib failed!
Retrying with gl1...
----- refresher initialization -----
Loading library: ref_gl1.dll
Sys_LoadLibrary failed: LoadLibrary returned 126 on e:\games\yquake2_pre_own_msys_builds\ref_gl1.dll
Loading ref_gl1.dll as renderer lib failed!
Retrying with soft...
----- refresher initialization -----
Loading library: ref_soft.dll
Sys_LoadLibrary failed: LoadLibrary returned 126 on e:\games\yquake2_pre_own_msys_builds\ref_soft.dll
Loading ref_soft.dll as renderer lib failed!
Shutting down OpenAL.
```

buildenv is an up to date  MSYS2 setup  with  gcc.exe (Rev1, Built by MSYS2 project) 11.2.0

**Comment by Yamagi** [comment]
Ha, nice. I wanted to make another Windows testbuild tonight with this weeks fixes... Looks like this was broken by the thread local stuff added to stb_image.h about two years ago: https://github.com/nothings/stb/commit/eb48fbdcede98f93dab3a5e42ce5b0072b739cf1 Maybe the mingw stuff doesn't implement enough threading for that. Or something like that. I'll need to dig deeper to figure out what exactly is wrong. I'll commit a band aid fix shortly.

**Comment by Yamagi** [comment]
The fix is committed and another testbuild is here: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20211105_a055082.zip

**Comment by DanielGibson** [comment]
alternative solution: https://github.com/yquake2/yquake2/pull/765
