### ISSUE TITLE
[Original bug] player_noise entity leak

### ISSUE THREAD

**Issue by BjossiAlfreds** [yquake2/yquake2#763]
I discovered this one pretty recently. Any time you go through a level transition, players lose their link to their player_noise entities, so PlayerNoise() will spawn new ones.

Steps to reproduce:
1. Open rogue (we need their "entcount" command)
2. Open ware2 and execute entcount
3. Fire the blaster
4. Execute entcount again and notice 2 entities were spawned
5. Go back to ware1 through the bulkhead
6. Return to ware2
7. Fire the blaster again
8. Execute entcount
9. Notice that 2 more entities have been spawned
10. You can keep repeating this process all the way until the game crashes to console

This is not a big issue in the moderately sized levels/units of the base campaign but this could be a showstopper in very entity heavy maps with lots of backtracking potential.

I have fixed this on my end by verifying mynoise and mynoise2 links when PlayerNoise() is called. If one or both of them are bad it will search the level entity list for matching player_noise and link them back to the player, or spawn new ones if one or both of them are missing. If you want I can replicate that code for YQ2 and do a PR.

Also, would you like player_noise to be optional entities? It would merely cause monsters to not hear player sounds any more, if the entity fails to spawn.

**Comment by Yamagi** [comment]
> I discovered this one pretty recently. Any time you go through a level transition, players lose their link to their player_noise entities, so PlayerNoise() will spawn new ones.
> [..]
> This is not a big issue in the moderately sized levels/units of the base campaign but this could be a showstopper in very entity heavy maps with lots of backtracking potential.

I'm always impressed what interesting problems can still be found after so many years. That's very impressive, myself and most other users would never have noticed. A PR would be appreciated. And making player_noise entities optional so that they can be omitted in case of an entity overflow sound like a good idea too.

**Comment by BjossiAlfreds** [comment]
A random thought led me to discovering this. I just randomly asked myself if those mynoise links are always maintained, and I found it likely level transitions would break them since player edicts are reset in those situations. Then I tested and confirmed that this is a leaky situation.

**Comment by Yamagi** [comment]
I've merged the pull requests.
