### ISSUE TITLE
[Suggestion] Multiplayer\Coop specific menu key binds

### ISSUE THREAD

**Issue by apartfromtime** [yquake2/yquake2#769]
There is a number of key binds that are implicit to the player in multiplayer or co-op games, like scoreboard, message mode chat and gestures. Could these be exposed through a sub-menu from either the "multiplayer" or "options" menu to the player? Suggested names could be "customize multiplayer controls", "multiplayer controls" or "customize multiplayer".

**Comment by apartfromtime** [comment]
I had a second thought that maybe the key binds could be cycled by page similar to how the load save game menu functions, but since everything has to fit on the lowest resolution screen (320x240), and the current "customize controls" screen uses all the available space of a screen at 320x240, and also has a tooltip status bar present, making paging the screen not possible.

I decided to simply copy how key binds are done in options, for multiplayer as mentioned in previous post. Maybe the menu item should be in options? Here is a commit for you to review. #[cb5214f](https://github.com/apartfromtime/yquake2/commit/cb5214f79578301f945a9b4263d204301e643c8f)

**Comment by Yamagi** [comment]
At a very first look this looks god. Can you do a pull request so this doesn't get lost? We'll have a deeper look in the next few days.

**Comment by Yamagi** [comment]
I've merged pull request #770.
