### ISSUE TITLE
[BUG] Oversampling at max multisampling level

### ISSUE THREAD

**Issue by apartfromtime** [yquake2/yquake2#772]
Not a showstopper, but the opengl 1.4 and 3.2 multi-texture sampler is sampling out of bounds at 16x on the console characters.

![q2_0000](https://user-images.githubusercontent.com/42292382/144529491-872f1c5d-e359-43d3-896d-9dd4ce3f6b37.png)

**Comment by apartfromtime** [comment]
This is on Windows. Is there someone that could verify this on another platform?

**Comment by Yamagi** [comment]
Do you mean these very tiny 1 pixel lines under some characters and the cursor?

**Comment by apartfromtime** [comment]
Yes.

**Comment by Yamagi** [comment]
This is indeed caused by the driver. For example I can reproduce it with Nvidia under Windows but not with a slightly older driver version under Linux. there's nothing we can do on our side, since MSAA is just a flag on the OpenGL context and all the magic happens inside the driver.
