### ISSUE TITLE
Link to Flatpak on the website' download page

### ISSUE THREAD

**Issue by Calinou** [yquake2/yquake2#776]
There is now a Flatpak provided for easy installation of Yamagi Quake 2 on Linux: https://flathub.org/apps/details/org.yamagi.YamagiQ2

Could it be linked on the [website](https://yamagi.org/quake2/), please? Thanks in advance :slightly_smiling_face:

**Comment by Yamagi** [comment]
Done. And keep up the good work! :)

**Comment by Calinou** [comment]
> Done. And keep up the good work! :)

Thanks! There is a typo though, it should be "Flat**pak**" and not "Flatpack".

**Comment by Yamagi** [comment]
\*hmpf\* These stylish spellings are a pain for us dyslexic kids. Fixed!

**Comment by RawSteelUT** [comment]
Sorry to bother and necro, but the Flatpak is out of date and unverified.  THink it'd be possible to get that fixed?
