### ISSUE TITLE
DDay normandy mod

### ISSUE THREAD

**Issue by Hernou** [yquake2/yquake2#78]
Hi :-)
[here](http://www.ddaydev.com/site/index.php) is a mod for quake2

I can compile [the source](http://www.ddaydev.com/site/index.php) 
but when I play, I have the menu of the mods, the maps, I can move in, but not see some models, I can do all moves of the mod...

So I send here beceause the comunity of this game is to small, and I never find a good help with it...

To install it, I compil the source of yamagi, compile DDay source, copy my ddaysource/gamex86_64.so into yqake2/release/dday

[Download the game here](https://mega.co.nz/#!H5QFHTCJ!MNpKjk0VZEVNh71JdKwPfWX10s8r8fiRNUrtxEtt2tQ) install with wine, and copy the contain of /ddaynormandy/dday into yqake2/realese/dday

In fat, I try to port it onto linux, but I'm not the best for that, so I hope that you will can help me :-)

**Comment by DanielGibson** [comment]
try renaming the gamex86_64.so to game.so, otherwise the engine can't 
find it and will try to use the baseq2 game.so

**Comment by Hernou** [comment]
Ho yes !
It work !
But I can't set my configs files (.cfg)... At every start, they are reconfigured by default... the game work realy good, but is not realy playble... :-/
