### ISSUE TITLE
Quake 2 software renderer with colored lighting

### ISSUE THREAD

**Issue by jan-kleks** [yquake2/yquake2#781]
Could these colored lighting enhancements for Q2's software renderer possibly work with Yamagi Quake? -- https://qbism.com/viewtopic.php?f=5&t=6 It would be nice for those who like the "classic look", but with some small improvements. I really like how the pixels and lighting look (it feels a bit brighter).

Here's a video so that you can see it in action: https://www.youtube.com/watch?v=MrnPu1cgR0Q

Regards

**Comment by maraakate** [comment]
The qbism renderer is horribly slow, just warning you in advance.

**Comment by Yamagi** [comment]
YQ2 has support for external render libraries. Porting existing libraries isn't too hart, as long as they don't make assumptions about the clients behavior. If someone wants to give it a try go ahead. However, running the GL3 renderer with texture filtering switched off and square particles is likely a better option for most players. It's way faster than any software renderer, especially at high resolutions.

**Comment by jan-kleks** [comment]
> If someone wants to give it a try go ahead. However, running the GL3 renderer with texture filtering switched off and square particles is likely a better option for most players. It's way faster than any software renderer, especially at high resolutions.

Yeah, it might be a good alternative. But is it just me, or the software renderer (even with colored lighting) still feels generally "brighter"? For example, after you launch the game, the first room feels more yellowish/orange than the software one. If there was an option to change that, I think that I would be completely satisfied (especially when https://github.com/yquake2/yquake2/issues/588 gets implemented as well).

**Comment by DanielGibson** [comment]
https://github.com/yquake2/yquake2/blob/master/doc/040_cvarlist.md describes CVars we added,
relevant for how "bright" it looks are `gl3_intensity`, `gl3_overbrightbits` and `vid_gamma`.
In the GL3 renderer, those three cvars are applied in realtime, so you can just open the console, change the value and see the result immediately (without `vid_restart`).

**Comment by 0lvin** [comment]
[![Current lightmaps in softrender](http://img.youtube.com/vi/jZMSzyZumAA/0.jpg)](http://www.youtube.com/watch?v=jZMSzyZumAA).

I have little bit patched code to replace all it_wall and it_skin to white textures. Just for show what we have inside. It looks like color light will be slower that original code from 30% up to 60%, in same time as you see we have limitation in palette. Changes in it_wall can be cheap (as we have caching of lightmaps), models can be more expensive. I don't have results for now.
