### ISSUE TITLE
Audio improvements

### ISSUE THREAD

**Issue by jan-kleks** [yquake2/yquake2#782]
I have recently found this video on a channel which specializes in demonstrating 3D audio in games -- "Yamagi Quake II: Broken OpenAL Soft doppler effect": https://www.youtube.com/watch?v=59t38Ju0qYk

Just in case, is this something that you are aware of (and it has been completely fixed)?

**Comment by Yamagi** [comment]
We've disabled the doppler effect some time ago. I can still be enabled with `s_doppler` or something like that. It's not worth fixing it, because it wasn't in Vanilla Quake II and the sound system is very limited anyways. Sound in Quake II is always two dimensional, the samples are 22 kHz, etc.

**Comment by jan-kleks** [comment]
@Yamagi I see, but according to this video the effect seems to be working fine in Q2Pro, wouldn't its source code be helpful here?

**Comment by maraakate** [comment]
Q2Pro is entirely different from regular Q2 engines, so the answer is "maybe".

**Comment by Yamagi** [comment]
YQ2s OpenAL backend is based on q2pro, so that should be possible. But... I just had an albeit short look at q2pro and there's no mention of a doppler effect inside their *al.c* and I wasn't able to find something which looks like doppler effect calculations in the frontend. Are we sure that q2pro has a nativ doppler effect?

**Comment by Enokilis** [comment]
Broken? I thought it was by design.

https://github.com/yquake2/yquake2/blob/8358e386fcdc76d70508239afc7b771795ee1017/src/client/sound/openal.c#L888

**Comment by DanielGibson** [comment]
Maybe we could feed the value of `s->doppler` directly into `qalDopplerFactor()` to make it configurable (with special case `0.0` to disable it)?

**Comment by jan-kleks** [comment]
> And yes, q2pro doesn't seem to have a doppler effect, it never calls (q)alDopplerFactor() or (q)alDopplerVelocity(), and it doesn't set listener's `AL_VELOCITY` either.

Hmm... I wonder what the creator of the video comparison I linked to in the first post had had in mind then when trying to compare the "doppler effect" in Yamagi vs Q2Pro.

Anyway, I have just found out there is a custom version of Q2RTX by SkacikPL with "Open AL effects extensions ported from Yamagi Quake 2" as well as **additional audio enhancements**:

- reverb
- occlusion effects
- footsteps sounds for all ground enemies (which were added to make an even better use of additional effects)
- they were also experimenting with [mitigating audible clicking issues](https://github.com/SkacikPL/Q2RTX/commit/49fe841841fec690dce09b97847c0fc69ab90bdf), [adding silence lead in](https://github.com/SkacikPL/Q2RTX/commit/f366f7c98f6731e47385983bb5fdf6dc63aeb5b2), and probably some other stuff...

Maybe these audio enhancements would of interest to Yamagi players too?

- [Q2RTX by SkacikPL Steam thread](https://steamcommunity.com/app/1089130/discussions/0/1636410430568305533/)
- [Q2RTX by SkacikPL on GitHub](https://github.com/SkacikPL/Q2RTX)

**Comment by Yamagi** [comment]
This was implemented by merging #869.
