### ISSUE TITLE
Mouse issue

### ISSUE THREAD

**Issue by raduprv** [yquake2/yquake2#784]
I built the client today (from github) on Linux Mint under Vmware player. Keyboard navigation works fine, but the mouse doesn't. If I move the mouse, the camera angles change chaotically. I tried changing the mouse sensitivity under options, and it doesn't fix it. Any idea what I can try?

**Comment by Yamagi** [comment]
This is caused by most virtualization and remote desktop software not supporting relative mouse input which is required by SDL. Nothing we can do on YQ2 side. But why not the nativ Linux version? Do you need some mod which is Windows only?

**Comment by raduprv** [comment]
I thought it might be that, but our game, Eternal Lands, also uses SDL2 and it works fine.
By the way, the Host OS is Windows 10, and Guest is Mint. I set up a Linux VM for development, since it's easier to compile some stuff on Linux.

**Comment by raduprv** [comment]
Never mind, some other engine was doing similar thing sin Vmware player. After looking on the net, it seems that this is a pretty well known issue, dating since at least 2008, and they still won't fix it :/
