### ISSUE TITLE
config file location

### ISSUE THREAD

**Issue by nr1995** [yquake2/yquake2#787]
Hi,
Does **_Yamagi Quake II_** just use the same config file as vanilla **_Quake II_**?  
i.e.  _...\baseq2\config.cfg_   ?

Cause I've just got **_Yamagi Quake II_** configured exactly the way I like it,
and I was hoping for a small file I could just e-mail to myself for later.
Thanks!

**Comment by Yamagi** [comment]
Under Windows he configuration files are under `%DOCUMENTS%\YamagiQ2` and under Linux they're under `$HOME/.yq2`. The actual directory (just the directory, not the whole path) can be given by `-cfgdir $dirname`. If the game is started with `-portable` the files are saved into the same dir as the executables. That's the Vanilla Quake II behavior.
