### ISSUE TITLE
Mouse mollet

### ISSUE THREAD

**Issue by Hernou** [yquake2/yquake2#79]
Is it possible to use the mousse roll to change weapons ?

Theyr is a documentation with all commands of yamagi ?

**Comment by Jarvik7** [comment]
You can do it with normal quake2 console commands. Nothing special about yamagi here...

BIND MWHEELUP WEAPNEXT
BIND MWHEELDOWN WEAPPREV

Put it in an autoexec.cfg to have it setup every time

http://www.eecis.udel.edu/~portnoi/quake/quakeiicom.html

**Comment by Yamagi** [comment]
You can bind them in the menu, too.

**Comment by Hernou** [comment]
hmm thanks you :-)
