### ISSUE TITLE
[question] Is there command to toggle HTTP download?

### ISSUE THREAD

**Issue by tojestzart** [yquake2/yquake2#793]
as in q2pro is '''cl_http_downloads

    Enables HTTP downloads, if server advertises download URL. Default value is 1 (enabled).
'''

Also not many commands yamagi has documented

**Comment by Yamagi** [comment]
You're right, for some reason I never added the HTTP download cvars to the documentation. Done that now. The cvar is the same as in r1q2 and q2pro: `cl_http_downloads 0` to disable.
