### ISSUE TITLE
enhancement for cmake configuration -- systemdir variable

### ISSUE THREAD

**Issue by Corin-EU** [yquake2/yquake2#798]
Now that there is a move to cmake, would you consider adding a CMAKE variable for SYSTEMDIR so that it is possible to do 

                         CMAKE_OPTIONS="\ 
                        -DSYSTEMWIDE_SUPPORT=ON                      \
                        -DSYSTEMDIR=/usr/local/share/games/quake2 \
                         "

                        cmake ${CMAKE_OPTIONS}  path_to_sourc_directory

rather than having to specify the system share directory separately in the CFLAGS variable?

**Comment by Yamagi** [comment]
I've merged the pull request.

**Comment by Corin-EU** [comment]
Thank you!
