### ISSUE TITLE
Disable 2D Texture Filtering (HUD, Menu GFX, etc.)

### ISSUE THREAD

**Issue by OpenRift412** [yquake2/yquake2#800]
Could we get an option to turn off the texture filtering that's specifically applied to HUD and menu elements? I think these were designed without the filtering in mind, since in the vanilla exe, they aren't filtered at all. The only part that _is_ filtered is the console background it seems.

I know that there's a cvar to disable certain graphics from using texture filtering, but that requires you to disable them all in a list, typing them out individually.

**Comment by DanielGibson** [comment]
I think you're describing the `r_2d_undfiltered` CVar ;)

Yes, looks like it's not documented on https://github.com/yquake2/yquake2/blob/master/doc/040_cvarlist.md

**Comment by OpenRift412** [comment]
> I think you're describing the `r_2d_undfiltered` CVar ;)
> 
> Yes, looks like it's not documented on https://github.com/yquake2/yquake2/blob/master/doc/040_cvarlist.md

interesting. Is there a way to have that on but make an exception for the console background?

**Comment by DanielGibson** [comment]
I don't think so. Might require a `r_lerp_list` in addition to the `r_nolerp_list`..

**Comment by OpenRift412** [comment]
> I don't think so. Might require a `r_lerp_list` in addition to the `r_nolerp_list`..

honestly, that would probably be a good idea. Having HUD texture filtering be off by default is a cleaner experience out of the box anyway.

**Comment by DanielGibson** [comment]
I implemented this (and added documentation), see #803 - could use some testing.

**Comment by OpenRift412** [comment]
> I implemented this (and added documentation), see #803 - could use some testing.

Awesome. Could you send me a build to test?

**Comment by DanielGibson** [comment]
In case you haven't tested yet, here's a current build: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20220510-1833f16.zip
