### ISSUE TITLE
[Feature] Separate Menu for Controller Binds

### ISSUE THREAD

**Issue by OpenRift412** [yquake2/yquake2#802]
It can get a bit clausterphobic in the keybinds menu trying to configure controller binds without overriding both of your keybinds. I think to make it a bit more intuitive and less cluttered, controllers should have their own binds menu.

**Comment by protocultor** [comment]
I think it's time to close this ;)

**Comment by protocultor** [comment]
Since https://github.com/yquake2/yquake2/pull/827 fixes this and has been merged a while ago, and YQ2 8.10 includes it, shouldn't this be closed by now?

**Comment by protocultor** [comment]
> It can get a bit clausterphobic in the keybinds menu trying to configure controller binds without overriding both of your keybinds. I think to make it a bit more intuitive and less cluttered, controllers should have their own binds menu.

This was solved by https://github.com/yquake2/yquake2/pull/827, and is included in YQ2 8.10.
I believe that, unless there's some feature missing, this is worth closing.
