### ISSUE TITLE
Compiled, but won't work. 

### ISSUE THREAD

**Issue by vorob1** [yquake2/yquake2#813]
Cloned latest git source, compiled it, copied PAK0.PAK to /home/fujitsu/Downloads/q2/release/baseq2
then tried /home/fujitsu/Downloads/q2/release/quake2 and no luck. Here is my log

[issue.txt](https://github.com/yquake2/yquake2/files/8490984/issue.txt)

**Comment by vorob1** [comment]
Strange that i've got same picture if won't copy PAK0.PAK  maybe it don't know where to look for this file?

**Comment by vorob1** [comment]
Case solved. It was linux naming issue. It should be pak0.pak

**Comment by DanielGibson** [comment]
Note that unless you're using the Quake2 Demo, you should also add the data from the Quake2 3.20 patch (pak1.pak, pak2.pak and players/), see https://github.com/yquake2/yquake2/blob/master/doc/020_installation.md#game-data-setup
