### ISSUE TITLE
[feature] add parallax with an (on/off) switch

### ISSUE THREAD

**Issue by Dremor8484** [yquake2/yquake2#817]
adding parallax effect on textures would improve the graphic, especially on the floors
like in these pictures:
https://media.moddb.com/cache/images/mods/1/21/20560/thumb_620x2000/q2xp0.jpg
https://media.moddb.com/cache/images/mods/1/21/20560/thumb_620x2000/s7.jpg

i am not sure if it can be easily ported from quakexp sourceport
it could be a nice improvement, and purists would be able to keep it off setting a variable to 0

**Comment by DanielGibson** [comment]
that doesn't look like quake2

**Comment by Yamagi** [comment]
Like @DanielGibson said, such things aren't in our scope.
