### ISSUE TITLE
[feature] add transparent water with an (on/off) switch

### ISSUE THREAD

**Issue by Dremor8484** [yquake2/yquake2#818]
adding transparent water, other than improve the graphic of the game, it could make easier to shoot weapons from underwater towards monster on the ground... a variable set to 0 could switch it off for who wouldn't like this.

here is an example: (taken from quake2xp)
https://media.moddb.com/cache/images/mods/1/21/20560/thumb_620x2000/s9.jpg

**Comment by DanielGibson** [comment]
the water already is transparent, see
![q2_0009](https://user-images.githubusercontent.com/1216493/164995247-c819eb8d-98c4-4a48-b252-78dbd9ccc5f9.jpg)
