### ISSUE TITLE
[bug] map hangar1.bsp, two "monster_infantry" stuck in geometry (fixed .ent file available)

### ISSUE THREAD

**Issue by Dremor8484** [yquake2/yquake2#821]
two "monster_infantry" cannot move and run on the spot, they are found as soon as the door locked by the "commander head" key is opened, after a very small hallway there is a room with 2 monsters, both stuck, one of them eventually is able to move, the other will always stay stuck. (i used latest yamagi build available on release)

here are the corrected lines

{
"spawnflags" "1"
"angle" "180"
"classname" "monster_infantry"
"origin" "992 8 1384" //stuck monster at the steps "1008 8 1384"
}
{
"classname" "monster_infantry"
"angle" "180"
"spawnflags" "1"
"origin" "992 -136 1384" //stuck monster at the steps "1008 -136 1384"
}

and here is the fixed .ent file: https://drive.google.com/drive/folders/1Dp6KWj3Nkro9KUYyqw6YSTOp9B2WCiEa?usp=sharing

**Comment by Yamagi** [comment]
Wow, this is a really nice found. I thought we finally had found and fixed all map bugs. I've committed the entity file. It will be part of the next release.
