### ISSUE TITLE
Retexturing and baseq2 slowdown

### ISSUE THREAD

**Issue by apartfromtime** [yquake2/yquake2#824]
When loading the base game maps with a "r_retexturing 1" on a "vid_restart", there is a enough of a slowdown to be noticeable, around 2x compared to "r_retexturing 0".

I'm not certain if this is the filesystem searching all the packs in numerical order, the zip file support (since the ai-upscaled textures are packed in the .pkz\.pk3\.zip format) or STB_Load().

**Comment by 0lvin** [comment]
Its expected but should be unnoticeable in most cases.

Could you please share more information? Do you have scaled images, which one? What render have you used? Do you have some timings for before and after?

**Comment by apartfromtime** [comment]
PEBKAC, I thought the images were then scaled to back down again. I have been trying these textures for models and world geometry https://github.com/Calinou/quake2-neural-upscale, Tested with opengl renderers 1.4 and 3.2, my timings were original ~3s, ai-upscaled ~7s.
