### ISSUE TITLE
Ubuntu 12.04 - OpenAL Sound Echo - Classic Sound Delay

### ISSUE THREAD

**Issue by plittlefield** [yquake2/yquake2#83]
When using OpenAL to PulseAudio, I get a sound doubling and echo.

When using the Classic Sound System, I get a 1 second delay.

All other multimedia software apps are fine. e.g. VLC, Kodi, Mplayer, etc.

Also, how do I force a particular choice of OpenAL sound driver, in order to try and debug the issue?

Yamagi: 5.00-1
Linux: Ubuntu 12.04.5 LTS Precise
Kernel: 3.2.0-86-generic #124-Ubuntu SMP
ALSA: 1.0.25
PulseAudio: 1:1.1-0ubuntu15.4
SDL: 1.2.14-6.4ubuntu3.1 and 2.0.3+z4~20140315-8621-1ppa1precise1

**Comment by DanielGibson** [comment]
Please try 5.30 or latest git code.

**Comment by plittlefield** [comment]
OK.

**Comment by plittlefield** [comment]
In fact, my laptop runs Ubuntu 14.04 with Yamagi 5.21 and the OpenAL 'soft'
driver with no problems at all.

It's my old HTPC that I'm trying to fix, so I know it's possible.

:-)

**Comment by plittlefield** [comment]
Build configuration
============================
WITH_CDA = no
WITH_OPENAL = yes
WITH_SDL2 = yes
WITH_X11GAMMA = no
WITH_ZIP = yes
WITH_SYSTEMWIDE = no
WITH_SYSTEMDIR =
============================

WARNING: CDA disabled because SDL2 doesn't support it!

===> Building quake2
make release/quake2
make[1]: Entering directory `/home/paully/Downloads/quake2-5.30'
===> CC src/backends/sdl/input.c
===> CC src/backends/sdl/refresh.c
===> CC src/backends/sdl/sound.c
===> CC src/client/cl_cin.c
===> CC src/client/cl_console.c
===> CC src/client/cl_download.c
===> CC src/client/cl_effects.c
===> CC src/client/cl_entities.c
===> CC src/client/cl_input.c
===> CC src/client/cl_inventory.c
===> CC src/client/cl_keyboard.c
===> CC src/client/cl_lights.c
===> CC src/client/cl_main.c
===> CC src/client/cl_network.c
===> CC src/client/cl_parse.c
===> CC src/client/cl_particles.c
===> CC src/client/cl_prediction.c
===> CC src/client/cl_screen.c
===> CC src/client/cl_tempentities.c
===> CC src/client/cl_view.c
===> CC src/client/refresh/r_draw.c
===> CC src/client/refresh/r_image.c
===> CC src/client/refresh/r_light.c
===> CC src/client/refresh/r_lightmap.c
===> CC src/client/refresh/r_main.c
===> CC src/client/refresh/r_mesh.c
===> CC src/client/refresh/r_misc.c
===> CC src/client/refresh/r_model.c
===> CC src/client/refresh/r_scrap.c
===> CC src/client/refresh/r_surf.c
===> CC src/client/refresh/r_warp.c
===> CC src/client/refresh/files/md2.c
===> CC src/client/refresh/files/pcx.c
===> CC src/client/refresh/files/sp2.c
===> CC src/client/refresh/files/stb.c
src/client/refresh/files/stb_image.h:1083:14: warning: ‘stbi__l2h_gamma’
defined but not used [-Wunused-variable]
src/client/refresh/files/stb_image.h:1083:36: warning: ‘stbi__l2h_scale’
defined but not used [-Wunused-variable]
===> CC src/client/refresh/files/wal.c
===> CC src/client/menu/menu.c
src/client/menu/menu.c: In function ‘StartServer_MenuInit’:
src/client/menu/menu.c:2887:18: warning: ignoring return value of ‘fread’,
declared with attribute warn_unused_result [-Wunused-result]
===> CC src/client/menu/qmenu.c
===> CC src/client/menu/videomenu.c
===> CC src/client/sound/ogg.c
===> CC src/client/sound/openal.c
src/client/sound/openal.c: In function ‘oal_update_underwater’:
src/client/sound/openal.c:554:19: error: ‘AL_LOWPASS_MIN_GAINHF’ undeclared
(first use in this function)
src/client/sound/openal.c:554:19: note: each undeclared identifier is
reported only once for each function it appears in
src/client/sound/openal.c:557:19: error: ‘AL_LOWPASS_MAX_GAINHF’ undeclared
(first use in this function)
src/client/sound/openal.c: In function ‘AL_InitUnderwaterFilter’:
src/client/sound/openal.c:745:51: error: ‘AL_LOWPASS_DEFAULT_GAIN’
undeclared (first use in this function)
make[1]: *** [build/client/src/client/sound/openal.o] Error 1
make[1]: Leaving directory `/home/paully/Downloads/quake2-5.30'
make: *** [client] Error 2

**Comment by Yamagi** [comment]
Looks like an incompatible OpenAL implementation.

**Comment by mckaygerhard** [comment]
i want added a note about that: now since 5.20 yamagi quake2 need openal >= 1.14 this error compilation its due are compiling agains libopenal << 1.14, and openal 1.13 has some bugs and are not taking in consideration by this note posted by me. For those using squeeze venenux has backported openal for compiling yquake2 for older machines or older linux
