### ISSUE TITLE
Music stops after I push some buttons.

### ISSUE THREAD

**Issue by TheShich** [yquake2/yquake2#831]
Music stops after I push some buttons. 
If I save and reload music is still off.
But if I restart the game and load same position the music is now on.
Are you sure it's correct behavior? IIRC, one track should loop entire level.

**Comment by DanielGibson** [comment]
This is most probably correct, buttons can trigger different music tracks (including switching music off)

**Comment by Yamagi** [comment]
Set `ogg_ignoretrack0 1` to ignore switching to track 0.
