### ISSUE TITLE
Machinery in meat factory don't work as intended in yquake2

### ISSUE THREAD

**Issue by TheShich** [yquake2/yquake2#832]
Hello again
Some machinery in fact2 level is definitely broken
1) Gears don't rotate here, people stack:
![q2_fact2_1](https://user-images.githubusercontent.com/24495655/167487584-64ca291e-324d-476e-a1c6-ebfee3474b80.png)
2) Belt doesn't run, people stack in the right part of tube
![q2_fact2_2](https://user-images.githubusercontent.com/24495655/167487610-4ada40ce-3ad3-4e55-ac2c-b98a794be74f.png)

**Comment by DanielGibson** [comment]
already fixed, see #786

**Comment by DanielGibson** [comment]
You can get all the bugfixes since last release by using the latest test build: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20220507-e294fc9.zip

**Comment by DanielGibson** [comment]
There is an even newer testbuild available at: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20220510-1833f16.zip

**Comment by TheShich** [comment]
I took the latest build
> There is an even newer testbuild available at: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20220510-1833f16.zip
first bug is fixed, but the second didn't.
I'm sure that the men in right tube should move with conveyor belt, but they stay and stack on each other.

**Comment by Yamagi** [comment]
The tube could be problem. I'll look into that.
