### ISSUE TITLE
This triangle looks wrong

### ISSUE THREAD

**Issue by TheShich** [yquake2/yquake2#833]
This triangle looks wrong on fact1 map

![q2_weird](https://user-images.githubusercontent.com/24495655/167930172-c4164f07-7813-45ec-a6b2-8f34532a9039.png)

Only with OpenGL 1.4  renderer. Same in original Q2 with OpenGL renderer.

**Comment by apartfromtime** [comment]
Looks like a duplicate brush, that GL1.4 can't resolve the depth for.

**Comment by Yamagi** [comment]
Yeah. There's `gl_zfix` to work around such problems, but it adds some new graphics glitches.
