### ISSUE TITLE
[help] compiled game.dll generates error: "error during initialization"

### ISSUE THREAD

**Issue by Dremor8484** [yquake2/yquake2#835]
hi there, i followed the guide here https://github.com/yquake2/yquake2/blob/1230e2c11cf5f3f212faaf6ffc37c2a1cdc254bd/doc/020_installation.md 

i followed these instructions:

01) download quake2-buildenv-20220109.7z and extract it in c:
02) rename buildenv into MSYS2
03) double click on c:\MSYS2\mingw64.exe and write exit, press enter key
04) download yquake2-master.zip and extract it in c:\MSYS2\home\"YourPcName"
05) double click on mingw64.exe, press 0 then enter key
06) write cd yquake2-master and press enter key
07) write make, press enter key and wait
08) write exit, press enter key and then collect the game.dll file found in c:\MSYS2\home\"YourPcName"\yquake2-master\release
09) copy game.dll into .\baseq2\
10) double click yquake2.exe

the compiled file game.dll doesn't work, while the file available in the already compiled release works without any problem

is it possible that either i did something wrong, or the buildenv.7z file has some problems ? i tried to compile both yquake2-master.zip and quake2-8.01.zip, but i always get a non working game.dll file

here is the console log: https://drive.google.com/drive/folders/1fETFlA2WSlu0FbWaRsWsbfHBdl3daxB8?usp=sharing

**Comment by DanielGibson** [comment]
The instructions say `msys32.exe`, not `mingw64.exe`.

You probably built a 64bit dll and are trying to use it with 32bit yquake2.exe

**Comment by Dremor8484** [comment]
ops.

there is no msys32.exe, but there is mingw32.exe
i tried to compile with mingw32.exe but i got error and interrupted compiling
then i tried to execute mingw32.exe as administrator, and i finally could compile using mingw32.exe
the yquake.exe file now has the same size as the one available in yquake2-8.01 release and it also works !

you are correct, i got a 64bit and 32bit mismatch error code 0xc000007b

using mingw32.exe as administrator fixed the problem.

**Comment by DanielGibson** [comment]
Ok, then the documentation is outdated.

Weird that you need to run it as admin, that *shouldn't* be necessary, I think (or did you extract the yq2 source as administrator or sth like that, so the yq2 dir is not writable by the normal user?)

**Comment by Dremor8484** [comment]
ok these should be the correct instructions:

01) download quake2-buildenv-20220109.7z and extract it in c:
02) rename buildenv into MSYS2
03) execute as administrator c:\MSYS2\mingw32.exe and write exit, press enter key
04) download yquake2-master.zip and extract it in c:\MSYS2\home\"YourPcName"
05) execute as administrator mingw32.exe, press 0 then enter key
06) write cd yquake2-master and press enter key
07) write make, press enter key and wait
08) write exit, press enter key and then collect the game.dll file found in c:\MSYS2\home\"YourPcName"\yquake2-master\release
09) copy game.dll into .\baseq2\
10) double click yquake2.exe

**Comment by DanielGibson** [comment]
Ok, maybe your mistake was extracting the yq2 source into c:\MSYS2\ (which might be write protected).
You can extract it anywhere, you just gotta change to that directory in the msys terminal, like
`cd /c/dev/yquake2-master` (if it's in `C:\dev\`)
