### ISSUE TITLE
Bug: Severe stuttering shortly after boot

### ISSUE THREAD

**Issue by RavenMacDaddy** [yquake2/yquake2#847]
Shortly after booting the game, for example when one of the first machine gun enemies fires at you in the demo, there will be very severe stuttering.

The duration and when it occurs is consistent, but the duration depends on the renderer that's being used.

More or less it's:

OpenGL 1: 0.5 sec
OpenGL 3: 1 sec
[Vulkan](https://github.com/yquake2/ref_vk): 2 sec

I tried making a completely clean install of the game, but this made no difference.

There are no issues presented in the Event Viewer.

This behavior is consistent with both the 8.01 and 8.10 release.

In the Zaero expansion, the stutter occurs already at the short logo that's shown at boot - the others simply play the normal demo and stutters at the point described in the beginning unless some form of action is taken by the player, in which case the duration of the stutter is the same, but it occurs usually right as the player stops pausing the game for example (demo is playing, player presses ESC, waits a while, presses ESC again, the stutter occurs).

---

OS: Windows 11 22H2 - 22621.1
GPU: Nvidia GTX 1080
CPU: AMD Ryzen 3600 @ 4.2GHz
RAM: 32GB DDR4 3000MHz

**Comment by Yamagi** [comment]
And of course - like every second timing bug - I cannot reproduce this. If I could I would have noticed. Which doesn't mean that it isn't there... Does setting `cl_maxfps 50` and restarting the game help? If not, can you try with `cl_async 0`?

**Comment by 0lvin** [comment]
If it happens near stairs - model image have not loaded on level initialization and cached only in first demo run.

**Comment by Yamagi** [comment]
Image loading sounds way more reasonable. The timting has no dynamic component, it should either work or not. Do you have an idea which commit might have broken it?

**Comment by 0lvin** [comment]
I know only one place with such issue demo2 near stairs, it have always been. I have found it when added caching images between restart levels several times. It can be more slow that in previous version if enabled images scale for 8 bit textures, in same time it just one time when image loaded from fs, after that it will be cached.

**Comment by Yamagi** [comment]
Ah, now that you're saying it, I'm seeing it also.

**Comment by RavenMacDaddy** [comment]
Weirdly the cl_maxfps command does nothing for me, so I limited the FPS to 50 through RTSS instead, no difference for the issue.

The issue is still there with cl_async 0 - but interestingly it makes the stutter occur a bit earlier.

Still the same duration though.

**Comment by maraakate** [comment]
Just to make absolutely certain, have you tried setting your power settings in windows to maximum (i.e. no power saving?) including your video card?  I've noticed that this can make older id engine games run poorly with stuttering and inconsistent frame rate if any kind of power saving mode is enabled.  Which it typically is by default on everything these days.

**Comment by maraakate** [comment]
There is a utility for your 1080 that can disable it for certain.  The control panel is somewhat fake on Nvidia I've found out.  Try this tool

https://www.techpowerup.com/download/nvidia-inspector/

For my 960 I run this in a batch file in my startup folder:

start nvidiaInspector.exe -setGPUClock:0,1,1305 -setGPUClock:0,2,1305 -setMemoryClock:0,1,3505 -setMemoryClock:0,2,3505 -setFanSpeed:0,100
start nvidiaInspector.exe -setGPUClock:0,1,1305 -setGPUClock:0,2,1305 -setMemoryClock:0,1,3505 -setMemoryClock:0,2,3505 -setFanSpeed:0,100
start nvidiaInspector.exe -setGPUClock:0,1,1305 -setGPUClock:0,2,1305 -setMemoryClock:0,1,3505 -setMemoryClock:0,2,3505 -setFanSpeed:0,100

I run it 3 times because sometimes the first time doesn't "take" I guess the driver is delayed fully enabling that until after the fact in some sitatuons.  But this should give you an idea of how to set that up and eliminate that as a possibility.  But, basically, find out what the max values are for your core and memory, then this sets each power profile to those values.  This will stop it from trying to be clever.

**Comment by Yamagi** [comment]
I booted up my Windows 10 - I don't have a Windows 11 installation - and still can't reproduce it. The game runs fine, the demos are smooth, etc. That `cl_maxfps 50` doesn't change anything and rules out the timing code. At least more or less. Several more ideas:

* Some fishy antivirus software. Wouldn't be the first time that they interfere with Quake II. Windows Defender should be okay, though.
* Power management. Quake II doesn't produce a lot of CPU and GPU load. That can have side effects, the CPU or GPU getting stuck in some low power state. The timing changes between 8.01 and 8.10 can have impact on load distribution.
* Do you have a high resolution texturing pack? It shouldn't lead to stuttering but can cause problems.

**Comment by RavenMacDaddy** [comment]
> I booted up my Windows 10 - I don't have a Windows 11 installation - and still can't reproduce it. The game runs fine, the demos are smooth, etc. That `cl_maxfps 50` doesn't change anything and rules out the timing code. At least more or less. Several more ideas:
> 
> * Some fishy antivirus software. Wouldn't be the first time that they interfere with Quake II. Windows Defender should be okay, though.
> * Power management. Quake II doesn't produce a lot of CPU and GPU load. That can have side effects, the CPU or GPU getting stuck in some low power state. The timing changes between 8.01 and 8.10 can have impact on load distribution.
> * Do you have a high resolution texturing pack? It shouldn't lead to stuttering but can cause problems.

- Paused Kaspersky Security Cloud Free, no difference
- Changed power management to Prefer Maximum Performance, however nothing related to GPU changes, simply because it doesn't have to; VRAM and clocks stay the same, since the game uses maximum around 20% on 1440p172
- Nope, clean install, only music is added, which playback is constant - the SFX lags because of the game stuttering

**Comment by Yamagi** [comment]
We did another test on @DanielGibson Windows system to have another data point. That's an old Haswell with a Radeon 580, running Windows 10 from an rather slow SSD. No problem there. I can't test Win 11 and can't rule out that it makes something different in regards to power management or something like that. Nevertheless, I'm 99% sure that the stuttering isn't a Quake II problem. It smells a little bit like a power management problem. Quake II isn't demanding enough load -> system clocks down -> stuttering -> system clocks up -> running smoothly.

**Comment by RavenMacDaddy** [comment]
I started writing about other old games where I got no issues, but now I'm testing again and I can't reproduce it.

What I did change was settings like pre-rendered frames to 1, and lots of other stuff to optimize rendering by reading the documentation for Nvidia Profile Inspector.

For good measure I turned off Threaded optimization like for other old titles - but leaving it on, the stutter is not occurring now.

Well, that confirms it was on my system - thanks for your time.

**Comment by RavenMacDaddy** [comment]
For anyone with the same issue, it seems to be caused by a faulty driver.

I'd stuttering issues with other GPU accelerated stuff (e.g. browsers like Firefox) and at the start of/switching to apps, and even switching window mode - specifically with a newer driver like 516.59 for NVIDIA GPUs.

Reverting to what's offered through Windows Update, at the time of writing 457.51, seems to have solved it all for me.
