### ISSUE TITLE
The Reckoning, Warehouse level - moving blocks are stuck

### ISSUE THREAD

**Issue by Franticware** [yquake2/yquake2#852]
Two blocks in this [screenshot](https://raw.githubusercontent.com/Franticware/miscellaneous/main/bugs/yq2bug.png) that should be moving are staying still. The sound effect of movement is there though.

**Comment by Franticware** [comment]
I am not sure, I installed it in Manjaro through package manager. Current version of yamagi-quake2 package in AUR is 8.01-1.
There are more packages with similar names that also contain names of the mission packs, which is confusing. I might check those eventually.

**Comment by Yamagi** [comment]
Can you send me a savegame? That would help me debugging this. The savegames are stored as subfolders in ~/.yq2/xatrix/save/.

**Comment by Franticware** [comment]
Here: https://github.com/Franticware/miscellaneous/blob/main/bugs/current.7z

**Comment by Yamagi** [comment]
Merging #909 **might** have solved this. I'm not sure.

**Comment by gwarser** [comment]
Still stuck. Rocketjumping over the second one and pushing the button moves the first one to the wall and thats all.

**Comment by BjossiAlfreds** [comment]
You can close this issue @Yamagi. I tested in-game with a new build of xatrix dll and the boxes work correctly.

**Comment by igorpupkinable** [comment]
`map xware`
I've just tested this on yQuake2 v8.30 and Xatrix 2.12. Boxes are moving horizontally before button push and vertically after pushing the button, so everything works as expected.

**Comment by Yamagi** [comment]
I remember vaguely that I fixed a bug involving these blocks a long time ago. Maybe it was d5d771d37308ebae01cb0f18b5db179236437878. Nice to here that this is already fixed.
