### ISSUE TITLE
Yamagi Quake 2 with Creative OpenAL (SB X-Fi Titanium)

### ISSUE THREAD

**Issue by Kappa971** [yquake2/yquake2#854]
Hi, I know that Yamagi Quake 2 uses OpenAL Soft, and I have no problem using it.
I was trying to use the Sound Blaster X-Fi OpenAL driver: at first everything seems to work fine, but just look at the demos to find that something is wrong. In the first demo, the sound works without any problems, from the second onwards there is no music. I played a few levels and the same thing happens: the first level I load works well, when I get to a new level, the music disappears and it also happens that some ambient sounds of the previous level are "inherited" from the new one.

I don't expect this to be solved, also because Creative's OpenAL Driver is known to have bugs, (but with other OpenAL games I have tried, in particular EAX games I have not had any problems), I just wanted to report it.

OS: Windows 11 x64

EDIT
As I thought, this is the X-Fi Titanium OpenAL stream buffer bug. Maybe another developer is going to develop a workaround as a OpenAL32.dll wrapper (but I'm not sure). 
If there is any news about it, I will report it.

**Comment by Yamagi** [comment]
Thank you for this report. :) Creatives OpenAL implementation is famous for is bugs. Which is somewhat ironic, because they were involved in making OpenAL famous... Since neither @DanielGibson nor me has a Creative sound card we cannot debug this. Maybe someone else will stop up.
