### ISSUE TITLE
Haptic/Force feedback doesn't work for xbox wireless elite controller 2 on Windows

### ISSUE THREAD

**Issue by Astronpower** [yquake2/yquake2#858]
Hey! First, thanks for the awesome project. 
I've tried Windows builds 8.01 and 8.10 on Windows 11 and found out that Haptic/Force feedback doesn't work for xbox wireless elite controller 2 though controller itself works good, all buttons are mapped correctly too.
It would be great if you could look into it this issue. I could help with testing, if needed.
Many thanks!

**Comment by protocultor** [comment]
Seems like the classic SDL2 haptic functionality stopped working around 2.0.14:
https://github.com/libsdl-org/SDL/issues/4435#issuecomment-896432954
I can do the update to the currently supported methods, but it will take some time.

**Comment by protocultor** [comment]
> I could help with testing, if needed.

@Astronpower , are you still interested in this? I've made a PR with what you wanted, and I'm curious to know how it feels in an Xbox controller. Here's a "testbuild" if you don't want to compile it yourself:
https://drive.google.com/file/d/1JmsrXcXnnCOGC3W1EXFV6Ppbtk6AlHxT/view?usp=sharing
Thank you in advance.

**Comment by Astronpower** [comment]
@protocultor, yes, I am! Thanks for the update. I've tested haptic on XBOX 360 Elite 2 controller and it feels great. Preferred 2.0 ramble intensity value by default. Also some time ago I've tested PS5 controller and haptic was working on it without noticeable issues.

**Comment by protocultor** [comment]
That's interesting, the PS5 controller was working with the "classic haptic". Can you test the PS5 controller with the "new haptic", and see if it works? Also, I'm interested to know if you notice any differences between the two, which one you like more, and why.
Sorry for having so many questions, but you offered your help, and currently, I'm needing it :)

**Comment by Astronpower** [comment]
Unfortunately my PS5 controller is out of reach now but I've asked my friend who has both controllers to try it out and give some feedback.

**Comment by Astronpower** [comment]
Apologies for the late replay. I have received feedback from my friend regarding PS5 controller behavior's. 

Seems PS5 haptic is somewhat broken. When firing, PS5 controller makes a enormously long haptic buzz and when fire trigger is pressed multiple times buzz becomes almost endless.

Comparing XBOX ELITE 1 and 2 shows that haptic behavior seems to be very close/identical. PS5 haptic feels a bit stronger at the same haptic value.

If you could look at the PS5 haptic issue that would be awesome. Anyway, many thanks for introducing the haptic patch!

**Comment by Astronpower** [comment]
> Unfortunately my PS5 controller is out of reach now but I've asked my friend who has both controllers to try it out and give some feedback.

Apologies for the late replay. I have received feedback from my friend regarding PS5 controller behavior's.

Seems PS5 haptic is somewhat broken. When firing, PS5 controller makes a enormously long haptic buzz and when fire trigger is pressed multiple times buzz becomes almost endless.

Comparing XBOX ELITE 1 and 2 shows that haptic behavior seems to be very close/identical. PS5 haptic feels a bit stronger at the same haptic value.

If you could look at the PS5 haptic issue that would be awesome. Anyway, many thanks for introducing the haptic patch!

**Comment by protocultor** [comment]
> Seems PS5 haptic is somewhat broken. When firing, PS5 controller makes a enormously long haptic buzz and when fire trigger is pressed multiple times buzz becomes almost endless.

Everything you're describing me, is with the testbuild ("new haptic", rumble) or with YQ2 8.10 (using "old haptic")?

> Comparing XBOX ELITE 1 and 2 shows that haptic behavior seems to be very close/identical. PS5 haptic feels a bit stronger at the same haptic value.

The difference in intensity was expected; I have to use 1.4 with a Switch Pro Controller to feel the same as a PS4 controller with 0.8, maybe less. That's why having an option is useful.

**Comment by Astronpower** [comment]
With the testbuild ("new haptic", rumble).

**Comment by protocultor** [comment]
There's not much I can do until I get a DualSense, but seems to me it's a SDL bug, because rumble effects should interrupt each other, and definitely not last forever.
Another question: your friend, is he using OpenAL? Or the SDL sound system? Tell him to write `snd_restart` in the console of the game, and paste the "`sound initialization`" result here. You can get the console output in `My Documents\YamagiQ2\baseq2\qconsole.log`.
An initial theory of mine is that having the DualSense as a valid "sound playing device" could make conflict with the sound duration, and by association, with the rumble duration.

**Comment by Astronpower** [comment]
> output in `My Documents\YamagiQ2\baseq2\qconsole.log`
Please take a look at the log file: https://drive.google.com/file/d/1SlLTKjNFKjC7tK3UO54T4utJ-o1U1QDb/
Yes, he is using OpenAl.

**Comment by protocultor** [comment]
> Yes, he is using OpenAL.

He is also using YQ2 8.10, and not my testbuild.
This is fine though; many thanks for all the help.

**Comment by Astronpower** [comment]
https://drive.google.com/file/d/16b63GzOqO6whwUJFB6sHwieCE01HYlQ6/ - logs from the testbuild.

**Comment by protocultor** [comment]
`Available OpenAL devices:`
`- OpenAL Soft on Speakers (Wireless Controller)`

Yeah, that's the one I don't have faith in. If you, and your friend, are in the mood, I'd like him to try a couple of things:

1. Reduce "rumble intensity" to `0.5`, or even lower. Maybe you both got confused with the background explosions in the first stage, the ones you can only hear very softly. Also, get (willingly) hurt by enemy fire; that should have a very different feeling to your own firing.

2. Apart from the last one, reduce your display Hz to 60, and try again.

If you want, I can send you another testbuild, one built with SDL 2.26.0; that might have additional bug fixes for the PS5 controller.

**Comment by Astronpower** [comment]
Yes, please send the new testbuild.

**Comment by protocultor** [comment]
Here it is: https://drive.google.com/file/d/193zGVdH7_rYo8jHNjcDvUJPzoEYR_UAo/view?usp=sharing

**Comment by Astronpower** [comment]
Overall rumble experience with the latest build on PS5 controller has been improved greatly. Single shots work good enough. If a trigger is continuously pressed shots are not well distinguished from one another. May be something could be done about it?

>Reduce "rumble intensity"
There is no noticeable difference between 2 and 0.5 with PS5 controller. On XBOX controller the difference between 2 and 0.5 is substantial.

>reduce your display Hz to 60
No noticeable changes were spotted on 60Hz.

>Disable "Wireless Controller" in Windows audio settings
No noticeable changes were spotted after "Wireless Controller" been disabled in windows audio settings.

**Comment by protocultor** [comment]
> Overall rumble experience with the latest build on PS5 controller has been improved greatly. Single shots work good enough. If a trigger is continuously pressed shots are not well distinguished from one another. May be something could be done about it?

I'm not sure, and I wouldn't even try without breaking support for controllers that have shown to work, like the PS4, Switch, and the Xbox ones. The most radical difference of this testbuild vs the previous one is the updated SDL version, which is definitely the responsible for any improvements this version presents. Let's hope PS5 controller support continues to advance in the future of SDL.

If you are interested to try one last thing, that I don't believe will solve the problem, is to switch to the SDL sound system. You can do this by entering in the console `s_openal 0` and then, `snd_restart`. If things don't get better, get back to OpenAL by entering `s_openal 1`.

Many thanks for taking the time to check this out.

**Comment by Astronpower** [comment]
Tested on https://drive.google.com/file/d/193zGVdH7_rYo8jHNjcDvUJPzoEYR_UAo/view?usp=sharing (latest) build:

`s_openal 0` on PS5 controller makes shots more distinguished from one another and far explosions feel more natural (less rumble feedback). Subjectively PS5 controller's rumble engines give more fun experience comparing to Xbox controller.

`s_openal 0` on Xbox controller doesn't make much of a difference.

Probably you could add OpenAL on/off option to the settings.

And many thanks for your too. It is very nice to have modern controllers support.
