### ISSUE TITLE
Help Installing on Linux

### ISSUE THREAD

**Issue by whipowill** [yquake2/yquake2#859]
I can't seem to find the answer to this.  I'm on Zorin, which is an Ubuntu based distro.  I installed via command line:

```
$ sudo apt install yamagi-quake2
```

I put the necessary game files in ``~/Games/Linux/Quake II``.  Then I try to run the game using this:

```
$ cd ~/Games/Linux/Quake\ II && quake2
```

And I get a Quake2 popup saying something about installing the game files to ~/Downloads.  

![image](https://user-images.githubusercontent.com/44954184/178873588-d65eccc1-d0a2-4e74-9c04-562322956c90.png)

Ultimately I'm trying to a) figure out where the files need to be located, and b) how to control game load so I specify where those files are.

**Comment by DanielGibson** [comment]
No idea where that popup comes from, must be something Zorin/Ubuntu/Debian added to their package.

You can just tell the game where the data files are located, like  
`quake2 -datadir ~/Games/Linux/Quake\ II`

`quake2 -h` should display information about some commandline arguments, including `-datadir`.
