### ISSUE TITLE
Remove SDL1.X support

### ISSUE THREAD

**Issue by bradc6** [yquake2/yquake2#86]
I would like to begin a conversation about removing SDL 1.X in order to simplify the codebase.

**Comment by Jarvik7** [comment]
I agree.
Users who for some reason cannot use SDL2 can just use one of the older builds.

**Comment by Yamagi** [comment]
At this time SDL 1.2 won't be removed. While we haven't merged the last backend bugfixes (keyboard layout problems, half broken fullscreen switch) into SDL 1.2, the code is still working. Yamagi Quake II is a kind of "bugfix mode" without big additions so there's no big burden in keeping the old SDL 1.2 API alive.
