### ISSUE TITLE
Centered Messages Go Off Edge of Screen/Crosshair Scale/F1 Notification

### ISSUE THREAD

**Issue by deuxsonic** [yquake2/yquake2#87]
![quake01](https://cloud.githubusercontent.com/assets/7662909/9754838/c07c31aa-569a-11e5-99d0-669f0d8e8b4d.jpg)

1) I've tried to scale up the crosshair with crosshair_scale but it doesn't seem to affect the scaling at all. I set it to 5 thinking that this would be best since I scale everything else to 5 in order to get it to fill the screen but lower numbers don't seem to work either. This might be related to...

2) Messages that are supposed to display centered on the screen (such as the message telling you how to climb a ladder) are not centered but rather seemingly slightly too far right. I use a screen resolution of 1600x1200.

Added a screenshot showing both.

**Comment by deuxsonic** [comment]
An idea I have is for the ability to disable the F1 notifications when objectives are updated. After you've played the game a million times you basically just open and close them to satisfy the game.

**Comment by maraakate** [comment]
I have a hack for this in my q2dos port if you're comfortable with 
compiling code yourself I can link you to the code.

Frank

**Comment by DanielGibson** [comment]
Am 09.09.2015 um 05:12 schrieb deuxsonic:
> Using 5.31, I downloaded a package that has the OGG music for the game
> already ripped for Quake 2 ports that support it and encoded, as
> track##.ogg, from track02.ogg to track21.ogg (includes the mission pack
> music). Since YQuake2 wants it as simply ##.ogg I renamed the files
> 02.ogg to 21.ogg. With the base game, this works fine, however with the
> mission packs, they can find the music files fine, but they play their
> respective track number rather than what the actual file is, which is a
> different number. How should I go about having it play the right tracks
> with the mission packs?
>

the tracks should be named 02.ogg to 11.ogg (or whatever the last track 
was).
the mission pack tracks should be in xatrix/music/ and rogue/music/

**Comment by deuxsonic** [comment]
Interesting, I had that issue figured out and changed the post to mention problems with the crosshair scaling and messages that should be centered on-screen being too far to the right.

**Comment by maraakate** [comment]
https://bitbucket.org/neozeed/q2dos/src/10110bd9c70f/client/cl_scrn.c look for cl_hide_gun_icon.

**Comment by deuxsonic** [comment]
Thanks for the code to do it. Perhaps the YQuake2 developers can add it if they see it as a useful option.

The scaling for the most part works perfectly at 5x (the same result as conwidth 320 in the original Quake) except for the deathmatch flag menu, which goes off the screen at this scale, as well as the centered in-game messages going off the screen. Perhaps the crosshair_scale CVAR relies on something else?

**Comment by Yamagi** [comment]
Hi,
I had a short look at the code:

* The crosshair_scale cvar is disfunctional. In fact it's never used. But it should be easy to implement it.
* The scaling of console elements is... It's the best we could do. I'll convince Daniel that we'll habe another look but don't expect much. This mess with magic numbers, diverent alignement rules and so on is next to impossible to scale while maintaining the margin.

**Comment by deuxsonic** [comment]
I understand it's kind of a fragile thing, but because it happens to one specific type of message perhaps it could be singled out and tweaked independently. The crosshair scale bug and centering those messages/longer menus going off the screen are really the last 2 noticable bugs. It's always slid to the right, so I'm wondering if maybe while using a 16:9 resolution it would be centered and if maybe it's assuming that that ratio is used, but since I'm using 4:3 it's not picking center correctly? I mean all the other dialogs like the inventory screen and icons along the sides of the screen are all aligned perfectly. It's just that specific type of message. Perhaps for instances in longer menus like for DM flags they could be split into 2 pages the way the save game/load game menus work if it runs out of room?

Thanks for an awesome port.

**Comment by deuxsonic** [comment]
Perhaps CVARs for the user making manual adjustments to margins and things? Since 5x scaling/320x240 equivalent is as large as would ever be needed (and what I use myself), if everything is aligned at this scaling then shouldn't it be okay for those who use lower scalings since there would be more and more room as elements are drawn smaller?

**Comment by deuxsonic** [comment]
![q2_grid](https://cloud.githubusercontent.com/assets/7662909/10505000/3bf253a8-72d6-11e5-9a3a-b4e14439be22.jpg)

Looking through the r1gl renderer designed alongside r1q2, it is designed to work with vanilla 3.2x releases, and has all the UI stuff made scalable via a single CVAR, *gl_hudscale* and since yquake2 also stays true to the original, I thought perhaps by comparing r1gl's source with the original could yield clues on a clean way of doing the UI scaling.

Looking through the source code, *gl_rmain.c* under *ref_gl* seems to contain the methods used to do the UI scaling. Knowing how id's original code went, is it possible to see what was changed to allow for the scaling? Not being much programming experience, looking through it, I'm wondering if there is enough here to figure out a much cleaner way to implement scaling so "magic numbers" and "margins" don't become an issue by searching for functionality based around where the CVAR is used? I wish I could be of more help.

The source being available here: http://old.r1ch.net/stuff/r1q2/src/r1q2-b7904-src.zip

	if (FLOAT_NE_ZERO(gl_hudscale->value))
	{
		r_newrefdef.width = (int)(r_newrefdef.width * gl_hudscale->value);
		r_newrefdef.height = (int)(r_newrefdef.height * gl_hudscale->value);
		r_newrefdef.x = (int)(r_newrefdef.x * gl_hudscale->value);
		r_newrefdef.y = (int)(r_newrefdef.y * gl_hudscale->value);
	}

	if (gl_hudscale->modified)
	{
		int width, height;

		gl_hudscale->modified = false;

		if (gl_hudscale->value < 1.0f)
		{
			ri.Cvar_Set ("gl_hudscale", "1.0");
		}
		else
		{
			//r1: hudscaling
			width = (int)ceilf((float)vid.width / gl_hudscale->value);
			height = (int)ceilf((float)vid.height / gl_hudscale->value);

			//round to powers of 8/2 to avoid blackbars
			width = (width+7)&~7;
			height = (height+1)&~1;

			gl_hudscale->modified = false;

			vid_scaled_width = vid.width / gl_hudscale->value;
			vid_scaled_height = vid.height / gl_hudscale->value;

			// let the sound and input subsystems know about the new window
			ri.Vid_NewWindow (width, height);
		}
	}

**Comment by Yamagi** [comment]
As said, we'll fix this problem. yq2 scales the several HUD / GUI elements by specialiced drawing functions Draw_CharScaled() and Draw_PicScaled(). That work's fine, but the alignment calculation done by the callers need to be adjusted too. We've done that for the menu, for the HUD elements and for the console. But we've forgotten the centered strings. They're aligned in SCR_CenterPrint() in cl_creen.c:173. As you can see the logic uses some magic numbers and it needs some hard thinkig how to alter the calculations to include the scale factor. Until now I just didn't have the time and more important the calm to do it. Daniel and I will do a "Quake II Weekend" next week and try to fix this and several other bugs.

**Comment by deuxsonic** [comment]
![comparison](https://cloud.githubusercontent.com/assets/7662909/10509695/920523da-72fc-11e5-8807-61f6d0f02cef.gif)

Oh okay. I did another grid of pictures of the same screens in YQ2 as of 5.31 just for comparison. The main menu and console are both perfect, as are the paused tag and the objectives as well as the inventory screens. With the crosshair fixed, what remains are centered text and all menu screens other than the main menu. Thanks for your hard work -- I wish I knew enough to contribute code to the port.

**Comment by deuxsonic** [comment]
Nice job with centered messages. Any ideas for the menus?

**Comment by Yamagi** [comment]
Thank you. I'll try to merge all outstanding pull requests and patches this weekend.

Regarding the menus: Only a very mad person will touch the menu code again. If someone want's to refactor that inconsistent crap, go ahead. But I won't do that. Nearly all menu items are aligned by hand, some from the right, some from the left and some from the center. The menu code itself is just horrible. And so on. Scaling the menu 100% correct would require a lot of code changes or even more time. And I don't think that's worth the effort.

**Comment by mackron** [comment]
I don't mind hacking away on it for a bit. It's not too bad, just tedious - lots of trial and error. I'm not bothering with a full refactor, but I'm pretty sure I can get the main stuff working. So far the Options and Video Options menus are done and part of the Multiplayer menu.

**Comment by deuxsonic** [comment]
Keep it up! You've already fixed some long-standing bugs. I know you can do it.

**Comment by deuxsonic** [comment]
I've been merging your code into my own copy as you release it because I'm so excited about these fixes.

**Comment by deuxsonic** [comment]
I think this is the full list of all the menus in-game:

Game
Game -> Load Game
Game -> Save Game

Multiplayer
Multiplayer -> Join Server
Multiplayer -> Join Server Address Book
Multiplayer -> Start Network Server
Multiplayer -> Start Network Server -> Deathmatch Flags
Multiplayer -> Player Setup
Multiplayer -> Player Setup -> Download Options

Options
Options -> Customize Controls

Video

**Comment by deuxsonic** [comment]
The only other thing I noticed is that some menu selections have a gray bar at the bottom to be centered.

Thanks for these fixes.

**Comment by deuxsonic** [comment]
Here are the menus that have one or more selections that show a gray bar at the bottom with text:

Game -> Load Game
Game -> Save Game

Multiplayer -> Join Server
Multiplayer -> Join Server Address Book
Multiplayer -> Start Network Server
Multiplayer -> Start Network Server -> Deathmatch Flags

Options -> Customize Controls

**Comment by deuxsonic** [comment]
You are my hero.

**Comment by mackron** [comment]
OK, I think I've finished with the menu scaling. I took a look at the crosshair scaling but that already works fine for me so I'm assuming that's already been fixed. Regarding the F1 notification, I'll leave that to issue #94.

**Comment by deuxsonic** [comment]
You can do #94 if you want. It would involve an option to turn off the F1 icon that never goes away until you press it and the background "computer updated" sound that plays 3 times.

The crosshair doesn't look like a scaled bitmap but rather a scaled vector. Why is this?

**Comment by Yamagi** [comment]
maraakate already explained why disabling the F1 is problematic. If it's done, the change has to be in the game code and must be ported to both addons and the ctf module.

**Comment by DanielGibson** [comment]
I think it's that hard to just press F1 twice whenever that pops up.
I do this automatically without even thinking about it whenever I hear 
that sound..

**Comment by deuxsonic** [comment]
Got it.

**Comment by Yamagi** [comment]
I've merged the pull request.

**Comment by maraakate** [comment]
Yamagi: My hide gun icon code works okay with the single player mods.
