### ISSUE TITLE
Fullscreen resolution wrong on Wayland Ubuntu 22.04

### ISSUE THREAD

**Issue by neclepsio** [yquake2/yquake2#872]
When using Ubuntu 22.04, with Wayland, I apparently always get 640x480 fullscreen, even using r_customwidth/height. Using Xorg, it works correctly, using native resolution.

**Comment by Yamagi** [comment]
Can you show us the full terminal output?

**Comment by neclepsio** [comment]
I'm sorry, I can no longer reproduce. I cannot think of anything that fixed it. No relevant updates (besides a kernel update), no modifications made by me.
