### ISSUE TITLE
victory.pcx modding and video formats

### ISSUE THREAD

**Issue by Screamerofstars** [yquake2/yquake2#878]
is it possible to add those into the mix of replaceable assets, like videos on mp4/avi/mkv format or victory screens with the existing image support that yamagi has? or both are hardcoded?

it would be nice to add 16:9 victory screens for Q2 or even some units, or even replace the existing .cin videos as legacy support for new cutscenes, like the intro remake on youtube https://www.youtube.com/watch?v=5TqxPdLSP-w

**Comment by TedThompson** [comment]
victory.pcx is replaceable just takes pics/victory.png or .tga in the baseq2 directory.

I wish the Cinematics were upscaled somewhere and could be replaced but AFAIK they aren't.

**Comment by Yamagi** [comment]
And if they were, we still wouldn't add support for foreign video formats... Decoding video streams like all MPEG revisions or AV1 is extremely complex and would require to link some universal decoding library and container format implementation like libavcodec (part of ffmpeg) into the client. Such libraries are way bigger and more complex than Quake II itself. That's way out of scope of our little project.
