### ISSUE TITLE
Can't disable joystick/gamepad in Windows?

### ISSUE THREAD

**Issue by MBYlt** [yquake2/yquake2#879]
I can't seem to disable the joystick in YQuake.

I've created a shortcut whose target is "[quake 2 directory]\yquake2.exe" +set in_initjoy 0", which Google tells me is the way to do it in vanilla Quake 2. But still, Quake recognizes joystick inputs - no good.

Would really rather not have to physically unplug my joystick each time I want to play Quake 2, so... is there any command to completely disable joystick/gamepad input?

**Comment by apartfromtime** [comment]
A quick scan of the source looks as though the "in_initjoy" has been removed and that only gamepad controllers are supported, which most if not all now have an on\off state, unless you set SDL_GAMECONTROLLERCONFIG for your particular joystick.

If your controller is a gamepad with an on\off state simply turn it off, the game should detect if a device was added or removed.
