### ISSUE TITLE
Panning issue for self-centered sounds with newer versions of OpenAL Soft

### ISSUE THREAD

**Issue by Hiradur** [yquake2/yquake2#88]
How to reproduce:
- use any version of OpenAL Soft >= 1.16
- use headphones
- without HRTF self-centered sounds quickly pan between left and right speaker, making for an unpleasant experience
- with HRTF enabled you can clearly hear how the sounds which should stay centered all the time move within certain bounds

I reported this to OpenAL Soft first, thinking it was an issue with OAL Soft itself but apparently it isn't:
https://github.com/kcat/openal-soft/issues/19 (note: my initial depiction of the issue was wrong, it's corrected later in the comments)

explanation and hints at a solution can be found from https://github.com/kcat/openal-soft/issues/19#issuecomment-141469955 onwards.

**Comment by Yamagi** [comment]
Hi,
this may be fixed by https://github.com/yquake2/yquake2/commit/432fdc271b41551ea60c957aab67da3f4afd019b on branch "issue88". Since I'm unable to reproduce it (as always :) ), would you mind giving it a try?

Thank you,
Yamagi

**Comment by Hiradur** [comment]
I built the "issue88" branch on WIndows with the MinGW environment and it's fixed.

Thanks!

**Comment by Yamagi** [comment]
Nice. I've merged the branch into Master.

**Comment by DanielGibson** [comment]
I just had to fix OpenAL code again, can you test it again please, @Hiradur ?

**Comment by Hiradur** [comment]
@DanielGibson I compiled current master and it's still working fine.

**Comment by DanielGibson** [comment]
Great, thanks a lot!
