### ISSUE TITLE
Mods are not being detected

### ISSUE THREAD

**Issue by TedThompson** [yquake2/yquake2#880]
Only baseq2 shows in the "Mods" menu, even tho I have:

- ctf
- Rogue
- xatrix
- gen
- Gladiator

mod folders, each with at least one *.pak file. ([files.txt](https://github.com/yquake2/yquake2/files/9396592/files.txt))

I *think* yQuake is searching for subdirectories of /baseq2 and not / when hunting for pak files? This is based on the behavior of the 'DIR' command. 

![q2_0007](https://user-images.githubusercontent.com/9302806/185987618-a552f0dd-3122-4986-aeba-87dcf303830e.png)

**Comment by DanielGibson** [comment]
Do the mods work when starting the game with `+set game rogue` (for example)?

**Comment by TedThompson** [comment]
Oh yes, and if I use a bat or shortcut with `+game rogue` etc. All works as expected *except* the "Mods" menu in the UI.

**Comment by TedThompson** [comment]
In fact I just did a full clean install of YQ2, which has CTF, Xatrix and Rogue and the same result, only baseq2 appears in the "mods" menu.

**Comment by BjossiAlfreds** [comment]
Are you pressing left/right arrow keys to cycle through the list?

**Comment by TedThompson** [comment]
Uh... NO I wasn't.  Now I've tried that and they are in fact there.

This is far from obvious, so I'll open another ticket suggesting the UI convention of surrounding left-right items with [ and ] be observed.

Thanks!!
