### ISSUE TITLE
Can't disable mouse invert via menu (Yamagi v8.10)

### ISSUE THREAD

**Issue by mm41707** [yquake2/yquake2#884]
I'm using inverted mouse for xinput gamepad support, but once you enable it using options menu it can't be disabled anymore. You can set it to 'No' but it won't have any effect and it will revert back to 'Yes' once you exit the menu. The only way to disable it, if you want to play it back using just keyboard/mouse is to find a following line in config.cfg:
**set m_pitch "0.022"**
and change it to:
**set m_pitch "-0.022"**
It would be great if this could be fixed.
Yamagi v8.10

**Comment by j4reporting** [comment]
works for me  with a  360 controller  _most_ of the time.
There is indeed some issue that sometimes the change is undone when you exit the options menu. This happens maybe  in 2 out of 10 attempts. Regardless of whether you want to enable or disable  this option.

**Comment by Yamagi** [comment]
This is a long standing bug in the menu, dating back to at least 7.43. Maybe even to Vanilla Quake II: For each time the user presses left or right on a `MTYPE_SPINCONTROL` the callback function gets executed. If the box is on yes and user presses left, it's executed once. If they press left twice, the menu still switches the box to no, but executes the callback twice disabling the option and enabling it again... I wonder why this wasn't reported before.
