### ISSUE TITLE
Missing elevator on first level of Rogue expansion

### ISSUE THREAD

**Issue by lucasmr** [yquake2/yquake2#885]
Yamagi Quake II v8.10
=====================
Client build options:
 + cURL HTTP downloads
 + OpenAL audio
 - Systemwide installation
Platform: Linux
Architecture: x86_64
Byte ordering: little endian

Missing elevator, cannot complete the level.

Save file is here:
https://file.io/Nrm1IPJauum0

**Comment by Paril** [comment]
Are you using the Rogue DLL? That elevator is a func_plat2, which is only available in the Rogue game DLL.

**Comment by lucasmr** [comment]
I got gamex86.dll and pak0.pak in the rogue folder, both from the Steam release. I launched quake2 with no command-line options and chose rogue in the "mods" option in the main "Game" menu. Base game works fine.

**Comment by j4reporting** [comment]
you need to compile  Yamagi's game.dll for both expansion discs. 
https://github.com/yquake2/rogue/tags
https://github.com/yquake2/xatrix/tags

**Comment by lucasmr** [comment]
Thanks, that solved it. I was unaware I needed to compile a new game.so for the expansions.
