### ISSUE TITLE
better machinima support

### ISSUE THREAD

**Issue by mdvhimself** [yquake2/yquake2#888]
i've been trying to recapture old machinimas in yamagi and ironwail. turns out there are bigger projects, that have several demo files chained together, but yamagi doesnt seem to play them, just only one at a time. also i always get cvar errors on the screen.

[stdout.txt](https://github.com/yquake2/yquake2/files/9483386/stdout.txt)

i have this log if it helps. been trying out the warrior's life video. 

https://drive.google.com/file/d/112fBNNi9kryihRVa2JJG1SU5lts-5MDq/view?usp=sharing

**Comment by 0lvin** [comment]
I can't reproduce such issue. Could you please check value of game variable?
