### ISSUE TITLE
"Track out of range" message

### ISSUE THREAD

**Issue by ghost** [yquake2/yquake2#890]
During level transitions, the following message frequently appears on screen:

"OGG_PlayTrack: # out of range"

I assume this is because I am playing without music: the message does not show if I disable OGG music in the settings menu. However, not having it appear all if no *.ogg files are found would be the better behavior (in my view).

Because the function `OGG_PlayTrack()` returns if `ogg_maxfileindex == -1`, one can accomplish this by setting `ogg_maxfileindex = -1` at the end of the function `OGG_InitTrackList()`, which always returns prior to that point if any tracks are found.

**Comment by protocultor** [comment]
I, respectfully, do not agree with that behavior. The warning message is useful for people that have the music, but haven't "installed" it properly; to know if the game tries to play it and haven't found it for some reason (wrong path on most cases). With no message, is like the game doesn't even attempt to play the music. Makes disabling it to have a purpose, and if you don't want the music, you should just disable it.

**Comment by Yamagi** [comment]
>  Makes disabling it to have a purpose, and if you don't want the music, you should just disable it.
Which can even be done in the menu. Options -> Ogg music -> disabled. I see it like @protocultor. If you don't want the music disable it.
