### ISSUE TITLE
Steam integration

### ISSUE THREAD

**Issue by cheater** [yquake2/yquake2#895]
This is probably a long shot, but I'd like to be able to play with friends via Steam:

1. Invite friends via Steam
2. Don't need to create my own dedicated server or open ports on firewall - or, if necessary, talk to the firewall via UPnP

I realize it's a long shot, but I just want to play games with some friends and people balk when they have to do advanced stuff

**Comment by cheater** [comment]
@turol linking is not the only way to use a library. You can have a separate non-GPL binary which links to that library, and then call it via sub-process spawning or talk to it via some form of IPC.

**Comment by Yamagi** [comment]
We won't link support for (proprietary) launchers into YQ2.
