### ISSUE TITLE
Makefile not working on Windows (in my case at least)

### ISSUE THREAD

**Issue by BjossiAlfreds** [yquake2/yquake2#901]
I just tried the Makefile that comes with the project but it doesn't work on my Windows installation of Make.

```
$ make game
===> Building baseq2/game.dll
G:/Programs/Make/bin/make release/baseq2/game.dll
make[1]: Entering directory `G:/Games/iD Software/Quake 2/yq2/yquake2'
===> CC src/common/shared/flash.c
process_begin: CreateProcess(NULL, cc -c -O2 -Wall -pipe -fomit-frame-pointer -std=gnu99 -fno-strict-aliasing -fwrapv -fvisibility=hidden -MMD -DYQ2OSTYPE=\"Windows\" -DYQ2ARCH=\"x86_64\" -mfpmath=sse -I/usr/include -o build/baseq2/src/common/shared/flash.o src/common/shared/flash.c, ...) failed.
make (e=2): The system cannot find the file specified.
make[1]: *** [build/baseq2/src/common/shared/flash.o] Error 2
make[1]: Leaving directory `G:/Games/iD Software/Quake 2/yq2/yquake2'
make: *** [game] Error 2
```
Seems that the CC variable defaults to cc on my installation, which is a simple Windows build of Make, contradicting what the text in the comment says.

```
# On Windows / MinGW $(CC) is undefined by default.
ifeq ($(YQ2_OSTYPE),Windows)
CC ?= gcc
endif
```

Any ideas for a fix, like using := or a conditional check? Or maybe I should just do "make -e CC=gcc game" as the command?

**Comment by Yamagi** [comment]
Hmm... That was a work around for msys2 in it's mingw64 variant not setting `CC`. It has been fixed upstream a long time ago. No need to fiddle with it, I'll just remove it.
