### ISSUE TITLE
[Original bug] Rare power cube state corruption in co-op

### ISSUE THREAD

**Issue by BjossiAlfreds** [yquake2/yquake2#905]
This is ultra-unlikely to happen but possible none the less. Power cube state is not cleared when going to a new unit, so if players carry unused power cubes as they leave, the game will still think they are carrying them even if the inventory is empty, possibly soft locking the game and requiring cheats to continue.

You can test this yourself:
1. Set coop 1 and cheats 1 (noclip and notarget save a lot of time here)
2. Load base2 and give yourself 4 power cubes ("give power cube" command)
3. Go to the exit elevator and leave the unit
4. Travel to ware1 (Supply Station) and get to the first power cube
5. Notice that you can not pick it up, yet there are no power cubes in your inventory

I will provide a PR that fixes this issue.

**Comment by Yamagi** [comment]
Responding only once to avoid the mail flood: Thank you for your continued work on all this rather rare corner cases. It's very much appreciated!
