### ISSUE TITLE
Bug: No Interpolation on Stairs

### ISSUE THREAD

**Issue by Marandal-l** [yquake2/yquake2#923]
Version:       Yamagi 8.10
Comparison: Q2 3.21

Ran into a strange jitter today when running up stairs.
I tested Original Q2(included in gif) and noticed it's not prevalant.

Stair height is 12 units tall

![yquake](https://user-images.githubusercontent.com/35547019/196792762-d5992f9a-e105-41a0-8bf5-fb7952f3a6b9.gif)

**Comment by 0lvin** [comment]
Have you used soft render or gl1?

**Comment by DanielGibson** [comment]
Should be fixed in latest git master, can you test it?

**Comment by Yamagi** [comment]
A Windows testbuild is here: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20221022-2c81e25.zip

**Comment by Marandal-l** [comment]
> A Windows testbuild is here

ran the testbuild works great! 👍

> Have you used soft render or gl1?

3,2 with GL_NEAREST

**Comment by Yamagi** [comment]
Thank you for testing it. The fix will be included in all upcoming testbuilds and the next release sometimes in early december.
