### ISSUE TITLE
Spurious key events right after startup

### ISSUE THREAD

**Issue by Yamagi** [yquake2/yquake2#926]
While debugging another issue I stumbled over this one:

1. Start the game with the software renderer from terminal
2. There is a high chance (>75%) that the game is spammed with 'K_ENTER down' events until the user presses another key.

I have only tested the Gnome wayland session with the game running under XWayland. It happens only with the software renderer. It is reproducable at least back to 8.00, maybe even more. Clearing the event queue by calling `In_FlushQueue()` at startup doesn't help. 

Theory: For some reason SDL recognizes the Enter key press used to start the command in the terminal as down event, but never sees the up event. `sleep 1 ; ./quake2` doesn't help and how can SDL see a keypress already processed before the process is even forked anyways? And why doesn't it happen with the GL renderers? Maybe some race in Gnomes input handling code when the SDL windows spawnes too fast?

This is Arch Linux with:

* gnome-shell 1:42.5-1
* mutter 42.5-1
* sdl2 2.24.1-1

**Comment by protocultor** [comment]
Could not reproduce anything like that in the current master of YQ2 on Ubuntu 20.04.5 LTS, Wayland.
- gnome-shell 3.36.9-0ubuntu0.20.04.2
- mutter 3.36.9-0ubuntu0.20.04.2 (yup, same version)
- sdl 2.25.0 (installed & updated from source)

**Comment by Yamagi** [comment]
This went away with the Gnome 43 update. Still strange, though.
