### ISSUE TITLE
Bug: Sound

### ISSUE THREAD

**Issue by Marandal-l** [yquake2/yquake2#931]
Firstly, thanks for supporting quake all these years.

Video example: [Youtube: Sound Bug](https://youtu.be/FQJIxV76W-M)

Updated Test Map [Map.with.sound_updated.zip](https://github.com/yquake2/yquake2/files/9996735/Map.with.sound_updated.zip)

**YQuake version**: Test Build 20221022-2c81e25 https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20221022-2c81e25.zip
_Originally posted by @Yamagi in https://github.com/yquake2/yquake2/issues/923#issuecomment-1287883839_

Alrighty,
i hopped into the map and heard a sound glitch for about 1 minute.
then it clears up.

In this map there's a second target_speaker that's using the same sound,
the bug ceases to exist if i delete one of the target_speaker's.

**Comment by Yamagi** [comment]
I cannot reproduce it, likely because the pak / zip misses some sound files:

```
]/map ism1                           
==== ShutdownGame ====
-------- game initialization -------
Loading library: game.so
Game is starting up.
Game is baseq2 built on Nov  5 2022.
------------------------------------

------- server initialization ------
gib_type is not a field
func_wall START_ON without TOGGLE
target_speaker with no noise set at (-514 -480 24)
0 entities inhibited.
0 teams with 0 entities.
------------------------------------

Server restarted
Server disconnected, reconnecting
Connecting to localhost...
[0.0.0.0]:0: challenge
[0.0.0.0]:0: client_connect


-===================================-

 ism1
Downloading sound/factory/achineCooling/irvent_Loop_16.WAV.wav
Server does not have this file.
Downloading sound/factory/achineCooling/irvent_Loop_08.WAV.wav
Server does not have this file.
Downloading sound/industrial_ambient/electricmotors/drill_loop_1.wav
Server does not have this file.
Downloading sound/water/ambience/sfx_ambience_downpour_loop.wav
Server does not have this file.
```

**Comment by Marandal-l** [comment]
Apologies, here we go.
[Map.with.sound_updated.zip] (https://github.com/yquake2/yquake2/files/9996741/Map.with.sound_updated.zip)

**Comment by Yamagi** [comment]
This was a very nice find. The OpenAL backend ran in an integer overflow while calculating the file length in samples. This happened even for rather short files and I wonder why no one noticed so far. I have pushed a fix. I will do a new Windows build later or tomorrow.

**Comment by Yamagi** [comment]
The test build is here: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20221120-15adee3.zip
