### ISSUE TITLE
Feature Request: Option to Disable Flashing F1 Notification Icon and Associated Sound

### ISSUE THREAD

**Issue by deuxsonic** [yquake2/yquake2#94]
I mentioned this in a previous issue but in case it was missed, I feel a useful feature would be the ability to disable the blinking F1 icon and associated "computer updated" sound when changes are made to the F1 screen (usually upon entering a new map.) Since it will continue to blink and play the sound if you ignore it, I think that those who have played the game many times as I have no longer feel the need to have this as inevitably you end up having to press F1 just to get the icon and sound to stop.

**Comment by maraakate** [comment]
I previously posted a link to my port that added this ability that you could add yourself very trivially: https://bitbucket.org/neozeed/q2dos/diff/client/cl_scrn.c?diff2=10110bd9c70f&at=asm_testing

**Comment by deuxsonic** [comment]
I was going to add your mention from the other thread but I wasn't sure if it also stops the sound that plays along with it.

**Comment by maraakate** [comment]
Now, I didn't remove the sound on purpose (it still serves as a reminder that something happened) since it only plays once anyways.  But, you could find the filename (forget what it is) and delete that yourself.

**Comment by deuxsonic** [comment]
It actually does play more than once. I'm also not sure that this is the only place where that sound is used. Thanks for your help.

**Comment by maraakate** [comment]
Does it?  I don't even remember.  The main reason I never bothered to filter out that specific sound was because you never know if a mod might use it for say ambient noise in a computer room or something like that.

**Comment by maraakate** [comment]
But... maybe it's worth me adding to my port if cl_hide_gun_icon is greater than 1 it will also filter the sound.

**Comment by deuxsonic** [comment]
Right. Yes it will keep playing indefinitely. I don't think the sound itself needs to be disabled but just having it play for that particular feature.

**Comment by maraakate** [comment]
I just checked right now, it plays 3 times then you never hear it again.

**Comment by maraakate** [comment]
Filtering out the sound specifically from the gun hide icon is tricky because it's controlled via the game code which requires in that point a hacky way to determine if the client wants to hear it (an easy hack would be making cl_hide_gun_icon a userinfo cvar) and decide if to send it to them.

**Comment by maraakate** [comment]
And since Yamagi is trying to specifically avoid hacky stuff like that it's very unlikely to be implemented, not to mention all mods you use would have to be recompiled to support that hack making it not worth the effort.

**Comment by deuxsonic** [comment]
I didn't wait long enough. ;) Fair enough.

**Comment by maraakate** [comment]
The hide gun icon hack itself may possibly break mods that rely on overflowing part of that for a counter or something else.  However, I play tested it across all the main mods and online and never experienced and issue.  Just letting that be known.

**Comment by deuxsonic** [comment]
I'm surprised id thought having it blink forever without a way to turn that feature off was a good idea.

**Comment by maraakate** [comment]
Objectives were kind of a newish concept in FPS' around the time (not counting FPS/RPG hybrids); so it was important you saw them.

**Comment by Yamagi** [comment]
As maraakate said: This is unlikely to arrive in YQ2.
