### ISSUE TITLE
[Question] How to build in Visual Studio 2022?

### ISSUE THREAD

**Issue by rrPKrr** [yquake2/yquake2#942]
Hey!

So, I am getting this error when trying to build the project in Visual Studio 2022:

1>C:\src\yquake2-master\src\common\frame.c(89,29): error C2054: expected '(' to follow 'YQ2_ATTR_INLINE'
1>C:\src\yquake2-master\src\common\frame.c(90,1): error C2085: 'Sys_CpuPause': not in formal parameter list
1>C:\src\yquake2-master\src\common\frame.c(90,1): error C2143: syntax error: missing ';' before '{'

Changing the line `static YQ2_ATTR_INLINE void Sys_CpuPause(void)` to something like `static YQ2_ATTR_INLINE; void Sys_CpuPause(void)` fixes the problem (and Yamagi Quake seems to be working fine and all), but how can I **properly** fix this error?

**Comment by turol** [comment]
You need to define `YQ2_ATTR_INLINE` properly in `src/common/header/shared.h` 

https://github.com/yquake2/yquake2/blob/15adee3b060a2d6b16f195fbfbd624067f5085ab/src/common/header/shared.h#L57

I suspect the new VS has changed the value of `__STDC_VERSION__` so the defines are now out of date.

**Comment by DanielGibson** [comment]
around line 66, after
```
#  elif defined(_MSC_VER)
   	#define YQ2_ATTR_MALLOC         __declspec(restrict)
```
(and before the corresponding `#  else`)
add `#define YQ2_ATTR_INLINE         __forceinline`

**Comment by DanielGibson** [comment]
I just pushed a fix

**Comment by rrPKrr** [comment]
Thanks! Everything works fine now. 👍

**Comment by DanielGibson** [comment]
great!
