### ISSUE TITLE
v8.20: Monster footsteps (CVAR) and other g_ based ones not working

### ISSUE THREAD

**Issue by RavenMacDaddy** [yquake2/yquake2#946]
Running the Windows version.

Manually typing `g_monsterfootsteps 1` in the console only produces a player message, and I already had the CVAR configured in my autoexec since before.

![image](https://user-images.githubusercontent.com/67732686/206767646-882d6ad1-74eb-44bc-afa6-442ab1b5b1dd.png)

EDIT: Did some more testing – seems most of the ones beginning with `g_` are missing;

When pressing TAB after typing `g_`:

![image](https://user-images.githubusercontent.com/67732686/206767943-292c4071-8224-4a0a-b0af-bea173dcad04.png)

**Comment by BjossiAlfreds** [comment]
Are you using the game.dll that comes with YQ2? It should be located in the baseq2 folder.

**Comment by DanielGibson** [comment]
and do you have the [footsteps.pkz](https://deponie.yamagi.org/quake2/assets/footsteps.pkz) in baseq2/ ?

**Comment by RavenMacDaddy** [comment]
Ah, dang it… The classic with persisted files with package manager – the game.dll was missing.

Thanks guys.
