### ISSUE TITLE
ERROR: Game Error: Savegame from another os.

### ISSUE THREAD

**Issue by inukaze** [yquake2/yquake2#950]
I had start a xatrix gameplay in multiplayer mode, under Windows 7, right now i had compile Yagami Quake 2 under Slackware64 14.2, but when i try to load the savegame i copy from Windows 7. appears the error : 

" ERROR: Game Error: Savegame from another os. "

Another thing. Exist a compatible bots with Yagami Quake 2 to use with q2base, xatrix, rogue, zaero, action quake 2, paintball ?. well i want to know if the answer is possitive if a option « bots » appear in multiplayer menu to use bots with any mod?

**Comment by BjossiAlfreds** [comment]
The savegame system doesn't have a struct serializer nor does it endianise ints, so this check is there as a safety layer. But if you want to try your luck, you could simply remove the OS checks from src/savegame/savegame.c, re-compile and see what happens, possibly the struct memory mapping and endianess match that of Windows.

**Comment by Yamagi** [comment]
You can alter the savegame header with a hex editor to forceload it on Linux. However in my experience Windows -> Linux never works, the systems are just too different. Also our Windows builds are 32 bit while the Linux build is likely 64 bit. Bit depth need to stay the same for savegames to load.

**Comment by Yamagi** [comment]
> Another thing. Exist a compatible bots with Yagami Quake 2 to use with q2base, xatrix, rogue, zaero, action quake 2, paintball ?. well i want to know if the answer is possitive if a option « bots » appear in multiplayer menu to use bots with any mod?

Most bots don't work under Linux because their source was never released. There is semi official supported version of 3zb2 for YQ2: https://github.com/yquake2/3zb2
