### ISSUE TITLE
game pauses when  changing  between vid_fullscreen  0  <-> 1   

### ISSUE THREAD

**Issue by j4reporting** [yquake2/yquake2#951]
probably introduced  by commit  https://github.com/yquake2/yquake2/commit/d93916d6ba86ff9f226cfe6394d1f96bce0d1dde and https://github.com/yquake2/yquake2/issues/911 

Please unpause when window/screen is visible again, or introduce a  CVAR  to disable  completely, Default  pausing disabled. :)

**Comment by Yamagi** [comment]
@devnexen can you have a look?

**Comment by apartfromtime** [comment]
Doesn't `cl_unpaused_scvis` fix the issue? Is `cl_unpaused_scvis` necessary?

https://github.com/yquake2/yquake2/blob/218ac53ce9e27f1ce0275389cc6beca5547d3cdf/src/client/input/sdl.c#L728-L734
