### ISSUE TITLE
failed to load opengl 3.2 and opengl es

### ISSUE THREAD

**Issue by Falcata** [yquake2/yquake2#959]
I have a pavillion g series with a intel 3000 and ati 7400 this setup show me opengl 4.5 compatible driver ( tested with quake spiked 1.50 but failed to load opengl 3.2 driver or opengl es driver to and revert to 1.4 opengl driver only.  I make a test with 8.01 and load the 3.2 opengl driver.

**Comment by Yamagi** [comment]
This might be caused by the addition of frame buffer object to support the underwater effect in GL3. Not all old GPUs support them, despite claiming full OpenGL 4.x support. You can try to disable them: `+set vid_renderer gl3 +set gl3_usefbo 0`

**Comment by Falcata** [comment]
Close the ticket. The main issue is caused by a bug using old drivers with an ati 7430m. I have the same problem in a quake client. I fix this using an udpated non compatible driver from another version (7xxx). I use a mix between Catalyst 15.11 beta and installing the legacy version driver from AMD CRIMSON DRIVER Relive 16.2.1. Sadly the ATI HD 24XX are very old gpu's and there's no updated driver from 2015...:(

**Comment by DanielGibson** [comment]
FWIW on Linux the drivers for these old GPUs should be in a better shape (and part of the kernel and mesa, i.e. don't require installing any additional drivers)
