### ISSUE TITLE
Cant play multiplayer on flatpak version

### ISSUE THREAD

**Issue by Luticus** [yquake2/yquake2#962]
Not sure what's up but for some reason when I use the flatpak version of the game, I can't get multiplayer to work. If I host a game and check ports with `sudo ss -tuplen` quake doesn't seem to be listening. I can't join a game either. The nmap tool also shows nothing when I do `sudo nmap -p 27910 steamdeck -sU`. Regular Debian installs from both stable and testing/sid seem to work fine. Normally I'd be fine just using those, but I want this to also work on my Steam Deck and that's where the flatpak is needed. I'm positive it's not a firewall issue. I haven't touched the default permissions with flatseal either. I've tested the flatpak both on the Steam Deck with SteamOS/Arch and on Debian stable and testing, and all cases have the same issue. When I use the native Debian packages on Debian laptops/desktops, everything works.

**Comment by Yamagi** [comment]
I don't have any experience with Flatpak. Quake II is a little special regarding network, however I don't see how it could interfere with Flatpack: Quake II binds both the server and the client to port 27910/UDP. Normally clients choose a random port. And it uses only UDP, no TCP.

We had this unexplainable bug report (without Flatpak) in late 2021: https://github.com/yquake2/yquake2/issues/754 Maybe the same problem or a variant of it?

**Comment by Luticus** [comment]
No worries, I'd just use a native install but with the steam deck that's not really a possibility. I wonder if there's an appimage I could try instead.

**Comment by Luticus** [comment]
Well, interesting development and I'm not sure if it helps or what it even tells me. On the off chance it does though, I figured I'd mention it. I went into the flatpak and ran the quake2 binary manually after copying the data to the ~/.yq2 folder so that it would find all the relevant stuff to make the game work. After doing that I attempted to run the game and play multiplayer and everything worked as expected until I got to the muli-player part. There, if I host a game and to a `sudo ss -tuplen | grep 27910`, I do not see the port listening and as expected I'm not able to join from another computer. Also if I host a game on another computer and attempt to join in my steam deck, still no dice. I think the version of yquake2 is simply broken in the flatpak. Is there any other way anyone can think of to install this on a steam deck? Has anyone else faced this issue?

**Comment by Luticus** [comment]
@Yamagi Sure enough, looking at your bug #754, it seem to be an issue with version 8.0.0 and appears to be fixed in version 8.0.1. interestingly the version available in flathub is in fact version 8.0.0.  So what we need is for someone to package 8.0.1 for flathub. I suppose an appimage would also work if anyone was interested in packaging that. I don't know either format and only work with debs for now, otherwise I'd volunteer. Might try to mess with it and learn though.

**Comment by Luticus** [comment]
Confirmed, I compiled the 8.20 release myself on my Debian system and then used scp to transfer the binaries to my deck. I overwrote the binaries in the flatpak and simply ran the game as normal from Steam. Now I can play multiplayer. The issue is a busted version in the flatpak. Whoever makes the flatpaks just needs to update it to your newest release and the issue is resolved.
