### ISSUE TITLE
gl_polyblend

### ISSUE THREAD

**Issue by KOKOSv8** [yquake2/yquake2#965]
Hi in original q2 there used to be gl_polyblend option.
Description: Toggle pallet blending.
Note: The pallet blending effect is used while being injured, using a powerup, or under water. It might be beneficial to disable this effect to see clearly in water, but then if the player is being injured he won't know it.

I personally like to turn off this effect in multiplayer, but with current yamagi version it is impossible, there is only cl_blend command but it doesnt solve problem.

**Comment by Yamagi** [comment]
The feature was still available for GL1 as `gl1_polyblend`. I have renamed the cvar back to `gl_polyblend' and implemented it for GL3. Have fun. :)

**Comment by Yamagi** [comment]
And a new test build for Windows: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20230121-2e939b1.zip

**Comment by KOKOSv8** [comment]
that was fast, thanks you very much ! I have manage to compile with mingw32, gonna bring more request tho :P
