### ISSUE TITLE
vid_maxfps with value 700+ affects rocket/grenade particles

### ISSUE THREAD

**Issue by KOKOSv8** [yquake2/yquake2#966]
Hi, I have noticed that only rocket launcher,grenade and grenade launcher smoke(particles) looks really wierd and found out its not any gl3_particles options that does that its vid_maxfps with value 700 or more starting to make it less visible. I want maximum fps so im using vid_maxfps 999 value and it makes flying rocket have like maybe 3-4 tiny particles so it basically looks like gl3_particles 0.

**Comment by DanielGibson** [comment]
Don't use vid_maxfps 700 or higher then :roll_eyes:

**Comment by Yamagi** [comment]
Above ~300 FPS things get hairy. That is cause by rounding errors - the more frames a sequence is divided into, the smaller the changes each frame get until they are too small - and assumptions the game makes about the minimal time it takes to render a frame.

This is the later one. Particles are created at a given time, with each rendered frame they fade a little bit more until their alpha value becomes zero and they are dropped. When too many frame are rendered, the alpha drops too fast and they become nearly invisible. It's likely not too hard to fix, however it requires some thinking. The problematic code is here: https://github.com/yquake2/yquake2/blob/master/src/client/cl_particles.c#L185

**Comment by Yamagi** [comment]
Mkay, the particle effects for weapons like blaster, rocket, grenade, etc. are in the render frame and not in the client frame.  `V_RenderView()` calls `CL_AddEntities()` calls `CL_AddPacketEntities()` and that one calls the particle effect function passing the distance the bullet, missile or grenade has moved since the last call. When this distance gets too small, the logic in the particle effect function fails. Nothing we can do here.

**Comment by KOKOSv8** [comment]
Some info from my testing:

Maybe this is only on 240hz monitors but i belive its not. 

YamagiQ2 have perfect smooth display feel, like better than q2pro in my opinion I just can feel it while playing so thats awesome.
You guys have setup vid_maxfps to value 300 by defualt which is not smooth, it actually make other players "teleport" and u can see it easily while moving mouse around. So i have tested few values and it looks like vid_maxfps 250, 333, 500, 999 works great! Except for that particle problems with 999, so probably would be good if you setup 250 or 333 vid_maxfps as default since most people not gonna dig that much into config.
