### ISSUE TITLE
Overhealed health gets set back to max after level transition

### ISSUE THREAD

**Issue by StroggVorbis** [yquake2/yquake2#974]
I'm not sure whether this is a bug or intentional, but I noticed that if you overheal with stimpacks, everything is lost after map change. With megahealth I can understand it, because it withers away on its own slowly.  My assumption is that the code doesn't distinguish between where the health comes from, it only compares it to the max, sees that it's greater and then clamps it.

Edit: This doesn't mean much, but armor doesn't get clamped. I tried changing maps with 202 jacket armor from armor shards and the game let me keep it.

**Comment by BjossiAlfreds** [comment]
This is not a bug, the original game behaves the same way. Armor not being affected is possibly an oversight by id, the code doesn't say one way or the other though.

**Comment by Yamagi** [comment]
Yes, this is the intended behavior.
