### ISSUE TITLE
baseq2 savegames displayed in mods / addons

### ISSUE THREAD

**Issue by Yamagi** [yquake2/yquake2#98]
Hallo Yamagi,

im gog.com Forum hat ein Benutzer einen kosmetischen Fehler gefunden.
Er/sie hat mich geben, dir Bescheid zu geben. Mir ist nicht klar,
warum er/sie es nicht selbst machen kann. 

Wenn man einen Mod verwendet, dann werden auch die Spielstände des
baseq2 Ordners angezeigt, solange in diesem Slot kein Spielstand des
Mods gespeichert ist. 

Ich habe kurz im Quellcode nachgesehen. Die Ursache liegt darin, dass
in Create_Savestrings() die Funktion FS_FOpenFile(...) verwendet wird,
um nach den Spielständen zu suchen. Somit wird, falls nichts im
Mod-Verzeichnis gefunden wird, im baseq2 Ordner gesucht.

**Comment by Yamagi** [comment]
The good news is: This is broken since ever.
The bad news is: A fix will be hard.

As said by the submitter, the save game list is generated through FS_FOpenFile() which relies on the VFS file enumeration logic. When a save game file isn't found in the mod directory, it takes a look at baseq2...

**Comment by DanielGibson** [comment]
should be fixed now
