### ISSUE TITLE
CFG file location?

### ISSUE THREAD

**Issue by Vitoria90** [yquake2/yquake2#982]
I'm trying to set up different config files for different graphics set ups, but I realized I can't find any config.cfg in my YQuake2 install, anywhere in there.
The game is saving my custom settings though, I just don't know where.

**Comment by BjossiAlfreds** [comment]
By default it's in the user data area. On Windows that would be C:\Users\<your profile>\Documents\YamagiQ2, not sure about other platforms.

You can use a command-line option to make YQ2 save user data in the install folder like the original game does: -portable
