### ISSUE TITLE
Monster footstep sounds directory?

### ISSUE THREAD

**Issue by MavisCelus19201** [yquake2/yquake2#988]
Checking the documentation, I put the file listed in the documentation into the baseq2 folder, but I still don't get any sounds from that, Tested on Linux, building from source, console showing the version as 8.20, alongside comparing it with the Windows build for comparison. Not sure if I'm missing some extra steps.

**Comment by BjossiAlfreds** [comment]
Is cvar `g_monsterfootsteps` set to 1?

**Comment by MavisCelus19201** [comment]
In the console commands? Cause I did that and now it worked for what it's worth.

**Comment by BjossiAlfreds** [comment]
It's a console variable (c-var). Setting it in the console in-game will work but you should add it to a config file so that it works reliably across game sessions. You can add this to autoexec.cfg:

`set g_monsterfootsteps 1`

**Comment by DanielGibson** [comment]
as `g_monsterfootsteps` has the `CVAR_ARCHIVE` flag set, setting it in the console will write it to a config, so the game should remember the setting (at least for the current game/mod, if you switch to another mod/addon you may have to set it again)
