### ISSUE TITLE
yquake2.exe reported as malware

### ISSUE THREAD

**Issue by omphalion** [yquake2/yquake2#989]
AVG antivirus reported yquake2.exe as malware (infected with IDP.generic).

I uploaded the file to virus total and no red flags came up.

I also uploaded quake2-8.20.zip and only 1 red flag appeared there.

I suppose the file is safe to use?

**Comment by BjossiAlfreds** [comment]
You suppose correctly. Anti-malware detection is not failsafe, harmless executables can coincidentally contain a sequence of bytes that match a malware signature sequence. Windows Defender has a couple of times told me my own compiled code is malware.
