### ISSUE TITLE
Grenades arcing to the left and right, BFG shot missing sprite

### ISSUE THREAD

**Issue by deuxsonic** [yquake2/yquake2#99]
![quake2 2015-10-16 05-58-36-371](https://cloud.githubusercontent.com/assets/7662909/10539131/8a5b6278-73cb-11e5-917d-56fdfc546b2b.jpg)

In just messing around I went through all the weapons and noticed the grenade launcher and hand grenades curve left or right when shot/thrown. Also the BFG projectile is missing the green sprite in the middle. Were these intended changes or is this wrong?

**Comment by Yamagi** [comment]
Fixed, thank you. As I said in the commit message: This is a perfect example why I'm so hesitant with merging anything that's not a fix for a reproducable bug.
