### ISSUE TITLE
crash in Quake II 25th Anniversary map using related to stereo wav file

### ISSUE THREAD

**Issue by nephatrine** [yquake2/yquake2#991]
We have a map `techbased` in our mod that crashes upon loading in Yamagi Q2 both 8.20 and master built from scratch. This crash does not occur in 3.21, 3.24 unofficial, and other engines we tested on.

```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00bb3d91 in S_GetVolume (data=0xe3a705c "ö\001\231ÿè\001ßÿO\001\025", sound_length=15482880, width=2, sound_volume=0x272f028) at C:/MSYS64/home/nephatrine/Q2/yquake2/src/client/sound/sound.c:263
263                             short sound_sample = LittleShort(*sound_data);
```

It looks like a particular sound file causes the crash. Changing the wav in question to mono does correct the issue from our end, but since other engines don't seem to be causing a **crash** there I figured I'd open an issue on your end too. It does look like Yamagi claims to support stereo sound files.

I've attached both the map and sound file in question.

[badsound.zip](https://github.com/yquake2/yquake2/files/11226937/badsound.zip)
[techbased.zip](https://github.com/yquake2/yquake2/files/11226940/techbased.zip)

(https://github.com/glhrmfrts/q25_game/issues/8)

**Comment by Bittermens** [comment]
it would be nice if Yamagidevs can check this out, Knightmare is working on a patch for KMQ2 to fix some issues too.

This project literally turned out to be a good surprise at all, all maps are solid and well done.

**Comment by Yamagi** [comment]
@0lvin was way faster than me with analyzing the problem and sending a fix. Man thanks for that :) If have merged his pull request and the master branch can now load the map without crash. The sound file plays correctly.
